### ISSUE TITLE
accessing an event by its HTML tag

### ISSUE THREAD

**Issue by Mona1992** [twinssbc/Ionic2-Calendar#100]
Hey there,
I am trying to build a 'drag and drop'-functionality for calendar events of the twinssbc/Ionic2-Calendar in the day view. My goal is to enable postponing an event with drag and drop.
The issue I am facing is that I don't know how to access an event by its HTML tag. 
As far as I know,  the only access to an event is the method 'onEventSelected(event){}' .

Is this possible?
Thank you in advance

**Comment by twinssbc** [comment]
@Mona1992 
There's a dayviewNormalEventTemplate option.

```
<template #template let-displayEvent="displayEvent">
      <div class="calendar-event-inner">{{displayEvent.event.title}}</div>
  </template>

  <calendar ... [dayviewNormalEventTemplate]="template"></calendar>
```

As you can see from above code snippet.
The default template is just displaying the event title.
This option was intended for you to customize the view of the events displayed in the day view.
In your case, I think you could add some custom attribute in the template, for example, you put the index of the event array. Then you can retrieve the event via the attribute and modify its start and end time.

**Comment by Mona1992** [comment]
Thank you so much for your quick answer.

How can I set the self-defined directive 'absolute-drag' as an attribute to this template?
I tried the following:
document.getElementsByClassName("calendar-event-inner")[0].setAttribute("absolute-drag", "absolute-drag");

Sadly this did not work since 'document.getElementsByClassName("calendar-event-inner")[0]' was undefined although events had already been created at this point.

Thank you

**Comment by twinssbc** [comment]
@Mona1992 
I think you could try directly setting the attribute when declaring the template.
```
<template #template let-displayEvent="displayEvent">
      <div class="calendar-event-inner" absolute-drag>{{displayEvent.event.title}}</div>
  </template>
```
