### ISSUE TITLE
How to modify the Event Detail

### ISSUE THREAD

**Issue by twbocklertorch** [twinssbc/Ionic2-Calendar#101]
I would like to include additional event properties, other than 'title', 'startTime', and 'endTime'.  And I would also like to display these new properties in the event detail section (i.e. when clicking on a day within the month view).
Can you point me to where I need to make these adjustments?
Thanks!

**Comment by twinssbc** [comment]
@twbocklertorch You could use monthviewEventDetailTemplate option to customize the information displayed in the event detail section. More details in README.

**Comment by twbocklertorch** [comment]
Thank you.  I've identified the template in calendar.ts.  Not being too familiar with how to make changes, can you instruct me how to change calendar.ts and update my imported plugin?

**Comment by twinssbc** [comment]
@twbocklertorch 
In your calendar.ts, just put an <template> element before <calendar> element.
Notice the # sign, it is to create a reference variable of the template.
Then you could pass that reference variable to [monthviewEventDetailTemplate].
```
<template #template let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
  ... 
  </template>

  <calendar ... [monthviewEventDetailTemplate]="template"></calendar>
```

**Comment by leon9608** [comment]
Hi, I am facing a problem. I wanted to use the calendar for my app development. When I installed the ionic2-calendar, it automatically installed under the node_moduels file. There are so many files under the ionic2-calendar file such calendar.d.ts , calendar.js , calendar.js.map , calendar.metadate.json and so on.   And I only see the original code
`<template #monthviewDefaultEventDetailTemplate let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
            <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
                <ion-item *ngFor="let event of selectedDate?.events" (click)="eventSelected(event)">
                        <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                            -
                            {{event.endTime|date: 'HH:mm'}}
                        </span>
                    <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn">All day</span>
                    <span class="event-detail">  |  {{event.title}}</span>
                </ion-item>
                <ion-item *ngIf="selectedDate?.events.length==0">
                    <div class="no-events-label">{{noEventsLabel}}</div>
                </ion-item>
            </ion-list>
        </template>`
under the Jason file. I have no idea what to do to change the format? Can you help me?  Thanks.

**Comment by twinssbc** [comment]
@leon9608 you dont need to change the source code. If you want to override the default eventdetail template. you could create a template in your ts file and pass it to the calendar. just like what I pasted in the above comment.
