### ISSUE TITLE
Css class in monthview template gets applied to inactive month

### ISSUE THREAD

**Issue by kianliang-iium** [twinssbc/Ionic2-Calendar#103]
Thank you for this great calendar.
When I use the template in this way:

<template #template let-view="view" let-row="row" let-col="col">
      {{view.dates[row*7+col].label}}
      <div *ngFor="let items of dataCount | async">
                    <ion-badge class="myBadge" *ngIf="items.$key == view.dates[row*7+col].label && items.dataCount !== 0">{{ items?.dataCount }}</ion-badge>
       </div>
  </template>

  <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>

The same badge gets applied to the inactive days in the same month. 
![img_1811 1](https://cloud.githubusercontent.com/assets/13483690/25713811/1f9d1756-3120-11e7-894c-4681879497db.jpg)
How do I prevent that?
Thank you.

**Comment by twinssbc** [comment]
@kianliang-iium The inactive days have text-muted class applied to the td element. You could override the style on this class.
