### ISSUE TITLE
Edit Options

### ISSUE THREAD

**Issue by hamzahamidi** [twinssbc/Ionic2-Calendar#104]
For some reason, noEventsLabel doesn't change

` <calendar [eventSource]="eventSource" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate" (onCurrentDateChanged)="onCurrentDateChanged($event)" (onEventSelected)="onEventSelected($event)" (onTitleChanged)="onViewTitleChanged($event)" (onTimeSelected)="onTimeSelected($event) [noEventsLabel]="noEvent"
        step="30"> `

noEvent="pas configuré"

**Comment by twinssbc** [comment]
@hamzahamidi noEventsLabel="noEvent"

**Comment by hamzahamidi** [comment]
Thank you , it works fine
