### ISSUE TITLE
Loading Delay

### ISSUE THREAD

**Issue by mikeyudin** [twinssbc/Ionic2-Calendar#105]
First, thanks for the great module.  

Has anyone noticed a 1-2 second delay on the initial rendering of the calendar?  If I try to load the calendar in a component (via tabs or menu item), it takes some time before the calendar loads.  

I'm using Ionic 3 btw.  Still seems to work, just this and one other small issue (opening a separate issue).

**Comment by GuilhermeBCC** [comment]
Hi everybody,

Great job  @twinssbc.

I'm using Ionic 3 too. When debugging my app I noticed a delay of 6s at app initialization when I added the module. Was there a problem with performace?

**Comment by twinssbc** [comment]
Is the delay happening on Android device only?
Quite a few users reported the slowness on Android device.
So far I'm not able to optimize the performance to make the delay unnoticeable.
Using prod version definitely helps.

**Comment by twinssbc** [comment]
I did some performance improvement. You could check the "Performance Tuning" section in README. If you don't need to localize some labels, you may be able to save some time.

**Comment by GuilhermeBCC** [comment]
Ow, Very Good, I'll take a look soon. I and many others use moment.js for locale http://momentjs.com/docs/#/i18n/. Is there any chance of automatically locating this library?

**Comment by twinssbc** [comment]
@GuilhermeBCC I don't want to bind to a specific library. But you can easily implement a date formatter using momentjs now.

**Comment by tryadelion** [comment]
only on android so far. it's weird isn't it? even on high end devices

**Comment by tryadelion** [comment]
@twinssbc 
http://i.imgur.com/fKqAjWG.png
^my chrome profiler result on a mid end device. i hide the calendar before IonViewDidEnter, because before it took about 800ms to load. now the load harm is on the animation layer tho. any way to improve it? i'm not a performance expert.

**Comment by twinssbc** [comment]
@tryadelion Are you saying you have hidden the calendar, but the app still takes 800 ms to load?
If you try the sample Ionic project, how long will it take to load?

**Comment by tryadelion** [comment]
@twinssbc  i hide it on load, and then on IonViewWillAppear show it again, so it doesn't lag the load time.  it still takes 800ms to render completely, just not like if the whole thing freeze up like before.

**Comment by tryadelion** [comment]
After some versions this is still happening to some androdi devices, @twinssbc

**Comment by twinssbc** [comment]
@tryadelion Is it related to the use of calendar in your app? If you try the Ionic sample app in the android devices, are you experiencing the same performance issue? Have you tried the step in the Performance Tuning section?

**Comment by tryadelion** [comment]
1) yes.
2) i've been unable to, what i experience is the whole angular slightly lags for 0.8s-2s right now when coming from a page in a menu and going to the calendar, performance wise the profiler turns red like a christmas tree. happens on different apps so far, i've managed to stop it by doing slightly hacks like hiding the calendar for quite some time before opening the page, or lazy loading it the ionic 3 way, depending on the app, but is still a nuissance.
3) yes, all of them, month week days titles included.

could you try to render the calendar outside of the angular ngZone? that has worked to me before with stuff like google maps doing too many calls to angular methods that slowed the stuff down.

**Comment by twinssbc** [comment]
@tryadelion Which mode of the calendar are you using? Is there any event get loaded when enter into the calendar page? Could you find any clue in the profiler, for example, the most time consuming method related to the calendar?

**Comment by tryadelion** [comment]
@twinssbc  i'm using the month view mode.
During calendar launch:

SwiperJS seems to be doing quite some jobs, function calls from polyfills that i can't relate also take a lot.
Animation frame also seems to take quite a lot.
each of those takes 100-300ms, plus ionic's own stuff make up to 1-2s in the end. can't find a clear time consuming method though.

**Comment by tryadelion** [comment]
Calendar page loading profiling:
![captura de pantalla 2017-11-15 a las 15 21 01](https://user-images.githubusercontent.com/3778474/32840716-c87621ba-ca18-11e7-90d0-eeac71057487.png)

**Comment by tryadelion** [comment]
The problem for me is not the time it takes to render the page, but that the page hangs.

**Comment by tryadelion** [comment]
i setted up a 1100ms timer between page load and calendar load. the lag dissapeared. you can see the performance difference between the ionic methods and yours on this screen:
![captura de pantalla 2017-11-15 a las 15 29 00](https://user-images.githubusercontent.com/3778474/32841120-cf6cf1d2-ca19-11e7-8123-1c1ca0cb9ed2.png)
Left yellow and purple blob: page load.  right blob: calendar after 1100ms.
not saying it's an easy thing to fix, i have no idea on JS render layers, just wanted to add as much info as i can.

**Comment by twinssbc** [comment]
@tryadelion I'm not sure if it's because of the Menu sliding animation generates too much burden.
I met similar situation in Ionic-Calender which is based on Angular1, at that time, when swiping the calendar, I felt obvious hang. By looking at the profiler, I found it's because the JS calculation and sliding animation happen at the same time. So I added some timeout and disabled the Angular animation to solve the problem.
Maybe you could try if the same issue happens in tab layout?

**Comment by tryadelion** [comment]
i am unable to change my navigation to tab layout right now, but i expect it to behave similarly.

**Comment by ACouasnonPerso** [comment]
i comment that post after a long time. This has happen to me. I'm using IONIC 5 and a calendar on popup.
On android device freeze the first time i oppened the popup, after some time or after close and open the popup it was working fine.
I just put mode="ios" on the calendar and now it work perfectly.
I hope this comment will help someone in the same case :)

**Comment by javapach** [comment]
> i comment that post after a long time. This has happen to me. I'm using IONIC 5 and a calendar on popup.
> On android device freeze the first time i oppened the popup, after some time or after close and open the popup it was working fine.
> I just put mode="ios" on the calendar and now it work perfectly.
> I hope this comment will help someone in the same case :)

I have the same problem, what do you mean with "put mode="ios" "?
