### ISSUE TITLE
Clicking a day in previous/next month loads wrong month.

### ISSUE THREAD

**Issue by mikeyudin** [twinssbc/Ionic2-Calendar#106]
I've noticed that when I click one of the gray dates (IE previous month or next month), it seems to load the calendar month for 2 months before the clicked month.  

For instance:  If I have May 2017 loaded, and click the "30" for April 30th, it actually loads the March month, and selects a day outside of March.   Or, if I select the gray 1 (June 1) with May 2017 loaded, it loads the July calendar.

Thanks!

**Comment by twinssbc** [comment]
@mikeyudin Which version of Ionic, Angular and Ionic2-Calendar are you using?
Did you add any customized logic in the onTimeSelected callback?

**Comment by mikeyudin** [comment]
@twinssbc Sorry, it is my fault.  Was updating the view incorrectly in the `onCurrentDateChanged` handler.  It's working now.  Any advice in #105 would be appreciated though.
