### ISSUE TITLE
Load date events on modal creation.

### ISSUE THREAD

**Issue by premorion** [twinssbc/Ionic2-Calendar#107]
Firstly, I wanted to thank you for the amazing job you did with this module.

I am having problems displaying the date events. My implementation creates a modal displaying the calendar causing events of the actual month not being displayed. I need to change the month to actually see the events or reenter the modal view.

This is my implementation:

home.ts
`calendarModal() {
   let contactModal = this.modalCtrl.create(CalendarPage, { data: [this.populateEvents()] });
   contactModal.present();
   contactModal.onDidDismiss(data => {
     if(data !== null){this.dateClient = data.startTime} 
 });
}`

where populateEvents returns an array with events (Same as createRandomEvents())

calendar.ts
`ionViewDidLoad() { 
        return this.eventSource = this.navParams.get('data')[0]
    }`

I'm using Ionic2, thank you for your time.

**Comment by twinssbc** [comment]
@premorion Is this populateEvents loading events asynchronously? If you put a breakpoint in ionViewDidLoad method, is eventSource actually getting valid data? If you directly set some random events to eventSource in ionviewDidLoad method instead of getting from navParams, will it work?

**Comment by premorion** [comment]
@twinssbc 

- Is this populateEvents loading events asynchronously?
Yep, is retreiving information from a firebase database. I know it is beyond the scope of the question but,
is there any way to wait until the data is available?

Here is my implementation:

populateEvents()

```
var events = [];
       return this.af.database.list('/dates/may').subscribe(dates => {
            this.dates = dates;
            this.dates.forEach(song => {
                var date = new Date(song.$value); 
                let startTime = new Date(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getHours(), date.getMinutes())
                let endTime = new Date(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getHours(), date.getMinutes() + 30)
                events.push({
                    title: song.$key,
                    startTime: startTime,
                    endTime: endTime,
                    })
                })
        })

```

 Thanks for the help.

**Comment by twinssbc** [comment]
@premorion You basically need to manipulate eventSoure in the async call back method, instead of directly use the return value of the method. Because at that point, the data hasn't been returned. You could use Promise to make the async call act as sync call. Some libraries/frameworks directly support Promise as the return type.

**Comment by premorion** [comment]
@twinssbc Thank you for the information, I will try to do some research,

**Comment by wilsoncx** [comment]
Hello,
Firstly thanks to work this component is very good.
But I'm having a problem similar to the one reported here;
I use the firebase too I am loading the data and populating the same eventSource out of the friend above, I have already verified that it loads the data to the eventSource at startup I am doing this in ionViewDidLoad, but when I initialize the component it does not load the events, only Loads when I call loadEvents () being that the eventSource is already populated, could you help me with this.

**Comment by twinssbc** [comment]
@wilsoncx Could you provide the code snippet that is loading events in ionViewDidLoad?
If your loading events call is an async call, you need to populate the eventSource in your callback function.

**Comment by wilsoncx** [comment]
` onRangeChanged(ev) {
         let loader = this.loadingCtrl.create({
        content: "Caregando Eventos...",
        });
       loader.present();
               let tmp = [];
          this.authData.getEventos().subscribe(evento=> {
            evento.forEach(element => {
                tmp.push({
                codigo: element.$key,    
                title: element.title,
                description: element.description,
                startTime: new Date(element.startTime),
                endTime: new Date(element.endTime),
                allDay: element.allDay,
                local:element.local
                     })               
            });
           loader.dismiss();
            this.eventSource = tmp;
            console.log(this.eventSource)
      },(err) =>{
        console.log(err)
    })
    }`

I did so and it worked,
Thanks

**Comment by squierll** [comment]
@wilsoncx  Thanks a lot.
