### ISSUE TITLE
new Events created don't appear unless I change the mode

### ISSUE THREAD

**Issue by hamzahamidi** [twinssbc/Ionic2-Calendar#109]
I do create new events in the calendar, but I need to change the mode(month, week ,day) so that I can notice the changes. Any suggestions please.

**Comment by twinssbc** [comment]
@hamzahamidi How do you add the new event to the eventSource array? If you directly push the element, the calendar won't notice the element change. You need to change the assignment of eventSource variable.

**Comment by hamzahamidi** [comment]
@twinssbc  You're right I directly push the element. Could you please give me an example on how to add an event?

**Comment by twinssbc** [comment]
@hamzahamidi You need to create another array and push the existing elements in eventSource into it and assign it back to eventSource. It's not a perfect solution right now, I will try to add some force refresh option.

**Comment by twinssbc** [comment]
@hamzahamidi I've exposed an instance method 'loadEvents', you no longer need to assign a new array to eventSource if you directly modify the element in the eventSource array.

**Comment by hamzahamidi** [comment]
@twinssbc  All right :) Thank you
