### ISSUE TITLE
[Customization] How to limit up to 5 rows on monthview instead of current 6 rows?

### ISSUE THREAD

**Issue by gacostasantex** [twinssbc/Ionic2-Calendar#111]
Hi, my question it's about how to display 5 rows on monthview instad of 6 like default. There is a way to do it setting a configutation or should I deep into monthview.js?

Best Regards.

**Comment by twinssbc** [comment]
@gacostasantex Unfortunately it's not configurable. You need to modify the code in monthview.ts.
Actually 6 rows are necessary, check July this year in the calendar, it occupies 6 rows.
