### ISSUE TITLE
Set minTime and maxTime for hours

### ISSUE THREAD

**Issue by hakikihacioglu** [twinssbc/Ionic2-Calendar#114]
Hi,

I only want to see the hours from 08:00 to 19:00 in weekview and dayview.

Is it possible?

Thank you

**Comment by twinssbc** [comment]
@hakikihacioglu Currently, it doesn't have these options.
A workaround is you could set the margin-top and height of the weekview-normal-event-container class to only display part of the table.

**Comment by gmarab** [comment]
Sorry @twinssbc, it is a banality but I can not find it.
I'm using the top negative margin to not see the weekview start hours: how can I do it to not show the time that appears in the image?
![screenshot_40](https://user-images.githubusercontent.com/5528670/29004885-77391d04-7acf-11e7-8397-b72dab7d7e8c.jpg)

Thanks in advance.

**Comment by twinssbc** [comment]
@gmarab You could set background-color: white to weekview-header and z-index: -1000 to weekview-normal-event-container.

**Comment by twinssbc** [comment]
@gmarab @hakikihacioglu I exposed startHour and endHour option in the latest version. You don't need to use the css hack to hide part of the calendar. Feel free to give a try.
