### ISSUE TITLE
Missleading documentation

### ISSUE THREAD

**Issue by bmarci** [twinssbc/Ionic2-Calendar#115]
In the docmentation you say:
formatWeekTitle
The format of the title displayed in the week view.
Default value: 'MMMM yyyy, Week w'

In reality the w part gives wrong value. According to the source it is:
'MMMM yyyy, Week $n' 
where $n is the week number.

It's a minor thing but it can save some time for other developers like me.

**Comment by twinssbc** [comment]
Fixed the README.
