### ISSUE TITLE
Disable swiping

### ISSUE THREAD

**Issue by jayordway** [twinssbc/Ionic2-Calendar#116]
Is there a way to prohibit the user from swiping the calendar back past the current month?

**Comment by twinssbc** [comment]
@jayordway It's not possible in the current version. But the underlyng ion-slides component has this option, I will expose it in the future version.

**Comment by twinssbc** [comment]
@jayordway I have added lockSwipeToPrev option in the latest version. Feel free to have a try.

**Comment by harishios** [comment]
@twinssbc : I want to lock the next swipe also. lockSwipeToPrev works great. Please help.

**Comment by Ahmadre** [comment]
To All: 

they have added LockSwipes perfectly! For Next and Prev:

`[lockSwipes]="lockSwipes"`

just add that to your calendar module. Default value is false.

Thanks @twinssbc :) great calendar

**Comment by akirilowski** [comment]
When setting "lockSwipes" to true, it's not possible to display events in the (day) calendar.

**Comment by danieltorrer** [comment]
@akirilowski Same happens to me, could you solve it?

**Comment by akirilowski** [comment]
@danieltorrer no, just used a workaround: lock the swipes after data loaded or in a setTimeout(..)

**Comment by mautenrieth** [comment]
hi @akirilowski. Could you please post a snipped of your code (controller & view)? Can't figure it out to work :-( Thank you :-)

**Comment by akirilowski** [comment]
@mautenrieth 
I don't have access to the code anymore. But it should work like in the README doc:

`        <calendar ... [lockSwipes]="lockSwipes"></calendar>

        ngAfterViewInit() {
            var me = this;
            setTimeout(function() {
                me.lockSwipes = true;
            },100);
        }
`
You could put the `setTimeout` method into your component constructor.
The timeout (100ms) in the example has to be greater than the time your calendar data needs to load.

**Comment by mautenrieth** [comment]
Thank you!
