### ISSUE TITLE
Event color in week view

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#119]
How to change color of events in week view based on event?

**Comment by Astacius** [comment]
I have found the answer, if someone is interested I can elaborate.

**Comment by opahti** [comment]
Please do!

**Comment by Astacius** [comment]
You have to use template as in documentation, I will tell exactly how tomorrow because I am not working today.

`<template #template let-displayEvent="displayEvent">
      <div class="calendar-event-inner">{{displayEvent.event.title}}</div>
  </template>

  <calendar ... [weekviewNormalEventTemplate]="template"></calendar>`

**Comment by Astacius** [comment]
Ok so here it comes:
```
<ng-template #weekEvents let-displayEvent="displayEvent">
      <div class="calendar-event-inner" 
      [style.backgroundColor]="dataService.getColor(displayEvent.event)"
      [style.top]="(37*displayEvent.startOffset/hourParts)+'px'"
      [style.left]="100/displayEvent.overlapNumber*displayEvent.position+'%'"
      [style.width]="100/displayEvent.overlapNumber+'%'"
      [style.height]="37*(displayEvent.endIndex - displayEvent.startIndex) - 4 + 'px'"
      >{{displayEvent.event.title}}</div>
  </ng-template>
```

This is my custom template of week view.

**Comment by divijm** [comment]
Can you explain a little more on how/where you implemented this? Or do you mind sharing your repo please where you tried implementing this calender component! :) @Astacius

**Comment by Astacius** [comment]
http://www.codeexpertz.com/blog/mobile/ionic-2-calendar

**Comment by divijm** [comment]
@Astacius  I can display the calendar with all the views (month, week, day) and load the events fine! :) 

I was more asking in regards to the ng-template section of your code which you posted recently - I am not sure which file I have to include that it in specifically. I want to edit the colors of the events etc.

**Comment by twinssbc** [comment]
@Astacius You just need to include ng-template section in your html file which declares calendar element.

**Comment by Bhavana1622** [comment]
I've tried this and it works for month view. Hope this helps.

https://github.com/Bhavana1622/ionic2-calendar-event
