### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by claudiozam** [twinssbc/Ionic2-Calendar#120]
Hi, I'm using ionic2-calendar@0.3.3. In my IPhone the calendar works perfect (es-AR  = Spanish  Argentina). But in my IPad it shows the calendar only in en-US.

This is my configuration.
 

```
import { LOCALE_ID } from '@angular/core';
.......
```

```
providers: [
    .....
    { provide: LOCALE_ID, useValue: 'es-AR' },
    Transfer,
    File,
    ....

```

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.12 
OS: macOS Sierra
Node Version: v7.6.0
Xcode version: Xcode 8.3.2 Build version 8E2002

**iPad 2 Wi-Fi + 3G (GSM)
IOS : 9.3.1**

Same issue in iPad Mini.

```
 "dependencies": {
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/compiler-cli": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@ionic-native/badge": "^3.2.2",
    "@ionic-native/calendar": "^3.1.1",
    "@ionic-native/core": "3.6.0",
    "@ionic-native/device": "^3.1.1",
    "@ionic-native/dialogs": "^3.4.4",
    "@ionic-native/facebook": "^3.1.1",
    "@ionic-native/file": "^3.1.1",
    "@ionic-native/google-analytics": "^3.2.2",
    "@ionic-native/google-plus": "^3.1.1",
    "@ionic-native/in-app-browser": "^3.1.1",
    "@ionic-native/keyboard": "^3.4.4",
    "@ionic-native/push": "^3.1.1",
    "@ionic-native/safari-view-controller": "^3.1.1",
    "@ionic-native/social-sharing": "^3.1.1",
    "@ionic-native/spinner-dialog": "^3.1.1",
    "@ionic-native/splash-screen": "^3.1.1",
    "@ionic-native/status-bar": "^3.1.1",
    "@ionic-native/transfer": "^3.1.1",
    "@ionic/storage": "2.0.1",
    "angular-rollbar": "0.0.2",
    "angular2-elastic": "^0.13.0",
    "angular2-moment": "^1.2.0",
    "cordova-custom-config": "^3.1.2",
    "font-awesome": "^4.7.0",
    "fs-extra": "^2.1.2",
    "intl": "^1.2.5",
    "ionic-angular": "3.1.0",
    "ionic-image-loader": "^2.0.2",
    "ionic-img-viewer": "^2.1.0",
    "ionic2-calendar": "^0.3.1",
    "ionicons": "3.0.0",
    "onscreen": "^1.2.0",
    "rxjs": "5.1.1",
    "sw-toolbox": "3.4.0",
    "xmldom": "^0.1.27",
    "zone.js": "^0.8.5"
  },
```

Thanks!!!

**Comment by twinssbc** [comment]
@claudiozam Does localization work in other pages in your iPad?

**Comment by wilsoncx** [comment]
Good morning, am I having this same problem could you help me?
` {provide: [ErrorHandler,LOCALE_ID], useClass: IonicErrorHandler, useValue: 'pt-BR'}`

**Comment by twinssbc** [comment]
@wilsoncx 
You need to put LOCALE_ID declaration separately.
```
    { provide: ErrorHandler, useClass: IonicErrorHandler },
    { provide: LOCALE_ID, useValue: 'pt-BR' }
```

**Comment by wilsoncx** [comment]
Everything was fine thank you

**Comment by marlonwesleysimon** [comment]
use in calendar module
       constructor() {
			moment.locale('pt-BR')
		}

**Comment by Nitinchavda** [comment]
@twinssbc : is it possible to register multiple languages at a same time?

**Comment by twinssbc** [comment]
@Nitinchavda 
You could import multiple locales, but when the app launches, you need to decide which one to use.

```
import { registerLocaleData } from '@angular/common';
import localeZh from '@angular/common/locales/zh';
import localeFr from '@angular/common/locales/fr';
registerLocaleData(localeZh);
```

**Comment by Nitinchavda** [comment]
Thanks the quick reply @twinssbc, i really appreciate it. Sometime getting headerDay issue. is it because language not found?.

**Comment by twinssbc** [comment]
what kind of headerDay issue?

**Comment by Nitinchavda** [comment]
I'm getting locale error. My apologies, it was locale error, i was using sp for Spanish while angular is using es.

Thanks again for quick reply.

It's working fine now.
