### ISSUE TITLE
Hide all-day label?

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#122]
Is there any way to do that?

**Comment by twinssbc** [comment]
@Astacius Just to confirm you want to hide all-day label in which view?
If it's weekview or dayview, you just want to hide the label or the entire all-day row?

**Comment by Astacius** [comment]
inside both of them, i want to hide entire row

**Comment by twinssbc** [comment]
You could refer to this issue.
https://github.com/twinssbc/Ionic2-Calendar/issues/54

**Comment by Astacius** [comment]
how to access .weekview-allday-table with css?
