### ISSUE TITLE
How to use this calendar

### ISSUE THREAD

**Issue by Abhishekl90** [twinssbc/Ionic2-Calendar#123]
Hello,
I using this calendar to show events, and when date is clicked a list of event for that day are displayed.Below are my requirements.

1.As per the demo, when load event button is clicked,events are fetched and all the days with events are displayed with blue background. Now in my app, I fetching events list from a web service, now when I give a call to web service and get events list I am not able to set background for the days.

2. I am showing custom list for the number of event on the particular day, now I want to remove the event list which come by default.

3. On each day click I want to load events for that day, again I will be giving a call to web service and will be fetching events for that day.

Any help is appreciated, as I am new to Ionic and Angular
Thanks in advance.

**Comment by twinssbc** [comment]
@Abhishekl90 
1. I assume your fetch event list call is async call? So you need to set the eventSource variable in your async callback.
2. You could use showEventDetail option to hide the default event list.
3. You could use onTimeSelected option to load the events on the selected day.
More details can be found in the README.

**Comment by Abhishekl90** [comment]
@twinssbc Thank you very much for your help, I surely follow these steps.

**Comment by Abhishekl90** [comment]
Sir, as u said, I called the events method for that particular day, but I am not able to
