### ISSUE TITLE
View Change, events not showing up

### ISSUE THREAD

**Issue by gdesplin** [twinssbc/Ionic2-Calendar#125]
I am remotely getting events, and I have my query mode set to remote. When I load the calendar initially it loads the events properly and I can see them. However, when I change the view to a different day or to week view, they no longer show up. When I create a new event or delete one, the eventSource successfully updates again and I can see them again.
I feel like I am misunderstanding what onRangeChanged does vs what onCurrentDateChanged. The documentation isn't clear to me. 
Those functions are as follows: 
```
    onCurrentDateChanged(event:Date) {
        var today = new Date();
        today.setHours(0, 0, 0, 0);
        event.setHours(0, 0, 0, 0);
        this.isToday = today.getTime() === event.getTime();
        this.getEvents(this); 
    }

    onRangeChanged = (ev: { startTime: Date, endTime: Date }) => {
        console.log(ev);
        this.getEvents(this); 
      
     };
```
What am I missing here or misunderstanding?
Thanks

**Comment by twinssbc** [comment]
@gdesplin onCurrentDateChanged is fired when the current selected date is changed, for example, if you swipe to the previous/next month, the selected date will also shift to that month. Or if you select a date, the selected date is also changed.
onRangeChanged is fired when the range of the current view is changed, for example, if you swipe to the previous/next month or change from monthview to weekview.
You need to fetch the events in onRangeChanged method. Note that your getEvents probably is an async call, you need to manipulate the eventSource in the callback method.

**Comment by manikandan07081995** [comment]
@twinssbc  When i scroll to next month current month appear after that desire month loading.How to solve hide when scroll next month current month view appear.

**Comment by manikandan07081995** [comment]
*not after before desire month sorry.

**Comment by twinssbc** [comment]
@manikandan07081995 I don't really understand your description. Maybe a screenshot could explain it? How can current month and next month be displayed together?

**Comment by manikandan07081995** [comment]
@twinssbc  I have implemented your calendar on iPad.When I trying to orientate entire calendar view disappeared.
