### ISSUE TITLE
when does the calendar update occur?

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#126]
whenever i am trying to assign new data to calendar it isn't refreshing at the same time, i have to swap date or change mode and then refresh occurs, is there any way to forcefully refresh calendar? or when is the right time to assign new data source? data in this case comes from async call

**Comment by twinssbc** [comment]
@Astacius You need to manipulate the eventSource in your async callback. Also the calendar only watches the eventSource variable itself, not the individual element in the eventSource array. So you need to assign eventSource to a new variable.

**Comment by Astacius** [comment]
oh i see, thanks for your answer

**Comment by twinssbc** [comment]
@Astacius I've exposed an instance method 'loadEvents', you no longer need to assign a new array to eventSource if you directly modify the element in the eventSource array.
