### ISSUE TITLE
Problem with hours on the weekview

### ISSUE THREAD

**Issue by dualshote** [twinssbc/Ionic2-Calendar#129]
Hello,

I have a little problem with de mode "week". The ours keys are hidden... I don't understand. The month view work perfectly :) 

Have you an idea for this problem ? :) 
Thanks :) 
ps : Great job for this component !! 

<img width="353" alt="capture d ecran 2017-06-11 a 20 09 23" src="https://user-images.githubusercontent.com/5940350/27013349-2c27fbe6-4ee2-11e7-9e23-8b122a322095.png">

**Comment by twinssbc** [comment]
@dualshote It's likely some css problem. Did you override some styles globally? Could you use developer tool to check why nothing displayed under all day row?

**Comment by dualshote** [comment]
Hi, i don't think that is a css problem... I have juste the "all day" row present in the DOM.... I didn't override the calendar styles for the moment. 

Thank's for your help :)

**Comment by dualshote** [comment]
<img width="405" alt="capture d ecran 2017-06-12 a 19 20 51" src="https://user-images.githubusercontent.com/5940350/27046342-552be814-4fa4-11e7-8e45-3360e4b64218.png">

This is a img from my DOM :/

**Comment by twinssbc** [comment]
@dualshote The init-position-scroll element in your snapshot is the container of the normal events.
Could you expand it to see if the child elements are rendered and where are they get rendered?

**Comment by dualshote** [comment]
@twinssbc Yeah i fount it into the init-position-scroll element ! Thank's ! But i don't understand why they are hidden... I verify all css properties but i don't understand witch property hide it....

<img width="1034" alt="capture d ecran 2017-06-13 a 19 14 46" src="https://user-images.githubusercontent.com/5940350/27095123-e924e99e-506c-11e7-8c35-4d86918422da.png">

**Comment by dualshote** [comment]
Ok, i found the solution. My calendar component is in a grid component that why the hours are hidden... Thank's for you help :)
