### ISSUE TITLE
Head to head on the contents of the calendar

### ISSUE THREAD

**Issue by Gtanxingwen** [twinssbc/Ionic2-Calendar#13]
![screenshot_2016-11-03-17-15-41-156_com ionicframe](https://cloud.githubusercontent.com/assets/18392906/19960752/aeed1f4e-a1e9-11e6-8291-bf4768766e39.png)

**Comment by Gtanxingwen** [comment]
@twinssbc i use android phone ,i am  chinese, help help help!!!  and i want clear '日' ,what should i do

**Comment by twinssbc** [comment]
@Gtanxingwen This is because DatePipe will use the local language as the locale by default, and the Chinese localisation seems not reasonable..
I have released a new version, 0.0.11, which will use 'en-US' as the locale when formatting the date in the month view.
Feel free to have a try.

**Comment by Jlabarca** [comment]
@twinssbc  How can I translate months and days? like using i18n on angular1's calendar

**Comment by twinssbc** [comment]
@Jlabarca The Angualr2 DatePipe formats the date using the local language on your device, so you don't need to do anything. But not sure how well it supports your language.

**Comment by Gtanxingwen** [comment]
@twinssbc the ion-header  cover the ion-content,running on the browser is no problem, running on the phone has been covered with a part,what should i do,
