### ISSUE TITLE
How display full width events 

### ISSUE THREAD

**Issue by fredlima87** [twinssbc/Ionic2-Calendar#130]
How can I display full-width events on DayCalendar by avoiding them side by side or 50% by the right?

**Comment by sacav1** [comment]
Hello and thanks for this awesome plugin !

I have the same question with two events which follow each other (the first ends at 9:30 and the second starts at 9:30).

How to display theses two events width full-width ? (like the picture below) 

![ionic-calendar](https://user-images.githubusercontent.com/32365066/30972025-c3b52c22-a469-11e7-9d86-718052a25435.png)

**Comment by twinssbc** [comment]
@sacav1 I can confirm it's a bug, will fix it later.

**Comment by twinssbc** [comment]
@sacav1 I have fixed this bug in the latest version. Feel free to have a try.
