### ISSUE TITLE
Method onTimeSelected is Called 3 Times in The Same Click Event

### ISSUE THREAD

**Issue by mfalzetta** [twinssbc/Ionic2-Calendar#139]
Hi friends,

All click in calendar page trigger 3 calls to onTimeSelected method and this make me load the content of calendar 3 times.
The method onCurrentDateChanged is called 3 times too.

I dont know if the issue (mentioned in the title) is a feature (bad configuration) or bug.

Someone can help me please?

**My page configuration:**

`<calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            [showEventDetail]="false"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            autoSelect="false"
            step="30">
  </calendar>
`

**My Softwares version:**

**"ionic2-calendar":** "^0.3.0"

**ionic --v**
3.4.0

**cordova --v**
7.0.1

**npm --v**
5.0.3

**uname -a**
Darwin Macbook-Pro 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017;

**Comment by twinssbc** [comment]
@mfalzetta Could you clarify which method is triggered 3 times? onCurrentDateChanged  or onTimeSelected? Also why do you load the events when triggering onCurrentDateChanged or onTimeSelected? Instead of loading the events in onRangeChanged?

**Comment by mfalzetta** [comment]
Hi @twinssbc 

Sorry, i don't see your response.

The method called 3 times is onTimeSelected.

I use onTimeSelected because a need load one event related at the selected date on calendar.

**Comment by mfalzetta** [comment]
Additionally, when i load the page in the first time, method onTimeSelected is triggered 3 times too.

**Comment by twinssbc** [comment]
@mfalzetta Could you provide code of your onTimeSelected method? I suspect it's related what you does in the method when it is triggered.
