### ISSUE TITLE
Module ''*'' has no exported member

### ISSUE THREAD

**Issue by SHELA** [twinssbc/Ionic2-Calendar#14]
Hi.
When i try emulate or build:

[23:40:22]  Error: Error at /Users/vlad/apps/eveses3/.tmp/pages/full/full.ngfactory.ts:149:36 
[23:40:22]  Module ''*'' has no exported member 'Wrapper_CalendarComponent'. 
[23:40:22]  ngc failed 
[23:40:22]  ionic-app-script task: "build" 
[23:40:22]  Error: Error 

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1

**Comment by twinssbc** [comment]
@SHELA May I know which version of Ionic, Angular and ionic2-calendar are you using?
Did you also follow **Note for Ionic Build/Run command** to add more lines in your main.prod.ts?

**Comment by SHELA** [comment]
@twinssbc 
ionic2-calendar - last from github
Ionic 2
Angular 2
when i add to main.prod.ts:
Unused import: 'CalendarComponent' 
Unused import: 'MonthViewComponent' 
Unused import: 'WeekViewComponent' 
Unused import: 'DayViewComponent' 
but build success, but when i can't open page where calendar. seems that some error

**Comment by twinssbc** [comment]
@SHELA Did you try to run it on IOS? I just found there's some localisation issue on IOS device as below.
https://github.com/angular/angular/issues/3333
I added the fix and published a new version, 0.0.12.
Could you try it? You also need to add Intl into the dependency. Thanks.

**Comment by omhybrid** [comment]
i havae same issue 
any solution?

**Comment by twinssbc** [comment]
@omhybrid  May I know which version of Ionic, Angular and ionic2-calendar are you using?
Did you also follow Note for Ionic Build/Run command to add more lines in your main.prod.ts?

**Comment by omhybrid** [comment]
i solve this thanks @twinssbc

**Comment by Gtanxingwen** [comment]
![image](https://cloud.githubusercontent.com/assets/18392906/20964685/7ca9d3d6-bcad-11e6-99a6-f498463525ec.png)
@twinssbc  怎么解决啊

**Comment by twinssbc** [comment]
@Gtanxingwen May I know which version of Ionic, Angular and ionic2-calendar are you using?
Did you also follow Note for Ionic Build/Run command to add more lines in your main.prod.ts?

**Comment by Gtanxingwen** [comment]
@twinssbc 
![image](https://cloud.githubusercontent.com/assets/18392906/20993979/95322e3c-bd28-11e6-88be-06898b9f5b06.png)
ionic-calendar 0.0.13

**Comment by twinssbc** [comment]
@Gtanxingwen what's your Angular version? Also did you add more lines in your main.prod.ts file?

**Comment by twinssbc** [comment]
@Gtanxingwen  You need to add below lines to main.prod.ts

```
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';
```
