### ISSUE TITLE
How can I change the first day of the week in monthview?

### ISSUE THREAD

**Issue by DennisBusk** [twinssbc/Ionic2-Calendar#140]
How can I change the first day of the week in monthview?

I have allready changed it in weekview.
But what about monthview?

**Comment by divijm** [comment]
Can you share how you changed it in the week-view please? @DennisBusk

**Comment by DennisBusk** [comment]
// Change the starting day in Week view
[startingDayWeek] = "startingDayWeek"

// Change  the starting day in Month view
[startingDayMonth] = "startingDayMonth"

  startingDayWeek = 1;
  startingDayMonth = 1;
