### ISSUE TITLE
calendar element is not getting loaded in component html

### ISSUE THREAD

**Issue by revanthmahesh** [twinssbc/Ionic2-Calendar#141]
'calendar' is not a known element:
1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component

**Comment by twinssbc** [comment]
@revanthmahesh Could you provide your dependencies in package.json?
Also did you add NgCalendarModule  in app.module.ts?
