### ISSUE TITLE
ionic cordova run android --prod won't allow Ionic2-Calendar

### ISSUE THREAD

**Issue by jordanpurinton** [twinssbc/Ionic2-Calendar#142]
I'm trying to run my app in prod mode, however I keep getting the following errors:

` 1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.`

I've already tried importing the `NO_ERRORS_SCHEMA` and `CUSTOM_ELEMENTS_SCHEMA` into my NgModule decorator in my module file, but I still keep getting the same.

Ionic Info:

```
global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 6.0.0
    Ionic CLI               : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 5.1.1, browser 4.1.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

```

**Comment by danielfnz** [comment]
Me too has this error! Are you solved it?

**Comment by jordanpurinton** [comment]
@danielfnz Unfortunately no, the only potential solutions I found online were to add those schemas into the NgModule decorator and those didn't do the trick for me. Have you found a workaround?

**Comment by twinssbc** [comment]
@jordanpurinton Could you try upgrading your ionic-angular dependency to a newer version?
Below is the dependencies in my package.json and it works ok when running ionic cordova run android --prod
```
"dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.10.2",
        "@ionic-native/splash-screen": "3.10.2",
        "@ionic-native/status-bar": "3.10.2",
        "@ionic/storage": "2.0.1",
        "cordova-android": "^6.2.3",
        "cordova-plugin-console": "^1.0.5",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.2",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.4.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
```

Also did you add NgCalendarModule in app.module.ts?

**Comment by jordanpurinton** [comment]
@twinssbc This resolved my issue, however now I'm getting template parse error:

> Error: Template parse errors:
Can't bind to 'monthviewDisplayEventTemplate' since it isn't a known property of 'calendar'. ("

I won't paste the whole error, but it essentially says this about all of the other fields in <calendar>

**Comment by jordanpurinton** [comment]
Wellp, not too sure how, but the prod build is working now. I'll close this for now and repost here if figure out why it's working now.

**Comment by bankai14** [comment]
Someone would have an answer?

**Comment by twinssbc** [comment]
@bankai14 Did you meet the same error? Did you upgrade your package.json recently? Maybe you could try using a clean project?

**Comment by enriquegarciagutierrez** [comment]
Any solution for this? I'm still getting the same error with `"ionic2-calendar": "^0.4.3"`

**Comment by twinssbc** [comment]
@enriquegarciagutierrez What error did you get? And how did you get the error? Could you provide your POM?
