### ISSUE TITLE
How to hide allDayLabel in week view and day view

### ISSUE THREAD

**Issue by santoshmodi** [twinssbc/Ionic2-Calendar#143]
Hi,
How to hide allDayLabel in week view and day view. I don't want to show allDayLabel . Is there any way to do this?

thanks

**Comment by twinssbc** [comment]
@santoshmodi Yes, you could apply display:none to weekview-allday-label and dayview-allday-label css class.

**Comment by ryaa** [comment]
The below worked for me

`
  .weekview-allday-table,
  .dayview-allday-table {
    display: none;
  }
  init-position-scroll {
    &.weekview-normal-event-container {
      margin-top: 37px;
    }
    &.dayview-normal-event-container {
      margin-top: 0px;
    }
  }
`
