### ISSUE TITLE
How to configure with firebase

### ISSUE THREAD

**Issue by wilsoncx** [twinssbc/Ionic2-Calendar#144]
Hello,
I would like a help, I was wanting to use the firebase as a database it is realtime, so I wanted to be able to change the current events to load at the beginning or directly from the bank without needing to be giving a reload at the bank, have to do this could give me Help in this.

**Comment by divijm** [comment]
Hey @wilsoncx - how did you manage to get around this? Did you find a solution? I am thinking to integrate my app with firebase too for live database.

**Comment by wilsoncx** [comment]
Not yet, but I'm still trying to solve this problem.

**Comment by divijm** [comment]
Please share once you are able to come to a working solution! :)

**Comment by twinssbc** [comment]
Hi, I think how to use firebase is out of the scope of this control.
The calendar refreshes its view as long as eventSource is changed.
If you want to load the events at the beginning, you could add logic in ngAfterViewInit or ionViewDidLoad hook like below.

```
  ionViewDidLoad() {
    this.loadEvents();
  }
```

**Comment by wilsoncx** [comment]
` onRangeChanged(ev) {
         let loader = this.loadingCtrl.create({
        content: "Caregando Eventos...",
        });
       loader.present();
               let tmp = [];
          this.authData.getEventos().subscribe(evento=> {
            evento.forEach(element => {
                tmp.push({
                codigo: element.$key,    
                title: element.title,
                description: element.description,
                startTime: new Date(element.startTime),
                endTime: new Date(element.endTime),
                allDay: element.allDay,
                local:element.local
                     })               
            });
           loader.dismiss();
            this.eventSource = tmp;
            console.log(this.eventSource)
      },(err) =>{
        console.log(err)
    })
    }`

I did so and it worked,
Thanks

**Comment by ramogundogdu** [comment]
@wilsoncx can you please share here how you implemented the calendar with Firebase, especially the method  `getEventos()` ?
