### ISSUE TITLE
Customising the hours on the Week View

### ISSUE THREAD

**Issue by divijm** [twinssbc/Ionic2-Calendar#145]
I want to customize a few things on the hour column - any help would be much appreciated. 

1. I want to only show every second hour on the left-hand side - e.g 6am, 8am, 10am etc. 

2. I want to start the hour column at 06:00 rather than the current 00:00. I know there is a scroll-to-hour view functionality but I would rather get rid of those initial hours at the start of the page and push them to the end. So ideally, the range would start from 06:00 and go till 05:00 at the end.

3. How do I adjust the hour column format. I want to adjust from '8 AM' to '8am'. I tried using:
formatHourColumn
Default value: ‘j’

Not sure what the format should be though to make it do what I need it to do - that is, appear in the format of '8am'

Thanks! :)

**Comment by twinssbc** [comment]
@divijm Below are my comments.
1. It's not supported to show every second hour unless changing source code.
2. You could apply margin-top to hide part of the hour rows.
```
  .weekview-normal-event-table {
    margin-top: -100px;
  }
```
3. The format in default DatePipe doesn't support am in lowercase. You could use dateFormatter option to write a custom formatWeekViewHourColumn and formatDayViewHourColumn. You could get more usage from the README.

**Comment by divijm** [comment]
Thanks @twinssbc for your replies. I had tried using the dateFormatter option through the Readme - but wasn't successful in implementing what I want to do for dot point number 3. So if I started at 00:00 and wanted to place that value in the first cell on the hour column and continue till the 24:00 - what would I put in the date formatter:

Current work in progress - 
```
dateFormatter: {
     formatWeekViewHourColumn: function(date:Date) {
       var hourNames = [];
       for (var hour = 0; hour < 24; hour += 1) {
       hourNames.push();
     }
       return hourNames;
     },
```

**Comment by twinssbc** [comment]
@divijm formatWeekViewHourColumn accepts a date parameter and returns a corresponding string, instead of all hour names.
For example,
```
dateFormatter: {
     formatWeekViewHourColumn: function(date:Date) {
         return date.getHour();
     },
```

Actually you could also use this formatter to achieve your first requirement.
You just need to return empty string if the date is at 1 am, 3 am, 5 am...
