### ISSUE TITLE
How to customize dynamically weekview hour range?

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#146]
The default hour range is from 12AM to 11PM, is there any way to customize this according to the hour of earliest and latest event?

**Comment by twinssbc** [comment]
@Astacius Do you mean you want to change the hour range based on the events in this week? What if there's no event in the current week?
If you just want to change to a fixed range, you could set margin-top and height of weekview-normal-event-table like below. But it won't support set different range in each week.

```
.weekview-normal-event-table {
    margin-top: -100px;
  }
```
Or you could use scrollToHour option to scroll the view to a specific hour by default.

**Comment by Astacius** [comment]
Is there any way to set scrollToHour according to current week? Not only globally?

**Comment by twinssbc** [comment]
@Astacius Unfortunately scrollToHour is used during the weekview initialization phase. Once it's set, navigating between weeks always use the same value. You could use some low level DOM selection query to locate the list and scroll it to your desired position.
