### ISSUE TITLE
Translate days in month-view

### ISSUE THREAD

**Issue by Li3wish** [twinssbc/Ionic2-Calendar#147]
Hi, first of all thank you for your amazing job.

I'm develloping an app using your calendar and it's translated in four languages. Therefore, I need the days to be translated too. I've seen the trick using LOCAL_ID but I can't use it while there is the possibility of multiple languages.

What I'm using elsewhere in my code is moment.js. Is it possible to access the days and format it with moment([day]).format('ddd')? If not, how can I manage to do it?

Btw sorry for my english, I'm not fluent.

**Comment by twinssbc** [comment]
@Li3wish I think you could use dateFormatter option. It allows you to write several custom format method. You could get more detail from README.

**Comment by Li3wish** [comment]
@twinssbc Thanks for answering that fast. It works like a charm.
