### ISSUE TITLE
Error: ./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.ngfactory.ts Module build failed: TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by chd999** [twinssbc/Ionic2-Calendar#148]
use ionic cordova build ios --prod

ionic_app-scripts1.3.4 no error , but ios app Can't use
ionic_app-scripts1.3.4----ionic_app-scripts1.3.12 error

leetekiMac-mini:MyTest0013 xyw$ sudo ionic cordova build ios --prod
✔ Creating ./www directory for you - done!
> cordova platform add --save ios
✔ Running command - done!
Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[09:52:15]  build prod started ... 
[09:52:15]  clean started ... 
[09:52:15]  clean finished in 1 ms 
[09:52:15]  copy started ... 
[09:52:15]  ngc started ... 
[09:52:25]  ngc finished in 10.53 s 
[09:52:25]  preprocess started ... 
[09:52:25]  deeplinks started ... 
[09:52:25]  deeplinks finished in 75 ms 
[09:52:25]  optimization started ... 
[09:52:26]  copy finished in 11.17 s 
[WARN] Error occurred during command execution from a CLI plugin
       (@ionic/cli-plugin-cordova). Your plugins may be out of date.
Error: ./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.ngfactory.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/xu_yw/Downloads/MyTest0013/node_modules/_@ionic_app-scripts@1.3.12@@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/xu_yw/Downloads/MyTest0013/node_modules/_@ionic_app-scripts@1.3.12@@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 55:0-82
 @ ./src/app/main.ts,./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.module.js
Module not found: Error: Can't resolve 'intl' in '/Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar'
resolve 'intl' in '/Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar'
  Parsed request is a module
  using description file: /Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/package.json (relative path: .)
    resolve as module
      /Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/node_modules doesn't exist or is not a directory
      /Users/xu_yw/Downloads/MyTest0013/node_modules/node_modules doesn't exist or is not a directory
      /Users/xu_yw/Downloads/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/xu_yw/Downloads/MyTest0013/node_modules
        using description file: /Users/xu_yw/Downloads/MyTest0013/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/xu_yw/Downloads/MyTest0013/package.json (relative path: ./node_modules)
          using description file: /Users/xu_yw/Downloads/MyTest0013/package.json (relative path: ./node_modules/intl)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl.ts doesn't exist
            as directory
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl doesn't exist
      looking for modules in /Users/xu_yw/node_modules
        using description file: /Users/xu_yw/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/xu_yw/package.json (relative path: ./node_modules)
          using description file: /Users/xu_yw/package.json (relative path: ./node_modules/intl)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/node_modules/intl doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/node_modules/intl.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/node_modules/intl.ts doesn't exist
            as directory
              /Users/xu_yw/node_modules/intl doesn't exist
[/Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/node_modules]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/node_modules]
[/Users/xu_yw/Downloads/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl.js]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl.ts]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl]
[/Users/xu_yw/node_modules/intl]
[/Users/xu_yw/node_modules/intl.js]
[/Users/xu_yw/node_modules/intl.ts]
[/Users/xu_yw/node_modules/intl]
 @ ./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.module.js 3:0-14
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.module.js
Module not found: Error: Can't resolve 'intl/locale-data/jsonp/en' in '/Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar'
resolve 'intl/locale-data/jsonp/en' in '/Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar'
  Parsed request is a module
  using description file: /Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/package.json (relative path: .)
    resolve as module
      /Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/node_modules doesn't exist or is not a directory
      /Users/xu_yw/Downloads/MyTest0013/node_modules/node_modules doesn't exist or is not a directory
      /Users/xu_yw/Downloads/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/xu_yw/Downloads/MyTest0013/node_modules
        using description file: /Users/xu_yw/Downloads/MyTest0013/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/xu_yw/Downloads/MyTest0013/package.json (relative path: ./node_modules)
          using description file: /Users/xu_yw/Downloads/MyTest0013/package.json (relative path: ./node_modules/intl/locale-data/jsonp/en)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en.ts doesn't exist
            as directory
              /Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en doesn't exist
      looking for modules in /Users/xu_yw/node_modules
        using description file: /Users/xu_yw/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/xu_yw/package.json (relative path: ./node_modules)
          using description file: /Users/xu_yw/package.json (relative path: ./node_modules/intl/locale-data/jsonp/en)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/node_modules/intl/locale-data/jsonp/en doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/node_modules/intl/locale-data/jsonp/en.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/xu_yw/node_modules/intl/locale-data/jsonp/en.ts doesn't exist
            as directory
              /Users/xu_yw/node_modules/intl/locale-data/jsonp/en doesn't exist
[/Users/xu_yw/Downloads/MyTest0013/node_modules/_ionic2-calendar@0.3.7@ionic2-calendar/node_modules]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/node_modules]
[/Users/xu_yw/Downloads/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en.js]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en.ts]
[/Users/xu_yw/Downloads/MyTest0013/node_modules/intl/locale-data/jsonp/en]
[/Users/xu_yw/node_modules/intl/locale-data/jsonp/en]
[/Users/xu_yw/node_modules/intl/locale-data/jsonp/en.js]
[/Users/xu_yw/node_modules/intl/locale-data/jsonp/en.ts]
[/Users/xu_yw/node_modules/intl/locale-data/jsonp/en]
 @ ./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.module.js 4:0-35
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts

leetekiMac-mini:MyTest0013 xyw$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    npm        : 3.10.10 

✔ Creating ./www directory for you - done!
> cordova platform add --save ios
✔ Running command - done!
Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[15:17:47]  build prod started ... 
[15:17:47]  clean started ... 
[15:17:47]  clean finished in 1 ms 
[15:17:47]  copy started ... 
[15:17:47]  ngc started ... 
[15:17:59]  ngc finished in 12.20 s 
[15:17:59]  preprocess started ... 
[15:17:59]  deeplinks started ... 
[15:17:59]  deeplinks finished in 57 ms 
[15:17:59]  optimization started ... 
[15:18:00]  copy finished in 12.92 s 
[WARN] Error occurred during command execution from a CLI plugin
       (@ionic/cli-plugin-cordova). Your plugins may be out of date.
Error: ./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.ngfactory.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (/Users/xu_yw/Downloads/MyTest0013/node_modules/_@ionic_app-scripts@1.3.12@@ionic/app-scripts/dist/webpack/optimization-loader-impl.js:14:24)
    at Object.loader (/Users/xu_yw/Downloads/MyTest0013/node_modules/_@ionic_app-scripts@1.3.12@@ionic/app-scripts/dist/webpack/optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 55:0-82
 @ ./src/app/main.ts

leetekiMac-mini:MyTest0013 xyw$

**Comment by twinssbc** [comment]
@chd999 You need to install intl
```
npm install intl@1.2.5
```

**Comment by chd999** [comment]
@twinssbc   sorry， I forgot to  install intl.    but  ，  After the installation.

ionic_app-scripts1.3.4 no error , but ios app Can't use
ionic_app-scripts1.3.5----ionic_app-scripts1.3.12 error

**Comment by chd999** [comment]
I have updated the  issue.
There is a new error message.

**Comment by twinssbc** [comment]
@chd999 What's the new error message?

**Comment by chd999** [comment]
@twinssbc 

✔ Creating ./www directory for you - done!

cordova platform add --save ios
✔ Running command - done!
Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser
[15:17:47] build prod started ...
[15:17:47] clean started ...
[15:17:47] clean finished in 1 ms
[15:17:47] copy started ...
[15:17:47] ngc started ...
[15:17:59] ngc finished in 12.20 s
[15:17:59] preprocess started ...
[15:17:59] deeplinks started ...
[15:17:59] deeplinks finished in 57 ms
[15:17:59] optimization started ...
[15:18:00] copy finished in 12.92 s
[WARN] Error occurred during command execution from a CLI plugin
(@ionic/cli-plugin-cordova). Your plugins may be out of date.
Error: ./~/ionic2-calendar@0.3.7@ionic2-calendar/calendar.ngfactory.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
at Object.optimizationLoader (/Users/xu_yw/Downloads/MyTest0013/node_modules/@ionic_app-scripts@1.3.12@/dist/webpack/optimization-loader-impl.js:14:24)
at Object.loader (/Users/xu_yw/Downloads/MyTest0013/node_modules/_@ionic_app-scripts@1.3.12@/dist/webpack/optimization-loader.js:5:32)
@ ./src/app/app.module.ngfactory.js 55:0-82
@ ./src/app/main.ts

leetekiMac-mini:MyTest0013 xyw$

**Comment by twinssbc** [comment]
@chd999 It's probably related to ionic-app-scripts.
There was same issue created and some user also works when downgrading to 1.3.4.
https://github.com/ionic-team/ionic-app-scripts/issues/1010

**Comment by chd999** [comment]
@twinssbc
Thank you, I see.

**Comment by lopezhansel** [comment]
## Possible Solution
I believe a webpack plugin decided to no longer accepts my declaration files that had the extension `.d.ts`.  **I had a file with only type annotations named `user.d.ts` and I was forced to rename it to `user.ts`.** This allowed me to get passed the error. 

## More Insight  
I had the same error where `Module build failed: TypeError: Cannot read property 'content' of undefined`. 

I didn't change any of my code, this only happened after I updated `@ionic/app-scripts@2.1.4`. I also tried  `@ionic/app-scripts@2.0.2` and got the same error.

While `ionic-app-scripts serve` worked flawlessly, `ionic-app-scripts build --prod --release` stopped working. 

"Properly" downgrading or updating to different versions Angular, Ionic-Angular,and @angular/cli didn't fix the error. I was using the current versions.
 - @angular/common@4.3.6
 - Ionic-Angular@3.6.1
 - @angular/cli@1.4.3


### Ionic Info: 
```
@ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.3
    Node              : v7.4.0
    npm               : 4.0.5
    OS                : Windows 10
```

**Comment by duffayapps** [comment]
Did anyone find a solution for this? Calendar runs on device ok but compiling error when building for release apk. Any advise is greatly appreciated on how to build for release.

**Comment by twinssbc** [comment]
@duffayapps What exact error did you get?

**Comment by duffayapps** [comment]
Error: ./node_modules/ionic2-calendar/calendar.ngfactory.ts
Module build failed: Error: No element indexed by 1

Error seen above when using the following command " ionic cordova build android --prod". 
The calendar runs well on ionic serve and the device but will not run on production any solutions greatly appreciated.

**Comment by duffayapps** [comment]
This issue is a matter of urgency I cannot release app without the fix. I will donate money to anyone that can solve this. It's too late to use an alternative calendar at this stage.

**Comment by twinssbc** [comment]
@duffayapps which version of ionic and calendar are you using?
It seems this error is caused when generating source map. Maybe you could try disable sourcemap?

**Comment by duffayapps** [comment]
Thaks for your reply.
"ionic2-calendar": "^0.3.7",
"@angular/common": "5.0.0",
 "@angular/compiler": "5.0.0";
How do you disable sourcemap?

**Comment by duffayapps** [comment]
@twinssbc  cant disable sourcemap.

The "tsconfig.json" file must have compilerOptions.sourceMap set to true.

**Comment by twinssbc** [comment]
@twinssbc If you already upgrade to angular 5.0.0, you need to upgrade Ionic version to at least 3.9.2 and ionic2-calendar version to 0.4.x. It has been stated in README.
I suggest you start a new Ionic project, otherwise you may have some incompatible dependencies if you do in-place upgrade.

**Comment by prathyushp1** [comment]
npm install intl@1.2.5 works for me

**Comment by abmnukmr** [comment]
@duffayapps  
i am giving you working solution

**copy calendar folder from node modules**

![screen shot 2018-06-13 at 6 01 34 pm](https://user-images.githubusercontent.com/14125496/41351505-3081fd54-6f34-11e8-8cea-38b13a83d48d.png)
**then  paste in component folder**
![screen shot 2018-06-13 at 5 50 44 pm](https://user-images.githubusercontent.com/14125496/41351555-5a528b26-6f34-11e8-8a2f-3e49bbb202dc.png)
go to appmodule.ts
![screen shot 2018-06-13 at 5 52 05 pm](https://user-images.githubusercontent.com/14125496/41351666-b9943d6e-6f34-11e8-9024-f9c26ae6234c.png)


**then** =============>>>>>>>>>>
==>>>>>>>>>>>>>>>>
![screen shot 2018-06-13 at 5 51 44 pm](https://user-images.githubusercontent.com/14125496/41351688-c9270b8a-6f34-11e8-8925-4bc5688983b3.png)

**then** =============>>>>>>>>>>
==>>>>>>>>>>>>>>>>

![screen shot 2018-06-13 at 5 52 37 pm](https://user-images.githubusercontent.com/14125496/41351693-d04f4620-6f34-11e8-9558-64361524c5fb.png)
