### ISSUE TITLE
Displaying events by date

### ISSUE THREAD

**Issue by wilsoncx** [twinssbc/Ionic2-Calendar#150]
![sample_project_-_page_ _moqups](https://user-images.githubusercontent.com/5439657/28146546-2f08aa72-6751-11e7-932e-edd2df551282.png)

I would like to know how to view the events only by date without the calendar, more or less like this image.

**Comment by twinssbc** [comment]
@wilsoncx You don't have to always display events using this calendar control, you could easily create your own page which contain a list to display the events happen on a particular day.
