### ISSUE TITLE
Calendar Current Time Red Line

### ISSUE THREAD

**Issue by divijm** [twinssbc/Ionic2-Calendar#151]
Hi @twinssbc - feature request for this functionality please

A live time-tracker denoted with a red-line marker or similar. 

![how-to-use-google-calendar-to-create-an-event-8-638](https://user-images.githubusercontent.com/25699280/28248938-6bc4fcf8-6a90-11e7-9057-c43167f5f9d4.jpg)

**Comment by arulmanoa** [comment]
@divijm did you find that solution. please update your code

**Comment by Thisisnarayan** [comment]
Any solution you found of current time indicator for day view and week view

**Comment by srephaniejoyce** [comment]
Is there a solution for this feature ?
