### ISSUE TITLE
allDay with momentjs is not working as expected

### ISSUE THREAD

**Issue by patrickbussmann** [twinssbc/Ionic2-Calendar#153]
I'm using version `^2.18.1` of `moment` and `^0.3.7` of `ionic2-calendar`.
And if I try to load events from my custom remote backend via API and show them in the calendar I see the events on wrong date.
I think there is a problem with the understanding of your sentence with `If allDay is set to true, the startTime has to be as a UTC date`.

## Test 1

![2017-07-17 01_31_58-kalender](https://user-images.githubusercontent.com/15617021/28252256-c1159ff6-6a8f-11e7-9bcb-efb8b2a8805f.png)

```javascript
    this.eventSource = [
      {
        title: 'Test 1',
        startTime: moment('2017-07-17 00:53:08').toDate(),
        endTime: moment('2017-07-17 00:53:08').toDate(),
        allDay: false
      },
      {
        title: 'Test 2',
        startTime: moment('2017-07-18 01:03:44').startOf('day').utc().toDate(),
        endTime: moment('2017-07-18 03:03:44').startOf('day').utc().toDate(),
        allDay: true
      }
    ];
```

**Expected:** That the `allDay` event is present only on 18th and not on 17th. Currently the 17th contains both events and the 18th contains no events.

## Test 2

![2017-07-17 01_46_11-kalender](https://user-images.githubusercontent.com/15617021/28252358-baea5296-6a91-11e7-8a23-88c97c898d7b.png)

```javascript
    this.eventSource = [
      {
        title: 'Test 1',
        startTime: moment('2017-07-17 00:53:08').toDate(),
        endTime: moment('2017-07-17 02:53:08').toDate(),
        allDay: false
      },
      {
        title: 'Test 2',
        startTime: new Date(Date.UTC(2017, 6, 18)),
        endTime: new Date(Date.UTC(2017, 6, 19)),
        allDay: true
      }
    ];
```

**Expected:** Now I'm using the data of the example in the documentation. This is working and the event is shown on 18th. But how to solve this with `momentjs`?

Thank's in Advance!

**Comment by patrickbussmann** [comment]
I fixed this temporarily with this function.

```javascript
this.eventSource.push({
  title: event.title,
  startTime: this.convertDateToCalendarUtc(event.start_time),
  endTime: this.convertDateToCalendarUtc(event.end_time || event.start_time),
  allDay: event.all_day
});
```

```javascript
convertDateToCalendarUtc(date: string) {
  // date = '2017-07-18T00:00:00+02:00'
  let realDate = moment(date);
  return new Date(Date.UTC(realDate.year(), realDate.month(), realDate.date(), realDate.hour(), realDate.minute(), realDate.second(), realDate.millisecond()));
}
```

Maybe there is a better solution but this is the only one I can work with at the moment 👍

**Comment by twinssbc** [comment]
I think you need to make sure the hour, minute and second part are all 0, even when converting using momentjs.

**Comment by patrickbussmann** [comment]
No this is no problem, @twinssbc.
I need this because I convert all calendar dates using this function.
No matter if `allDay` is true or false.
But it seems to be working completely for all cases 👍
