### ISSUE TITLE
Swiping issue

### ISSUE THREAD

**Issue by Abhishekl90** [twinssbc/Ionic2-Calendar#154]
Hi,
I am getting this error

`Error: Error in ./MonthViewComponent class MonthViewComponent - inline template:2:12 caused by: Invalid regular expression: unmatched parentheses`

while swiping to next or previous months. What is the issue I am not able to figure it out
Thanks

**Comment by twinssbc** [comment]
@Abhishekl90 Did you customize anything? Maybe you could provide the code snippet that using this calendar control?
