### ISSUE TITLE
How can I update time in event display?

### ISSUE THREAD

**Issue by EiJiKo** [twinssbc/Ionic2-Calendar#155]
I used date array  like this.
var startArr=["2017-06-13 00:00:00","2017-06-13 02:00:00","2017-06-13 03:00:00","2017-06-13 04:00:00"];
 var endArr=["2017-06-14 00:00:00","2017-06-14 002:02:00","2017-06-14 03:03:00","2017-06-14 04:04:00"];

In UI, time is showing like this. 
![git](https://user-images.githubusercontent.com/30255272/28304942-5b12265c-6b89-11e7-9001-f03372952872.png)

It shows all time 06:30 - 06:30 (May be GMT+0630 standard time zone )! I have **2 things** to ask.
## 2) How can I do if I dont want to show time (06:30 - 06:30)?
Thanks in advance. Please share me your thought.

**Comment by twinssbc** [comment]
@EiJiKo You could use monthviewEventDetailTemplate option to customize the look of this section.
You could get more information from README.

**Comment by EiJiKo** [comment]
@twinssbc Thanks a lot. It is a real solution.
