### ISSUE TITLE
Calendar not showing up

### ISSUE THREAD

**Issue by rangathedon** [twinssbc/Ionic2-Calendar#156]
I have tried the exact steps given to show a calendar in an ionic app but the calendar does not appear; how do I debug the behavior? I dont see any error on console either;

**Comment by twinssbc** [comment]
@rangathedon Maybe you could inspect the DOM element using the developer tool to see if the calendar element is rendered or not? Maybe it's hidden because of some other elements? If you could provide the code snippet that is using the calendar, that will be helpful.

**Comment by rangathedon** [comment]
the only element on the page is calendar element; I dont see it being
rendered; size sticks at 0, 0;

**Comment by twinssbc** [comment]
@rangathedon Could you provide the code that is using the calendar?

**Comment by rangathedon** [comment]
got it working; looks like the issue was with the project created with
ionic creator; ionic creator is a mess; thanks a lot for the support;
