### ISSUE TITLE
How to set background color of specific date(had event) in calendar?

### ISSUE THREAD

**Issue by EiJiKo** [twinssbc/Ionic2-Calendar#157]
In my calendar.ts, I have **eventSource** array like this..
 **event.push({
       title:holiday_desc[i],
       startTime:_startTime[i],
       endTime:_endTime[i],
       style:"background-color:rgb(255, 0, 0) !important;"
        });**
Then, holidays(with default setted background color) are shown in like that..

![git](https://user-images.githubusercontent.com/30255272/28407014-1dfb6504-6d22-11e7-9c46-323dd6445384.png)

But, I want that holidays date must show with **style:"background-color:rgb(255, 0, 0) !important;"**
In documentation , I read this-
![git](https://user-images.githubusercontent.com/30255272/28407688-915ac13c-6d24-11e7-8f98-0609fae4bccf.png)

When I add this, there is **no difference**. I think there should be somewhere to tell **#template** to know event of style,but I have no idea. **Please** help me by sharing your thought and experience. Thanks a lot in advance.

**Comment by twinssbc** [comment]
@EiJiKo As your title indicates, the holiday date has event attached?
You could give your event a special property, for example
```
event.push({
title:holiday_desc[i],
startTime:_startTime[i],
endTime:_endTime[i],
isHoliday: true
});
```

Then in your template, you could use ngClass to add css class depends on this field, for example
```
<template #template let-view="view" let-row="row" let-col="col">
    <div [ngClass]="{'holiday-cell': view.dates[row*7+col].events[0].isHoliday}">{{view.dates[row*7+col].label}}</div>
</template>
```

**Comment by EiJiKo** [comment]
**Yes** ! It worked @twinssbc . I have learned a lot because of you. Thanks you so much.
