### ISSUE TITLE
<ng-template> not show inside <ion-col> on android 6

### ISSUE THREAD

**Issue by thanhdk** [twinssbc/Ionic2-Calendar#159]
Hi, I have a problem to show dayview mode of calendar.
I have a screen that divide on 2 columns, 1 for display days of month and 1 for display dayview. I put the calendar inside ion-col with my custom template but it's not show on android 6, but android 8 is ok. Anyone have this issue?

**Comment by twinssbc** [comment]
@thanhdk Is there any error displayed in the console? If you try ng-template in your other page, does it work? Maybe you could also investigate if it's because of the different WebView version in android 6 and 8.

**Comment by thanhdk** [comment]
Yes, I have inspected on Chrome and found that there is different between android 6 and 8.
With android 8, the height of calendar can display with the attribute "height: 100%", but android 6 is not. So that I have to set the height programmatically depend on the contentHeight of device.

`ngAfterViewInit() {
        // Disable lockSwipes
          let vm = this;
        setTimeout(function () {
            //vm.lockSwipes = true;
            document.getElementsByClassName('dayview-container')[0].setAttribute('style', "height: " + vm.content.contentHeight + 'px');
        }, 1000);  

        this.scrollTo('item-' + this.arrDays.findIndex(x => x.isSame(this.selectedDay, 'day')));
        this.content.scrollToTop();
    }`

Is there any solution or hint for this case?

![1](https://user-images.githubusercontent.com/18607187/28553144-4ffb7000-711c-11e7-892d-059d6201d970.jpg)

**Comment by twinssbc** [comment]
@thanhdk Could you try just setting the height on dayview-container css class? 
```
.dayview-container
{
    height: 100%
}
```

**Comment by thanhdk** [comment]
Did you try that? I am sorry for my late response but I am not in charge on the project so maybe I will try on another project
