### ISSUE TITLE
Limit the range for weekview

### ISSUE THREAD

**Issue by jayh92** [twinssbc/Ionic2-Calendar#16]
Is it possible within the current build to limit the number of weeks (on weekview) that a user can swipe? Or if not, is it possible to implement this feature?

For example, I'd like to only allow them to swipe within the current month.

Thanks!

**Comment by twinssbc** [comment]
@jayh92 It requires quite a few code changes. If you want to modify the source code, you can start from populateAdjacentViews in the calendar.service.ts.
