### ISSUE TITLE
ionic3.5.0 used ionic2-Calendar

### ISSUE THREAD

**Issue by cgrddv** [twinssbc/Ionic2-Calendar#161]
hello,i have install typings and intl(1.2.5),but calendar directive is wrong
```
'calendar' is not a known element:
1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

```
anyone help me out , thanks

**Comment by twinssbc** [comment]
@cgrddv Did you follow README to import the calendar module? Maybe you could show the related code  that is using the calendar?

**Comment by cgrddv** [comment]
**thank your help**
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { MyApp } from './app.component';
import { Logger,UtilService } from '../services/';
import { NgCalendarModule } from 'ionic2-calendar';
@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    NgCalendarModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ],
  providers: [
    StatusBar,
    SplashScreen,
    Logger,
    UtilService,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ],
})
export class AppModule {}

**then in pages:**

import {Component, OnInit} from '@angular/core';
import { NavParams } from 'ionic-angular';
import { IonicPage } from 'ionic-angular';
import { UtilService } from '../../services';

@IonicPage()

@Component({
  templateUrl: './other-page.html'
})
export class OtherPage implements OnInit{
  id:string;
  name:string;
  constructor(private navParams: NavParams,private UtilService:UtilService) {
    this.id = this.navParams.get('id');
    this.name = this.UtilService.getTime('yyyy_MM-dd hh:mm:ss');//navParams.get('name');
  }

  ngOnInit(){
    this.loadEvents()
  }

  eventSource;
  viewTitle;
  isToday: boolean;
  calendar = {
    mode: 'month',
    currentDate: new Date()
  }; // these are the variable used by the calendar.
  loadEvents() {
    this.eventSource = this.createRandomEvents();
  }
  onViewTitleChanged(title) {
    this.viewTitle = title;
  }
  onEventSelected(event) {
    console.log('Event selected:' + event.startTime + '-' + event.endTime + ',' + event.title);
  }
  changeMode(mode) {
    this.calendar.mode = mode;
  }
  today() {
    this.calendar.currentDate = new Date();
  }
  onTimeSelected(ev) {
    console.log('Selected time: ' + ev.selectedTime + ', hasEvents: ' +
      (ev.events !== undefined && ev.events.length !== 0) + ', disabled: ' + ev.disabled);
  }
  onCurrentDateChanged(event:Date) {
    var today = new Date();
    today.setHours(0, 0, 0, 0);
    event.setHours(0, 0, 0, 0);
    this.isToday = today.getTime() === event.getTime();
  }
  createRandomEvents() {
    var events = [];
    for (var i = 0; i < 50; i += 1) {
      var date = new Date();
      var eventType = Math.floor(Math.random() * 2);
      var startDay = Math.floor(Math.random() * 90) - 45;
      var endDay = Math.floor(Math.random() * 2) + startDay;
      var startTime;
      var endTime;
      if (eventType === 0) {
        startTime = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + startDay));
        if (endDay === startDay) {
          endDay += 1;
        }
        endTime = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + endDay));
        events.push({
          title: 'All Day - ' + i,
          startTime: startTime,
          endTime: endTime,
          allDay: true
        });
      } else {
        var startMinute = Math.floor(Math.random() * 24 * 60);
        var endMinute = Math.floor(Math.random() * 180) + startMinute;
        startTime = new Date(date.getFullYear(), date.getMonth(), date.getDate() + startDay, 0, date.getMinutes() + startMinute);
        endTime = new Date(date.getFullYear(), date.getMonth(), date.getDate() + endDay, 0, date.getMinutes() + endMinute);
        events.push({
          title: 'Event - ' + i,
          startTime: startTime,
          endTime: endTime,
          allDay: false
        });
      }
    }
    return events;
  }
  onRangeChanged(ev) {
    console.log('range changed: startTime: ' + ev.startTime + ', endTime: ' + ev.endTime);
  }
  markDisabled = (date:Date) => {
    var current = new Date();
    current.setHours(0, 0, 0);
    return date < current;
  };

}`
**in html :** 
<ion-header>
  <ion-navbar color="primary">
    <ion-title>{{viewTitle}}</ion-title>
    <ion-buttons end>
      <button ion-button [disabled]="isToday" (click)="today()">Today</button>
      <button ion-button (click)="changeMode('month')">M</button>
      <button ion-button (click)="changeMode('week')">W</button>
      <button ion-button (click)="changeMode('day')">D</button>
      <button ion-button (click)="loadEvents()">Load Events</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content class="has-header">
  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onRangeChanged)="reloadSource(startTime, endTime)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30">
  </calendar>
</ion-content>
when i run the serve,it throw that problem

**Comment by cgrddv** [comment]
<ion-header>
  <ion-navbar color="primary">
    <ion-title>{{viewTitle}}</ion-title>
    <ion-buttons end>
      <button ion-button [disabled]="isToday" (click)="today()">Today</button>
      <button ion-button (click)="changeMode('month')">M</button>
      <button ion-button (click)="changeMode('week')">W</button>
      <button ion-button (click)="changeMode('day')">D</button>
      <button ion-button (click)="loadEvents()">Load Events</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content class="has-header">
  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onRangeChanged)="reloadSource(startTime, endTime)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30">
  </calendar>
</ion-content>
here the code left about html

**Comment by twinssbc** [comment]
@cgrddv Are you using IonicPage in your project? Because I see you import it in your component.
Although you use ionicpage() in lowercase, which I don't think is correct.
If you are using IonicPage, you should also have a PageModule. You need to import the calendar module in this PageModule instead of AppModule.

http://ionicframework.com/docs/api/navigation/IonicPage/

**Comment by cgrddv** [comment]
@twinssbc yes! I did what you said ,it's work.thanks very much. i use **ionicpage** want to make the app lazy load .thanks again.
