### ISSUE TITLE
Programatically trigger swipe left/right?

### ISSUE THREAD

**Issue by plindsay** [twinssbc/Ionic2-Calendar#162]
Hi, finding this library very useful for my app, I have a query though. Is there a way of programmatically swiping or moving the calendar either left or right (I'm was thinking of something similar to the slideNext() or slidePrev() functionality of the built-in Ionic Slides component).

e.g. I want to have buttons above the calendar which also trigger a swipe when clicked/tapped.

Cheers, Phil

**Comment by twinssbc** [comment]
@plindsay You could change currentDate to the date in previous/next month.

**Comment by plindsay** [comment]
Ah I see... thank you - I will try this and let you know how I get on 👍

**Comment by plindsay** [comment]
Great, I ended up doing this -

```
previousMonth() {
	this.calendar.currentDate = moment(this.calendar.currentDate).subtract(1, 'month').toDate();
}

nextMonth() {
	this.calendar.currentDate = moment(this.calendar.currentDate).add(1, 'month').toDate();
}
```

Getting it to animate left/right would've been nice, but it's not a big deal. Thanks for the pointers!

**Comment by jayzyaj** [comment]
@plindsay I tried to do that but it has a conflcit if I call it programmatically and I swipe after it. To explain further: 
Today is Sept 14, 2018 here in PH. Now I swipe to the next month which is October. Now I tried to click the button to trigger the nextMonth() method. But after I click the button it still went to october which suppose to be november.

**Comment by twinssbc** [comment]
@jayzyaj What's the logic in your nextMonth method? In theory, if you set the currentDate properly, the calendar will navigate to the corresponding month automatically.
