### ISSUE TITLE
Styling ionic2-calendar

### ISSUE THREAD

**Issue by moniquenichols92** [twinssbc/Ionic2-Calendar#163]
I'm trying to style the calendar in my scss file and I am able to change the font and font color by specifying calendar{ "some style here"} but I can't seem to edit the calendar background here and borders.

What element or class do I specify to change the background of the calendar? To change the background of the current day (now shown in green)? To remove the borders? 

Any help is greatly appreciated!

Monique

**Comment by moniquenichols92** [comment]
Hey everyone I found the answer to this question in another user's post.copying below for reference:

  .monthview-selected {
    background-color: transparent !important;
    color: black !important;
  }

  td.monthview-current {
    color: white;

    .calendar-day {
      background-color: color($colors, 'light') !important;
    }
  }

  .monthview-datetable {
    border: 0 !important;

    td, th {
      border: 0 !important;
      padding: 3px!important;
      background-color: transparent!important;
    }
  }

  .calendar-day {
    border-radius: 6px;
    padding: 3px 5px;

    &.primary {
      background-color: color($colors, 'primary');
      color: white;
    }

    &.success {
      background-color: color($colors, 'success');
      color: white;
    }

    &.warning {
      background-color: color($colors, 'warning');
      color: white;
    }

    &.danger {
      background-color: color($colors, 'danger');
      color: white;
    }
  }

**Comment by twinssbc** [comment]
@moniquenichols92 I'm glad that you found the solution by yourself.
