### ISSUE TITLE
Applying styling to only first and last days on a multi-day event

### ISSUE THREAD

**Issue by monichols** [twinssbc/Ionic2-Calendar#166]
I'm attempting to configure the style of only the first and last day of an event spanning 2 or more days. I am trying to recreate this:

![fd9dc0c2279308b0c265235a9e48b1ea--application-design-mobile-application](https://user-images.githubusercontent.com/26590425/28748188-26071766-747f-11e7-86c7-370b7336ba14.jpg)

 I created a template: 

html:
 <template #template let-view="view" let-row="row" let-col="col">
    <div class="calendar-day {{ view.dates[row*7+col].events[0]?.color }}">
      {{view.dates[row*7+col].label}}
    </div>
  </template>

ts:
  this.eventSource.push({
           title: eventData1.title,
           startTime: eventData1.startTime,
           endTime: eventData1.endTime,
           allDay: false,
           color: eventData1.color
           });

but when I apply style using :nth-last-child(1) all of the days within the event change style not just the last day. :last-child yields the same issue.

any suggestions?

**Comment by twinssbc** [comment]
@monichols How do you want to handle the situation that there are more than one events on a day?

**Comment by monichols** [comment]
I would like to give the event spanning multiple days priority i.e. if there is no multi day event then the single day events will be displayed visually. If there is a multi day event then only the multi day event will be displayed visually.

**Comment by twinssbc** [comment]
@monichols Below is the default template, it accepts three variables, view, row and col.

```
        <template #monthviewDefaultDisplayEventTemplate let-view="view" let-row="row" let-col="col">
            {{view.dates[row*7+col].label}}
        </template>
```

view.dates[row*7+col] points to the data structure on a specific day.
The data structure is as below
```
export interface IMonthViewRow {
    current?: boolean;
    date: Date;
    events: IEvent[];
    hasEvent?: boolean;
    label: string;
    secondary: boolean;
    selected?: boolean;
    disabled: boolean;
}
```

Two important field in this data structure are date and events.
date is the date associated with this cell, and events are all events happen on that day.

I think you could per-calcuate some custom fields based on your criteria and set on your events.
Then use ngClass to set some css class based on the fields.
For example, some pseudo code,
```
[ngClass]="{'event-start': view.dates[row*7+col].events[0].startTime == view.dates[row*7+col].date }"
```
