### ISSUE TITLE
onCurrentDateChanged triggered twice

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#167]
Why it got called twice on single swipe in week-view?

**Comment by twinssbc** [comment]
@Astacius Do you still meet this issue?

**Comment by Astacius** [comment]
nope, you can close, it was my bad

**Comment by VinuthaShreyas** [comment]
This issue is still replicable.
When onCurrentDateChanged is configured in the html. The function is called twice whenever the date changes on the month view calendar

**Comment by twinssbc** [comment]
@VinuthaShreyas Is it possible in the onCurrentDateChanged method, you set the calendar date again?

**Comment by auflint** [comment]
Still have this issue November 2019
