### ISSUE TITLE
onEventSelected selects wrong event

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#168]
So, basically, I have template looking like this and the event that got selected is not the one I click on, but instead it always selects event that's on the bottom of the stack. How can I repair that?
![capture](https://user-images.githubusercontent.com/26569213/28771481-43a778aa-75e3-11e7-9101-ddf781d240c7.JPG)

**Comment by twinssbc** [comment]
@Astacius Could you provide your template code?

**Comment by Astacius** [comment]
`  <ng-template #weekEvents let-displayEvent="displayEvent">
      <div class="calendar-event-inner" 
      [style.backgroundColor]="dataService.getColor(displayEvent.event)"
      [style.margin-top]="calculateTop(displayEvent.event.startTime)*6+'px'"
      [style.top]="(37*displayEvent.startOffset/hourParts)+'px'"
      [style.height]="6*displayEvent.event.Combined + 'px'"
      ></div>
  </ng-template>`

**Comment by twinssbc** [comment]
@Astacius I'm not sure if I understand your layout. Are the events overlapping with each other? Also the events are quite condense, not sure a specific event could be selected on a mobile device.

**Comment by Astacius** [comment]
Every single color bar is a single event, they are not overlapping, they are placed according to their starting and ending time. But if there are 2 events in a single hour then click event selects the first one all the time.
And I dont know how to change that.

**Comment by twinssbc** [comment]
@Astacius If there are 2 events in a single hour, are they still not overlapping with each other? To be honest, it won't be user friendly in a small screen if there are many events need to be displayed. The height of an event is too small that can't be selected easily.

**Comment by Astacius** [comment]
Yes, they are not overlapping, they are placed next to each other, but still if I select an event and there are a few events in single hour, only the last event in that hour can be selected.
Maybe not user friendly but I was told to do so.

**Comment by twinssbc** [comment]
@Astacius Could you also provide the code of dataService.getColor and calculateTop methods?
Also how is Combined  field get calculated?
Did you add any custom style to calendar-event and calendar-event-inner css class?
I suspect although the events are displayed like as not overlapping, their surrounding DOM are overlapping. As you can see from below source code, the eventSelected method is triggered on the element having calendar-event class, not the custmoized template element.

```
<div *ngFor="let displayEvent of day.events" class="calendar-event" tappable
       (click)="eventSelected(displayEvent.event)"
       [ngStyle]="{top: 25*displayEvent.position+'px', width: 100*(displayEvent.endIndex-displayEvent.startIndex)+'%', height: '25px'}">
       <ng-template [ngTemplateOutlet]="weekviewAllDayEventTemplate"
             [ngOutletContext]="{displayEvent:displayEvent}">
       </ng-template>
</div>
```

**Comment by Astacius** [comment]
dataService.getColor returns a hex of color for a specific event
calculateTop:
```
calculateTop(date: Date) {
    return date.getMinutes() / 10;
  }
```
yes I have a custom style for calendar-event:
```
.calendar-event {
      left: 0% !important;
      width: 100% !important;
    }
```
You are probably right, so how can I make it work in my case?
