### ISSUE TITLE
Hello, what should you do to achieve this effect

### ISSUE THREAD

**Issue by Gtanxingwen** [twinssbc/Ionic2-Calendar#17]
![image](https://cloud.githubusercontent.com/assets/18392906/20387556/a227e808-acfb-11e6-8ab3-ae54725f12af.png)
@twinssbc

**Comment by twinssbc** [comment]
@Gtanxingwen This ionic2 version calendar hasn't exposed the view customisation option, the Ionic1 version has, but I didn't have time to port it.
If you want to modify the source code, you can change the template section in the monthview.ts

**Comment by Gtanxingwen** [comment]
@twinssbc hello dashen  ，I now need to add some content to reach the demand ，What should I do to run this calendar component, and test it

**Comment by twinssbc** [comment]
If you just want to test in dev environment, u can fork my code and launch the index.html, it directly reference the ts source file. You can also just copy the source code into your own project and import them.
Once u are happy with the change, you probably need to build it, you can run
npm run build-prod to generate the compiled files in aot folder, then you can reference them.

**Comment by twinssbc** [comment]
@Gtanxingwen I have added view customization in version 0.1.0. You can get more information from README. Feel free to have a try. Thanks.

**Comment by Gtanxingwen** [comment]
@twinssbc 好的,ok ,ok. if i hava some question, i ask you.   hhaha
