### ISSUE TITLE
How to manually set currentDate?

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#170]
Whenever I am trying to set a currentDate variable manually like this:
`this.calendar.currentDate = data.Date;`
it doesn't refresh the calendar and I have to swipe or do some action before change got noticed

**Comment by twinssbc** [comment]
@Astacius When do you trigger this line? this.calendar.currentDate = data.Date;
Is it possible that you trigger it in an async call?

**Comment by Astacius** [comment]
I am doing this inside of .onDidDismiss:
`dateSwapModal.onDidDismiss(data => {
          this.calendar.currentDate = data.Date;
    })
    dateSwapModal.present();`

**Comment by twinssbc** [comment]
@Astacius The calendar.currentDate is called in an async callback, I'm not sure if the view will be updated automatically.
Could you check this.calendar.current is pointing to the current scope, not some variable belongs to the callback method scope?
Could you try putting the code inside setTimeout?
```
let me = this;
setTimeout(function() {
    me.calendar.currentDate = data.Date;
}, 0);
```

**Comment by Astacius** [comment]
I have found the solution but it doesn't look good, I have to first assign data.Date to new object and then I am setting calendar.currentDate.setFullYear manually from that object

**Comment by twinssbc** [comment]
@Astacius, I don't know how date.Date is changed. But Angular watches the object reference change, not some internal property of an object.

**Comment by Astacius** [comment]
so I have to assign currentDate to new object to refresh the calendar view?

**Comment by twinssbc** [comment]
yes, you need to assign currentDate to a new object.
