### ISSUE TITLE
how to modify CSS for the current selected day?

### ISSUE THREAD

**Issue by tryadelion** [twinssbc/Ionic2-Calendar#172]
I understand there's a custom templating system for events on the calendar but would like to know if there was a way to modify the template for the current selected day. i wish to display selected dates as a circle and the current <td> text <td> structure makes it quite hard.

**Comment by twinssbc** [comment]
@tryadelion If a date is selected, there will be a monthview-selected css class applied on the cell.
Maybe you could customize the style of this css class to achieve your requirement?

**Comment by JoanJosep33** [comment]
Hello @twinssbc ! Really awesome work! But could you pls explain the option u presented to @tryadelion ? 
I want to change the colors (Depending the day one color or another). But I don't understand how to apply css on the class monthview-selected. 

Thanks a lot!

**Comment by twinssbc** [comment]
@JoanJosep33 
You could easily add below declaration in your app css file.
```
.monthview-selected {
  background-color: red;
}
```

But I think you are looking for different things, as you want to use different color for the days, not the selected date.
You could use customized template to achieve this. For example,
In HTML,
```
<ng-template #template let-view="view" let-row="row" let-col="col">
    <div class={{getDateClass(view.dates[row*7+col].date)}}>{{view.dates[row*7+col].label}}</div>
  </ng-template>

  <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>
```
In ts,
```
getDateClass(date) {
    return 'test';
  }
```
You could find more details in README.

**Comment by JoanJosep33** [comment]
Hi there, sry for the delay answer. I had no time! 

Well, u are right, I've finally solved. But, when I was solving the problem, another one comes up. 
Right now, I have this: 

    https://gyazo.com/ab3a2f4df4948a3d138773d7f6c1061b

This I did it with the following code: 
  `.test{
  background-color: red !important;
}`

My answer is, which is the instrucction to mark the whole square and not just the div from the numbers? Transform all the box in the color red. 


Thank you a lot!

**Comment by selloutdesign** [comment]
I was having trouble doing this and found the answer by targeting 
.monthview-selected[_ngcontent-c1]{ background-color: red;}
Not quite sure what is going on here yet - https://angular.io/guide/component-styles#appendix-inspecting-generated-css

**Comment by JoanJosep33** [comment]
Wow @selloutdesign , it works!

Amazing man. Thanks to everybody!

**Comment by wilsoncx** [comment]
Could you send me as you did?
