### ISSUE TITLE
Clicking on next or past months days in MonthView breaks date selection

### ISSUE THREAD

**Issue by tryadelion** [twinssbc/Ionic2-Calendar#173]
If i clic on the next month days ( visible with a slightly greyed out font on the monthview ), the swipe is triggered, but then clicking on any day triggers again the swipe.  if you click a "next month day" the selected day will be wrong, but swiping again to another month will select the correct value.

**Comment by tryadelion** [comment]
also, the next month's swipe preview doesn't have the templates or css applied.

uploaded a video: (still processing)

https://youtu.be/KBbwHJbg-d4

**Comment by tryadelion** [comment]
removed library, readded it on latest version and it worked again.  i don't know how. or why.

**Comment by plindsay** [comment]
@tryadelion out of curiosity - were you able to trigger the swipe animation when navigating to previous and next months (as shown in your video with the < and > icons)? I've been trying to do this but not managed to yet.

**Comment by tryadelion** [comment]
not yet, i'ts on the to-do list.
