### ISSUE TITLE
onTimeSelected frequently called while vertical scrolling on iOS devices

### ISSUE THREAD

**Issue by Seao** [twinssbc/Ionic2-Calendar#174]
Hey @twinssbc,

First thanks for your work on this plugin, it works very well!

I encountered an issue on iOS devices with the onTimeSelected function, which is frequently called while I'm vertically scrolling on the week view. When I'm scrolling slowly and properly, there is no issue. But if it's more a "tap and scroll" movement, the calendar is detecting a click which triggers the onTimeSelected function.

This accidentally call is quite frequent, mainly on iPhone 5 and more weakly on iPhone 6s. As the onTimeSelected function pushes another page in my app, this issue leads to a bad user experience.

Based on a [stackoverflow user advices](https://stackoverflow.com/questions/39628718/ionic2-tap-vs-click), I solved the issue quite drastically by replacing all the (click) events on your plugin by (tap) events. This solution is working well, without modifying the initial expected behavior.

Would you accept a pull request with these modifications?

**Comment by twinssbc** [comment]
@Seao I added tappable per other users' suggestion to eliminate the 300ms
http://technotip.com/5093/tappable-attribute-ionic-2/
I didn't notice that it may introduce the accidental click.
Since there's no other user reporting this issue, I think it's better to leave it there.
Could you try remove the tappable to see if it could solve your problem?

**Comment by Seao** [comment]
Sorry for the delay. I tried to remove the tappable attribute but this doesn't solve the issue. I decided to modify manually the plugin before each production build. I close this issue, if someone meet the same problem on iOS devices, feel free to reopen it.
