### ISSUE TITLE
How to set manually selected date?

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#175]
Is there any way to set selected date from code?

**Comment by twinssbc** [comment]
@Astacius you just need to set the currentDate.

**Comment by Astacius** [comment]
oh wow i thought it is something different, ok nevermind

**Comment by twinssbc** [comment]
@Astacius Actually currentDate and selectedDate are two different variables internally. But unless you turn off autoSelect, they are always pointing to the same day.
