### ISSUE TITLE
Calendar empty when eventSource lasted for several days

### ISSUE THREAD

**Issue by MrHOY** [twinssbc/Ionic2-Calendar#176]
Example:
event start: Wed Apr 12 2017 00:00:00 GMT+0700 (SE Asia Standard Time)
event finish: Fri Apr 14 2017 00:00:00 GMT+0700 (SE Asia Standard Time)

I try allDay: true but Calendar still empty event. (monthView)

**Comment by twinssbc** [comment]
@MrHOY Could you show me how do you set the startTime and endTime of the event? Are you using a standard date object or parse from a string?

**Comment by MrHOY** [comment]
@twinssbc 
Data I get:
       start_date: 2017-03-08T07:00:00
       end_date: 2017-03-15T19:00:00
then I change from string to Date():
      startTime: new Date(item.start_date),
      endTime: new Date(item.end_date)
If event start and finish in one day, calendar work good. But event lasted for several days, calendar empty

**Comment by twinssbc** [comment]
@MrHOY In some browser, some string format is not supported.
https://stackoverflow.com/questions/4310953/invalid-date-in-safari

Could you try creating an event using below code see if it works?
```
        var start = new Date();
        var end = new Date();
        end.setDate(end.getDate() + 7);

        events.push({
           title: 'test',
            startTime: start,
            endTime: end
        });
```

**Comment by MrHOY** [comment]
@twinssbc  it work good with your code
But my data get from API and format string, how can I apply my data to calendar ?
Also, I want to take rangeTime( startTime and endTime ) of calendar when load component, how can I do this?
Thank you.

**Comment by twinssbc** [comment]
@MrHOY You could use some date library, for example, momentjs, to parse the string to a valid date object.
If you set the queryMode to remote and add rangeChanged callback, you will get the startTime and endTime in the rangeChanged method when loading the calendar.

**Comment by MrHOY** [comment]
Thank you so much,
