### ISSUE TITLE
Display events from firebase

### ISSUE THREAD

**Issue by squierll** [twinssbc/Ionic2-Calendar#178]
Hoping someone can help. After several tries, I'm stuck in display events on ionic2-calendar. I fetch data from firebase, but in calendar events not shown.
Here is my code.

**calendar.ts**

    export class CalendarPage {
      eventSource: FirebaseListObservable<any[]>;     
      constructor(public firebaseService: FirebaseServiceProvider, public afd: AngularFireDatabase) {}
      
     ionViewDidLoad(){
           this.firebaseService.authState.subscribe(user => {
          if (user) {
    
            this.eventSource = this.afd.list(`/usersCalendars/${user.uid}/events`);
            this.eventSource.forEach(events => {
                console.log(events);
            });
          }
        });
      }
**console.log(events);**

    (2) [{…}, {…}]
    0:{endTime: "2017-08-19T13:00:00+02:00", note: "test note", recievedDt: "2017-08-18T13:33:40.371Z", startTime: "2017-08-19T12:00:00+02:00", status: "done", …}
    1:{endTime: "2017-08-18T13:00:00+02:00", note: "test 2", recievedDt: "2017-08-18T13:34:42.047Z", startTime: "2017-08-18T12:00:00+02:00", status: "pending", …}
    length: 2

**calendar.html**

    <ion-content>
      <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30"
            class="calendar">
     </calendar>

**Comment by avazquezpr** [comment]
Could you get it to work?

**Comment by twinssbc** [comment]
@avazquezpr What kind of issue did you meet? It seems @squierll solved the issue. I guess it's related to the startTime and endTime fields. The value of these two fields should be valid date object, instead of string.

**Comment by avazquezpr** [comment]
Thanks for the reply. That's what I found out yesterday after writing this haha. The date gets stored as a string, so I tried to convert it back to a Date object and it worked. 👍
