### ISSUE TITLE
 Module ''*'' has no exported member 'Wrapper_CalendarComponent'

### ISSUE THREAD

**Issue by omhybrid** [twinssbc/Ionic2-Calendar#18]
ionic 2 for android 

![ionic 2](https://cloud.githubusercontent.com/assets/22111807/20595946/21719094-b262-11e6-8e64-cfdd369d977a.PNG)

cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
OS: Windows 7
Node Version: v6.9.1

**Comment by omhybrid** [comment]
ok i solve it

**Comment by Gtanxingwen** [comment]
@omhybrid  how to solve this

**Comment by twinssbc** [comment]
Solution: add below lines in main.prod.ts

```
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';
```
