### ISSUE TITLE
Day view

### ISSUE THREAD

**Issue by Kilomat** [twinssbc/Ionic2-Calendar#180]
Hey everyone, there are any right way to display day hours by column ? 
I mean having the events on the line and the hours per column.

Thx

**Comment by twinssbc** [comment]
@Kilomat I'm not sure if I understand your requirement. Maybe a mockup could help?

**Comment by Kilomat** [comment]
For me the suitable design should be displayed like this:
[https://ibb.co/hRZjbk](url)

Another question : i want to remove  100% height of monthview-container class. how ??  
ps : wanna remove this line ":host > div { height: 100%; }\n\n" from the style.

**Comment by twinssbc** [comment]
@Kilomat 
This kind of layout is not supported.
Also this calendar allows you to swipe left and right to switch days.
If you display events by hour horizontally, there will be a horizontal scrollbar.
It's kind of conflict with the swipe action.

```
.monthview-container {
    height: auto !important;
    overflow: hidden;
}
```

**Comment by Kilomat** [comment]
Thank you.
