### ISSUE TITLE
Fetched events from post request does not show until swiping to another month.

### ISSUE THREAD

**Issue by Avislux** [twinssbc/Ionic2-Calendar#181]
Hi. I've managed to implement the calendar into my ionic 3 app with almost no issues except for one problem. When I load my calendar page, the page constructor calls a function that makes a post request to a PHP server, which returns the events in a JSON array. In the http.post promise I replace the date strings with date objects and push them to the eventSource array. 

Problem is that these events will not appear when the calendar loads. They will appear after I swipe the month left or right first. Furthermore, if I push a hardcoded event object into the eventSource array, that will appear when the calendar loads, but not the events from the post request (until I swipe). 

How do I ensure that the calendar will load after the post request? (Or how do I refresh the event source after the post request is complete?)

Also if I try to use this.myCalendar.loadEvents() I get an error: 
` Runtime Error
Uncaught (in promise): TypeError: Cannot read property 'loadEvents' of undefined TypeError: Cannot read property 'loadEvents' of undefined at new CalendarPage (http://10.0.0.3:8100/build/main.js:339:24) at createClass (http://10.0.0.3:8100/build/vendor.js:11412:26) at createDirectiveInstance (http://10.0.0.3:8100/build/vendor.js:11230:37) at createViewNodes (http://10.0.0.3:8100/build/vendor.js:12593:49) at createRootView (http://10.0.0.3:8100/build/vendor.js:12498:5) at callWithDebugContext (http://10.0.0.3:8100/build/vendor.js:13713:42) at Object.debugCreateRootView [as createRootView] (http://10.0.0.3:8100/build/vendor.js:13173:12) at ComponentFactory_.create (http://10.0.0.3:8100/build/vendor.js:10419:46) at ComponentFactoryBoundToModule.create (http://10.0.0.3:8100/build/vendor.js:3955:29) at NavControllerBase._viewInit (http://10.0.0.3:8100/build/vendor.js:47739:44)`

**Comment by twinssbc** [comment]
@Avislux If you directly modify the element in eventSource array. You could use loadEvents method. Take a 
 look at Instance Methods section in README.

**Comment by Avislux** [comment]
Adding
`loadEvents: function() {
        this.eventSource.push({
            title: ‘test’,
            startTime: startTime,
            endTime: endTime,
            allDay: false
        });
        this.myCalendar.loadEvents();
    }`
below the constructor gives me a bunch of syntax errors in my IDE. I assume it's supposed to look something like this: 
`loadEvents():void{
        this.myCalendar.loadEvents();
    }`
And while this builds, putting ` this.myCalendar.loadEvents();` in the constructor or another function in the module causes the above Runtime Error when I try to load the page.

**Comment by twinssbc** [comment]
@Avislux could u provide the code snippet about viewchild definition, looks like it doesnt get the calendar instance.

**Comment by Avislux** [comment]
@twinssbc


```
{ other irrelevant import statements}
import {CalendarComponent} from "ionic2-calendar/calendar";
import {GlobalsService} from "../../app/globals.service";
@Component({
    selector: 'page-calendar',
    templateUrl: 'calendar.html'
})
export class CalendarPage {
    calendar: any = {};
    noEventsLabel = "No Classes";
    viewTitle: "Calendar Title";
    formatMonthTitle = "MMMM yyyy";
    data1 any;
    data2: any;
    eventSource: any = [];
    @ViewChild(CalendarComponent) myCalendar: CalendarComponent;

    constructor(public navCtrl: NavController, public http: Http, private storage: Storage, public navParams: NavParams, private globals:GlobalsService, public myCalendar2:CalendarComponent) {
        this.data1 = this.globals.getData1();
        this.calendar.currentDate = new Date();
        this.getClasses();
     
        //this.loadEvents();
    }
    loadEvents(): void {
        this.myCalendar.loadEvents();

 getClasses() {
        this.storage.get('data1').then(
            data => {
                let options: RequestOptionsArgs = {responseType: ResponseContentType.Json};
                let link = obfucatedlink;
                this.http.post(link, {"data1": this.data1, "data2": data}, options).subscribe(data => {
                    //Change json string dates into date objects
                    if (data["_body"] != null ){
                        data["_body"].forEach(classObject => {
                            classObject.startTime = new Date(classObject.startTime);
                            classObject.endTime = new Date(classObject.endTime);
                            this.eventSource.push(classObject);
                         
                        });
                    }
                }, error => {
                    console.log("Oooops!");
                })
            });

    }

`

That's the gist of what I'm doing with some obfuscated things. The myCalendar2 injection was a test to see if I could get it working with that method (I won't get a runtime error with it but doesn't load the events when page is loaded).

**Comment by twinssbc** [comment]
@Avislux I think there are two problems in your code. Your getclasses method is an async call, so the loadevents method should be called in the callback method.
When constructor is called, the calendar element hasn't been fully rendered, so it cant get the viewchild. Its better to load your data in ionViewDidLoad method.

**Comment by Avislux** [comment]
I put loadEvents() everywhere BUT the callback function. Not sure why I didn't think of that. Also put my getClasses() in ionViewDidLoad(), although it seems to work without it. 

It works as intended now, thanks!
