### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Template parse errors: Can't bind to 'monthviewEventDetailTemplate' since it isn't a known property of 'calendar'.

### ISSUE THREAD

**Issue by lampofdrog** [twinssbc/Ionic2-Calendar#184]
hi 

![screen shot 2017-08-24 at 09 08 18](https://user-images.githubusercontent.com/11801709/29656277-ef53d7d6-88ab-11e7-9ff9-db1cb8408128.png)

![screen shot 2017-08-24 at 09 10 37](https://user-images.githubusercontent.com/11801709/29656351-209a809c-88ac-11e7-908a-408ce64e7014.png)

help me plz thank you

**Comment by twinssbc** [comment]
@lampofdrog Are you using a PageModule?
If so, you should import the calendar module into your page module, for example
```
import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  declarations: [
    MyPage
  ],
  imports: [
    IonicPageModule.forChild(MyPage),
    NgCalendarModule
  ],
  entryComponents: [
    MyPage
  ]
})
export class MyPageModule {}
```

**Comment by lampofdrog** [comment]
@twinssbc  thank you very much ;) i will test and i come back to you to confirm the solution

**Comment by ArgHakobyan** [comment]
> 

> ### ### [``](url)

**Comment by ArgHakobyan** [comment]
.
