### ISSUE TITLE
allDay events in day view are displayed multiple times when swipping

### ISSUE THREAD

**Issue by youch12** [twinssbc/Ionic2-Calendar#185]
Hi there everyone, I keep getting this error: when I try to display my events which are all **allDay** events, everything seems fine but when I swipe back or forth and return to a pervious event, the dayView displays my events, each multiple time:
At first display, everything seems fine:

![image](https://user-images.githubusercontent.com/16466678/29724518-a6642240-89c0-11e7-98c5-9bc3b64ec641.png)

but when I swipe forth and back:

![image](https://user-images.githubusercontent.com/16466678/29724547-c26571f6-89c0-11e7-8c24-9aafb6c6fb4c.png)

I even checked the online demo, same issue:

https://twinssbc.github.io/Ionic2-Calendar/demo/

Thanks.

**Comment by twinssbc** [comment]
@youch12 I can confirm it's a bug, will fix it this weekend. Thanks for reporting it!

**Comment by youch12** [comment]
Thank you

**Comment by twinssbc** [comment]
@youch12 I have fixed the bug in the latest version.

**Comment by youch12** [comment]
Thank you !
