### ISSUE TITLE
Month names are incorrect in monthView

### ISSUE THREAD

**Issue by youch12** [twinssbc/Ionic2-Calendar#187]
Hi there @twinssbc , I think there is a bug with the callendar's monthView. In the month view, some month names are incorrect, for example:

This is suppose to be June 2017 but it displays may 2017:
![image](https://user-images.githubusercontent.com/16466678/29863114-8f988b06-8d66-11e7-8571-84a5a14e6fbe.png)
This is suppose to be July 2017 but it displays june 2017:
![image](https://user-images.githubusercontent.com/16466678/29863159-b8a880aa-8d66-11e7-9d0c-ef37308cd976.png)
This is suppose to be june 2018 but it displays may 2018:
![image](https://user-images.githubusercontent.com/16466678/29863234-ed5399ca-8d66-11e7-825b-64fad920e283.png)
However july 2018 is correct.

This is suppose to be may 2020 but it displays april 2020:
![image](https://user-images.githubusercontent.com/16466678/29863282-15f5547c-8d67-11e7-88c6-5ed6318772b5.png)
but june, july 2020 are correct.

So as you can see the error itself isn't consistant.

All the images here are taken from the demo: https://twinssbc.github.io/Ionic2-Calendar/demo/
I'm getting the same error in my app.

Thank you

**Comment by twinssbc** [comment]
@youch12 Could you provide the reproduce steps? It seems the month names are correct at my side.

**Comment by youch12** [comment]
I'm not quite sure I understand what you mean, like I said all the images are from the demo.

**Comment by twinssbc** [comment]
@youch12 I mean this behavior must be triggered at certain circumstance. I understand that it is quite random, but do you have any clue to reproduce it easily? Do you use some special movement, for example, swipe left x times, the right y times?

**Comment by youch12** [comment]
No special, I just swipe back to previous dates and even to far distant dates, I thought it could be language related but it's not. When I click on dates in these incorrect months, the console displays correct values:
![image](https://user-images.githubusercontent.com/16466678/30031151-38fdcd76-9188-11e7-97d9-48aacbe8208f.png)

**Comment by twinssbc** [comment]
@youch12 Which browser are you using? So you just swipe back to previous month, the error appears immediately?

**Comment by youch12** [comment]
I'm using Opera 47.0.2631.71, and my friend is using Google Chrome 60.0.3112.113: she is experiencing the same issue.

**Comment by twinssbc** [comment]
@youch12 What's your time zone and locale? Do you swipe the calendar very quickly?

**Comment by youch12** [comment]
My time zone is that of Morocco's: GMT+1. No I do not swipe quickly.

**Comment by twinssbc** [comment]
@youch12 I'm sorry, I changed my computer to your timezone, and set the locale to 'fr-FR', still cannot reproduce your issue.
Maybe you could record a video to show how do you reproduce it?
Also what if you change to other timezone or locale, does the issue still happen?

**Comment by twinssbc** [comment]
It's likely related to DST. I have released new version to fix this bug.
