### ISSUE TITLE
calendar doesn't change language on the go

### ISSUE THREAD

**Issue by magnoou** [twinssbc/Ionic2-Calendar#188]
I'm using the calendar in my app, and I have a language selector but when I change it, the calendar doesn't change language unless y restart the app since it takes the value in the module provider when the app starts, is there a way to reload it?

{ provide: LOCALE_ID, deps: [LanguageProvider], useFactory: getLocal_id }

I have this in my i18n module, and it works only when the app starts not if i change it later

thanks

**Comment by twinssbc** [comment]
@magnoou I think the question is not calendar specific, but how to change language dynamically in Angular/Ionic app. I wonder if the language can be changed dynamically in other parts of your app?

**Comment by magnoou** [comment]
@twinssbc yes, every other part of the app changes the language but not the calendar, the only way it changes is when closing the app and opening it again

**Comment by Kr0n092** [comment]
I'd like to know how to do this as well.

**Comment by twinssbc** [comment]
@magnoou 
I could expose an instance method to change the locale.
But I wonder how is your language selector working? Just want to check if there's any clean way. Otherwise, each time you change language using the selector, you also need to call the calendar method.

**Comment by magnoou** [comment]
I use the ngx-translate module, so when I change the lang I execute the method

       this.translateService.use(lang);

and save it in my localstorage 

       localStorage.setItem(this.LOCALSTORAGE_LANGUAGE_KEY, language);

**Comment by twinssbc** [comment]
@magnoou I exposed **locale** option in the latest version.
It has higher priority than the LOCALE_ID at the module level.
If you change calendar.locale at runtime, the whole calendar language will also be changed dynamically.
Feel free to have a try.

```
  <calendar ... [locale]=“calendar.locale”></calendar>

  calendar = {
      locale: 'en-GB'
  };
```

**Comment by magnoou** [comment]
@twinssbc thanks for the time, Ill give it a try and let you know how it goes

**Comment by magnoou** [comment]
@twinssbc I just made some tests but with no success, even if I put it like this

> [locale]="en-GB"

let me show you some of my code, so I have a Wrapper class for the callendar which has this template:

`@Component({
	selector: 'calendar-wrapper',
	template: `
		<div style="display: block">

			<calendar-controls
				[viewTitle]="viewTitle"
				[showCalendarIn]="calendarShow"
				[showSearchBar]="showSearchBar"
				[calendarDate]="calendarConfig.currentDate"
				(onShowCalendarChanged)="onShowCalendar($event)"
				(onCalendarDateChanged)="onCalendarControlsDateChanged($event)">
			</calendar-controls>

			<div class="calendar-wrapper" [style.display]="(calendarShow)?'block':'none'">
				<calendar
					[locale]="en-GB"
					[formatDayHeader]="calendarConfig.formatDayHeader"
					[eventSource]="calendarSource"
					[calendarMode]="calendarConfig.mode"
					[currentDate]="calendarConfig.currentDate"
					[queryMode]="'remote'"
					[showEventDetail]=false
					(onTitleChanged)="onViewTitleChanged($event)"
					(onRangeChanged)="onRangeChanged($event)"
					(onTimeSelected)="onTimeSelected($event)"
					(onCurrentDateChanged)="onCalendarCurrentDateChanged($event)"
					step="30">
				</calendar>
			</div>			
			<calendar-list [groups]="eventsList" [showSearchBar]="showSearchBar"></calendar-list>
		</div>`,
	// changeDetection: ChangeDetectionStrategy.OnPush
})
export class CalendarWrapperComponent {
	@Input() showSearchBar: boolean;
	@Input() calendarConfig: any;
	@Input() eventSource: any = [];
	@Input() locale: string;`

....
`	mylocale: string = "en-GB";
`

...then on the ngChanges I tried this

`this.mylocale = this.locale;`

And I logged that the value was actually changing es/en.. etc but the calendar wasn't changing the lang.

Then I have this in the html

`<calendar-wrapper
		[locale]="calendar.locale"....`

and added a button for toggling the calendar.locale value.

As I said even if in the calendarWrapper template I try putting it like [locale]="en-GB" its not working
any ideas?

**Comment by twinssbc** [comment]
@magnoou locale should be bound to a variable not a constant string.

```
<calendar ... [locale]=“calendar.locale”></calendar>

  calendar = {
      locale: 'en-GB'
  };
```

**Comment by magnoou** [comment]
I tried both

**Comment by twinssbc** [comment]
@magnoou How do you change the locale? The new locale only takes effect when the calendar executes its ngOnInit function again. 
If you have a button in the page containing the calendar, once you click it, the calendar won't be rendered, so the language won't change immediately. Only when you switch to a different view, for example monthview to weekview or you switch to a new tab in the app, the ngOnInit will be triggered again.
If you need to go to another setting page to change the locale, then go back to the page including the calendar, the new locale should take effect.

**Comment by magnoou** [comment]
@twinssbc oh I see, I was testing this change with a button on the same page, moved out and its working now, thanks for your time dude!

**Comment by rodrake1** [comment]
I didn't get how to implement the language change. I'm not trying to do it dynamically, just a plain and simple change from en-US to another language. I'm using Ionic 3.20.0. Could somebody show me how it is done?

**Comment by pookdeveloper** [comment]
You can use:
````
import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';
registerLocaleData(localeEs);
````
````
 <calendar [eventSource]="eventSource" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate"
    (onCurrentDateChanged)="onCurrentDateChanged($event)" (onEventSelected)="onEventSelected($event)"
    (onTitleChanged)="onViewTitleChanged($event)" (onTimeSelected)="onTimeSelected($event)" step="30">
  </calendar>
````
