### ISSUE TITLE
Idea: refresh calendar 

### ISSUE THREAD

**Issue by omhybrid** [twinssbc/Ionic2-Calendar#19]
when change calendar  mode  by funcationally (not button click)  this.calendar.mode = mode; not working

**Comment by twinssbc** [comment]
Whats the value of the mode variable? button click also sets the calendar mode in the same way.

**Comment by omhybrid** [comment]
mode value day, week and month i want funcationally change mode not button click

**Comment by twinssbc** [comment]
Is there any error printed out in the console? The change mode button is external to the calendar, also calls a function, so it should be the same. Another reason I can think out is you are not set the mode variable in the right scope.
