### ISSUE TITLE
Ionic3 - onRangeChanged is not triggered by range change

### ISSUE THREAD

**Issue by TheKalin** [twinssbc/Ionic2-Calendar#190]
Hello I have a problem with this component in ionic3 application. When i'm swiping left and right or changing the calendar mode nothing is happening ;x 
My html code:
`
<ion-content text-wrap>
<calendar [eventSource]="eventSource" [noEventsLabel]="foo1" [autoSelect]="false" [queryMode]="remote"  [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate" [startingDayWeek]="1" [startingDayMonth]="1" (onCurrentDateChanged)="onCurrentDateChanged($event)"  (onRangeChanged)="onRangeChanged($event)"
    (onEventSelected)="onEventSelected($event)" (onTitleChanged)="onViewTitleChanged($event)" (onTimeSelected)="onTimeSelected($event)" [step]="15">
  </calendar>
</ion-content>
`
Service code 
`
onRangeChanged(ev) {
        console.log('range changed: startTime: ' + ev.startTime + ', endTime: ' + ev.endTime);
}
`
All other events (onEventSelected,onCurrentDateChanged, etc) works perfectly. 
`

    @ionic/app-scripts : 2.0.2 

    Cordova Platforms  : android 6.2.3 

    Ionic Framework    : ionic-angular 3.5.3

    ionic2-calendar@0.3.9

`

**Comment by twinssbc** [comment]
@TheKalin It needs to bind to a variable like calendarMode, it doesn't support pass a constant value in html.

**Comment by TheKalin** [comment]
@twinssbc Ok it works now. I would never guess that this is the issue. Passing startingDayWeek,startingDayMonth values from html templated worked. This is what tricked me. 
Anyway, thanks for help! 

PS: Do you plan to write a feature for custom period view ? For example 2-3 days in single slide.

**Comment by twinssbc** [comment]
@TheKalin No plan for that. I try to make this calendar can meet the general requirements, while different people may have different expectation on the custom period view.

**Comment by TheKalin** [comment]
@twinssbc Oki.Keep up the good work. :) Feel free to close the issue.

**Comment by victorcarvalhosp** [comment]
can someone please provide an example?

**Comment by twinssbc** [comment]
@victorcarvalhosp You could get some idea from the demo directory.

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
@twinssbc @victorcarvalhosp 
I don't really get it after viewing the demo files. _home.html_ contains nothing related to `onRangeChanged` and the following is everything in _home.ts_:

**TS**
```
onRangeChanged(ev) {
	console.log('range changed: startTime: ' + ev.startTime + ', endTime: ' + ev.endTime);
}
```
**HTML**
```
<calendar
	*ngIf="eventSource"
	startingDayMonth="1"
	startingDayWeek="1"
	[monthviewEventDetailTemplate]="template"
	[currentDate]="calendar.currentDate"
	(onRangeChanged)="onRangeChanged($event)"
	(onTitleChanged)="onViewTitleChanged($event)"
	step="30">
</calendar>
```

What else do I need? Because this doesn't work for me. It just isn't triggered.

**Comment by twinssbc** [comment]
@MatthiasVanMeerbeek-r0670805 onRangeChanged is only triggered when the queryMode is set to 'remote'

**Comment by guetstudio** [comment]
> @TheKalin It needs to bind to a variable like calendarMode, it doesn't support pass a constant value in html.

Sorry if this is too damn question but what do you mean by 'it needs to bind to a variable'? Taking any of the example codes above, how different that should be to make it trigger the callback function. I have also tried setting   [queryMode]="remote" and still onRangeChaged does nothing. How should I bind what to a variable? Again, sorry if this is too damn to ask.

**Comment by twinssbc** [comment]
@guetstudio It means you should have something like below in your HTML

```
[queryMode]="calendar.queryMode"
```

And set calendar.queryMode = 'remote' in your component ts code.
It doesn't support setting 'remote' directly in HTML.

**Comment by guetstudio** [comment]
> @guetstudio It means you should have something like below in your HTML
> 
> ```
> [queryMode]="calendar.queryMode"
> ```
> 
> And set calendar.queryMode = 'remote' in your component ts code.
> It doesn't support setting 'remote' directly in HTML.

Ahh ok, perfect, it's working now! Thanks dude!
