### ISSUE TITLE
Mark multiple days as selected?

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#191]
I have to mark the entire week-row in month view as selected, what is the easiest way to do that? Like on this picture:
![capture](https://user-images.githubusercontent.com/26569213/30367340-47f7c038-986e-11e7-9a9f-f6222b9c9ab7.JPG)

**Comment by twinssbc** [comment]
@Astacius I think you could leverage customized view.
For example, in HTML
```
<ng-template #template let-view="view" let-row="row" let-col="col">
    <div class={{getEventClass(view.dates[row*7+col].events)}}>{{view.dates[row*7+col].label}}</div>
  </ng-template>

  <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>
```

In ts,
```
getEventClass(events) {
    return 'test' + events.length;
  }
```

Below snippet allows you to add your own css class to the cell based on the events happen on that day. Once you select a date, you could insert some fake event for the whole week.
You could also generate the css class based on the date on that cell if you use view.dates[row*7+col].date.
