### ISSUE TITLE
Event Detail - Add more classes to elements

### ISSUE THREAD

**Issue by twbocklertorch** [twinssbc/Ionic2-Calendar#192]
It would be nice to split out and wrap each event item with a <span>, each with its own classname, so that we can control the display better.  

For instance, you have this for event detail:
<span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">
{{event.startTime|date: 'HH:mm'}} -{{event.endTime|date: 'HH:mm'}}
</span>

It would be nice to have something like this:
<span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">
<span class='eventStartTime'>{{event.startTime|date: 'HH:mm'}}</span> <span class='eventHyphen'>-</span><span class='eventEndTime'>{{event.endTime|date: 'HH:mm'}}</span>
</span>

This doesn't change your code, but it would allow me to hide the end time and hyphen through css.  You already do it for the event name.  I'm just asking to add more control and flexibility over the display without having to customize the code.

Thanks!

**Comment by twinssbc** [comment]
@twbocklertorch You could check the **View Customization Option** section in README. It supports using a customized template.
