### ISSUE TITLE
Dev vs Prod - Build differences

### ISSUE THREAD

**Issue by twbocklertorch** [twinssbc/Ionic2-Calendar#193]
I modified the monthviewEventDetailTemplate, so that the event day detail displays differently.  When I package my Ionic3 application using a development profile, the display looks great.  But when I build it using --release, the display looks like the out-of-box version.  Any ideas why these modes would produce different results?

**Comment by twinssbc** [comment]
@twbocklertorch Did you directly modify the source code or you use the way described in the **View Customization Option** section in README. Is it possible you put your template in a separate file, but it is not packaged in the release mode?

**Comment by twbocklertorch** [comment]
@twinssbc I created a local repo and modified the calendar.ts file directly.  I modified the event start date within the monthviewDefaultEventDetailTemplate template, built the plugin, and then brought the dist folder code within the node_modules folder.
Is that correct?

**Comment by twinssbc** [comment]
@twbocklertorch You don't have to modify the source code.
The calendar supports view customization. Unless certain part of the calendar doesn't support that, you could modify the source code.
For example, if you want to customize the event detail section, you could use below code in your own component.
```
<template #template let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
  ... 
  </template>

  <calendar ... [monthviewEventDetailTemplate]="template"></calendar>

```

**Comment by twbocklertorch** [comment]
@twinssbc  Great.  That worked...however.  The eventSelected event it not firing.
Here is my custom template:
<template #templateApptCustom let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
        <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
            <ion-item-sliding #item *ngFor="let event of selectedDate?.events">
                <ion-item (click)="eventSelected(event)">
                    <div href="#" class="calendar-hour calendar-hour-taken">
                        <strong class="cal-from">{{event.startTime|date: 'h:mm a'}}</strong>
                        <h4>{{event.title}}</h4>
                        <a class='edit' href='#'><i class='fa fa-pencil'></i></a>
                    </div>
                </ion-item>
                <ion-item *ngIf="selectedDate?.events.length==0">
                    <div class="no-events-label">{{noEventsLabel}}</div>
                </ion-item>
                <ion-item-options side="right">
                    <button ion-button color="primary" (click)="eventSelected(event)">Edit</button>
                    <button ion-button color="danger" (click)="eventDeleted(event)">Delete</button>
                </ion-item-options>
            </ion-item-sliding>
        </ion-list>
</template>

And here is my calendar element:
<calendar [eventSource]="eventSource"
              [currentDate]="calendar.currentDate"
              (onCurrentDateChanged)="onCurrentDateChanged($event)"
              (onEventSelected)="onEventSelected($event)"
              (onEventDeleted)="onEventDeleted($event)"
              (onTitleChanged)="onViewTitleChanged($event)"
              (onTimeSelected)="onTimeSelected($event)"
              [monthviewEventDetailTemplate]="templateApptCustom"
              step="60">
    </calendar>

Do you seen anything out of the ordinary?  All I did is add the <template> and then added that name into the attribute of the <calendar> element.

**Comment by twbocklertorch** [comment]
@twinssbc When running in the browser, I see this error:
Runtime Error
co.eventSelected is not a function

I basically took your month detail template and customized it.  I'm not sure why it's not finding the event selected method.

Thank you...

**Comment by twbocklertorch** [comment]
@twinssbc Nevermind.  I found the issue.  My template event selected methodname was 'EventSelected(event), while the actual method name was 'onEventSelected(event).  All works.

Thank you for the quick help.  I can now test and release my app.

**Comment by qasmaoui** [comment]
hello to you all
im getting the same error heer


Runtime Error
co.onViewTitleChanged is not a function

Stack
TypeError: co.onViewTitleChanged is not a function
    at Object.eval [as handleEvent] (ng:///AppModule/CalendrierPage.ngfactory.js:377:24)
    at Object.handleEvent (http://localhost:8100/build/vendor.js:12273:138)
    at Object.handleEvent (http://localhost:8100/build/vendor.js:12976:85)
    at dispatchEvent (http://localhost:8100/build/vendor.js:9173:21)
    at http://localhost:8100/build/vendor.js:11101:20
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/vendor.js:4222:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:42439:16)
    at SafeSubscriber.next (http://localhost:8100/build/vendor.js:42386:22)
    at Subscriber._next (http://localhost:8100/build/vendor.js:42326:26)
    at Subscriber.next (http://localhost:8100/build/vendor.js:42290:18)

my configuration 

Ionic Framework: 3.6.1
Ionic App Scripts: 2.1.4
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 8.9.3
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

<img width="893" alt="capture d ecran 2018-01-02 a 09 29 54" src="https://user-images.githubusercontent.com/16212917/34479640-d7c40b94-ef9f-11e7-9980-2aab1e2ed795.png">

heer is my html 

<ion-header>
  <ion-navbar color="primary">
    <ion-title>{{viewTitle}}</ion-title>
    <ion-buttons end>
      <button ion-button [disabled]="isToday" (click)="today()">Today</button>
      <button ion-button (click)="changeMode('month')">M</button>
      <button ion-button (click)="changeMode('week')">W</button>
      <button ion-button (click)="changeMode('day')">D</button>
      <button ion-button (click)="loadEvents()">Load Events</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content class="has-header">
  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30">
  </calendar>
</ion-content>

i have also impoter the calendar module on 
app.module.ts

**Comment by twinssbc** [comment]
@qasmaoui Did you add onViewTitleChanged function in your component code?
