### ISSUE TITLE
Is there a way to add the event below the calendar inside of a card?

### ISSUE THREAD

**Issue by pimatco** [twinssbc/Ionic2-Calendar#195]
I've been trying this but couldn't find a way.

When you add an event, it appears below the calendar in a one line only. I would like to customize it more and add it in a card.

Thanks for the great work, by the way.

**Comment by twinssbc** [comment]
@pimatco You probably could try the use the customized template. You could get more details from the "View Customization Option" section in README.

**Comment by vancuren** [comment]
I found a way that works for me. Not sure if its a preferred method of editing. If you navigate to node_modules/ionic2-calendar/calendar.js you will see the template html within the javascript file.

```
CalendarComponent.decorators = [
        { type: Component, args: [{
                    selector: 'calendar',
                    template: ...

<div class=\"event-detail-container\" has-bouncing=\"false\" *ngIf=\"showEventDetail\" overflow-scroll=\"false\">\n    

<ion-card *ngFor=\"let event of selectedDate?.events\" (click)=\"eventSelected(event)\">\n     

```
You can then 

- change the *ngif statement to a div

- modify *ngFor  to ion-card and ion-item to ion-card-content etc.

remember to use line feeds \n

**Comment by twinssbc** [comment]
@vancuren You don't need to modify the files in node_modules, because next time you upgrade a new version, your changes will be overwritten.
The calendar allows you provide a template to custom the view. Take a look at  monthviewEventDetailTemplate option in README.
