### ISSUE TITLE
viewTitle not updating correctly

### ISSUE THREAD

**Issue by nandokferrari** [twinssbc/Ionic2-Calendar#197]
I have been experiencig some bugs with viewTitle's update as we slide to a next or previous month. If I start at september, then slide to the next one, i got october; if I slider to the next one again, I should get november, but I get october again for instance.

It also happens in the project's demo, you can here: https://twinssbc.github.io/Ionic2-Calendar/demo/   It duplicates October, and skips February. Very unusual.

This is just one example, it is very glitchy, has more scenarios where this does not work well.

Any ideas?

**Comment by twinssbc** [comment]
@nandokferrari
Some other user reports this issue.
https://github.com/twinssbc/Ionic2-Calendar/issues/187
But I'm still not able to reproduce it.

The logic is like below, it will use the first day of the current month to generate the title.
Could you spot anything wrong?
```
    getTitle():string {
        let currentViewStartDate = this.range.startTime,
            date = currentViewStartDate.getDate(),
            month = (currentViewStartDate.getMonth() + (date !== 1 ? 1 : 0)) % 12,
            year = currentViewStartDate.getFullYear() + (date !== 1 && month === 0 ? 1 : 0),
            headerDate = new Date(year, month, 1);
        return this.formatTitle(headerDate);
    }
```

**Comment by youngcholo** [comment]
@twinssbc 
Logic is correct, it will get the first day of the current month.
I'm loading my calendar on monthView/queryMode configuration and set current date to today (Nov 8, 2017).

onRangeChanged I'm getting this  : 
range changed: startTime: Mon Oct 30 2017 00:00:00 GMT+1100 (AEDT), endTime: Mon Dec 11 2017 00:00:00 GMT+1100 (AEDT).

headerDate : "Wed Nov 01 2017 00:00:00 GMT+1100 (AEDT)", which is correct, first day of the current month.

but "this.formatTitle(headerDate)" is producing October 2017

Can you have a look on this line of code in monthview.js , 

 this.formatTitle = function (date) {
                return datePipe.transform(date, this.formatMonthTitle);
 };

**Comment by twinssbc** [comment]
@youngcholo I guess it may due to day light saving. 
Looks like this bug is also raised to Angular repo.
https://github.com/angular/angular/issues/8319

Unfortunately I can't reproduce it even when I set the timezone to UTC+11, somehow I'm allowed to turn on/off DST manually in my desktop.
Could you do me a favor to set the headerDate to midday to avoid the edge case around 0AM and see if it could solve the problem? If so, I will release a new version including this change.
```
headerDate.setHours(12);
```

**Comment by youngcholo** [comment]
@twinssbc setting hours to 12 will solve the issue. I did a temporary workaround for the viewTitle inside the onRangeChange(ev) while waiting for the response last week.

onRangeChanged(ev) {
  let date = ev.startTime.getDate(),
  month = (ev.startTime.getMonth() + (date !== 1 ? 1 : 0)) % 12,
  year = ev.startTime.getFullYear() + (date !== 1 && month === 0 ? 1 : 0),
  headerDate = new Date(year, month, 1);
  headerDate.setHours(12);
  headerDate.setMinutes(0);
  headerDate.setSeconds(0);
  var datePipe = new DatePipe('en-US');
  this.tempTitle = datePipe.transform(headerDate, 'MMMM yyyy');
  }

Thank you.

**Comment by twinssbc** [comment]
@youngcholo Great, I will release a new version containing this change.

**Comment by twinssbc** [comment]
I have released the new version to fix this bug.

**Comment by youngcholo** [comment]
@twinssbc Thank you for the update, will it support  angular5 now?
I'm having issues, I updated my ionic native plugins, now its requiring angular5, so my angular libraries are updated to 5.0.

**Comment by twinssbc** [comment]
@youngcholo yes, version 4.x is built on Ionic 3.9.2 which depends on Angular 5.
