### ISSUE TITLE
Render the swipe animation lag on Android

### ISSUE THREAD

**Issue by lingyilun** [twinssbc/Ionic2-Calendar#20]
When week# changed will got about 5~7 sec latency,
No matter in the Dev or run in Android phone (it runs well on iOS devices),
Is there any solution?

**Comment by twinssbc** [comment]
Yes, same issue was submitted. I'm still investigating.
https://github.com/twinssbc/Ionic2-Calendar/issues/15

**Comment by RS-Shekhawat** [comment]
@twinssbc could i disable swipe event in the calendar?

**Comment by twinssbc** [comment]
@RS-Shekhawat Why do you want to disable swipe event? This is how this calendar works.
But you can modify the source code to achieve this effect if you want. The underlying Swiper control has such option.
Also could you open a separate issue if you want to ask a new question? Thanks.
