### ISSUE TITLE
Demo Page is not working

### ISSUE THREAD

**Issue by fdambrosio** [twinssbc/Ionic2-Calendar#200]
Hi, the Demo page https://twinssbc.github.io/Ionic2-Calendar/demo/ is not working, it returns a blank page. 

Thanks

**Comment by twinssbc** [comment]
@fdambrosio Which browser are you using? Any error message printed out in the console?

**Comment by fdambrosio** [comment]
@twinssbc now i've seen that it's working, but it require almost 30 seconds to load all the resources and rendering the page. Thanks

**Comment by kaiyuan01** [comment]
The demo page still did not load

**Comment by twinssbc** [comment]
@kaiyuan01 Any error printed out in the console? Or does it stuck at loading certain file? The demo page needs to load many files from CDN and it may take a while until all files are downloaded completely.
