### ISSUE TITLE
using the calendar twice in the same page one of them is not responsive anymore.

### ISSUE THREAD

**Issue by darkholiday** [twinssbc/Ionic2-Calendar#201]
i want to use the monthview and the dayview in the same page any tips i am new in ionic.
i using the same calendar twice in the same page one of them is not responsive anymore.
but if i use only one its responsive and works perfectly.

**Comment by twinssbc** [comment]
@darkholiday This is the known issue of ion-slides.
See https://github.com/ionic-team/ionic/issues/12008, Ionic team hasn't come up an official fix for it.

**Comment by darkholiday** [comment]
Thank you man 
keep up the good work ;)
