### ISSUE TITLE
display data from database into calendar

### ISSUE THREAD

**Issue by fahmisaad** [twinssbc/Ionic2-Calendar#203]
hi, 
as i stated at my title, i trying to figure out how to display data from database(mysql) into calendar.
For example i got data on 2017-10-26 00:11:00 (the datatype is datetime) said meeting, and i want to show this data into my calendar. I really need help on how to do it.

i'm using ionic and php as backend. 

i'm following this website as my tutorials.
[https://devdactic.com/ionic-calendar-app/](url)

it will be great if you can help me in this matter.

**Comment by twinssbc** [comment]
@fahmisaad The calendar only cares the events pushed into eventSource no matter it comes from where.
You could also refer to the Demo page. In the demo page, it directly fills the eventSource with some fake events. You just need to fill the eventSource with the data fetched from your database. Also you probably need to use 'remote' queryMode and load the events in rangeChanged callback function.
You could find more information from README.

**Comment by johnmikelridz** [comment]
The demo page is not working: https://twinssbc.github.io/Ionic2-Calendar/demo/

**Comment by twinssbc** [comment]
@johnmikelridz please create a separate issue

**Comment by johnmikelridz** [comment]
Oh, sorry about that. I will do that.

**Comment by fahmisaad** [comment]
can you give or show some coding example on how to do in "'remote' queryMode and load the events in rangeChanged callback function."part.  Honestly i'm new on ionic.
Trying to find tutorial on internet but sadly didn't found any.

**Comment by twinssbc** [comment]
@fahmisaad 

In HTML,
```
<calendar ... [queryMode]="calendar.queryMode" (onRangeChanged)="onRangeChanged($event)"></calendar>
```

In ts,
```
 calendar = {
        queryMode: 'remote',
        ...  //omit other options
  };

  onRangeChanged = (ev: { startTime: Date, endTime: Date }) => {
      DB.query(ev, (events) => {
          this.eventSource = events;
      });
  };
```

**Comment by AravindrajanSampathkumar** [comment]
Hi Twin,
I also facing the same problem, i need to get the whole month events below the calendar not for the particular date. It should display like date wise events. I new to Angular2, can you help me to solve the issue. Can you share some brief explanation code to fetch the whole events from the month.PFA for your reference. That is the current view.



![currentcalendar_view](https://user-images.githubusercontent.com/31069793/38469815-4467d644-3b78-11e8-858a-fcc46e63969a.png)

**Comment by twinssbc** [comment]
@AravindrajanSampathkumar If you want to display the events of the whole month as a list, you could just add a list below the calendar. The default eventDetail list is only for the selected date, you could set  showEventDetail option to false to hide the default list.

**Comment by AravindrajanSampathkumar** [comment]
Hi twinssbc,
I tried still I didget the response can you pls help me to solve the issue . PFB code of mine
HTML code:
<template #monthviewDefaultEventDetailTemplate showEventDetail="showEventDetail" selectedDate="selectedDate" noEventsLabel="noEventsLabel">
          <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
              <ion-item *ngFor="let event of managelist" (click)="eventSelected(event)"> 
                      <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                          -
                          {{event.endTime|date: 'HH:mm'}}
                      </span>
                  <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn">All day</span>
                  <span class="event-detail">  |  {{event.title}}</span>
              </ion-item>
              
      </template>

TS Page:
addEvent() {
    let modal = this.modalCtrl.create('EventModalPage', {selectedDay: this.selectedDay});
    modal.present();
    modal.onDidDismiss(data => {
      if (data) {
        let eventData = data;
        eventData.startTime = new Date(data.startTime);
        eventData.endTime = new Date(data.endTime);
        let events = this.eventSource;
        events.push(eventData);
        this.eventSource = [];
         setTimeout(() => {
          this.eventSource = events;
          this.managelist= events;
          console.log( this.managelist);
         // this.eventSource = this.managelist[0];
        });
      }
    });
  }

**Comment by AravindrajanSampathkumar** [comment]
@twinssbc I can't able to fetch the this.managelist data to html page. Please check and solve

**Comment by twinssbc** [comment]
@AravindrajanSampathkumar 
It seems your HTML code is not complete, could you provide more?
Did you get any error or simply the eventDetail list is empty?

**Comment by AravindrajanSampathkumar** [comment]
@twinssbc thus is my complete html code, Please check

<ion-content>
    <ion-buttons >
        <button ion-button  (click)="toggle()" label="Hide">
          Add
        </button>
      </ion-buttons>
  

  <calendar *ngIf="show" [eventSource]="eventSource"
          [calendarMode]="calendar.mode"
          [currentDate]="calendar.currentDate"
          [monthviewEventDetailTemplate]="template"
          (onEventSelected)="onEventSelected($event)"
          (onTitleChanged)="onViewTitleChanged($event)"
          (onTimeSelected)="onTimeSelected($event)"
          step="30"
          class="calendar">
        </calendar>
        <template #monthviewDefaultEventDetailTemplate showEventDetail="showEventDetail" selectedDate="selectedDate" noEventsLabel="noEventsLabel">
          <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
              <ion-item *ngFor="let event of managelist" (click)="eventSelected(event)"> 
                      <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                          -
                          {{event.endTime|date: 'HH:mm'}}
                      </span>
                  <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn">All day</span>
                  <span class="event-detail">  |  {{event.title}}</span>
              </ion-item>
              
          </ion-list>
      </template>
      <div>
        
      </div>
  </ion-content>

**Comment by twinssbc** [comment]
@AravindrajanSampathkumar There are multiple places need to be corrected.
1. In your template, you declare the id as "monthviewDefaultEventDetailTemplate", when you set the template in the calendar attribute, you should also use it. [monthviewEventDetailTemplate]="monthviewDefaultEventDetailTemplate"
2. I don't quite understand below code. It seems you try to assign eventSource to other variable, and then clear it. Also what's the usage of setTimeout?
```
let events = this.eventSource;
events.push(eventData);
this.eventSource = [];
setTimeout(() => {
this.eventSource = events;
this.managelist= events;
console.log( this.managelist);
// this.eventSource = this.managelist[0];
});
```

If you just want to add an event into eventSource, you could just call this.eventSource.push(eventData). But as I mentioned in the Event Source section in README, directly modifying the eventSource element requires explicitly call the loadEvents method. Alternatively you could create a new array, push eventData, then assign that array to eventSource variable.

Below code works for me.
```
  addEvent() {
    var startTime = new Date();
    startTime.setHours(9,0,0,0);
    var endTime = new Date();
    endTime.setHours(10,15,0,0);
    var eventData = {
     title: 'test',
     startTime: startTime,
     endTime: endTime,
     allDay: false
    };
    let events = this.eventSource;
    events.push(eventData);
    this.myCalendar.loadEvents();
    this.managelist= events;
    console.log( this.managelist);
  }
```

**Comment by AravindrajanSampathkumar** [comment]
@twinssbc Thanks for you response but still I got the error under the line   this.myCalendar.loadEvents();
error is coming under myCalendar.

**Comment by twinssbc** [comment]
@AravindrajanSampathkumar loadEvents is an instance method. Take a look at the Instance Methods section in README.
