### ISSUE TITLE
Buttons to Swipe

### ISSUE THREAD

**Issue by johnmikelridz** [twinssbc/Ionic2-Calendar#204]
For user experience, I have added buttons right beside the viewTitle variable in Ionic. However, I cannot seem to understand how the slider slides to the next month (or the previous month). Is there any possible way we can use (click) and have the calendar either move to the previous month or next month?

**Comment by twinssbc** [comment]
@johnmikelridz Yes, you just need to set the currentDate to a date in previous/next month.

**Comment by Titoch** [comment]
Hi,
I think the need (it's also my need) is to show the Swipe animation when setting the new currentDate to next/previous month.
Actually, setting this currentDate make the calendar updated but without any animation.

**Comment by twinssbc** [comment]
@Titoch It's not supported in the current version. I will investigate if I could expose such method.

**Comment by darkholiday** [comment]
any updates about the animation ?

**Comment by twinssbc** [comment]
@darkholiday @Titoch 
I found the solution.
You could get the underlying Swiper instance by using pure DOM query.
Then you could any Swiper instance method you want.
```
    var mySwiper = document.querySelector('.swiper-container')['swiper'];
    mySwiper.slideNext();
```

**Comment by darkholiday** [comment]
i will try it soon i am working on another project right now. i will let you know if it worked or not ;)

**Comment by ramogundogdu** [comment]
@twinssbc  yes `slideNext()` shows the next months. But how can I slide back again? With wich method?

**Comment by ramogundogdu** [comment]
@twinssbc I found it :) `slidePrev()` shows the previous slide

**Comment by idanb11** [comment]
Hi @twinssbc ,,,

Thanks for this plugin.

Is there a way to can a handle of the slides instance without the `document.querySelector`?
and use instead the Ionic way like so:

```
import { ViewChild } from '@angular/core';
import { Slides } from 'ionic-angular';

class MyPage {
  @ViewChild(Slides) slides: Slides;

  goToSlide() {
    this.slides.slideNext();
  }
}
```

**Comment by twinssbc** [comment]
@idanb11 Because the slides is inside the calendar component, so you can't get the slide reference via ViewChild. I could expose instance method on calendar component to call the underlying calendar.
Anyway, I think directly using document.querySelector to get the Swiper reference is not a bad idea. In this way, you don't need to wait IonSlide and my calendar to expose a method.

**Comment by idanb11** [comment]
Yes, I agree that using `document.querySelector` is not a bad idea,
but in case you have multiple instances of your calendar component in a single page - you have to add IDs to each component `<calendar id="some-id"></calendar>` which it not a good practice.

I'll be happy if you could expose a method to call the underlying calendar.

Thanks.

:+1:

**Comment by slzr** [comment]
@idanb11 there is not updates about that method?

**Comment by Jai-Kumaresh** [comment]
> @darkholiday @Titoch
> I found the solution.
> You could get the underlying Swiper instance by using pure DOM query.
> Then you could any Swiper instance method you want.
> 
> ```
>     var mySwiper = document.querySelector('.swiper-container')['swiper'];
>     mySwiper.slideNext();
> ```

It's not work in ionic 4. If you know any solution please tell me. My need is clicking the arrow icon event to trigger the calendar next month swipe.
![ionic2-calendar-issue](https://user-images.githubusercontent.com/43090102/55212485-e9b11c00-5215-11e9-865a-904a657c4b82.png)

**Comment by NIYASSURABHI** [comment]
> @darkholiday @Titoch
> I found the solution.
> You could get the underlying Swiper instance by using pure DOM query.
> Then you could any Swiper instance method you want.
> 
> ```
>     var mySwiper = document.querySelector('.swiper-container')['swiper'];
>     mySwiper.slideNext();
> ```

this is not working in my ionic4 app (Angular 8). Can you please help me on this?

**Comment by twinssbc** [comment]
Add new instance methods slideNext/slidePrev in version 0.5.8. Feel free to give a try.
