### ISSUE TITLE
Some Customizations for the DayView

### ISSUE THREAD

**Issue by johnmikelridz** [twinssbc/Ionic2-Calendar#208]
We are currently working on a scheduling / booking app that leverages this ionic2-calendar.
One of the features that I need to have working with this app is the core of it, the booking part. I sent the video to you to understand.

What I want to achieve is the following:

1. Pass the selectedDate to the title of the DayPage (it always shows October 20, or whatever the current date is).
2. Trim down the dayView to remove the allday event at the very top and start the dayview row to say, maybe 8am or 9am up until 8pm or 9pm only.
3. Pass a value to this dayView page so as when a user selects an initial time, say 8am, and the passed value is 5 hours, then automatically a gray shade or some css powered color will appear stating that the timing is visually confirmed.
4. We're syncing this with firebase's firestore, I want to be able to cross out or make unavailable the times that another user has booked.

If you would have guessed it, we are trying to customize the dayView page to be the page where a user selects an hour only if it is available, otherwise, he will have to select another date.

Thank you.

John

**Comment by twinssbc** [comment]
@johnmikelridz 
1. Once you select the date, it also becomes the current date, so no need to set it again. You could also set the currentDate programatically.
2. You could use below css
```
.dayview-allday-table {
  display:none;
}
.dayview-normal-event-contaienr {
margin-top: 0;
}
.dayview-normal-event-container .scroll-zoom-wrapper {
margin-top: -296px;
height: 710px;
overflow: hidden;
}
```
3. You just need to add an event to the corresponding timeslot and add some css style for the event element.
4. You could add an event, and have some custom property like 'blocked', then add some css style for such kind of event. You could take a look at the View Customization to find out how to create some custom template

**Comment by twinssbc** [comment]
@johnmikelridz I just added startHour and endHour options, so you don't need to css to hide part of the calendar as I suggested in item 2 above.

**Comment by johnmikelridz** [comment]
Oohh, how do I update the code? Do I just run npm install ionic2-calendar@latest --save once more? 

As an added to my question number 3 above, how does one initialize an array for eventSource? I want to be able to pull this data from FireStore using AngularFire2 but I want to test it out with mockdata first before I use a service.

Thanks!

**Comment by twinssbc** [comment]
@johnmikelridz Yes, you just run npm install ionic2-calendar@latest.
To fill some mocked data into eventSource, you could refer to the Demo page in the source code. It is doing the exact thing.

**Comment by johnmikelridz** [comment]
Thanks for your help.

I'm going to push this a little further.

I am combining the month view and day view on a single page. I want them both to reference the same instance of the calendar. If I select a date on the month view, the day view should update (depending on the eventSource) and vice versa (meaning, if I swipe left / right on the day view - the month view should change it's highlighted date).

Is this possible? Please let me know if this confuses you. I can show you a screenshot to visualize what I am trying to achieve.

Thank you very much.

**Comment by twinssbc** [comment]
@johnmikelridz Unfortunately it's not possible to have two calendars in the same page.
This is due to a bug of the underlying ion-slides. It doesn't support that.
