### ISSUE TITLE
Creating a new view

### ISSUE THREAD

**Issue by carolineberger** [twinssbc/Ionic2-Calendar#209]
Hi! I'm super new to javascript- this is my first 'real' project. 
Is there a way to create a new view, like monthview, weekview, and dayview? Specifically, I'm looking to create a mode that shows three days. For example, if today is October 30, I'd want to show October 29, 30 and October 31. 
Is it possible to use CSS to create this view from the pre-existing views? 

Thank you!
Caroline

**Comment by twinssbc** [comment]
@carolineberger Unfortunately just using CSS is not sufficient to create three-day view. There's some logic in JavaScript code to calculate each event should be placed in which position, and they are calculated based on 7 days. If you want to display the events like the weekview and dayview, I'm afraid you need to read the source code and mimic the logic for 3 days view. If you just want to display the events in some simple format, for example, in a list, you could create a separate page to display them easily.
