### ISSUE TITLE
 The days go wrong

### ISSUE THREAD

**Issue by IversonViana** [twinssbc/Ionic2-Calendar#211]
The days are out of order, instead of starting on Sunday, starts on Friday.
![calendar](https://user-images.githubusercontent.com/33282266/32271127-9ee82170-bedf-11e7-97b6-b328f75ad96f.JPG)

**Comment by twinssbc** [comment]
@IversonViana Did you do any customization on the style or use startingDayMonth option?

**Comment by twinssbc** [comment]
@IversonViana 
Could you provide your code that is using the calendar?
Is there any error printed out in the console?
Can you still swipe to the previous/next month?

**Comment by IversonViana** [comment]
I got it sorted. The problem was in my main css, I was setting the ion-slide with left: 25%. Thanks for the feedback.
