### ISSUE TITLE
onTimePress($event)

### ISSUE THREAD

**Issue by RM650** [twinssbc/Ionic2-Calendar#212]
Hi, is possible to create a custom event working similar like onTimeSelected using press event?

**Comment by twinssbc** [comment]
@RM650 In monthview, the default template is like below, you could create your own template using monthviewDisplayEventTemplate. In your own template, you could add extra HTML element and attach press event to it.

```
<template #template let-view="view" let-row="row" let-col="col">
      {{view.dates[row*7+col].label}}
  </template>
```

**Comment by RM650** [comment]
Thanks, I understand. I will try.

**Comment by RM650** [comment]
I have one more question. Is possible to custom day view? I know, that I can custom displaying events but what about all view. I want customize drawing col and rows in day view. Is possible by #template or I need override css?

**Comment by RM650** [comment]
Next question. I want change height & top styles of '.calendar-event'. I know how to add some elements inside, its possible by template directive. Overriding css its not good idea, because when I start draw my event in 8:30am then it is not in middle. I also change '.calendar-cell' height, so I need higher '.calendar-event'. Can you help me?

**Comment by RM650** [comment]
Ok, I have solution. I create directive which update parentElement properties.
`
@Directive({
  selector: '[calendar-event-inner]'
})
export class CalendarEventInnerDirective {
  @Input() displayEvent: any;

  element = <ElementRef>null;
  hourParts = 4;

  constructor(el: ElementRef) {
    this.element = el;
  }

  ngAfterViewInit() {
    this.element.nativeElement.parentNode.style.top = (109 * this.displayEvent.startOffset / this.hourParts) + 'px';
    // this.element.nativeElement.parentNode.style.height = 109*(this.displayEvent.endIndex - this.displayEvent.startIndex - (this.displayEvent.endOffset + this.displayEvent.startOffset)/this.hourParts)+'px'
    this.element.nativeElement.parentNode.style.height = 109*moment.duration(moment(this.displayEvent.event.endTime).diff(this.displayEvent.event.startTime)).asHours() + 'px';
    this.element.nativeElement.parentNode.style.left = 100 / this.displayEvent.overlapNumber * this.displayEvent.position + '%';
    this.element.nativeElement.parentNode.style.width = 100 / this.displayEvent.overlapNumber + '%';
  }

}
`
@twinssbc 
But i have problem with events overlapping, look at screenshot: http://prntscr.com/h7w4qk
There are no overlapping events for me, how to fix it?

**Comment by JoanJosep33** [comment]
@RM650 
Can you pls explain me how u solved the press event??

Thank you.

**Comment by RM650** [comment]
@twinssbc 
If I remove all custom code then drawing is bugged, or maybe I should set some options. So, now in visual version is here overlapping and in code is too. So what now? Can u help? If u need I can put some code, just tell me what kind piece of code.
Screen with original code:
![Overlapping](https://image.prntscr.com/image/BWCTe8QxRcSyIZHUem_W1w.png)

@JoanJosep33 
Sorry I still working for press event in DAY VIEW. But I saw your topic and some people explained you how to did it for month view. I can explain you how to create press event for drawing BLOCK EVENT.

**Comment by twinssbc** [comment]
@RM650 Did you customize any CSS style?
I just tried two fake events as below, and they are not overlapping.
```
    var start1 = new Date();
    start1.setHours(10,0,0,0);
    var end1 = new Date(start1);
    end1.setHours(10,30,0,0);
    var start2 = new Date(start1);
    start2.setHours(10,30,0,0);
    var end2= new Date(start2);
    end2.setHours(10,59,0,0);

    events.push({
      title: 'test1',
      startTime: start1,
      endTime: end1,
      allDay:false
    });

    events.push({
      title: 'test2',
      startTime: start2,
      endTime: end2,
      allDay:false
    });
```

**Comment by RM650** [comment]
@twinssbc Hmm.. strange. I try again and i have exactly the same result. I create new page and copy code from your tutorial and I didn't customize any CSS. Look at the screen:

first block: 10:00
second block 10:30
![Overlapping](https://image.prntscr.com/image/QJ2ZYk-DTymE3ENZml36Jw.png)

HTML: 
`
<ion-content>
  <calendar [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate"
    step="30">
  </calendar>
</ion-content>
`

Page.ts:
<pre>
  eventSource = [];
  calendar = {
     mode = 'day', 
     currentDate = new Date()
  };
</pre>

@JoanJosep33 I create custom DAY VIEW press event. There is some logic for my app but I think this piece of code can help you.
Calendar function event:
<pre>
onTimePress(event) {
        if(this.isEventSelected){
            return;
        }

        let currentRow = event.target.closest('tr');
        let table = document.body.querySelector('#elementCalendarDay .swiper-slide-active .dayview-normal-event-container .dayview-normal-event-table');
        let rows = table.querySelectorAll('tr');
        
        let i = 0;
        while(currentRow != rows[i]){
            i++
        }

        this.pressedTime = new Date(moment(this.currentDate).format('YYYY-MM-DD'));
        this.pressedTime.setHours(i + this.calendarComponent.startHour, 0, 0, 0);

        let eventData = {
            title: '',
            startTime: this.pressedTime, 
            endTime: new Date(moment(this.pressedTime).add(1, 'hours').format("YYYY-MM-DD HH:mm:ss")), 
            allDay: false
        };

        this.eventSource.push(eventData);
        this.calendarComponent.loadEvents();
    }

onEventSelected(event) {
        this.isEventSelected = true;
}
</pre>

HTML: 
`
<calendar [eventSource]="eventSource"
    [calendarMode]="calendarDay.mode"
    [currentDate]="calendarDay.currentDate"
    (press)="calendarDay.onTimePress($event)"
    step="30">
 </calendar>
`

**Comment by twinssbc** [comment]
@RM650 Could you show me how do you create the date? Are the second and millisecond part both 0?

**Comment by RM650** [comment]
@twinssbc Hehehe, okay man, it was a problem... sorry for the confusion. Thanks :)
