### ISSUE TITLE
'ng-template' is not a known element:

### ISSUE THREAD

**Issue by HamzaouiMounir** [twinssbc/Ionic2-Calendar#216]
Cannot configure the calendar in my app.module.ts [IONIC 2] 
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("          [ngClass]="getHighlightClass(views[0].dates[row*7+col])">
                                [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ngOu"): MonthViewComponent@16:32
'ng-template' is not a known element:

**Comment by twinssbc** [comment]
@HamzaouiMounir Which Angular version are you using? **ng-template** is introduced in Angular4. If you are still using Angular2, you should use **template**
