### ISSUE TITLE
Upgrade to ionic 3.9.2 ngOutletContext error

### ISSUE THREAD

**Issue by aces-tm** [twinssbc/Ionic2-Calendar#217]
I just upgraded to Ionic 3.9.2 which runs Angular 5.0.0 and one of the breaking changes is replacing ngOutletContext with ngTemplateOutletContext. This breaking change causes plugin to display folloring error: 

Template parse errors: Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'. 1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component. 2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("emplate [ngTemplateOutlet]="dayviewAllDayEventTemplate" [ERROR ->][ngOutletContext]="{displayEvent:displayEvent}"> </ng-templat"): ng:///NgCalendarModule/DayViewComponent.html@17:44 Property binding ngOutletContext not used by any directive on an embedded template.

When I go to dayview.js, monthview.js and weekview.js and update ngTemplateContext the plugin works fine, but on dayView instead of hours in the column shows letter "j" and I am not sure why. I found a function where the plugin calculates hours, but I don't won't to mess with plugin since I don't know the code that well.

Can you update the plugin or give me instructions how to fix it. Thanks!

**Comment by aces-tm** [comment]
So I fixed "j" issue it by adding following code to my ts file:

        dateFormatter: {
            formatDayViewHourColumn: function(date:Date) {
              return moment(date).format('ha')
            },
        }

All the issues on my end are solved. I suggest updating the plugin. 

Thanks for the awesome plugin!

**Comment by FallenRiteMonk** [comment]
I would also like start using this library.  @aces-tm could you please create a PR for your changes so that it works with ionic 3.9.2 and angular 5.0.0?

**Comment by aces-tm** [comment]
@FallenRiteMonk Not sure how to create PR, but all you need to do is go to node_modules --> ionic2-calendar and find files dayview.js, monthview.js and weekview.js and in your code editor search for ngOutletContext and replace it with ngTemplateOutletContext. In dayview.js and weekview.js I believe there was 6 locations and in monthview.js there was 7. That's it. Hope it helps.

**Comment by FallenRiteMonk** [comment]
@aces-tm The problem with changing it in nodes_modules folder is that it's not persistent, but if I'll find the time I'll create a PR in the hope that it gets merged.

**Comment by aces-tm** [comment]
@FallenRiteMonk I agree... If somebody gives me instructions how to do it I will... I just never done it

**Comment by FallenRiteMonk** [comment]
I have already done it, but for the next time:
1) Fork repo
2) Clone fork locally
3) Make changes (normally done in new branch)
4) Commit & push
5) Go to github fork and create PR (Use the button that appears on your changed branch)

More detailed:
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by chsukhesh** [comment]
@aces-tm Thank you. It work's perfectly.

**Comment by danielehrhardt** [comment]
Same yere

**Comment by twinssbc** [comment]
I have released 0.4.0 which supports Ionic 3.9.2. Feel free to have a try.

**Comment by aces-tm** [comment]
@twinssbc works great thanks

**Comment by faizan1219** [comment]
@twinssbc i am still having this issue..

**Comment by twinssbc** [comment]
@faizan1219 Only 0.4.x version supports Ionic 3.9.2 and Angular 5.0.

**Comment by faizan1219** [comment]
@twinssbc  so do i have to add '@latest' flag with npm install? or if there is another way to get 0.4.x version?

**Comment by twinssbc** [comment]
@faizan1219 Take a look at the rule of semver.
https://docs.npmjs.com/misc/semver
You could use 0.4.x, so that the version stick to 0.4

**Comment by faizan1219** [comment]
@twinssbc thanks for the help :)

**Comment by waleedshkt** [comment]
Using ionic@3.9 with angular@5
`------------------------------------------`

@aces-tm, it seems like one has to change `ngOutletContext` to `ngTemplateOutletContext` not only in DayView.js, WeekView.js and Month.js but in all the remaining files under node_modules/ionic2-calender that contain `ngOutletContext`. 

It is tedious but I guess it's the only way to change the `ngOutletContext` to `ngTemplateOutletContext` manually by using _search_ tool in code editor to find `ngOutletContext` in the files!

Hope this helps others having a similar issue.

**Comment by twinssbc** [comment]
@waleedshkt The js files are release files, they are generated automatically. You don't have to touch them. Instead, you need to use ionic2-calendar 0.4.x version. It supports Angular 5 and has resolved the ngTemplateOutletContext change.

**Comment by waleedshkt** [comment]
@twinssbc , thanks a lot for your quick response!
Yeah, that worked perfectly!

**Comment by yewness** [comment]
In case someone gets stuck with the initial installation that gives you 0.3.13 (as per written), you can install 

`npm install ionic2-calendar@0.4.x --save`

to get the latest version that the change to ngTemplateOutletContext has been fixed.

A lot of breaking changes after not touching the app for months.
