### ISSUE TITLE
Scroll position in day and weekview not saved after swiping

### ISSUE THREAD

**Issue by Daskus1** [twinssbc/Ionic2-Calendar#22]
When swiping in dayview or weekview the scroll-point is not saved.
This means if I scroll to the bottom and then swipe the scroll position will be again at the top (12am).

**Comment by twinssbc** [comment]
I will try to expose an option for this feature.

**Comment by twinssbc** [comment]
@Daskus1 I have added two scrolling related options, **scrollToHour** and **preserveScrollPosition**. Feel free to have a try.

**Comment by Daskus1** [comment]
Works fine! Good work.
the only thing I had to do in order to make it work, since I got a typescript error, was changing `super(el)` to `super()` in the constructor of `src\init-position-scroll.ts`

**Comment by twinssbc** [comment]
@Daskus1 The scroll component in Ionic3 was updated last month to remove the parameter of the constructor. Since I still need to make my code compatible with old versions, so I can't remove that parameter. I may remove it in the future version.
