### ISSUE TITLE
Is there any option to (press) event calendar?

### ISSUE THREAD

**Issue by JoanJosep33** [twinssbc/Ionic2-Calendar#220]
Hello there, I am trying to do a press event, since the double click is not working on Ionic 2. 

The problem is that if I create a (press)="myFunction($event)" this event is from the pressed action, and not from the calendar. 

Is there any option to do this? 

Thank you so much!

**Comment by paean99** [comment]
You probably need to change the template as explained here: [view-customization-option](https://github.com/twinssbc/Ionic2-Calendar#view-customization-option).

An example with the 'monthviewEventDetailTemplate' would be:
`<template #yourPressTemplate let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
            <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
                <ion-item *ngFor="let event of selectedDate?.events" (click)="eventSelected(event)" (press)="myFunction(event)">
                        <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                            -
                            {{event.endTime|date: 'HH:mm'}}
                        </span>
                    <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn">{{allDayLabel}}</span>
                    <span class="event-detail">  |  {{event.title}}</span>
                </ion-item>
                <ion-item *ngIf="selectedDate?.events.length==0">
                    <div class="no-events-label">{{noEventsLabel}}</div>
                </ion-item>
            </ion-list>
        </template>
        
        <calendar ... [monthviewEventDetailTemplate]="yourPressTemplate"></calendar>`

You just have to add this in your component template. 
The original code was taken from [calendar.ts#L134](https://github.com/twinssbc/Ionic2-Calendar/blob/master/src/calendar.ts#L134) with your press function added.

**Comment by JoanJosep33** [comment]
Hello @paean99 

Copying this code doesen't solve the problem. If I press a day, nothing happens :/

**Comment by paean99** [comment]
I made the code very generic.
One obvious error in it is on the way the event in passed to the myFunction.

The proper way should be: (press)="myFunction($event, event)"
The first ($event) is the DOM event object and the seceond (event) is the one from the calendar.

The two have to be passed i believe.
