### ISSUE TITLE
ionic 2 :  i need only select date in console. please help me my code is bellow 

### ISSUE THREAD

**Issue by dkandari** [twinssbc/Ionic2-Calendar#221]
html           <calendar 
		[eventSource]="eventSource"
		[calendarMode]="calendar.mode"
		[currentDate]="calendar.currentDate"
		(onEventSelected)="onEventSelected($event)"
		(onTitleChanged)="onViewTitleChanged($event)"
		(onTimeSelected)="onTimeSelected($event)"
		></calendar>

ts  

onTimeSelected(ev) {
console.log('Selected time: '+ ev.selectedTime);
 
}

console output is : Thu Nov 16 2017 12:00:00 GMT+0530 (India Standard Time)

i need this type of format : Thu Nov 16 2017

**Comment by JoanJosep33** [comment]
What do u need exactly, put an example.

**Comment by Anujmoglix** [comment]
use Js and format that date .

**Comment by twinssbc** [comment]
The issue description is not clear.
