### ISSUE TITLE
Error: Missing locale data for the locale "de-DE"

### ISSUE THREAD

**Issue by ramogundogdu** [twinssbc/Ionic2-Calendar#223]
I get the following Error after updating` ionic-angular` from `3.8.0` to `3.9.2` 

 `<calendar [eventSource]="eventSource" [locale]="calendar.locale"  ...  </calendar>`

```
  calendar = {
    mode: 'month',
    locale: 'de-DE',
    currentDate: new Date()
  };
```

if I change locale to `'en-GB'` it works, but I need to set up the locale to `'de-DE'`

**Comment by paean99** [comment]
The maintainer just added new info that might help you at [Ionic2-Calendar#localization](https://github.com/twinssbc/Ionic2-Calendar#localization).
