### ISSUE TITLE
Locale ERROR

### ISSUE THREAD

**Issue by FallenRiteMonk** [twinssbc/Ionic2-Calendar#224]
I get the following error:
```
ERROR TypeError: Cannot read property 'dayHeaders' of undefined
```
pointing to line 19 of the monthview.ts file (```<th *ngFor="let dayHeader of views[0].dayHeaders">```)
when trying to display a calendar in a different locale. Relevant code parts are:
```
html:
<calendar [currentDate]="calendar.currentDate" [locale]="calendar.locale"></calendar>

ionic page (ts):

import 'intl';
import 'intl/locale-data/jsonp/de';
...
calendar = {
    currentDate: new Date(),
    locale: 'de-DE'
  }
```
It works perfectly fine with locale en-GB, en-US and even just en, but doesn't work for de-DE, it-IT and es-ES (These are just the ones I tried, there might be more).

Ionic2-Calendar version:
```
0.4.0
```
intl version:
```
1.2.5
```
Ionic info:
```
cli packages: (/home/fallenritemonk/dev/clubBoard/app/node_modules)

    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.8.1
    npm               : 5.5.1 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/fallenritemonk/bin/android-sdk

Misc:

    backend : legacy

```

**Comment by paean99** [comment]
The maintainer just added new info that might help you at [Ionic2-Calendar#localization](https://github.com/twinssbc/Ionic2-Calendar#localization).

**Comment by FallenRiteMonk** [comment]
@paean99 I totally missed that. Thanks, now it works.
