### ISSUE TITLE
dynamic locale change

### ISSUE THREAD

**Issue by FallenRiteMonk** [twinssbc/Ionic2-Calendar#225]
Having a simple calendar (only month view, no events, no template customization,...) and changing the 'locale' dynamically during runtime, the monthview header doesn't get updated.

Am I missing something, or is this a bug?

**Comment by twinssbc** [comment]
@FallenRiteMonk How do you change locale? It won't update the current view itself. You need to either switch from a view that doesn't contain calendar or switch to other week/day mode. So that the calendar will get a chance to reinitialize.

**Comment by FallenRiteMonk** [comment]
@twinssbc I set the apps default locale and then get the users locale from a provider over a subscription, so a view change is not possible since then also the users local is fetched again. Changing the mode of the calendar is also no possibility since that would result in bad user experience. Is there some kind of possibility to trigger a re initialization manually? Maybe by specifying a custom header or so! If not, I would be happy to implement it and create a PR for it. Just let me know, because I really like this library and would like to use it over a different one I'm using at the moment due to some drawbacks of that library.

**Comment by paean99** [comment]
If you only need to set the language one time depending on the device language, you should be able to do it in the parent component of the component with the calendar before the child DOM loads.
Ex: If the calendar is loaded at the root, you can edit app.component.ts:
```javascript
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

// import you provider
import { LanguageProvider} from './providerPath';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  // do not set rootPage yet.
  rootPage:string;

  constructor(
    platform: Platform,
    statusBar: StatusBar,
    splashScreen: SplashScreen,
    languageService: LanguageProvider
  ) {

    // get the language and set it before defining the rootPage
    this.languageService.getLanguage().subscribe(language=> {
      setCalendarLanguage(language);
      this.rootPage = 'CalendarPage';
    })

    platform.ready().then(() => {
      // Or put your code here, if you need the DOM to be ready
      //////////////////////////////////////////////////////////////////
      statusBar.styleDefault();
      splashScreen.hide();
    });
  }
}
}
```
With app.html:
```HTML
<ion-nav [root]="rootPage"></ion-nav>
```

**Comment by FallenRiteMonk** [comment]
No this is not the case, a user can dynamically change the preferred language during runtime.

**Comment by paean99** [comment]
In that case you could just reload the component as described here [stackoverflow - How to reload the current Angular 2 Component](https://stackoverflow.com/a/42369191) or another 'method'. They should work. But they are more similar to hacks than an solution.

The best would probably be to update the loadEvents method of calendar at [calendar.ts#L379](https://github.com/twinssbc/Ionic2-Calendar/blob/ea092a37c750b66b5795603f5ebcc6ed060bd336/src/calendar.ts#L379) or add a broader one (like updateProperties() ).

Another idea would be to connect the properties in calendar to Observables...

**Comment by FallenRiteMonk** [comment]
That doesn't quite work as expected, but it works if I prevent rendering until the users locale is set.
Though for a long term, this isn't the right solution!

@twinssbc what do you think? Can we implement this somehow into the lib? Would really appreciate it and I think there are going to be more use cases for this.

**Comment by paean99** [comment]
I have put for consideration the start of a possible solution in a pull request.

**Comment by twinssbc** [comment]
@FallenRiteMonk How does the user change locale? Is it at the same page with the calendar? I would assume you have a "settings" page to allow user changing the locale and then navigate back to the calendar page?

**Comment by FallenRiteMonk** [comment]
@twinssbc your assumption is right, but I use a settings provider which maintains my settings. So when the page with the calendar opens I subscribe to the BehaviorSubject and get my current state of the settings (so it is not known when rendering the view). Surly to prevent memory leaks I also unsubscribe once the page leaves, so even when returning back to the calendar page the setting again arrives with the delay of the subscription.

**Comment by twinssbc** [comment]
@FallenRiteMonk 
You mentioned that you subscribe and unsubscribe the locale change when entering and leaving the calendar page, while you change the locale in a different page. In this case, why do you need to subscribe the change? I would think subscription only works when calendar is there, otherwise there's no need to subscribe to a change?
Could you just retrieve the locale in a sync way?
For example, you define the locale like

```
<calendar [locale]="calendar.locale" ...></calendar>
```

Then set the locale in component
```
this.calendar.locale = this.preferenceService.getLocale();
```

**Comment by FallenRiteMonk** [comment]
@twinssbc I'm currently investigating on a major change to the structure of my app which would could solve this problem by also having access to settings (including locale) in a sync way, but since it's quiet a big change it will take me some time to get it done, until then I cannot say if is will really be fixed. I'll keep you informed once I get the time to implement the change and how it worked out, but I guess there will also be apps where the local will be changed on the same view as the calendar, so I believe the possibility of changing it dynamically will sooner or later be required.

**Comment by tryadelion** [comment]
any news?
could we provide our own translations instead?

**Comment by twinssbc** [comment]
@tryadelion The calendar provides dateFormatter option to allow you use your own way to transform from the date to text. You could just add localization logic in your dateFormatter.
