### ISSUE TITLE
SelectedDay Active when the Day has Event

### ISSUE THREAD

**Issue by JoanJosep33** [twinssbc/Ionic2-Calendar#226]
Hello there again, I want to know how can I do it to the selectDay get the color as selectedDay even if is marked with an event. 

Actually looks like this : 

https://gyazo.com/82de42bc6c0cca60f7bd1474632f1c29

I am selecting the Friday 17, but the ActiveDay css is not applying it. 

Any consideration? 

Thank you!

**Comment by JoanJosep33** [comment]
after some tries, I solved using the following code: 
 .monthview-selected[_ngcontent-c1].monthview-primary-with-event[_ngcontent-c1]{
    background-color: green;
  } 

this is how looks like: 

https://gyazo.com/c8e49e653596f9694227f7a4af661530

**Comment by paean99** [comment]
You might consider removing the [_ngcontent-c1] attribute. it is dynamically created by angular for their [View encapsulation](https://angular.io/guide/component-styles#view-encapsulation). You should use ::ng-deep to do a similar thing.

Note from Angular: 
> The shadow-piercing descendant combinator is deprecated and support is being removed from major browsers and tools. As such we plan to drop support in Angular (for all 3 of /deep/, >>> and ::ng-deep). Until then ::ng-deep should be preferred for a broader compatibility with the tools.
 [source](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep)
