### ISSUE TITLE
Feature request: spaceBetween

### ISSUE THREAD

**Issue by FallenRiteMonk** [twinssbc/Ionic2-Calendar#227]
When having horizontal padding to the calendar the swiping animation looks kind of confusing/weard to me and I think settings the 'spaceBetween' attribute on the 'ion-slides' could improve that and shouldn't be to hard to implement.
http://ionicframework.com/docs/api/components/slides/Slides/#input-properties

@twinssbc What do you think?

**Comment by twinssbc** [comment]
@FallenRiteMonk Sure, I can add it.

**Comment by FallenRiteMonk** [comment]
@twinssbc thanks!

**Comment by twinssbc** [comment]
@FallenRiteMonk I have added spaceBetween option, feel free to have a try.
