### ISSUE TITLE
Event Didn`t Load To Calendar

### ISSUE THREAD

**Issue by satriantorobimo** [twinssbc/Ionic2-Calendar#228]
Hello,

Please help me, my event didn`t load to my calendar in real device but in browser loaded. I saved my event in local storage. Please help me.

**Comment by twinssbc** [comment]
@satriantorobimo You could try use Developer Tool to connect to your remote device to debug the code and see if any error printed out in the console.
You could also try just create some dummy events in the eventSource array to see if it works.
Some user hit this problem is because some data storage plugin doesn't work consistently in the real device.

**Comment by satriantorobimo** [comment]
@twinssbc can you help me? Im stuck about 3 days and almost die with this problem.

**Comment by satriantorobimo** [comment]
my problem is my selected day value is Thu Nov 16 2017 00:00:00 GMT+0700 (SE Asia Standard Time).

I follow the instruction and get that, how can i set time?

**Comment by twinssbc** [comment]
@satriantorobimo 
Sorry, I don't quite understand your problem.
-- my problem is my selected day value is Thu Nov 16 2017 00:00:00 GMT+0700 (SE Asia Standard Time).

Maybe you could show your code?

**Comment by satriantorobimo** [comment]
Sorry for late reply, so i made application for scheduling their assignments. I have feature rescheduling, which mean user can rescheduling their assignments. But when i show calendar event for reschedule page, that event is disappear. I think the format startTime and endTime change. I retrieve eventSource from my local storage.

![111](https://user-images.githubusercontent.com/26141281/33106711-1ec36d64-cf66-11e7-8ac2-8bcc28409302.jpg)
This is what happen when user do scheduling their assign (and working well)

And this is what happen when im doing rescheduling
![222](https://user-images.githubusercontent.com/26141281/33106816-b7b645b4-cf66-11e7-89fe-376feb3f64db.jpg)

I use same resource, but why i getting error like that?
(sorry my english is bad, but help me please)

**Comment by twinssbc** [comment]
@satriantorobimo As you can see from your second screenshot, the startTime and endTime are String, not Date. That's why it says startTime.getTime is not a function.

**Comment by satriantorobimo** [comment]
I already convert to date format and warning about startTime.getTime gone, see this SS
![code](https://user-images.githubusercontent.com/26141281/33156977-60020ae4-d031-11e7-8da8-d428d1485d0b.jpg)

But still not showing the event 
![2](https://user-images.githubusercontent.com/26141281/33157022-83e801fc-d031-11e7-9a01-c8853be12ea8.jpg)

Whats wrong with my apps? or you can give me advice?

**Comment by twinssbc** [comment]
The calendar doesn't watch the change on the individual element change in the eventSource array for performance consideration.
You could either fill an array first, then assign it to eventSource variable, or manually call the loadEvents method. 
For example,
```
        this.eventSource.push({
            title: 'test',
            startTime: startTime,
            endTime: endTime,
            allDay: false
        });
        this.myCalendar.loadEvents();
```
You could get more information from the loadEvents option in README.

**Comment by satriantorobimo** [comment]
Thank you for your help, it work like a charm!!!!! OMG you save my life... thank you!
