### ISSUE TITLE
Is it possible to show left and right arrows in week view to move to next and previous week.

### ISSUE THREAD

**Issue by severus1990** [twinssbc/Ionic2-Calendar#23]
Is it possible to show left and right arrows in week view to move to next and previous week. Now only swipe is possible

**Comment by twinssbc** [comment]
@severus1990 I think you can either add the button in the navbar or modify the weekview code to add them. In the click callback method, you just need to set the currentDate to the day in next or previous week. Similar to what happens on the today button in the demo page.

```
     today() {
        this.calendar.currentDate = new Date();
    }
```

**Comment by severus1990** [comment]
Thanks it worked!!

**Comment by divijm** [comment]
Can you show how you did this please @severus1990? Thanks
