### ISSUE TITLE
event_1.startTime.getTime is not a function

### ISSUE THREAD

**Issue by Bohmaster** [twinssbc/Ionic2-Calendar#230]
Whenever I click on day that has events this error appears:

> event_1.startTime.getTime is not a function

This is the response from the server to fill eventSource:
`
this.eventSource = data.response;`

`{"response":[{"title":"AA051400-tamara","description":"joaquin v  gonzalez 954 () SIN ASIGNAR, Ciudad Autonoma De Buenos Aires","allDay":false,"startTime":"2014-05-08T00:00:00.000Z","endTime":"2014-05-09T00:00:00.000Z"},{"title":"AA051400-tamara","description":"joaquin v  gonzalez 954 () SIN ASIGNAR, Ciudad Autonoma De Buenos Aires","allDay":false,"startTime":"2014-05-08T00:00:00.000Z","endTime":"2014-05-09T00:00:00.000Z"}]}`

The kind of events I need to use doesn't need startTime, endTime or allDay. Instead I need a description for example.

Can I use my custom event format?

Ionic Framework 3.7.0
Angular Core 4.4.6

**Comment by twinssbc** [comment]
@Bohmaster This is because your startTime and endTime are String, you need to convert them to a valid Date object.

**Comment by cemceliks** [comment]
Hi I have a similar problem. I have created some dummy events on my iPhone calendar. When I use Cordova native plugin to load those events like below I get an error "undefined is not an object (evaluating 'event_1.startTime.getTime'). Console.log shows iPhone dates in following format "2018-02-01 00:00:00". Do I need to update the result array returned by the promise before assisting to eventSource. Is this a known issue on Android as well. Thanks

this.calendarSrv.calendar.findAllEventsInNamedCalendar("Work").then(result => {
            this.eventSource = result;
            result.forEach(event => {
                console.log(event.startDate);
            });       
        }).catch(err => this.showAlert(err.message))

**Comment by twinssbc** [comment]
@cemceliks You need to parse the string to a valid Date object.

**Comment by mowaiskalam** [comment]
Hi @twinssbc, Same issue for me and I am passing the correct date 
'Fri Apr 20 2018 01:18:00 GMT+0500 (Pakistan Standard Time)'

Example: 
this.calendar.currentDate = new Date(1524169080000);

Can you please let me know what mistake I am doing Thanks

**Comment by AravindrajanSampathkumar** [comment]
@twinssbc I am facing the same issue here. I got the error like event_1.endTime.getTime is not a function
I tried to convert the string by using parse but it shows the value like NAN.
I have to parse the below time, can you suggest any ideas to solve?
var unixTimeZero = Date.parse('12:00 PM');

**Comment by twinssbc** [comment]
@AravindrajanSampathkumar Take a look at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
The input string needs to follow certain format, I don't think 12:00 PM is a valid one.

**Comment by AravindrajanSampathkumar** [comment]
@twinssbc Thanks it is working for me:)

**Comment by shashical** [comment]
How fix this issue TypeError: event_1.startTime.getTime is not a function
i have passed json sample  and i have read about date.parse how do i convert in dynamic json structure 
loadEvents() {
this.eventSource = [
    {
        "title": "All Day - 0",
        "startTime": "2018-06-28T00:00:00.000Z",
        "endTime": "2018-06-28T00:00:00.000Z",
        "allDay": true
    },
    {
        "title": "All Day - 48",
        "startTime": "2018-06-28T00:00:00.000Z",
        "endTime": "2018-06-28T00:00:00.000Z",
        "allDay": true
    },
    {
        "title": "All Day - 49",
        "startTime": "2018-06-28T00:00:00.000Z",
        "endTime": "2018-06-28T00:00:00.000Z",
        "allDay": true
    }   
]
}

**Comment by shashical** [comment]
If i pass this format am getting error typescript does not allowing to execute.
What i have to do to pass proper date format which calendar has to read that.
{title: "All Day - 0", startTime: Tue Jul 03 2018 05:30:00 GMT+0530 (IST), endTime: Wed Jul 04 2018 05:30:00 GMT+0530 (IST), allDay: true}

**Comment by shashical** [comment]
How do i show total number of events in month view
