### ISSUE TITLE
Feature Request: weekviewNormalDisplayTemplate

### ISSUE THREAD

**Issue by Titoch** [twinssbc/Ionic2-Calendar#232]
Hello!
In MonthViewComponent, there is a template permitting to customize style and action on each displayed dates : monthviewDisplayEventTemplate.
It's a very useful function that permits to do a lot of things.
I use it to color the days depending on date (today, week-ends, holidays...) without using any events.
I use events only for user's real activities.

Would it be possible to add the same type of template for WeekViewComponent (and not only for events) ?
 - weekviewNormalDisplayTemplate (for normal section) 
 - weekviewAllDayDisplayTemplate (for all-day section)

Thanks a lot for your work!

**Comment by twinssbc** [comment]
@Titoch I get the idea, but it's a bit complicated to expose such template in weekview.
In monthview, the template is applied on each cell, which is a single day. In weekview, even if I expose a template on each cell, which is an hour within a day, I'm afraid you are still not be able to color the whole day.
If I expose the template at a bigger scope, for example, make the whole table as a template, I think there's no difference from you modifying the source code directly.
In addition, since I already exposed the template on each event, it will introduce nested template if I expose another one at higher level. I did a quick test, it seems the nested template still works, but can't make sure if there will be any side effect.

**Comment by Titoch** [comment]
@twinssbc  Actually, Monthview permits to disable some days (markDisabled) that are grayed and can not be clicked.
When switching in Weekview these days can neither be clicked, but user can not see it.
Because the only difference between an active and a disabled day is the cursor, (only visible on web browser, not visible on mobile).

So in weekview when user clicks/taps on a disable day nothing happens ! Then he may thinks it's a bug...

I think your first proposal "expose a template on each cell" is a very good solution (better and less complex than nested templates).
Using the column parameter in this template would permit to customize each cell of a day to enhanced specific day's caracterisitcs (like markDisabled, but not only).

**Comment by twinssbc** [comment]
@Titoch I could expose template on each cell, but it may not meet your expectation.
Because I think you normally want to give the whole column on that day some background color or border. But now you could only apply to each cell.

**Comment by Titoch** [comment]
@twinssbc : Yes That's right I want to customize a whole column. 
But exposing the template on each will permit to do it and will fulfill all my needs.

Please could you do it ? 
I'll give you a feedback.

**Comment by twinssbc** [comment]
@Titoch Which version of Ionic2-Calendar are you using?
I'm still not confident to add this feature to official release.
I will publish a version for this particular change.

**Comment by Titoch** [comment]
@twinssbc : I'm currently using  ionic2-calendar@0.3.13
Please could you expose the template for dayView also?
Why are not you confident?

**Comment by twinssbc** [comment]
@Titoch I have released 0.3.13-weekdayview-tpls.
You could get the usage from View Customization section in below link
https://github.com/twinssbc/Ionic2-Calendar/tree/v3-weekdayview-tpls

The reason I'm not confident is because I have to implement nested template, not sure about the side effect.
Right now, you only need to notice that since eventSelected method is defined in your own html file, so you have to implement eventSelected in your component ts file. Luckily, the original eventSelected inside the calendar only contains one line of code which triggers the eventSelected event. So you don't need to port extra logic from the internal implementation of the calendar.

**Comment by Titoch** [comment]
@twinssbc : I have reused the 2 section templates you supplied.

Finally I use exactly the same sectionTemplate. for week and day views. 
weekviewNormalEventSectionTemplate

My sectionTemplate reuses your sectionTemplate and includes 3 nested DIV to render different elements.
I also use the weekviewNormalEventTemplate as I did before (no change in code).

Just a thing : 'hourparts' variable  is not known in my component. I replaced it with 15 in my template.

So I manage to do all I wanted easily.
The weekview and monthview are now coherent together.

Here is a monthview : 
Red line on the left shows the lockPrevious
Gray cells are Disabled-days. Green circle is a threshold, blue circle is the current day.
Yellow is for weekend. Orange are holidays.
Only days filled in blue are real user events (IEvent).
![monthview-with-holidays](https://user-images.githubusercontent.com/7573777/34162958-b782932a-e4d5-11e7-86b5-6b3395666fe5.png)

Here is the corresponding weekview with multiple user events using the nested eventTemplate.
As in the monthview, the  11 to 14 days  are disabled and now it's visible!
![weekview-with-events](https://user-images.githubusercontent.com/7573777/34162968-bdb66cda-e4d5-11e7-9617-8aa59c5323fb.png)

From my point of view it works perfectly. 
Will it be possible to merge this version with the main branch?
Thank you!

**Comment by twinssbc** [comment]
@Titoch That's very nice. I will leave that branch version for a while, if no issue found, then move it to main branch.

**Comment by abdulkadhir** [comment]
@Titoch can you explain how to disable weekend thanks

**Comment by Titoch** [comment]
@abdulkadhir You just have to edit markDiabled method and return true when date is a week-end.
Here for Saturday(6) and sunday (0) :
`markDisabled = (date: Date) => { return (date.getDay() == 6) || (date.getDay() == 0);  };`

You can see the result in monthView (saturday and sunday) days are grayed.
In WeekWiew you'll see nothing else than mouse is 'default', no more 'pointer'.

**Comment by abdulkadhir** [comment]
@Titoch thanks it works.
how to set different colors for the events.

**Comment by Titoch** [comment]
@abdulkadhir modify the css style of 
`.monthview-container  .table-bordered[_ngcontent-c1] > tbody[_ngcontent-c1] > tr[_ngcontent-c1] > td[_ngcontent-c1].monthview-disabled`
This is only possible in monthview.
If you want to do it in week or day view you have to use new weekviewNormalEventSectionTemplate or dayviewNormalEventSectionTemplate templates supplied in [https://github.com/twinssbc/Ionic2-Calendar/tree/v3-weekdayview-tpls](https://github.com/twinssbc/Ionic2-Calendar/tree/v3-weekdayview-tpls)

**Comment by abdulkadhir** [comment]
Thanks @Titoch

**Comment by Titoch** [comment]
@twinssbc Just about unknow hourparts property in weekviewNormalEventSectionTemplate or dayviewNormalEventSection templates :
Initially I replaced hourparts with 15 (like stepMinute) . In fact it has to be replaced with (60/stepMinute).
So now the position is very good.

**Comment by abdulkadhir** [comment]
@Titoch how to disable the particular day between given time, for example, I want to disable all Mondays between 9th  January  2018 to 30th March 2018

**Comment by Titoch** [comment]
@abdulkadhir 
You have to extend you markDisabled method:
`  markDisabled = (date: Date): boolean => {
      return (date.getDay() == 1
                 && (date.getTime() >= new Date(2018, 0, 9, 0, 0, 0, 0).getTime()
                 && date.getTime() <= new Date(2018, 2, 30, 23, 59, 59, 999).getTime()));
  };`

**Comment by abdulkadhir** [comment]
@Titoch I want to disable set of dates that are on my backend, my JSON format is

[

     {
        "5": "2018-01-06",
        "6": "2018-01-07",
        "12": "2018-01-13",
        "13": "2018-01-14",
        "19": "2018-01-20",
        "20": "2018-01-21",
        "26": "2018-01-27",
        "27": "2018-01-28",
        "33": "2018-02-03"
  }

]

how to disable that 
thanks

**Comment by twinssbc** [comment]
@abdulkadhir Your question is not related to this issue, and you already asked it in a separate issue. To keep the issue context clean, please post your comment only related to this issue.

**Comment by twinssbc** [comment]
@Titoch Just FYI, I have merged this feature to 0.3.x and 0.4.x branches.

**Comment by Titoch** [comment]
@twinssbc  Great news for me ! 
Thanks a lot !
