### ISSUE TITLE
Cannot read property 'dayHeaders' of undefined

### ISSUE THREAD

**Issue by joshnissenbaum** [twinssbc/Ionic2-Calendar#234]
After installing and placing into the component

**Comment by NiklasMerz** [comment]
@joshnissenbaum What was your solution?

**Comment by twinssbc** [comment]
@NiklasMerz 
For version 0.4.x which depends on Ionic 3.9.2 and Angular 5.0, locale module needs to be registered explicitly in module file as below.

```
import { registerLocaleData } from '@angular/common';
import localeZh from '@angular/common/locales/zh';
registerLocaleData(localeZh);
```

**Comment by NiklasMerz** [comment]
Thank you @twinssbc . I have found that in the README after finding another issue. Is there any way so get the old behavior where the correct locale is detected by the browser?

**Comment by twinssbc** [comment]
@NiklasMerz
I don't have a perfect solution right now.
Below is what I could achieve.
The locale could still be detected by using the window.navigator.language, I think that's also how the previous Angular version does.
Unfortunately, I don't find a way to load a module dynamically based on the locale, so I have to load all the supported locale modules.
Then based on the detected locale, I could register the corresponding module.
If the detected locale is not supported, then fallback to en-US.

```
import localeZh from '@angular/common/locales/zh';
import localeFr from '@angular/common/locales/fr';
let locale = window.navigator.language;
if(locale == 'zh-CN') {
  registerLocaleData(localeZh);
} else if(locale == 'fr-CA'){
  registerLocaleData(localeFr);
} else {
  locale = 'en-US';
}
```

**Comment by NiklasMerz** [comment]
Thank you. I will try that.

**Comment by paean99** [comment]
I have found a rough solution in this issue at the angular repository: [Document how to lazy load locale data on bootstrap of application](https://github.com/angular/angular/issues/20487#issuecomment-345213206).
It uses the relatively new [dynamic imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html).

Do not forget:
> In order to support the dynamic import expressions, the module setting has to be set to esnext in tsconfig.js
From [Dynamic Components Using TypeScript 2.4](https://medium.com/@yiyisun/dynamic-components-using-typescript-2-4-de109be6d135)
