### ISSUE TITLE
 Weekview day headers are offset

### ISSUE THREAD

**Issue by Hermiona** [twinssbc/Ionic2-Calendar#236]
When Locale_ID is changed, in weekview day headers are offset. how to place day headers' cells correctly like shown  in the pic below with yellow lines?
![localhost_8100_ nexus 6p 2](https://user-images.githubusercontent.com/19423390/33164093-96d74816-d05b-11e7-98b7-cb9607ce05d9.png)

**Comment by twinssbc** [comment]
@Hermiona Which locale are you using? Did you do any customization on the view? You could hover on the element to see which element width needs to be adjusted, then find an appropriate css class that attached to this element and override the style.

**Comment by Hermiona** [comment]
I use LOCALE_ID=ru (cyrillic) localization. I'm afraid that if I hardly code in css the  margin-left to be this many px then this solution isn't flexible in case of devices of  different size.
P.S. Sorry for my not very good English
