### ISSUE TITLE
pull data from json and feed eventsource

### ISSUE THREAD

**Issue by heperionjak** [twinssbc/Ionic2-Calendar#238]
Hi,

I am a beginner in coding and certainly lack of basics, but here is what i would like to do and need your help. 
I would like to pull the data in my json file to feed the eventSource array.

I define the model:

`export class EventModel {
  title: string;
  date: EventDate;
}
export class EventDate {
  day: number;
  month: number;
  year: number;
  time: string;
  finishtime: string
}
`

then the injectable:

`getData2(): Promise<EventModel> {
    return this.http.get('./assets/example_data/myfile.json')
     .toPromise()
     .then(response => response.json() as EventModel)
     .catch(this.handleError);
  }`

And finally my typescript file, which I am note sure how to code properly:

import { Component } from '@angular/core';
import { NavController, SegmentButton, LoadingController, AlertController } from 'ionic-angular';
import 'rxjs/Rx';

import { ScheduleModel } from './schedule.model';
import { ScheduleService } from './schedule.service';

import * as moment from 'moment';

@Component({
  selector: 'schedule-page',
  templateUrl: 'schedule.html'
})
export class SchedulePage {
  segment: string;
  schedule: ScheduleModel = new ScheduleModel();
  loading: any;

    eventSource = [];
    viewTitle;
    isToday: boolean;
    calendar = {
        mode: 'month',
        currentDate: new Date()
      }

    

  constructor(
    public nav: NavController,
    public scheduleService: ScheduleService,
    public loadingCtrl: LoadingController,
    public alertCtrl: AlertController,
  ) {
    this.segment = "list-game";
    this.loading = this.loadingCtrl.create();
  }

  ionViewDidLoad() {
    this.loading.present();
    this.scheduleService
      .getData()
      .then(data => {
        this.schedule.today = data.today;
        this.schedule.upcoming = data.upcoming;
        this.loading.dismiss();
      });
  }

  onSegmentChanged(segmentButton: SegmentButton) {
    // console.log('Segment changed to', segmentButton.value);
  }
  
  onSegmentSelected(segmentButton: SegmentButton) {
    // console.log('Segment selected', segmentButton.value);
  }

     loadEvents() { 
      
       this.loading.present();
       
       this.scheduleService
      .getData2()
      .then(data => {   
        
        let eventData = data;
        
        let h = moment(data.date.time, "HH:mm").hours();
        let m = moment(data.date.time, "HH:mm").minutes();
        let hf = moment(data.date.time, "HH:mm").hours();
        let mf = moment(data.date.time, "HH:mm").minutes();

        
        let startTime = new Date(Date.UTC(data.date.year, data.date.month, data.date.day,h,m,0));
        let endTime = new Date(Date.UTC(data.date.year, data.date.month, data.date.day,hf,mf,0));
        let title = new String(data.title);

        let events = this.eventSource;
        events.push({
                    title: title,
                    startTime: startTime,
                    endTime: endTime,
                    allDay: false
                });
        
        
        events.push(eventData);
        this.eventSource = [];
        this.loading.dismiss();
      });
    }

**Comment by twinssbc** [comment]
@heperionjak Suppose you bind eventSource to the calendar. You need to fill the events into eventSource variable, instead of fill the events variable and set eventSource to empty array.

```
let events = [];
    events.push({
                title: title,
                startTime: startTime,
                endTime: endTime,
                allDay: false
            });
    
    
    events.push(eventData);
    this.eventSource = events;
```
