### ISSUE TITLE
Disabling a particular day

### ISSUE THREAD

**Issue by vipindhmn87** [twinssbc/Ionic2-Calendar#239]
Hi,

I am trying to implement the following feature:-
onClick of a day in month's view, I am showing two options in an actionsheet - "Block Day" and "set Meetup"
for blocking a day, i want to disable that day. I have implemented the following code:-

HTML:-
`<calendar [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate"
    [markDisabled]="markDisabled"
    (onCurrentDateChanged)="onCurrentDateChanged($event)"
    (onEventSelected)="onEventSelected($event)"
    (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)"
    step="30">
</calendar>`
.ts file:-
`markDisabled = (date:Date) => {
        var current = new Date(date);
        current.setHours(0, 0, 0);
        return date.getTime() == current.getTime();
  };`

`openActionSheet(event){
    console.log('opening');
    let actionsheet = this.actionSheetCtrl.create({
      title:"Choose Option",
      buttons:[{
        text: 'Block Date',
        handler: () => {
          console.log("Block Date Clicked: "+ event);
          this.markDisabled(event.selectedTime);
        }
      },{
        text: 'Meet Up With',
        handler: function(){
          console.log("Meet Up With Clicked");
        }
      }]
    });
    actionsheet.present();
  }
`

But it does not disable the day. please help @twinssbc.

**Comment by twinssbc** [comment]
@vipindhmn87 The hour part of date object is 12, instead of 0. Also setHours has forth parameter to set the millisecond part.

**Comment by vipindhmn87** [comment]
@twinssbc Thank you for your reply. I made the change mentioned by you but still it does not work. I can see that markDisabled is called automatically when rendering the month view for the first time. And When I click on any day and call the markDisabled method in home.ts file, it is get called but I think it is not calling your library's method this time. Do you have any idea if this possible?

**Comment by twinssbc** [comment]
@vipindhmn87 Ah, yes, markDisabled is a callback method only used when rendering the calendar.
It's not useful for your case. I think there are two ways to solve that.
1. If you could navigate to another page, then navigate back, then you could store your disabled date and use it in the markDisabled method. Once you navigate back, the calendar will be re-rendered, so the markDisabled method will be called.
2. If you don't want to navigate to other page. You could use a customized template to implement your own disable logic.

**Comment by Titoch** [comment]
Hi,
I think the second solution: "use a customized template" is only applicable to MonthView ?  
Am I right?
This is the reason why I created the feature request #232.

**Comment by vipindhmn87** [comment]
@twinssbc First solution does not sound convincing but let me try second solution. If I face any issues while implementing the same will get in touch with you again.
Thanks

**Comment by FrancescoPaiola** [comment]
@Titoch can you share the custom template for disable date runtime in monthview? and how to use it?
