### ISSUE TITLE
Strange behavior with loading new events

### ISSUE THREAD

**Issue by joakiwpc** [twinssbc/Ionic2-Calendar#240]
Hey guys,
in my calendar, when the month changes on slide I have to reload the events list (eventSource) with new events for the new month.

The events are added correctly in eventSource, but they are only shown on the "central view" of calendar widget, not on the "lateral view".

The events are "red bullets" shown below the day number, and are made with the property monthviewDisplayEventTemplate.

Maybe if i explain the process you can stand me better:
1. The calendar is shown with the current month (**December**) and its current events.
2. I scroll to previous month (**November**), that got events too. The month is changed, but the events are not rendered, but are added to **eventSource** list.
3. If I scroll back to the **December**, before I do the server request to get the December events, the events of **November** are shown there.

I don't know if I'm missing something :/

**Comment by joakiwpc** [comment]
Ty for fast answer.

I'm sorry to say that, but that was i did (pushing directly to eventSource and assigning new array to it) 😭
```
fillCalendarEvents(days) {
let events = [];
 
    for (var i = 0; i < days.length; i++) {
        let date = new Date();
        let time = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), days[i] ));
        let id = this.getFirstEventId(days[i]);

        events.push({
            title: '',
            startTime: time,
            endTime: time,
            allDay: false,
            event_id: id
        });
        // this.eventSource.push({
        //     title: '',
        //     startTime: time,
        //     endTime: time,
        //     allDay: false,
        //     event_id: id
        // });
        // this.myCalendar.loadEvents();
    }
this.eventSource = events;
    this.myCalendar.loadEvents();
}
```

**Comment by twinssbc** [comment]
@joakiwpc Your startTime and endTime are same?

**Comment by joakiwpc** [comment]
Yes, they are. This is the issue? :/

Because i don't use the widget list.

**Comment by twinssbc** [comment]
@joakiwpc No, it shouldn't be the issue, just feeling strange. Could you provide more code to demonstrate how do you trigger fillCalendarEvents method? Your server request fetches events only happen on this month or multiple months?

**Comment by joakiwpc** [comment]
Hey sry for late response.

The server request could return events on multiple months.

This is the callback of the server request:
```
public callbackGetCalendarSummary( response ) : void {
    try {
        /// Check if there is data on server response
    if ( response["Success"] ) {
        this.json = response;

        /// Check if there are DaysWithEvent
        ///     DaysWithEvent --> integer List like [2,3,14,22] with the days with events
        if ( response["DaysWithEvent"] != null ) {
            /// Here we fill the calendar events
            this.fillCalendarEvents(response["DaysWithEvent"]);
        }

        /// Check if we can disable InfiniteScroll
        if ( response["Events"].length > 0 ) {
          this.canLoadMore = true;
        } else {
          this.canLoadMore = false;
        }
    } else {
        this.canLoadMore = false;
    }

      /// Hidde LoadingIndicator
      this.globals.hideLoadingIndicator();
    } catch(e) {
        console.error("ELOL callbackGetCalendarSummary --> "+e);
    }
}
```

**Comment by twinssbc** [comment]
@joakiwpc I can't spot any error so far. How do you trigger the callbackGetCalendarSummary method? Maybe you could try fill the eventSource with some mock events, instead of fetching events from the backend?

**Comment by joakiwpc** [comment]
I trigger it like this:

```
getCalendarSummary() {
        this.globals.showLoadingIndicator();

        let json = {
            year: this.selectedDay.getFullYear(),
            month: this.selectedDay.getMonth() + 1,
            page: this.currentPage,
            limit: this.PAGE_LIMIT
        };

        this.services.getCalendarSummary(json,
            (response) : void => {
                this.callbackGetCalendarSummary(response);
            }
        );
    }
```
Am I supposed to update the **currentDate** manually in onCurrentDateChanged?

**Comment by joakiwpc** [comment]
Hmm I think the problem is on my fillCalendarEvents, in the for i use new Date, and I think thats why all events are put on the "central calendar". So if I use **currentDate** to set the events date they will be shown correctly. I will try now :)

```
fillCalendarEvents(days) {
let events = [];
 
    for (var i = 0; i < days.length; i++) {
        let date = new Date();
        let time = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), days[i] ));
        let id = this.getFirstEventId(days[i]);

        events.push({
            title: '',
            startTime: time,
            endTime: time,
            allDay: false,
            event_id: id
        });
        // this.eventSource.push({
        //     title: '',
        //     startTime: time,
        //     endTime: time,
        //     allDay: false,
        //     event_id: id
        // });
        // this.myCalendar.loadEvents();
    }
this.eventSource = events;
    this.myCalendar.loadEvents();
}
```
