### ISSUE TITLE
100% width on events that are not full hour

### ISSUE THREAD

**Issue by aces-tm** [twinssbc/Ionic2-Calendar#241]
On dayView when I schedule more than 1 event at the same time the column is split in 2. When I schedule events on full hour it works fine, but when I schedule events, for example,  from 3:30 to 4:30 than every next event doesn't take a full width although that's the only event in that slot. Please take a look at the picture.  Is it possible those events to be in full width? Thanks

<img width="391" alt="screen shot 2017-12-01 at 09 52 20" src="https://user-images.githubusercontent.com/15965559/33490776-d0db320c-d67d-11e7-8ca8-d6de81d2035d.png">

**Comment by twinssbc** [comment]
@aces-tm I have fixed this bug in the latest version. Feel free to give a try.

**Comment by aces-tm** [comment]
@twinssbc Thanks. It's perfect. Appreciate improving this plugin
