### ISSUE TITLE
 (onTimeSelected) and  (onCurrentDateChanged) triggered  without clicking on any date

### ISSUE THREAD

**Issue by SoniaGarmar** [twinssbc/Ionic2-Calendar#242]
Hi,
First of all thanks for such a useful plugin.
I'm trying to use it in a project and I have found he following issue.

When I access the calendar form the tab menu, everything is ok. However, if I access the calendar from a button that pushes the calendar page,  (onTimeSelected) and  (onCurrentDateChanged)  are triggered automatically on loading the page, without clicking on any date.

Here is my code:
calendar.html
```

<ion-header>
  <ion-navbar>
      <ion-title>
          {{ viewTitle }}
        </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
    <calendar [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate"
    (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)"
    (onCurrentDateChanged)="onCurrentDateChanged($event)"
    step="15">
  </calendar>
</ion-content>
```

calendar.ts
```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { IVehicle, IService } from '../../models/serviceModel';
import * as moment from 'moment';
import { CalendarComponent } from "ionic2-calendar/calendar";

@IonicPage()
@Component({
  selector: 'page-calendar',
  templateUrl: 'calendar.html',
})
export class CalendarPage {
 
  eventSource = [];
  viewTitle: string;
  selectedDay = new Date();
 
  calendar = {
    mode: 'month',
    currentDate: new Date()
  };

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  
  }

 
  onViewTitleChanged(title) {
    this.viewTitle = title;
  }
 
  onTimeSelected(ev) {
    console.log('Selected time: ' + ev.selectedTime + ', hasEvents: ' +
        (ev.events !== undefined && ev.events.length !== 0) + ', disabled: ' + ev.disabled);
}
onCurrentDateChanged(event:Date) {
   console.log("change");
  }

}
```
Any help will be appreciated,
Thanks.
Sonia

**Comment by marcRDZ** [comment]
Hi,
I am facing a similar issue intermitently but I cannot isolate the conditions that cause this, onTimeSelected() triggers automatically in the first event of the eventSource array sometimes.

**Comment by joakiwpc** [comment]
I have this problem too, onTimeSelected. In my case is triggered twice and always the event clicked is the first event of eventSource.

**Comment by twinssbc** [comment]
Hi, it's expected that these two callback methods are triggered.
onTimeSelected is triggered when events are loaded or manually select a date. If you don't want to trigger onTimeSelected when events are loaded, you could set autoSelect option to false.
onCurrentDateChanged  is triggered when current date is changed, the initial date you binds to the calendar also counts.

**Comment by joakiwpc** [comment]
Thanks, that worked. I didn't check autoSelect property.

**Comment by marcRDZ** [comment]
Hi,
Thanks for the quick reply. I don't know that property, sorry. Then I guess that the random behaviour is caused if today has events or not

**Comment by SoniaGarmar** [comment]
Thanks a lot, twinssbc.
Setting the autoSelect property to false fixed the issue for onTimeSelected. I guess there is no way to prevent onCurrentDateChanged to be triggered on load, but it's ok.

**Comment by krishnaworkdi** [comment]
> Hi, it's expected that these two callback methods are triggered.
> onTimeSelected is triggered when events are loaded or manually select a date. If you don't want to trigger onTimeSelected when events are loaded, you could set autoSelect option to false.
> onCurrentDateChanged is triggered when current date is changed, the initial date you binds to the calendar also counts.
it's

**Comment by krishnaworkdi** [comment]
> Hi, it's expected that these two callback methods are triggered.
> onTimeSelected is triggered when events are loaded or manually select a date. If you don't want to trigger onTimeSelected when events are loaded, you could set autoSelect option to false.
> onCurrentDateChanged is triggered when current date is changed, the initial date you binds to the calendar also counts.

it's working
