### ISSUE TITLE
Customed color according to the event

### ISSUE THREAD

**Issue by romulus001** [twinssbc/Ionic2-Calendar#244]
Hello,
I would like to custom the background color to an event in a month view, is that possible?
Thanks

**Comment by twinssbc** [comment]
@romulus001 Yes, you could refer to View Customization section in README.

**Comment by romulus001** [comment]
Hello, I almost got what I wanted, now, each time I add an event, I would like the custom the background color of its cell and to change the contained text.
Here you have my code : [calendar.html](https://github.com/romulus001/ESS/blob/master/src/pages/Calendar/calendar.html) and [calendar.ts](https://github.com/romulus001/ESS/blob/master/src/pages/Calendar/calendar.ts)

I have [this result](https://github.com/romulus001/ESS/blob/master/src/pages/Calendar/ionic2-calendar-result.PNG) but I want to [make this](https://github.com/romulus001/ESS/blob/master/src/pages/Calendar/ionic2-calendar-result-expected.PNG).
How can I achieve such a result? Also, can you please update your readme, in your examples, you use the **template** tag but it's actually **ng-template**.
Thanks.

**Comment by twinssbc** [comment]
@romulus001 
Below is your current template.
The problem is you are looping against all events happen on that day.
Suppose you have 5 events on that day, you will end with 5 <p> elements having background-color as obj.eventColor.
```
  <ng-template #template let-view="view" let-row="row" let-col="col">
    <div  *ngFor="let obj of view.dates[row*7+col].events"  >
      <p [ngStyle]="{'background-color': obj.eventColor}">{{obj.message}}</p>
    </div> 
  </ng-template>
```

You probably want to create some css class based on whether you have events or not, or only the first event. For example,
[ngClass]="getCustomClass(view.dates[row*7+col].events)"

The reason you have empty cell on other date is because you only handle the dates having events, you need to give some static text for dates not having events.

The reason you have blue padding around red <p> element, is because each cell has css class "monthview-primary-with-event" with background set to blue, you could override the class to set background to other color.

**Comment by romulus001** [comment]
@twinssbc the code I put was from [this project](https://github.com/Bhavana1622/ionic2-calendar-event), but I dont' have the same result as showed on the page...
I also wanted to use the code from [fureszk](https://github.com/twinssbc/Ionic2-Calendar/issues/94#issuecomment-298194910) but I have default colors, strangely.
In my template, I have this 

```
<ng-template #template let-view="view" let-row="row" let-col="col">
  <div class="calendar-day {{ view.dates[row*7+col].events[0]?.color }}">
    {{view.dates[row*7+col].label}}
  </div>
</ng-template>
```
In my ts file : 
 ```
   let colors: string[] = ['primary', 'warning', 'danger', 'success'];
    let date = new Date(), y = date.getFullYear(), m = date.getMonth();
    let datetest:Date=new Date(y,m,2);
    this.eventSource.push({
      title: "test",
      startTime: datetest,
      endTime: datetest,
      allDay:true,
      color: colors[Math.floor(Math.random()*colors.length)],
      message: 'msg'
    });

    datetest=new Date(y,m,4); 
    this.eventSource.push({
      title: "test",
      startTime: datetest,
      endTime: datetest,
      allDay:true,
      color: colors[Math.floor(Math.random()*colors.length)],
      message: 'msg'
    });
   let colors: string[] = ['primary', 'warning', 'danger', 'success'];
    let date = new Date(), y = date.getFullYear(), m = date.getMonth();
    let datetest:Date=new Date(y,m,2);
    this.eventSource.push({
      title: "test",
      startTime: datetest,
      endTime: datetest,
      allDay:true,
      color: colors[Math.floor(Math.random()*colors.length)],
      message: 'msg'
    });

    datetest=new Date(y,m,4); 
    this.eventSource.push({
      title: "test",
      startTime: datetest,
      endTime: datetest,
      allDay:true,
      color: colors[Math.floor(Math.random()*colors.length)],
      message: 'msg'
    });
```

My css : 
```
page-voir-calendrier {
    .monthview-selected {
        background-color: transparent !important;
        color: black !important;
      }
    
      td.monthview-current {
        color: white;
    
        .calendar-day {
          background-color: color($colors, 'light') !important;
        }
      }
    
      .monthview-datetable {
        border: 0 !important;
    
        td, th {
          border: 0 !important;
          padding: 3px!important;
          background-color: transparent!important;
        }
      }
    
      .calendar-day {
        border-radius: 6px;
        padding: 3px 5px;

        &.primary {
            background-color: '#FF0000';
            color: white;
          }
      
          &.success {
            background-color: '#FFF000';
            color: white;
          }
      
          &.warning {
            background-color: '#FF000F';
            color: white;
          }
      
          &.danger {
            background-color: '#FF00FF';
            color: white;
          }
        }
}
```
Is the way okay to achieve this? I don't see how to use
[ngClass]="getCustomClass(view.dates[row*7+col].events)"

**Comment by twinssbc** [comment]
@romulus001 I used your code and I can see the color text appears in the class, for example,
<div class="calendar-day primary">
Is it possible you didn't apply the css rule correctly?

Regarding the getCustomClass, for example, you could have your template as
```
    <div [ngClass]="getCustomClass(view.dates[row*7+col].events)">
```
Then in your compontent ts file, you just add getCustomClass
```
  getCustomClass(events) {
    return 'test';
  }
```

**Comment by kevinpallado** [comment]
@romulus001 any update of your work? @twinssbc  I`m also doing this the same but I get this kind of [result](https://github.com/romulus001/ESS/blob/master/src/pages/Calendar/ionic2-calendar-result.PNG) seems that the other day that has no event will disappear. Even after following [this](https://github.com/twinssbc/Ionic2-Calendar/issues/94#issuecomment-298194910) method still getting the same [result](https://github.com/romulus001/ESS/blob/master/src/pages/Calendar/ionic2-calendar-result.PNG)

**Comment by romulus001** [comment]
@kevinpallado I could solve my problem, the matter comes from the node_modules\ionic2-calendar\calendar.js file, in which something was missing but I can't remember what it might be, the updated files I used can be found via [this link](https://github.com/romulus001/Shared-files/blob/master/calendar.js)

**Comment by twinssbc** [comment]
@kevinpallado Sorry, I can't open your link. What do you mean "the other day that has no event will **disappear**"?

**Comment by romulus001** [comment]
@twinssbc he put a link to an image I uploaded on my account, I put as private my repository which contains the image, I uploaded it on my dropbox, it's [this image](https://www.dropbox.com/s/l0qllmtvwvedgbu/ionic2-calendar-result.PNG?dl=0) he is talking about.

**Comment by twinssbc** [comment]
@romulus001 Thanks. Looks like no events get displayed? @kevinpallado Do you fill the eventSource correctly?

**Comment by kevinpallado** [comment]
@twinssbc yep i got it correctly. How can i get the event color in the calendar , from this [image](https://imgur.com/a/eFUyDFa) I want to remove the color the background color of the box?

**Comment by twinssbc** [comment]
@kevinpallado Add below styles in global.scss file. They will set the background  to transparent.

```
.monthview-current {
  background-color: transparent !important;
}

.monthview-primary-with-event {
  background-color: transparent !important;
}
```

**Comment by kevinpallado** [comment]
@twinssbc  is it possible to put markers on the day column? like put something number in the top right of the day on how many events occur in that day?

**Comment by twinssbc** [comment]
@kevinpallado Take a look at **weekviewHeaderTemplate** option. It allows you to provide the custom view of the day header.

**Comment by svknvs** [comment]
How to reset the date range if another event changed 
I changed as below in 
onSelectionChanged(){
this.dateTo = this.dateFrom;
}
but the date range color is not cleared fully
but shown in disabled / dim color

**Comment by twinssbc** [comment]
@svknvs I don't quite understand your question. The onSelectionChanged, dateTo and dateFrom seems are all from your own code, how is it related to the calendar?

**Comment by Yossri21** [comment]
@twinssbc  I want to change the color of event 
I did like that in the html 
`<ng-template #template let-view="view" let-row="row" let-col="col">
  <div *ngIf="view.dates[row*7+col].events == ''">{{view.dates[row*7+col].label}}</div>
  <div *ngFor="let obj of view.dates[row*7+col].events">
    <div [ngStyle]="{'background-color': obj.eventColor    } ">{{view.dates[row*7+col].label}}</div>
  </div>
</ng-template>`
and `<calendar 
[monthviewDisplayEventTemplate]="template" ....`
the color is change but not the full background 
![image](https://user-images.githubusercontent.com/26494296/92767630-35ff0600-f38f-11ea-9247-c81af061771f.png)
I want to be for all the case and remove the blue color
I check the css 
![image](https://user-images.githubusercontent.com/26494296/92768128-a3129b80-f38f-11ea-8b0b-aa2faa53788f.png)
please what's the solution

**Comment by Yossri21** [comment]
![image](https://user-images.githubusercontent.com/26494296/92768310-d0f7e000-f38f-11ea-8724-e4df08e0e52b.png)
