### ISSUE TITLE
load event from api

### ISSUE THREAD

**Issue by abdulkadhir** [twinssbc/Ionic2-Calendar#247]
I want to load an event from API which is in JSON format.
my JSON data is 
`
[
  
  {
        "event_title": "Holiday",
        "event_description": "Holiday",
        "event_type": "Holiday",
        "start_time": "2017-12-15",
        "end_time": "2017-12-15"
    },
    {
        "event_title": "Holiday",
        "event_description": "Holiday",
        "event_type": "Holiday",
        "start_time": "2017-12-12",
        "end_time": "2017-12-12"
    }
]`

I'm new to ionic, I'm stuck in this can you help me with this?
Thanks in advance

**Comment by twinssbc** [comment]
@abdulkadhir You need to convert your json format data to the format the calendar can recognize.
Take a look at the EventSource section in README about the mandatory fields in the event object.
You could also refer to the code in demo page.

**Comment by abdulkadhir** [comment]
thanks, @twinssbc  I'll check and reply

**Comment by abdulkadhir** [comment]
![image](https://user-images.githubusercontent.com/32663252/34091349-227c8756-e3e3-11e7-810e-e53595a7e2cb.png)

**Comment by twinssbc** [comment]
@abdulkadhir I don't quite understand your logic. Where do you call your loadEvents method?

**Comment by twinssbc** [comment]
@abdulkadhir And what error do you get?

**Comment by abdulkadhir** [comment]
this my ts file

`import { Component, ViewChild } from '@angular/core';
import { NavController } from 'ionic-angular';
import { NgCalendarModule } from 'ionic2-calendar';
import { CalendarComponent } from "ionic2-calendar/calendar";
import {CalenProvider} from '../../providers/calen/calen';

import 'rxjs/add/operator/map';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
  providers:[CalenProvider]
})
export class HomePage {
  @ViewChild(CalendarComponent) myCalendar:CalendarComponent;
  eventSource;
  viewTitle;
  startTime;
  endTime;
  isToday: boolean;
  calendar = {
      mode: 'month',
      currentDate: new Date()
  };
  callist:any=[];

  constructor(public navCtrl: NavController,private calenprovider: CalenProvider) {

    this.getCalData();
  }

  getCalData(){
    
    this.calenprovider.getCalData().subscribe(data =>this.callist=data);
      }

      loadEvents: function(): {
          eventSource=this.callist
        this.eventSource.push({
            title: 'test',
            startTime: this.startTime,
            endTime: this.endTime,
            allDay: false
        });
        this.myCalendar.loadEvents();
    }
onViewTitleChanged(title) {
    this.viewTitle = title;
}
onEventSelected(event) {
    console.log('Event selected:' + event.startTime + '-' + event.endTime + ',' + event.title);
}
changeMode(mode) {
    this.calendar.mode = mode;
}
today() {
    this.calendar.currentDate = new Date();
}
onTimeSelected(ev) {
    console.log('Selected time: ' + ev.selectedTime + ', hasEvents: ' +
        (ev.events !== undefined && ev.events.length !== 0) + ', disabled: ' + ev.disabled);
}
onCurrentDateChanged(event:Date) {
    var today = new Date();
    today.setHours(0, 0, 0, 0);
    event.setHours(0, 0, 0, 0);
    this.isToday = today.getTime() === event.getTime();
}
// createRandomEvents() {
//     var events = this.callist;
//     for (var i = 0; i < 50; i += 1) {
//         var date = new Date();
//         var eventType = Math.floor(Math.random() * 2);
//         var startDay = Math.floor(Math.random() * 90) - 45;
//         var endDay = Math.floor(Math.random() * 2) + startDay;
//         var startTime;
//         var endTime;
//         if (eventType === 0) {
//             startTime = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + startDay));
//             if (endDay === startDay) {
//                 endDay += 1;
//             }
//             endTime = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + endDay));
//             events.push({
//                 title: 'All Day - ' + i,
//                 startTime: startTime,
//                 endTime: endTime,
//                 allDay: true
//             });
//         } else {
//             var startMinute = Math.floor(Math.random() * 24 * 60);
//             var endMinute = Math.floor(Math.random() * 180) + startMinute;
//             startTime = new Date(date.getFullYear(), date.getMonth(), date.getDate() + startDay, 0, date.getMinutes() + startMinute);
//             endTime = new Date(date.getFullYear(), date.getMonth(), date.getDate() + endDay, 0, date.getMinutes() + endMinute);
//             events.push({
//                 title: 'Event - ' + i,
//                 startTime: startTime,
//                 endTime: endTime,
//                 allDay: false
//             });
//         }
//     }
//     return events;
// }
onRangeChanged(ev) {
    console.log('range changed: startTime: ' + ev.startTime + ', endTime: ' + ev.endTime);
}
markDisabled = (date:Date) => {
    var current = new Date();
    current.setHours(0, 0, 0);
    return date < current;
};

}
`

**Comment by abdulkadhir** [comment]
html file:
`<ion-header>
  <ion-navbar color="ddd">
      <ion-title>{{viewTitle}}</ion-title>
      <ion-buttons end>
          <button ion-button color= "black" [disabled]="isToday" (click)="today()">Today</button>
          <button ion-button color="black" (click)="changeMode('month')">Month</button>
          <button ion-button color="black"(click)="changeMode('week')">Week</button>
          <button ion-button color="black" (click)="changeMode('day')">Day</button>
          <button ion-button color="black"(click)="loadEvents()">Load Events</button>
      </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content class=has-header>
 <div>
  <calendar  [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30">
  </calendar>
</div> 
</ion-content>`

**Comment by abdulkadhir** [comment]
provider:

`import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import {Http, RequestOptions, Response, HttpModule} from '@angular/http';
import { HttpClientModule } from '@angular/common/http';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/do';

/*
  Generated class for the CalenProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class CalenProvider {

  private url: string = "https://dev-api.ucdemos.biz/v1/student-dashboard/view-events";

  constructor(public http: Http) {
    console.log('Hello CalenProvider Provider');
  }



  getCalData(){
    return this.http.get(this.url)
    .do(this.logResponse)
    .map(this.extractData)
    .catch(this.catchError)
  }

  private catchError(error: Response |any){
    console.log(error);
    return Observable.throw(error.json().error || "server Error.");

  }

  private logResponse(res : Response){
    console.log(res);

  }

  private extractData(res : Response){
    return res.json();
  }

}
`

**Comment by twinssbc** [comment]
@abdulkadhir Your logic is not that clear. I suggest you clean your code a bit and add the logic step by step.
First, make sure when you click a button, you can fill some random events to eventSource.
Second, implement a method to fetch events from backend and fill the retrieved events to eventSrouce.

**Comment by abdulkadhir** [comment]
@twinssbc thanks 
hi I try it and it works well but the problem is when I pass the date like this the event is shown in january 28 2018 instead of december 28 2017 
`
startTime: new Date(2017,12,28,11,0,0,0),

  endTime: new Date(2017,12,28,11,30,0,0),`

**Comment by twinssbc** [comment]
@abdulkadhir It's because the number starts with 0, not 1.

**Comment by abdulkadhir** [comment]
thanks, @twinssbc .
Then how to convert my json data to that

**Comment by abdulkadhir** [comment]
@twinssbc any possible ways to alter the start number

**Comment by twinssbc** [comment]
That is the JavaScript API.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
You need to workaround it by yourself.

Or if your original date in the JSON data is a valid string, you could try parse method.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

**Comment by abdulkadhir** [comment]
thanks, @twinssbc it's working.
now I want to disable some selected days in a month.
can explain how to do that.

**Comment by twinssbc** [comment]
@abdulkadhir Take a look at markDisabled option in README.
This method accepts a date parameter, and you can add your logic to decide return true (disabled) or false (not disabled).

```
markDisabled = (date: Date) => {
            var current = new Date();
            return date < current;
        };
```

**Comment by abdulkadhir** [comment]
@twinssbc thanks for the reply.
I tried it but it won't work.
I want to disable Sundays.
Can you send some sample code snippets?

**Comment by abdulkadhir** [comment]
How can i load the event with a only date.
my json is `

[
{
            "date": "2017-09-05",
            "reason": ""
        },
        {
            "date": "2017-09-04",
            "reason": ""
        },
        {
            "date": "2017-09-01",
            "reason": ""
        },
]`

**Comment by abdulkadhir** [comment]
How can I load an event with the only date there is no start time and end time.
my json data  is  `

[
{
            "date": "2017-09-05",
            "reason": ""
        },
        {
            "date": "2017-09-04",
            "reason": ""
        },
        {
            "date": "2017-09-01",
            "reason": ""
        },
]`

**Comment by twinssbc** [comment]
@abdulkadhir Does that mean they are full day event? Then you need to populate the eventSource array with full day event format. The format has been explained in the README.

**Comment by abdulkadhir** [comment]
@twinssbc is it possible to disable dates that are on the backend.

**Comment by twinssbc** [comment]
@abdulkadhir You need to fetch the disabled dates from the backend and check them in the markDisabled function.

**Comment by abdulkadhir** [comment]
@twinssbc I use the below method to get the backend dates
`getWeekendData(){

     this.calenprovider.getWeekendData().subscribe((data)=>{
            this. week_end = data[0];
               if(this.week_end) {
                     this.week_end_leaves = Object.values(this.week_end).map((item)=>new Date(item));
                     console.log(this.week_end_leaves);              
               }
           });
}

//this to disable dates.
 markDisabled = (date: Date) => {
      return this.weekend;
 };`

but it is not working.

my JSON data is

`
[

    {
        "5": "2018-01-06",
        "6": "2018-01-07",
        "12": "2018-01-13",
        "13": "2018-01-14",
        "19": "2018-01-20",
        "20": "2018-01-21",
        "26": "2018-01-27",
        "27": "2018-01-28",
        "33": "2018-02-03"
   }
]`

**Comment by twinssbc** [comment]
@abdulkadhir This markDisabled accepts a Date object and returns true of false.
So you need to check if the passed date is in your disabled date list. If it is, then need to return true, otherwise return false.

**Comment by abdulkadhir** [comment]
thanks, @twinssbc I tried in many ways but I didn't the desired result.I convert my json format also 
my json format is:
`

[
    "2018-01-06",
    "2018-01-07",
    "2018-01-13",
    "2018-01-14",
    "2018-01-20",
    "2018-01-21",
    "2018-01-27",
    "2018-01-28"
]` when i tried to convert the above array to date object  it throws runtime error.
can you send me some sample code for this
thanks in advance

**Comment by abdulkadhir** [comment]
hi, @twinssbc I converted the string to a date object, but I did not know how to disable the set of dates.I don't know how to pass date object in the markDisabled method.I'm stuck in this send snippets to solve this. thank you

**Comment by twinssbc** [comment]
@abdulkadhir markDisabled is a callback method, it's called by the calendar during the view initialization. And it is called on each date in the current month view.
So you don't actively call markDisabled method and pass a date object.
Suppose you have already covert your json to an array of date object.
Then your markDisabled method should look like below:

```
markDisabled = (date: Date) => {
     let checkDates = [d1, d2, d3, d4];
     for(let d of checkDates) {
          if(d.getTime() === date.getTime()) {
              return true;
          }
     }
    return false;   
};
```

**Comment by abdulkadhir** [comment]
Thanks, @twinssbc I tried but the problem here is when I use this condition if(d.getTime() === date.getTime()) d.getTime gives the date with 12.00 time where date.getTime gives the current date with current time.the time is not equal so I can't disable the days.
my converted array of date object is
[ 0:Sat Jan 06 2018 05:30:00 GMT+0530 (India Standard Time) {}
1:Sun Jan 07 2018 05:30:00 GMT+0530 (India Standard Time) {}
2:Sat Jan 13 2018 05:30:00 GMT+0530 (India Standard Time) {}
3:Sun Jan 14 2018 05:30:00 GMT+0530 (India Standard Time) {}
4:Sat Jan 20 2018 05:30:00 GMT+0530 (India Standard Time) {}
5:Sun Jan 21 2018 05:30:00 GMT+0530 (India Standard Time) {}
6:Sat Jan 27 2018 05:30:00 GMT+0530 (India Standard Time) {}
7:Sun Jan 28 2018 05:30:00 GMT+0530 (India Standard Time) {}
8:Sat Feb 03 2018 05:30:00 GMT+0530 (India Standard Time) {} ]

how I disable days.
Thanks.

**Comment by twinssbc** [comment]
@abdulkadhir You could set your time to 12:00 or only compare the date part.
Take a look at the official document to learn how to use Date object.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by abdulkadhir** [comment]
hi, @twinssbc I set time to 12.00 by using the setHours method, I tried setTime method also but it won't works.how I set time to 12.00. thanks

**Comment by twinssbc** [comment]
setHours(12, 0, 0, 0)

**Comment by abdulkadhir** [comment]
thanks @twinssbc it works,
It is possible to sync calendar to device calendar

**Comment by twinssbc** [comment]
@abdulkadhir I support you are asking "Is it possible to sync calendar to device calendar"? You need to fetch the calendar information from the device by yourself and fill it to the eventSource array.

**Comment by twinssbc** [comment]
@abdulkadhir The eventSource array is filled by yourself. I think you should be able to know the current month events? You just need to put a list below the calendar and bind it to another array, and each time the month is changed, you change the elements in that array.

**Comment by abdulkadhir** [comment]
hi @twinssbc  the events are show in month view but not in week view or day view
my code is  

```
<ng-template #template let-displayEvent="displayEvent" >
            <div  *ngFor="let item of eventSource" class="calendar-event-inner">{{tem.title}}</div>
    </ng-template>

 [weekviewAllDayEventTemplate]="template"
```

i tried in all ways but it wont works

**Comment by twinssbc** [comment]
@abdulkadhir Your template is not correct.
Below is the default template weekview is using, it accepts a single event.
Take a look at the View Customization Option in README.
```
<ng-template #template let-displayEvent="displayEvent">
            <div class="calendar-event-inner">{{displayEvent.event.title}}</div>
        </ng-template>

        <calendar ... [weekviewAllDayEventTemplate]="template"></calendar>
```

**Comment by twinssbc** [comment]
@abdulkadhir You want to select the whole day? weekview only triggers eventSelected and timeSelected callback, if you click on a particular time slot.
weekviewAllDayEventTemplate applies to the individual all day event, you could change background color or add some text based on the property of that event.
weekviewNormalEventTemplate applies to the individual normal event, you could change background color or add some text based on the property of that event.
weekviewAllDayEventSectionTemplate applies to the all day event section on a particular day, if you want to change the layout of these events, you could use it. For example, currently the events are stacked vertically with 25px height, you could use this template to change the height.
weekviewNormalEventSectionTemplate  applies to the normal event section on a particular time slot. A typical use case is if you want to add some background for all weekend or holiday time slot. You could use this.

**Comment by abdulkadhir** [comment]
thanks @twinssbc i solved it.
I use calendar in two places in my project. In one module i want to hide the no events label that is placed under the calendar can you help me on this.

**Comment by abdulkadhir** [comment]
Hi @twinssbc in my project the markDisabled function is not render when i open the calendar, when i go to next month and comeback the disabled function is working.
Is any option to render the markDisabled function when the calendar starting

**Comment by twinssbc** [comment]
@abdulkadhir The markDisabled should be triggered when the calendar starts. Could you provide the code how do you use markDisabled? Could you add a break point to check if that method is triggered or not during start?
Regarding the second question, could you also provide the code how do you use the customize template? What do you mean not working? Is the event actually get displayed but no background color?

**Comment by abdulkadhir** [comment]
hi @twinssbc 
my markDisabled code is 
`
       markDisabled = (date: Date) => {
            console.log("test");
             let checkDates = this.wk;
            for (let d of checkDates) {
                     if (d.getTime() === date.getTime()) {
                             return true;
                    }
    
            }
             return false;
    };
`
this. wk is an array of date to be disabled that i get from my back end.
whenever i open the calendar "test" is printed  first in console after i navigate to another month and come back to current month the date is disabled.

**Comment by abdulkadhir** [comment]
Event is displayed but i want to show different color for event type

my code is  

<ng-template #template let-view="view" let-row="row" let-col="col">
            <div *ngIf("event.event_type==birthday")else birthday></div>
  </ng-template>
<template #birthday  let-view="view" let-row="row" let-col="col">   
      <div style="background-color:red"></div>
</template>

**Comment by twinssbc** [comment]
@abdulkadhir Could you also add console.log('disabled') before 

> return true;
See if that is actually printed out when you open the calendar?

**Comment by twinssbc** [comment]
@abdulkadhir Your template doesn't contain any logic to display background color. You could use ngClass to generate custom css class based on the event.event_type.

<ng-template #template let-view="view" let-row="row" let-col="col">
<div *ngIf("event.event_type==birthday")else birthday>

<template #birthday let-view="view" let-row="row" let-col="col">

**Comment by abdulkadhir** [comment]
thanks @twinssbc i checked with console.log('disabled') before

`return true`

disabled is not printed in console

**Comment by abdulkadhir** [comment]
@twinssbc  could you provide sample code snippets for ngClass to generate custom css class

**Comment by twinssbc** [comment]
@abdulkadhir If console.log("test"); is executed, but console.log('disabled') is not, this means checkDates is empty when you just open the calendar. Is it possible this.wk is updated at a later time?

**Comment by twinssbc** [comment]
You could define the template as below. Notice this getCustomClass, you need to implement it in your component ts code. It accepts the event array on that day, so you just need to return different css class based on the property of events.

```
        <ng-template #template let-view="view" let-row="row" let-col="col">
            <div [ngClass]="getCustomClass(view.dates[row*7+col].events])"{{view.dates[row*7+col].label}}</div>
        </ng-template>

        <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>
```

**Comment by abdulkadhir** [comment]
thank @twinssbc  when run tour code it shows 
 **Failed to execute 'setAttribute' on 'Element': '{{view.dates[row*7+col].label}}' is not a valid attribute name.** error

**Comment by twinssbc** [comment]
Sorry, there is a typo.
```
<div [ngClass]="getCustomClass(view.dates[row*7+col].events])">{{view.dates[row*7+col].label}}</div>
```

**Comment by abdulkadhir** [comment]
thanks @twinssbc 
below is my custom class method in ts file

`getCustomClass(eventSource){
if(event_type=='holiday'){
return red;
elseif(event_type=='party'){
return green;
}else
{return blue;}
}
`

**Comment by AnkitS221** [comment]
Hey twinssbc
In the onTimeSelected event.....is it possible to not call the event on page load of calendar

**Comment by twinssbc** [comment]
@AnkitS221 Yes, you could set autoSelect to false. Or you could use some internal flag to ignore the first time onTimeSelected is triggered

**Comment by AnkitS221** [comment]
![cal](https://user-images.githubusercontent.com/37686348/58796549-369cde80-861b-11e9-87f9-81b148700204.PNG)

Hey Twinssbc.....above screen is rendered even after binding the eventSource array with an array received from API only when the first time the page is loaded
Next page load renders events properly....Help needed urgent
Thank YOU

**Comment by twinssbc** [comment]
@AnkitS221 May I know how do you fill eventSource array? If you just use push to add individual elements, you need to call loadEvents explicitly.

You could get some idea from below note in README:

> Note The calendar only watches for the eventSource reference for performance consideration. That means only you manually reassign the eventSource value, the calendar gets notified, and this is usually fit to the scenario when the range is changed, you load a new data set from the backend. In case you want to manually insert/remove/update the element in the eventSource array, you can call instance method ‘loadEvents’ event to notify the calendar manually.

**Comment by tu81t** [comment]
> I want to load an event from API which is in JSON format.
> my JSON data is
> `
> [
> 
> {
> "event_title": "Holiday",
> "event_description": "Holiday",
> "event_type": "Holiday",
> "start_time": "2017-12-15",
> "end_time": "2017-12-15"
> },
> {
> "event_title": "Holiday",
> "event_description": "Holiday",
> "event_type": "Holiday",
> "start_time": "2017-12-12",
> "end_time": "2017-12-12"
> }
> ]`
> 
> I'm new to ionic, I'm stuck in this can you help me with this?
> Thanks in advance




> @twinssbc thanks
> hi I try it and it works well but the problem is when I pass the date like this the event is shown in january 28 2018 instead of december 28 2017
> `
> startTime: new Date(2017,12,28,11,0,0,0),
> 
> endTime: new Date(2017,12,28,11,30,0,0),`

how do you solved buecause

> @twinssbc thanks
> hi I try it and it works well but the problem is when I pass the date like this the event is shown in january 28 2018 instead of december 28 2017
> `
> startTime: new Date(2017,12,28,11,0,0,0),
> 
> endTime: new Date(2017,12,28,11,30,0,0),`

how did you solve becuase seems error like typescpript . Can you post solved form please

**Comment by tu81t** [comment]
how did you solve becuase seems error like typescpript . Can you post solved form please

**Comment by tu81t** [comment]
@abdulkadhir  please help me how did you solve your error. My json api  is similar to your api. Can you send here your  .ts file because ı get the error still.
