### ISSUE TITLE
"let-" is only supported on ng-template elements.

### ISSUE THREAD

**Issue by gdesplin** [twinssbc/Ionic2-Calendar#248]
Using templates for dayView etc. with angular 5 breaks on the 'let-displayEvent' part, with the error saying "let-" is only supported on ng-template elements.

For example my code
```
<template #colors let-displayEvent="displayEvent">
        <div class="calendar-event-inner {{displayEvent.event.goalLink}}">{{displayEvent.event.title}}
        </div>
</template>
```

I thought version 0.4.0 added support for angular 5.
What can I do to fix this or do I need to downgrade angular?

**Comment by twinssbc** [comment]
@gdesplin You just need to replace template with ng-template.

**Comment by gdesplin** [comment]
Thanks that solved it!
