### ISSUE TITLE
can I set scroll only the event detail template?

### ISSUE THREAD

**Issue by NattapolPraew** [twinssbc/Ionic2-Calendar#249]
In month mode, Can I set calendar to fix position and scroll only event detail view?

**Comment by NattapolPraew** [comment]
right now, I work around with setting height for the eventDetailTemplate with `Page.height - 262(default calendar's height)` and use ion-scroll in the eventDetailTemplate. Does anyone else have better idea?

**Comment by twinssbc** [comment]
@NattapolPraew Yes, that's a classical layout problem. Basically you have two divs, you want the second div to occupy the remaining height of the parent div.

The modern way is to use flex attribute.
https://stackoverflow.com/questions/42304725/two-divs-one-fixed-height-the-other-to-fill-the-remaining-space
https://stackoverflow.com/questions/28503305/how-to-create-a-vertical-flexbox-with-one-fixed-height-top-div-and-one-remainin

If you take a look at the element tree.
You will notice there's a div containing two child elements, ion-slides and ion-list.
ion-slides is the table part, and ion-list is the event detail part.
So you set below style to the parent div.
```
height: 100%;
display: flex;
flex-direction: column;
overflow: hidden;
```
Set height:auto to the ion-slides element (The default height style of ion-slides is 100%)
Finally set below style to the ion-list element.
```
flex-grow: 1;
overflow-y: scroll;
```

**Comment by NattapolPraew** [comment]
It's worked!. but do I have a way to add this style without hard fix in the library?

**Comment by twinssbc** [comment]
@NattapolPraew Yes, you don't need to modify the library. Just add the styles in a separate css file.

**Comment by Monuvv** [comment]
> @NattapolPraew Yes, that's a classical layout problem. Basically you have two divs, you want the second div to occupy the remaining height of the parent div.
> 
> The modern way is to use flex attribute. https://stackoverflow.com/questions/42304725/two-divs-one-fixed-height-the-other-to-fill-the-remaining-space https://stackoverflow.com/questions/28503305/how-to-create-a-vertical-flexbox-with-one-fixed-height-top-div-and-one-remainin
> 
> If you take a look at the element tree. You will notice there's a div containing two child elements, ion-slides and ion-list. ion-slides is the table part, and ion-list is the event detail part. So you set below style to the parent div.
> 
> ```
> height: 100%;
> display: flex;
> flex-direction: column;
> overflow: hidden;
> ```
> 
> Set height:auto to the ion-slides element (The default height style of ion-slides is 100%) Finally set below style to the ion-list element.
> 
> ```
> flex-grow: 1;
> overflow-y: scroll;
> ```

hi..what is the id/class of parent div here ?
