### ISSUE TITLE
startingDayMonth is ignored when compiling on android.

### ISSUE THREAD

**Issue by dlaynes** [twinssbc/Ionic2-Calendar#25]
This option runs as it should on the browser, but it seems the default value is used when running inside an emulator/(smartphone?).
Thanks for your help.

**Comment by twinssbc** [comment]
@dlaynes I tested it's working in android, may I know how do you specify startingDayMonth in your view?

**Comment by dlaynes** [comment]
The problem was fixed indicating the values as Input() parameters.
[startingDayMonth]="1" [startingDayWeek]="1"
