### ISSUE TITLE
 Metadata version mismatch for module [...] found version 4, expected 3

### ISSUE THREAD

**Issue by TheKalin** [twinssbc/Ionic2-Calendar#251]
Hello, during production build (ionic build --prod) I'm getting the metadata version mismatch error.
It looks like it caused by ionic2-calendar module. 

**Full error available below:**
`Error: Metadata version mismatch for module ~/myProject/node_modules/ionic2-calendar/calendar.module.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (~/myProject/node_modules/@angular/compiler/bundles/compiler.umd.js:24474:34)
    at StaticSymbolResolver._createSymbolsOf (~/myProject/node_modules/@angular/compiler/bundles/compiler.umd.js:24260:46)
    at StaticSymbolResolver.getSymbolsOf (~/myProject/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:14)
    at ~/myProject/node_modules/@angular/compiler/bundles/compiler.umd.js:23023:30
    at Array.forEach (native)
    at extractProgramSymbols (~/myProject/node_modules/@angular/compiler/bundles/compiler.umd.js:23022:79)
    at AotCompiler.compileAll (~/myProject/node_modules/@angular/compiler/bundles/compiler.umd.js:22720:47)
    at CodeGenerator.codegen (~/myProject/node_modules/@angular/compiler-cli/src/codegen.js:30:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (~/myProject/node_modules/@angular/compiler-cli/src/ngtools_api.js:61:30)
    at Object.doCodegen (~/myProject/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:51)`

**Package.json**
  `  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/firebase": "^4.2.1",
    "@ionic-native/globalization": "^4.1.0",
    "@ionic-native/network": "^4.2.0",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "@ngx-translate/core": "^7.1.0",
    "@ngx-translate/http-loader": "^0.1.0",
    "cordova-android": "^6.2.3",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-crypt-file": "^1.3.3",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-firebase": "^0.1.22",
    "cordova-plugin-globalization": "^1.0.7",
    "cordova-plugin-network-information": "^1.3.3",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "intl": "^1.2.5",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-calendar": "^0.4.2",
    "ionicons": "3.0.0",
    "moment": "^2.18.1",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "typings": "^2.1.1",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.0.2",
    "ionic": "3.9.2",
    "typescript": "2.3.4"
  },`
**Ionic info** 

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

**Comment by twinssbc** [comment]
@TheKalin You are using Ionic 3.9.2, it depends on Angular 5.0. You need to upgrade your Angular dependencies.

**Comment by TheKalin** [comment]
@twinssbc Oh silly me, thanks for the help.

**Comment by twinssbc** [comment]
@TheKalin To be accurate, ionic-angular 3.9.2 relies on Angular 4.4.6.
https://github.com/ionic-team/ionic/blob/master/package.json
So you don't have to upgrade to Angular 5.0. But if you want to use the calendar 0.4.x version, then it depends on both ionic-angular 3.9.2 and Angular 5.0.

**Comment by TheKalin** [comment]
@twinssbc Thanks for info. I decided to update everything in my project before initial release. Angluar 5 and the changes in http handling  (HttpClient & HttpClientModule) are major, therefore i need some tine for code refactoring.
