### ISSUE TITLE
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template' 

### ISSUE THREAD

**Issue by its-Aman** [twinssbc/Ionic2-Calendar#252]
Please fix it for Angular v5+. As `ngOutletContext` is replaced by `ngTemplateOutletContext`  
See [here](https://github.com/angular/angular/blob/master/CHANGELOG.md#deprecated-code) for deprecate code list.

I just migrate my project from `ionic-angular` version `3.5.2` to `3.9.0` and all the `@angular/*` versions to `5.0.0` In my node module package `dayview.js`, `weekview.js` and `monthview.js` have `ngOutletContext` property bind to the respective properties. This was giving me the error `Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'`. Changing `ngOutletContext` to `ngTemplateOutletContext` solved my problem.

**Comment by its-Aman** [comment]
also when build apk for android with `ionic cordova build android --prod --release --aot` gives error of missing module related to ngFactory

**Comment by twinssbc** [comment]
@its-Aman Which calendar version are you using? 0.4.x version supports ionic-angular 3.9.2 and Angular 5.0.

**Comment by its-Aman** [comment]
@twinssbc I'm using version 0.4.2
Running command ./node_modules/.bin/ngc giving me details of error. After looking in the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#deprecated-code), I changed the code accordingly and all code complile successfully.

**Comment by cemceliks** [comment]
I only installed the ionic2-calendar today and seem to have an older version. package.json entry showing   "ionic2-calendar": "^0.3.13-weekdayview-tpls".
Done the updates as its-Aman referred on the weekview.js etc. Still the same message. Would be nice to have component. Help please.

**Comment by twinssbc** [comment]
@cemceliks So I'm maintaining 3 versions of ionic2-calendar. 
You could choose the proper version based on your project dependencies.

version 0.1.x depends on Ionic 2.0.0-rc.1 ~ Ionic 2.0.0-rc.4
version 0.2.x depends on Ionic 2.0.0-rc.5 (rc.5 has breaking change on the slide API) and 2.0.0 final version onwards. version 0.2.9+ depends on Ionic 2.3.0 version onwards.
version 0.3.x depends on Ionic 3.1.1 version onwards.
version 0.4.x depends on Ionic 3.9.2 version onwards and supports Angular 5.

**Comment by cemceliks** [comment]
Thank you for clarifying. Great component!
