### ISSUE TITLE
loadEvents function not working in my app.

### ISSUE THREAD

**Issue by cosmokwh** [twinssbc/Ionic2-Calendar#253]
Hi, I'm developing a hybrid app based on ionic.
It does not display event data imported from firebase on the calendar.
When I first developed it, the event information I saved was displayed on the calendar.
When I use "loadEvents()", sometimes it shows a not instance error.

Is there a problem?
Please answer. thanks!

**My Ionic Info below:**

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    npm  : 3.10.10
    OS   : Windows 10

**In my schedule.ts**
`...
export class SchedulePage {
  eventSource;
  calendar = {
    mode: 'month',
    dayheader: 'E',
    queryMode: 'remote',
    eventlabel: 'no events.',
    currentDate: new Date()
  };
  @ViewChild(CalendarComponent) myCalendar:CalendarComponent;
  constructor(public navCtrl: NavController, public app: App, public dateService: DateService, 
   public usersv: UserService, private modalCtrl: ModalController, private alertCtrl: AlertController,
   public util: UtilProvider, navParams: NavParams) {  	
    this.eventSource = [];
    this.dateService.getDates().subscribe ( snapshot => {
        let dateDatas = [];
        snapshot.forEach( dates => {
          this.eventSource.push({
            title: dates.title,
            startTime: new Date(dates.startTime),
            endTime: new Date(dates.endTime),
            allDay: false
          });
          this.myCalendar.loadEvents();
          let d =  new Date().toString();
          this.setCheckdate(d);
        });
    });
  }

setCheckdate(dateParam){
    let d =  new Date(dateParam);
    let checkDate = this.leadingZeros(d.getFullYear(), 4) + '-' + this.leadingZeros(d.getMonth() + 1, 2) + '-' + this.leadingZeros(d.getDate(), 2);
    this.dateUser = [];
    this.dateService.getPartnerInfo(this.currentUserId, checkDate).subscribe( (dates) => {
        let dateUsers = [];
        dates.forEach( date => {
           let s = new Date(date.startTime);
           let setStartTime = this.leadingZeros(s.getHours(), 2) + this.leadingZeros(s.getMinutes(), 2);
           this.usersv.getSelectedUser(date.partner).subscribe( user => {
              let userData = JSON.parse( JSON.stringify(user) );
              let setDataUser = {
                $key : date.partner,
                profile1 : userData.profile1,
                name : userData.name,
                age : userData.age,
                userAffiliation : userData.userAffiliation,
                title : date.title,
                addr : date.addr,
                startTime : setStartTime,
                checkDate : checkDate
              }
              dateUsers.push(setDataUser);
          });
        });
        this.dateUser = dateUsers;
    });
  }
...
`

**In my schedule.html**
...
`
<template #template let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
        <ion-list *ngIf="dateUser.length < 1" class="list-full-border">
          <ion-item text-wrap>
            <h3 class="noEvents" style="text-align: center;">no event</h3>
          </ion-item>
        </ion-list>
        <ion-list class="list-full-border" style="margin:0px;" *ngFor="let user of dateUser let i = index">
          <ion-item text-wrap>
            <ion-avatar item-left>
              <img class="profile-picture" src="{{ user.profile1 }}" alt="" (click)="userDetail(user.$key)"/>
            </ion-avatar>
            <h2 (click)="onEventSelected($event, user.title, user.addr)">{{user.name}}, {{user.age}}</h2>
            <h3 (click)="onEventSelected($event, user.title, user.addr)">{{user.userAffiliation}}</h3>
            <h3 style="font-size: 10px; color: #52B8BC;">{{ user.title }}, {{ user.startTime }}</h3>
            <h3 style="font-size: 10px; color: #52B8BC;">{{ user.addr }}</h3>
            <button item-right ion-button color="primary" (click)="changeEvent(user.$key, user.checkDate)">
              Rescheduling
            </button>
          </ion-item>
        </ion-list>
  </template>
	<calendar [monthviewEventDetailTemplate]="template"
            [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [queryMode]="calendar.queryMode"
            [currentDate]="calendar.currentDate"
            [formatDayHeader]="calendar.dayheader"
            [noEventsLabel]="calendar.eventlabel"
            (onCurrentDateChanged) = "onCurrentDateChanged($event)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30"
            class="calendar">
  </calendar>
`

**Comment by twinssbc** [comment]
@cosmokwh What exact error did you get when you call loadEvents method?
You mentioned you sometimes get the error, which means it doesn't always happen.
Could you find out in which particular condition, you could reproduce this error?

**Comment by cosmokwh** [comment]
@twinssbc 

Thanks for the reply.
In my app, the loadEvents method is not always called.....

occasionally, when running the "ionic serve" command, 
an error occurs saying that loadEvents is not called, but it is not clear under what conditions it occurs.

What's wrong with my code?
Firebase snapshots are delivering the data I want.

Some of the problems I think are:

1) call loadEvent () from within the constructor..

I have created it to call it in the ioViewDidload function, 
which I have seen in other issues in the past, 
but it does not work and it is currently located in the constructor.

2) this.eventSource = [];

In the ReadMe file, the format of the eventSource is not specified. 
In my code, I initialize it as array type.
If the array type is not initialized, a "TypeError" is raised.

Is there a way to solve it...?

**Comment by twinssbc** [comment]
@cosmokwh You should not call loadEvents in the constructor. Because it needs to get the reference of the calendar component, but at that time, it hasn't been initialized completely.
You have several options:
1. Fetch your data in ionViewDidLoad method
2. Fetch your data in onRangeChanged callback. You need to set queryMode to 'remote'
3. Don't call loadEvents in your fetch data event. Always initialize a new array, and fill the events into it.

Regarding your eventSource  type error, I didn't meet this error. Could you try set the type to any or define some of your own type?

**Comment by cosmokwh** [comment]
@twinssbc 
Thank you for your kind reply.

The eventSource that was initialized in the constructor was removed, 
and the event information was called again in the ionViewDidLoad () function.

It works very well. It's a really cool plugin!
thanks!
