### ISSUE TITLE
ionic3.9.2:Unexpected directive 'CalendarComponent' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by allenwei123** [twinssbc/Ionic2-Calendar#254]

**Comment by twinssbc** [comment]
@allenwei123 How do you import the calendar module in your app module file?

**Comment by allenwei123** [comment]
hi! sir,i hope to get your help.

import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  declarations: [
    MyApp,
  ],
  imports: [
    BrowserModule,
    NgCalendarModule,//import calendar module
    IonicModule.forRoot(MyApp,{
      tabsHideOnSubPages:'true',
      backButtonText:''
    }),
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp
  ],
  providers: [
    StatusBar,
    GlobalData,
    SplashScreen,
    InAppBrowser,
    Network,
    NativeService,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

**Comment by twinssbc** [comment]
@allenwei123 Which Ionic and Angular version are you using?
Could you provide your tsconfig.json and package.json?
Maybe you could also try adding the calendar in a clean Ionic project to see if you still have this error.

**Comment by allenwei123** [comment]
Here's my code,can you find that error?
package.js:
   {
    "name": "myApp",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve"
    },
    "dependencies": {
        "@angular/common": "5.0.3",
        "@angular/compiler": "5.0.3",
        "@angular/compiler-cli": "5.0.3",
        "@angular/core": "5.0.3",
        "@angular/forms": "5.0.3",
        "@angular/http": "5.0.3",
        "@angular/platform-browser": "5.0.3",
        "@angular/platform-browser-dynamic": "5.0.3",
        "@ionic-native/core": "4.4.0",
        "@ionic-native/in-app-browser": "^4.5.2",
        "@ionic-native/network": "^4.5.2",
        "@ionic-native/splash-screen": "4.4.0",
        "@ionic-native/status-bar": "4.4.0",
        "@ionic/pro": "1.0.16",
        "@ionic/storage": "2.1.3",
        "com.kit.cordova.amapnavigation": "git+https://github.com/yanxiaojun617/com.kit.cordova.amapnavigation.git",
        "cordova-android": "^6.2.3",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-inappbrowser": "^1.7.2",
        "cordova-plugin-ionic-webview": "^1.1.11",
        "cordova-plugin-network-information": "^1.3.4",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-whitelist": "^1.3.1",
        "intl": "^1.2.5",
        "ionic-angular": "3.9.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionic2-calendar": "^0.3.13-weekdayview-tpls",
        "ionicons": "3.0.0",
        "rxjs": "5.5.2",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.6",
        "typescript": "2.4.2"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-device": {},
            "cordova-plugin-ionic-webview": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-network-information": {},
            "cordova-plugin-inappbrowser": {},
            "com.kit.cordova.amapnavigation": {}
        },
        "platforms": [
            "android"
        ]
    }
};

tsconfig.json:

 {
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

**Comment by allenwei123** [comment]
Here's my code,can you find that error?
package.js:
{
"name": "myApp",
"version": "0.0.1",
"author": "Ionic Framework",
"homepage": "http://ionicframework.com/",
"private": true,
"scripts": {
"clean": "ionic-app-scripts clean",
"build": "ionic-app-scripts build",
"lint": "ionic-app-scripts lint",
"ionic:build": "ionic-app-scripts build",
"ionic:serve": "ionic-app-scripts serve"
},
"dependencies": {
"@angular/common": "5.0.3",
 "@angular/compiler": "5.0.3",
 "@angular/compiler-cli": "5.0.3",
"@angular/core": "5.0.3",
"@angular/forms": "5.0.3",
"@angular/http": "5.0.3",
"@angular/platform-browser": "5.0.3",
"@angular/platform-browser-dynamic": "5.0.3",
"@ionic-native/core": "4.4.0",
"@ionic-native/in-app-browser": "^4.5.2",
"@ionic-native/network": "^4.5.2"
"@ionic-native/splash-screen": "4.4.0",
 "@ionic-native/status-bar": "4.4.0",
 "@ionic/pro": "1.0.16",
 "@ionic/storage": "2.1.3",
"cordova-android": "^6.2.3",
"cordova-plugin-device": "^1.1.4",
"cordova-plugin-inappbrowser": "^1.7.2",
"cordova-plugin-ionic-webview": "^1.1.11",
"cordova-plugin-network-information": "^1.3.4",
"cordova-plugin-splashscreen": "^4.0.3",
"cordova-plugin-whitelist": "^1.3.1",
"intl": "^1.2.5",
"ionic-angular": "3.9.2",
"ionic-plugin-keyboard": "^2.2.1",
"ionic2-calendar": "^0.3.13-weekdayview-tpls",
"ionicons": "3.0.0",
"rxjs": "5.5.2",
"sw-toolbox": "3.6.0",
"zone.js": "0.8.18"
},
"devDependencies": {
"": "3.1.6",
"typescript": "2.4.2"
},
"description": "An Ionic project",
"cordova": {
"plugins": {
"cordova-plugin-device": {},
"cordova-plugin-ionic-webview": {},
"cordova-plugin-splashscreen": {},
"cordova-plugin-whitelist": {},
"ionic-plugin-keyboard": {},
"cordova-plugin-network-information": {},
"cordova-plugin-inappbrowser": {},
"com.kit.cordova.amapnavigation": {}
},
"platforms": [
"android"
]
}
};

tsconfig.json:

{
"compilerOptions": {
"allowSyntheticDefaultImports": true,
"declaration": false,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"lib": [
"dom",
"es2015"
],
"module": "es2015",
"moduleResolution": "node",
"sourceMap": true,
"target": "es5",
"typeRoots": [
"../node_modules/@types"
]
},
"include": [
"src//*.ts"
],
"exclude": [
"node_modules",
"src//.spec.ts",
"src/**/tests/.ts"
],
"compileOnSave": false,
"atom": {
"rewriteTsconfig": false
}
}

**Comment by allenwei123** [comment]
Here's my code,can you find that error?
package.js:

"dependencies": {
"@angular/common": "5.0.3",
 "@angular/compiler": "5.0.3",
 "@angular/compiler-cli": "5.0.3",
"@angular/core": "5.0.3",
"@angular/forms": "5.0.3",
"@angular/http": "5.0.3",
"@angular/platform-browser": "5.0.3",
"@angular/platform-browser-dynamic": "5.0.3",
"@ionic-native/core": "4.4.0",
"@ionic-native/in-app-browser": "^4.5.2",
"@ionic-native/network": "^4.5.2"
"@ionic-native/splash-screen": "4.4.0",
 "@ionic-native/status-bar": "4.4.0",
 "@ionic/pro": "1.0.16",
 "@ionic/storage": "2.1.3",
"cordova-android": "^6.2.3",
"cordova-plugin-device": "^1.1.4",
"cordova-plugin-inappbrowser": "^1.7.2",
"cordova-plugin-ionic-webview": "^1.1.11",
"cordova-plugin-network-information": "^1.3.4",
"cordova-plugin-splashscreen": "^4.0.3",
"cordova-plugin-whitelist": "^1.3.1",
"intl": "^1.2.5",
"ionic-angular": "3.9.2",
"ionic-plugin-keyboard": "^2.2.1",
"ionic2-calendar": "^0.3.13-weekdayview-tpls",
"ionicons": "3.0.0",
"rxjs": "5.5.2",
"sw-toolbox": "3.6.0",
"zone.js": "0.8.18"
},
"devDependencies": {
"": "3.1.6",
"typescript": "2.4.2"
},
"description": "An Ionic project",
"cordova": {
"plugins": {
"cordova-plugin-device": {},
"cordova-plugin-ionic-webview": {},
"cordova-plugin-splashscreen": {},
"cordova-plugin-whitelist": {},
"ionic-plugin-keyboard": {},
"cordova-plugin-network-information": {},
"cordova-plugin-inappbrowser": {},
"com.kit.cordova.amapnavigation": {}
},
"platforms": [
"android"
]
}
};

tsconfig.json:

{
"compilerOptions": {
"allowSyntheticDefaultImports": true,
"declaration": false,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"lib": [
"dom",
"es2015"
],
"module": "es2015",
"moduleResolution": "node",
"sourceMap": true,
"target": "es5",
"typeRoots": [
"../node_modules/@types"
]
},
"include": [
"src//*.ts"
],
"exclude": [
"node_modules",
"src//.spec.ts",
"src/**/tests/.ts"
],
"compileOnSave": false,
"atom": {
"rewriteTsconfig": false
}
}

**Comment by allenwei123** [comment]
"@angular/common": "5.0.3",
        "@angular/compiler": "5.0.3",
        "@angular/compiler-cli": "5.0.3",
        "@angular/core": "5.0.3",
        "@angular/forms": "5.0.3",
        "@ionic-native/core": "4.4.0",
        "@ionic-native/in-app-browser": "^4.5.2",
        "@ionic-native/network": "^4.5.2",
        "@ionic-native/splash-screen": "4.4.0",
        "@ionic-native/status-bar": "4.4.0",
        "@ionic/pro": "1.0.16",
        "@ionic/storage": "2.1.3",

**Comment by allenwei123** [comment]
angular/common:5.0.3,
angular/core: 5.0.3,
ionic-native/core: 5.0.3,

**Comment by twinssbc** [comment]
@allenwei123 I notice you are using 0.3.13-weekdayview-tpls version. For Ionic 3.9.2 project, please use 0.4.x version.

**Comment by allenwei123** [comment]
How to get 0.4.x version?

**Comment by allenwei123** [comment]
Thank you for your advice！
