### ISSUE TITLE
Show only the current month

### ISSUE THREAD

**Issue by mohitook** [twinssbc/Ionic2-Calendar#256]
Hello,

I'll show only the current month, without any days from the next and previous month, only empty cells.
Can you suggest an easy way to do it?

I've already found this solution:
```
<ng-template #template let-view="view" let-row="row" let-col="col">
    <div *ngIf="!view.dates[row*7+col].secondary"
...
```
but in this case the days are still there, but without label, so basically it is not a solution

thank you!

**Comment by twinssbc** [comment]
@mohitook Sorry, I'm not quite clear about the effect you want to achieve. You want to have empty cells, but it seems the days without label couldn't meet your requirement? Maybe you could draw some mockup?

**Comment by mohitook** [comment]
so,  basically the empty cells not meet with my requirements because the event colors are still visible in the "unlabeled" cells,.. I just simply want to let them empty in a way that it won't show the events, won't be  activated if I click on them etc..
![image](https://user-images.githubusercontent.com/15103326/34447533-3dde9178-ece5-11e7-86a8-d853c77a05d6.png)

basically I won't see what I marked with red line (no label, no background color when event is there and no action when clicking on them), and won't display additional row like on this picture what I marked with yellow!

**Comment by twinssbc** [comment]
@mohitook To not displaying event on these days, you just skip these days when filling eventSource array. For example, only returning the events within the current month.
To not activate them, you could use markDisabled callback.
Unfortunately, the month view is based on 42 days, because in some month, it still occupy 6 rows, so not able to hide that row.
