### ISSUE TITLE
Could I  prevent vertical scrolling in month view in iOS?

### ISSUE THREAD

**Issue by qwertytoki** [twinssbc/Ionic2-Calendar#257]
Hello, thank you for your great calendar. 
This time, I met a trouble in monthly view.

When I try to change month by swiping left/right, then also scrolling vertically.
Could I prevent vertical scrolling?
(This problem happens only ios. Not happen when using "ionic serve")

I appreciate your help.

<img width="608" alt="2017-12-31 17 41 53" src="https://user-images.githubusercontent.com/22290203/34460448-f13e598e-ee51-11e7-9d88-70ba515d886a.png">

**Comment by twinssbc** [comment]
@qwertytoki
This bounce behavior on ion-content is the default effect in ios, there is a no-bounce, but someone says it's not working.
I don't have a ios device at hand, so can't test.
Maybe below issue discussion could help you.
https://github.com/ionic-team/ionic/issues/7644

**Comment by qwertytoki** [comment]
@twinssbc 
Thank you very much for your reply.
I solved by using
`<ion-content no-bounce>
</ion-content>`

[note]
"no-bounce" will move 2 patterns.
1 if there is no event -> no bounce
2 if there are events more than display size ->this time we can scroll.
<img width="593" alt="2018-01-03 19 09 13" src="https://user-images.githubusercontent.com/22290203/34516262-a18a8cf4-f0b9-11e7-8ec7-3cf90b2840c6.png">

**Comment by manikandan07081995** [comment]
@twinssbc  Scroll continues wrong date showing and hanging sometimes view white screen appears.
![Uploading Screen Shot 2018-03-12 at 4.17.26 PM.png…]()

**Comment by manikandan07081995** [comment]
![screen shot 2018-03-12 at 4 17 26 pm](https://user-images.githubusercontent.com/34768728/37281694-e9174402-2617-11e8-9357-b410e4044f53.png)

**Comment by twinssbc** [comment]
@manikandan07081995 Your question is not related to this issue. 
Don't comment irrelevant question under multiple issues.
You could create a separate issue.
