### ISSUE TITLE
Runtime Error co.onViewTitleChanged is not a function on ionic serve

### ISSUE THREAD

**Issue by qasmaoui** [twinssbc/Ionic2-Calendar#258]
hello to you all
im getting the same error heer

Runtime Error
co.onViewTitleChanged is not a function

Stack
TypeError: co.onViewTitleChanged is not a function
at Object.eval [as handleEvent] (ng:///AppModule/CalendrierPage.ngfactory.js:377:24)
at Object.handleEvent (http://localhost:8100/build/vendor.js:12273:138)
at Object.handleEvent (http://localhost:8100/build/vendor.js:12976:85)
at dispatchEvent (http://localhost:8100/build/vendor.js:9173:21)
at http://localhost:8100/build/vendor.js:11101:20
at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/vendor.js:4222:36)
at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:42439:16)
at SafeSubscriber.next (http://localhost:8100/build/vendor.js:42386:22)
at Subscriber._next (http://localhost:8100/build/vendor.js:42326:26)
at Subscriber.next (http://localhost:8100/build/vendor.js:42290:18)

my configuration

Ionic Framework: 3.6.1
Ionic App Scripts: 2.1.4
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 8.9.3
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

<img width="893" alt="capture d ecran 2018-01-02 a 09 29 54" src="https://user-images.githubusercontent.com/16212917/34480718-ebc0aab6-efa5-11e7-9e94-d0b78bce357f.png">

heer is my html
```

<ion-header>
  <ion-navbar color="primary">
    <ion-title>{{viewTitle}}</ion-title>
    <ion-buttons end>
      <button ion-button [disabled]="isToday" (click)="today()">Today</button>
      <button ion-button (click)="changeMode('month')">M</button>
      <button ion-button (click)="changeMode('week')">W</button>
      <button ion-button (click)="changeMode('day')">D</button>
      <button ion-button (click)="loadEvents()">Load Events</button>
    </ion-buttons>
  </ion-navbar>
</ion-header>

<ion-content class="has-header">
  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30">
  </calendar>
</ion-content>
```

i have also impoter the calendar module on
app.module.ts

**Comment by qasmaoui** [comment]
just miss used the code .

**Comment by davidmpaz** [comment]
Small explanation of how was misused can help others.
