### ISSUE TITLE
Need help of ngOutletContext

### ISSUE THREAD

**Issue by ghost** [twinssbc/Ionic2-Calendar#260]
Hi, after looking through the issues of others users. I still do not understand on how to solve.

Currently, I am having this problem "Uncaught Error: Template parse errors:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'."

How can I fix it? Thankyou in advance. 

My system info.
PS C:\Users\Chin_\Desktop\calendarApp> ionic info

cli packages: (C:\Users\robert\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.1.2
    npm  : 5.0.3
    OS   : Windows 10

**Comment by ecert** [comment]
Hi there,
it happened to me that i upgraded from Angular4 to Angular5.
if you use Angular5 and your ionic2-calendar version number is 0.3.x
i suggest you to use 0.4.x version.
i install it (npm install ionic2-calendar@0.4.2) and i am not getting any ngOutletContext error.

I think Angular5 is using ionic2-calendar 0.4.x version.

**Comment by robertrobertlow** [comment]
@ecert Hi, thankyou for your help. How can I change the version as you mention? Plus not sure if it will affect my other projects.

**Comment by ecert** [comment]
in your package.json files if you see "@angular/common": "5.0.x" you use Angular5 version.
Then you use ionic2-calendar 0.4.x version. Because ng-template structure is changed on Angular5.
You use below for updating your ionic2-calendar version to 0.4.x
NOT: First get your backup before using it.

npm install ionic2-calendar@0.4.2

**Comment by robertrobertlow** [comment]
@ecert yes, my angular version is 5.0.3. And I tried your "npm install ionic2-calendar@0.4.2 --save". And verified that the ionic2-calendar is indeed in version 0.4.2. However, it is still the same error.

**Comment by Kr0n092** [comment]
Does the error still persist if you remove the npm_modules folder and run npm install?

**Comment by robertrobertlow** [comment]
yes, tried. will it affect my other projects?

**Comment by Kr0n092** [comment]
Your other projects, if they use the same npm_modules folder, will only be affected if they use packages that you've upgraded (like Angular 5.0.x)

**Comment by twinssbc** [comment]
@robertrobertlow How do you make sure ionic2-calendar 0.4.2 is installed in your project? Could you search "ngOutletContext" in the calendar install folder? It should not exist, 0.4.x version is using "ngTemplateOutlet"

**Comment by robertrobertlow** [comment]
Thankyou guys for all the help given. I have 1 more question for now. Please tolerate me thankyou. 
If I just change the version to 0.4.2, would it affect the program pre-default done by @twinssbc. As I do not know will it affect in anyway. thankyou. Because I would use this as a base and built on it for my parents to used as a reminder

**Comment by twinssbc** [comment]
@robertrobertlow The features between calendar 0.3.x and 0.4.x are always the same. The reason I maintain separate version series are Angular itself has some breaking changes on the syntax.
So you don't need to worry about your app behavior changes when upgrading the calendar version.

**Comment by robertrobertlow** [comment]
@twinssbc Where can I learn how to use the calendar to enhance it? Thankyou.
