### ISSUE TITLE
How can I load events at startup ?

### ISSUE THREAD

**Issue by dirodriguezm** [twinssbc/Ionic2-Calendar#261]
I have a method to add events to the _eventSource_ array.

I tried calling it from the constructor of the page, and under the ngAfterViewInit / Checked methods but I get TypeError: _a is undefined.

I think the error happens because the calendar view is not ready yet. When I create a button and load the events when clicking the button it works ok, but I need to add the events at the begining of the page load.

**Comment by abdulkadhir** [comment]
@dirodriguezm use "this .eventSource.push();" in the constructor, it loads the event source array when the calendar starts.

**Comment by twinssbc** [comment]
@dirodriguezm Try loading events in ionViewDidLoad?

**Comment by dirodriguezm** [comment]
@twinssbc loading events on ionViewDidLoad gives a runtime error: _a is undefined

**Comment by juntaforce** [comment]
Hi @dirodriguezm 
Could you please share your solution with a code ?
ionViewDidLoad is not  load the events at startup

**Comment by twinssbc** [comment]
@juntaforce Did you get any error when you load events in ionViewDidLoad?

**Comment by juntaforce** [comment]
Hi @twinssbc 
Fixed with this issue #144
