### ISSUE TITLE
Changing Color of Today's Date in Month View 

### ISSUE THREAD

**Issue by waleedshkt** [twinssbc/Ionic2-Calendar#262]
Hi,

I get a light pale background with a white font style for the today's date view in month view mode when not selected. 

Can anyone please tell me what class to use to change the above-mentioned style properties?
 
Thank you very much.

**Comment by pipolamenace** [comment]
I'm fairly new to Angular/Ionic, but here's what I did:

I've added these lines of CSS code to my "calendar.scss" file (the scss file for the page where my calendar is displayed). I wanted the selected date to have a green background color, white and bold text:

```
	.monthview-selected {
		background-color:#7ed321 !important;
		color:#fff !important;
		font-weight:bold !important;
	}
```

So if you want to change the background color to something else than, just copy my code and change the background-color hex code value. Same for the "color" part.

That might not be the best way to handle this, I'm new to this but I've managed to achieve what I wanted doing that method. Hope it helps

**Comment by waleedshkt** [comment]
Thanks a lot @pipolamenace ,

Yes, that certainly does change the style of selected date view. But I'm trying to do this for non-selected today's date. I am getting pale background color with white font for it which isn't very noticeable.

**Comment by twinssbc** [comment]
@waleedshkt You could override the style for .monthview-current
