### ISSUE TITLE
ionic-angular... component.ngfactory not found

### ISSUE THREAD

**Issue by hewham** [twinssbc/Ionic2-Calendar#263]
Using calendar version 0.3.13

all calendar.module.ngfactory.ts imports from ionic-angular do not exist in node_modules/ionic-angular. (as well as other ngfactory files within ionic2-calendar)

example..

import * as import5 from 'ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import6 from 'ionic-angular/components/alert/alert-component.ngfactory';
import * as import7 from 'ionic-angular/components/app/app-root.ngfactory';
import * as import8 from 'ionic-angular/components/loading/loading-component.ngfactory';
import * as import9 from 'ionic-angular/components/modal/modal-component.ngfactory';
import * as import10 from 'ionic-angular/components/picker/picker-component.ngfactory';
import * as import11 from 'ionic-angular/components/popover/popover-component.ngfactory';
import * as import12 from 'ionic-angular/components/select/select-popover-component.ngfactory';
import * as import13 from 'ionic-angular/components/toast/toast-component.ngfactory';

all do not exist.

Have tried uninstalling/ reinstalling ionic-angular, no success.

Am I missing something obvious?

Hews-MBP:Giggot hew$ ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v6.10.3
    npm        : 4.2.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by twinssbc** [comment]
@hewham  I'm not quite clear about your issue.
If you don't use calendar, could you run your project successfully?
When you start using the calendar, what kind of error message did you get? How do you run your project? ionic server? or in any real device?

**Comment by hewham** [comment]
[10:31:32]  typescript: src/components/ionic2-calendar/calendar.module.ngfactory.ts, line: 15 
            Cannot find module 'ionic-angular/components/action-sheet/action-sheet-component.ngfactory'. 

      L14:  import * as import13 from 'ionic-angular/components/select/select-popover-component.ngfactory';
      L15:  import * as import14 from 'ionic-angular/components/toast/toast-component.ngfactory';            
      L16:  import * as import15 from './calendar.ngfactory';

[10:31:32]  typescript: src/components/ionic2-calendar/calendar.module.ngfactory.ts, line: 16 
            Cannot find module 'ionic-angular/components/alert/alert-component.ngfactory'. 

      L15:  import * as import14 from 'ionic-angular/components/toast/toast-component.ngfactory';
      L16:  import * as import15 from './calendar.ngfactory';                                  
      L17:  class NgCalendarModuleInjector extends import0.ɵNgModuleInjector<import1.NgCalendarModule> {



.....etc, it continues like that for the other ionic-angular components.

I checked within the node_modules/ionic-angular and these .ngfactory files do not exist where the calendar module is importing them from.

This is only in calendar version 0.3.X
0.4.X doesn't import these .ngfactory files, but I cannot use it because I'm still on ionic v3.8.0, which uses angular 4.X

I'm confused at what the ngfactory files are for, and why they are being imported when they do not exist in ionic-angular.

My project works and builds fine without the calendar module, using both ionic serve and ionic build/run on both android and ios

**Comment by twinssbc** [comment]
@hewham Do you directly add the calendar source code in your project?
Why don't you use the release version?

**Comment by hewham** [comment]
Ok figured it out!

I had moved from node_modules to my src because I heavily edited the html code to change the appearance.

To avoid doing this again, is there a way to edit the html code of the event list (Changing the way events look and their function for a certain day underneath the calendar) without editing the src code? Also a way to change colors of selected dates on calendar itself?

thank you for your responses

**Comment by hewham** [comment]
Figured out the templates as well, so no help is needed there. Thanks again!

**Comment by lluisnieto** [comment]
Same here:

Error: ./src/pages/track-manager/event-data/event-data.ngfactory.js Module not found: Error: Can't resolve
            '../../../../node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory' in
            '/Users/lluissoler/Projects/braapfinder-pwa/src/pages/track-manager/event-data' resolve
            '../../../../node_modules/ionic3-calendar-en/src/calendar/calendar.ngfactory' in
            '/Users/lluissoler/Projects/braapfinder-pwa/src/pages/track-manager/event-data' using description file:
            /Users/lluissoler/Projects/braapfinder-pwa/package.json

**Comment by twinssbc** [comment]
@lluisnieto It seems you are using ionic3-calendar-en? This project is not related.
You should create an issue under https://github.com/DydjyZ/ionic3-calendar-fr
