### ISSUE TITLE
Error Can't bind to 'startingDayMonth' since it isn't a known property of 'calendar'

### ISSUE THREAD

**Issue by Zodar** [twinssbc/Ionic2-Calendar#265]
This error is displayed only when I use "--prod" tag.

```
Error: Template parse errors:
Can't bind to 'startingDayMonth' since it isn't a known property of 'calendar'. ("
<ion-content>
        <calendar
                [ERROR ->][startingDayMonth]="startingDayMonth"
                [locale]="calendar.locale"
                [noEventsLabel]="calendar.noEv"): ng:///C:/Users/tarik/Documents/ink_mobile/ink_v2/src/pages/AgendaPages/agenda/agenda.html@15:2
```

**Comment by twinssbc** [comment]
@Zodar Which version of the calendar are your using? If you remove startingDayMonth, are the rest options working?

**Comment by Zodar** [comment]
I resolved this case, but with an ugly way.
It seems _--dev_ and _--prod_ argument for building ionic app doesn't use the same compilator.
So the only way I found yet:

1/ I put _NgCalendarModule_ in both my _appModule_ and my _pageModule_ (page where my calendar is) to resolve **this error**.

2/ I have to comment _pageModule_ in declarations of _appModule_  when I use --prod, and uncomment it when not. If I don't do this, it throw me "**module declared 2 times**" with --prod, and "**module not declared**" without --prod

It seems I don't understand a thing with declarations of module in angular4, but I search and I doesn't found a solution yet.
Sorry for my english writing.

**Comment by twinssbc** [comment]
@Zodar Regarding the issue when appModule and pageModule need to coexist, not sure if below discussion could give you some help.
https://github.com/ionic-team/ionic/issues/11487
