### ISSUE TITLE
'calendar' is not a known element:

### ISSUE THREAD

**Issue by robertrobertlow** [twinssbc/Ionic2-Calendar#267]
[Angular]
'calendar' is not a known element:
1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

Hello guys,
How come it became a problem after I move it into a new project file?

Thankyou very much.

**Comment by robertrobertlow** [comment]
this is my ionic information:

cli packages: (C:\Users\Chin_\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.1.2
    npm  : 5.0.3
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by twinssbc** [comment]
@robertrobertlow  Did you import the calendar module? Could you provide your app module code?

**Comment by robertrobertlow** [comment]
Hi @twinssbc this is my module.ts

import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { AngularFireModule } from 'angularfire2';
import { AngularFireDatabaseModule } from 'angularfire2/database';
import { FIREBASE_CREDENTIALS } from './firebase.credentials';

import { MyApp } from './app.component';
import { ScheduleDataProvider } from '../providers/schedule-data/schedule-data'

import { NgCalendarModule } from 'ionic2-calendar';

@NgModule({
  declarations: [
    MyApp,

  ],
  imports: [
    BrowserModule,
    NgCalendarModule,
    IonicModule.forRoot(MyApp),
    // Initialise AngularFire with credientials from the dashboard
    AngularFireModule.initializeApp(FIREBASE_CREDENTIALS),
    // Import the AngularFireDatabaseModule to use database interactions
    AngularFireDatabaseModule

  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,

  ],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: ErrorHandler, useClass: IonicErrorHandler },
    ScheduleDataProvider,
  ]
})
export class AppModule { }

**Comment by robertrobertlow** [comment]
@twinssbc I am lazy loading my page with "ionic g page calendar".

**Comment by twinssbc** [comment]
@robertrobertlow 
I don't quite understand your lazy loading command, "ionic g page calendar".
What does that mean?
Is there any other error printed out in the console?
Could you provide more code to demonstrate how do you use the calendar?

**Comment by robertrobertlow** [comment]
@twinssbc Thankyou for solving this for me. Really appreciate. Thankyou once again.
