### ISSUE TITLE
IEvent : missing ID property

### ISSUE THREAD

**Issue by Titoch** [twinssbc/Ionic2-Calendar#268]
Hi,
My events in Calendar are database data set in objects implementing IEvent.
So when a user selects an event in WeekView Calendar I have to retrieve the respective object using the supplied IEvent parameter from the onEventSelected method.

The difficulty is when the user has 2 or more events having same : startTime, endTime and title.
The EventSelect gives me the correct IEvent, but I can not know to which object it is mapped. as there is no differences in the IEvents.

Would it be possible to extend Interface IEvent with an 'id' property that developpers could use to store and and retrieve the data when the event is selected ?
I think it would be helpful for many developpers.

**Comment by twinssbc** [comment]
@Titoch startTime, endTime and title are the mandatory fields. It doesn't prevent you adding your own fields.

**Comment by Titoch** [comment]
@twinssbc 
Oh yes of course... I thought that I could only push IEvent in the Calendar eventSource...
I was mistaken.
Then it already works fine !!!
Thank you !
This issue can be closed...
