### ISSUE TITLE
allDay: true event not working as expected

### ISSUE THREAD

**Issue by mauriciogardini** [twinssbc/Ionic2-Calendar#269]
I am trying to create an event that lasts a whole single day, like this:

```
  {
    "allDay": true,
    "endTime": new Date(Date.UTC(2018, 1, 22)),
    "startTime": new Date(Date.UTC(2018, 1, 22)),
    "title": "Evento - 11"
  }
```

For some reason, the event isn't showing in the calendar.

Related to that, when I try to add a multi-day event, like the one below, it only shows it at its second day:

```
  {
    "allDay": true,
    "endTime": new Date(Date.UTC(2018, 1, 10)),
    "startTime": new Date(Date.UTC(2018, 1, 11)),
    "title": "Evento - 11"
  }
```

Am I doing something wrong? Did I understand something badly?

**Comment by twinssbc** [comment]
@mauriciogardini You can't set startTime and endTime on the same day. 
Below startTime and endTime means the allDay event starts at 2014-05-08, doesn't include 2014-05-09.
var startTime = new Date(Date.UTC(2014, 4, 8));
var endTime = new Date(Date.UTC(2014, 4, 9));

**Comment by mauriciogardini** [comment]
Hm, I get it. Wasn't aware of this behavior.

Thank you for the prompt response!
