### ISSUE TITLE
Highlight specific columns + doubleclick event to select data

### ISSUE THREAD

**Issue by iNDicat0r** [twinssbc/Ionic2-Calendar#27]
Hi 
Two questions:
1) I would like to highlight specific days.. for instance highlighting the weekends.
2) use doubleclick instead of click to select a day in month view.

Regards

**Comment by twinssbc** [comment]
@iNDicat0r 
1. This version doesn't support view customization yet. I will add it soon. Another workaround is there's a markDisabled option to allow you mark certain days as disabled, there will be a monthview-disabled css class applied to the cell. You can add styles to that class.
2. I'm afraid you have to modify the source code to achieve that. A workaround is you can record the click counts in the current single callback to simulate the double click. Also note that in the mobile device, we probably don't do double tap quite often.

**Comment by twinssbc** [comment]
@iNDicat0r I have added view customization in version 0.1.0. You can get more information from README. Feel free to have a try. Thanks.

**Comment by iNDicat0r** [comment]
Thanks you i will try.

**Comment by Seao** [comment]
Hi @twinssbc, is it possible to have more details on the workaround using markDisabled option to highlight specific days please ? I'm currently facing this issue, and my implementation using markDisabled is not working as expected.

#### Html
```html
<calendar
  calendarMode="week"
  startingDayWeek="1"
  [markDisabled]="markDisabled"
  ...
  step="30">
</calendar>
 ```
#### Typescript
```javascript
markDisabled = (date: Date) => {
  console.log("called");
  var current = new Date();
  return date < current;
}
```
markDisabled is called only when I click on the calendar (event or not), it's triggered exactly like onTimeSelected. How can I use it to mark past days, block them an add a css background-color attribute ?

Thanks for this module,
Regards

**Comment by twinssbc** [comment]
@Seao You want to display disabled date on monthview or other view? In month view, it will be called when rendering each cell, if you return true, there will be a monthview-disabled class applied to the cell.

**Comment by Seao** [comment]
@twinssbc Thanks for you answer. I'm using exclusively the week view and I would like disable and color in grey the past cells based on the current date. This disabled class looks perfect for fit my purpose, is it possible to use it in the week view ?

**Comment by twinssbc** [comment]
@Seao this option is not used in weekview. I'm afraid you need to modify the source code.

**Comment by Seao** [comment]
@twinssbc Ok, I will take a look if I can do something for it. Thanks for your availability 👍
