### ISSUE TITLE
Show only 5 rows in calendar month view

### ISSUE THREAD

**Issue by jd0048** [twinssbc/Ionic2-Calendar#273]
Hello
currently i am facing issue for setup calendar month view column, how to control calendar so it will only visible for 5 row only currently it will showing 6 row in calendar month view 

please check attached image  for reference.
![screen shot 2018-01-15 at 12 22 37 pm](https://user-images.githubusercontent.com/28923124/34930337-0b2b1d3e-f9ef-11e7-96ca-9522eba34834.png)

**Comment by twinssbc** [comment]
@jd0048 The month view is based on 6 rows, because some months may occupy 6 rows. And there's no way to change this behavior unless you modify the source code.
