### ISSUE TITLE
MonthView is not updating new events properly (after adding and reloading in eventSource)

### ISSUE THREAD

**Issue by en-sevilla** [twinssbc/Ionic2-Calendar#274]
Hi Twinssbc,

first at all, thanks for your amazing work and support with this plugin, we are very grateful.

We are implementing a multi-date picker, so when user clicks on a day in Month View, an icon appears and replaces the number of that day.

We are updating a "events" global variable with the selected dates by pushing a new event object, and then we assign it to "eventSource", as you described on the documentation.

But the view only updates the first click with the icon, the following clicks don't update the view until we move from the current month to another, and go back.

My version of ionic2-calendar is **0.4.2^**

This is the .ts and .html code (I copy everything because it could be usefull for future doubts about templates, etc...).

Thanks and best regards from Spain.

**home.ts**
```
import { Component } from '@angular/core';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  eventSource;
  viewTitle;
  events;

  isToday: boolean;
  calendar = {
    mode: 'month',
    currentDate: new Date(),
    dateFormatter: {
      formatMonthViewDay: function (date: Date) {
        return date.getDate().toString();
      }
    }
  };

  constructor() {
    this.events = [];
  }

  onViewTitleChanged(title) {
    this.viewTitle = title;
  }

  onEventSelected(event) {
    console.log('Event selected:' + event.startTime + '-' + event.endTime + ',' + event.title);
  }

  changeMode(mode) {
    this.calendar.mode = mode;
  }

  today() {
    this.calendar.currentDate = new Date();
  }

  onTimeSelected(event) {
    console.log('Selected time: ' + event.selectedTime + ', hasEvents: ' +
      (event.events !== undefined && event.events.length !== 0) + ', disabled: ' + event.disabled);

    this.events.push({
      title: 'Event',
      startTime: event.selectedTime,
      endTime: event.selectedTime,
      allDay: true
    });

    this.eventSource = this.events;
    console.log(this.eventSource);

  }

  onCurrentDateChanged(event: Date) {
    var today = new Date();
    today.setHours(0, 0, 0, 0);
    event.setHours(0, 0, 0, 0);
    this.isToday = today.getTime() === event.getTime();
  }

  onRangeChanged(ev) {
    console.log('range changed: startTime: ' + ev.startTime + ', endTime: ' + ev.endTime);
  }

  markDisabled = (date: Date) => {
    var current = new Date();
    current.setHours(0, 0, 0);
    return date < current;
  };

  getEventClass(events) {
    return 'test' + events.length;
  }

}
```
**home.html**
```
<ion-header>
  <ion-navbar color="primary">
    <ion-title>{{viewTitle}}</ion-title>
  </ion-navbar>
</ion-header>

<ion-content class="has-header">

  <ng-template #template let-view="view" let-row="row" let-col="col">

    <!-- If there are events on selected day, show a check icon -->
    <div *ngIf="view.dates[row*7+col].events.length>0">
      <ion-icon name="checkmark-circle" color="secondary"></ion-icon>
    </div>

    <!-- If no events, show day as normally -->
    <div *ngIf="(view.dates[row*7+col].events.length)===0">
      <div>
        {{view.dates[row*7+col].label}}
      </div>
    </div>

  </ng-template>

  <calendar 
  [calendarMode]="calendar.mode" 
  [noEventsLabel]="calendar.noEventsLabel" 
  [allDayLabel]="calendar.allDayLabel" 
  [currentDate]="calendar.currentDate" 
  [eventSource]="eventSource" 
  (onCurrentDateChanged)="onCurrentDateChanged($event)"
  (onRangeChanged)="reloadSource($event)" 
  (onEventSelected)="onEventSelected($event)"
  (onTitleChanged)="onViewTitleChanged($event)"
  (onTimeSelected)="onTimeSelected($event)" 
  [autoSelect]="false" 
  step="30" 
  [monthviewDisplayEventTemplate]="template">
  </calendar>

</ion-content>
```

**package.json with versions:**
```

{
  "name": "test-ionic2-calendar",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic/storage": "2.1.3",
    "intl": "^1.2.5",
    "ionic-angular": "3.9.2",
    "ionic2-calendar": "^0.4.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.0",
    "typescript": "2.4.2",
    "ws": "3.3.2"
  },
  "description": "An Ionic project"
}


```

**Comment by twinssbc** [comment]
@en-sevilla 
Actually your eventSource is always assigned to the same events variable.

this.eventSource = this.events;

So it's basically the same as you directly push event to this.eventSource.

As I explained in the README, it watches the whole eventSource variable change.
So you should either each time assign eventSource a brand new object, for example, at the beginning of onTimeSelected method, you could set the events to a new array.
 this.events = [];
Or you could just push event to eventSource, but call loadEvents method to force refresh.

**Comment by en-sevilla** [comment]
thank you for your response, I didn't know how to implement the loadEvents() method and I tried by updating auxiliary variables. Thanks , now **It works**, I paste the code with the correct approach (only the modified code).

Best regards,

```

import { Component, ViewChild } from '@angular/core';
import { CalendarComponent } from "ionic2-calendar/calendar";

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  @ViewChild(CalendarComponent) myCalendar: CalendarComponent;

  eventSource = [] ;
  viewTitle;
  isToday: boolean;
  calendar = {
    mode: 'month',
    currentDate: new Date(),
    dateFormatter: {
      formatMonthViewDay: function (date: Date) {
        return date.getDate().toString();
      }
    }
  };

  constructor() {
  }

```
[ ..... ]
```
  onTimeSelected(event) {

    this.eventSource.push({
      title: 'Selected date',
      startTime: event.selectedTime,
      endTime: event.selectedTime,
      allDay: true
    });

    this.myCalendar.loadEvents();

  }
```

**Comment by en-sevilla** [comment]
sorry @twinssbc , I'm testing the functionality and when I click on a date, the market day is just the one on the left, like this:

I click on 18 and the market is 17

[![calendar.png](https://s10.postimg.org/k0coq212x/calendar.png)](https://postimg.org/image/4evd63p4l/)

This is the eventSource array:

[![eventsource.png](https://s10.postimg.org/qqt5zptg9/eventsource.png)](https://postimg.org/image/kd42wgok5/)

This is the function where I update "Event Source":

```
  onTimeSelected(event) {

    console.log(this.eventSource);

    //If we have already selected, remove from array, refresh and return
    for (var index = 0; index < this.eventSource.length; index++) {
      if (this.eventSource[index].startTime === event.selectedTime) {
        this.eventSource = this.eventSource.slice(0, index);
        this.myCalendar.loadEvents();
        return;
      }
    }

    //Insert selected date/event
    this.eventSource.push({
      title: 'Selected',
      startTime: event.selectedTime,
      endTime: event.selectedTime,
      allDay: true
    });

    //Refresh the view
    this.myCalendar.loadEvents();
  }
```

And this is the template:

```
    <ng-template #template let-view="view" let-row="row" let-col="col">
      <!-- If there are events on selected day, show a check icon -->
      <div *ngIf="view.dates[row*7+col].events.length>0">
        <ion-icon name="checkmark-circle" color="secondary"></ion-icon>
      </div>
      <!-- If no events, show day as normally -->
      <div *ngIf="(view.dates[row*7+col].events.length)==0">
        <div>
          {{view.dates[row*7+col].label}}
        </div>
      </div>
  
    </ng-template>

    <p text-center no-padding no-margin>{{ viewTitle }}</p>
  
    <calendar 
      [calendarMode]="calendar.mode" 
      [noEventsLabel]="calendar.noEventsLabel" 
      [startingDayMonth]="calendar.startingDayMonth"
      [allDayLabel]="calendar.allDayLabel" 
      [currentDate]="calendar.currentDate" 
      [eventSource]="eventSource"
      (onCurrentDateChanged)="onCurrentDateChanged($event)"
      (onRangeChanged)="reloadSource($event)" 
      (onEventSelected)="onEventSelected($event)"
      (onTitleChanged)="onViewTitleChanged($event)"
      (onTimeSelected)="onTimeSelected($event)" 
      [autoSelect]="false" 
      step="30" 
      [monthviewDisplayEventTemplate]="template">
    </calendar>
```

**Comment by twinssbc** [comment]
@en-sevilla You can't directly use the selected time retrieved from the onTimeSelected method as a all-day event.
If allDay is set to true, the startTime has to be as a UTC date which time is set to 0:00 AM, and endTime is the same requirement but one day later.

**Comment by en-sevilla** [comment]
THANKS!!, Now It works fine. My fault, I need to deep more on date manipulations. 

The final code for a multidate picker with select/deselect is:

```
  onTimeSelected(event) {

    var selectedDate = new Date(event.selectedTime);
    var selectedYear = selectedDate.getFullYear();
    var selectedMonth = selectedDate.getMonth();
    var selectedDay = selectedDate.getDate();

    //If we have already selected, remove from array, refresh and return
    for (var index = 0; index < this.eventSource.length; index++) {
      var date = new Date(this.eventSource[index].startTime);
      //Compare
      if ((selectedYear == date.getFullYear())
        && (selectedMonth == date.getMonth())
        && (selectedDay == date.getDate())) {
        //Extract matching date from the eventSource array
        this.eventSource.splice(index, 1);
        this.myCalendar.loadEvents();
        return;
      }
    }

    var startTime = new Date(Date.UTC(selectedYear, selectedMonth, selectedDay));
    var endTime = new Date(Date.UTC(selectedYear, selectedMonth, selectedDay + 1)); //Plus one day

    //Insert selected date/event
    this.eventSource.push({
      title: 'Selected date',
      startTime: startTime,
      endTime: endTime,
      allDay: true
    });

    //Refresh the view
    this.myCalendar.loadEvents();
    console.log(this.eventSource);

  }

```

**Comment by rajkanase** [comment]
> thank you for your response, I didn't know how to implement the loadEvents() method and I tried by updating auxiliary variables. Thanks , now **It works**, I paste the code with the correct approach (only the modified code) and the method to check/uncheck correctly when user press for the second time.
> 
> Best regards,
> 
> ```
> 
> import { Component, ViewChild } from '@angular/core';
> import { CalendarComponent } from "ionic2-calendar/calendar";
> 
> @Component({
>   selector: 'page-home',
>   templateUrl: 'home.html'
> })
> export class HomePage {
> 
>   @ViewChild(CalendarComponent) myCalendar: CalendarComponent;
> 
>   eventSource = [] ;
>   viewTitle;
>   isToday: boolean;
>   calendar = {
>     mode: 'month',
>     currentDate: new Date(),
>     dateFormatter: {
>       formatMonthViewDay: function (date: Date) {
>         return date.getDate().toString();
>       }
>     }
>   };
> 
>   constructor() {
>   }
> ```
> [ ..... ]
> 
> ```
>   onTimeSelected(event) {
> 
>     //If we have already selected, remove from array, refresh and return
>     for (var index = 0; index < this.eventSource.length; index++) {
>       if (this.eventSource[index].startTime == event.selectedTime) {
>         this.eventSource = this.eventSource.slice(0,index);
>         this.myCalendar.loadEvents();
>         return;
>       }
>     }
> 
>     //Insert selected date/event
>     this.eventSource.push({
>       title: 'Selected date',
>       startTime: event.selectedTime,
>       endTime: event.selectedTime,
>       allDay: true
>     });
> 
>     //Refresh the view
>     this.myCalendar.loadEvents();
>     
>   }
> ```
Thanks for your explaination..I did same but getting following error.
core.js:1449 ERROR TypeError: Cannot read property 'loadEvents' of undefined
    at SafeSubscriber._next (calendar.ts:45)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:196)
    at SafeSubscriber.next (Subscriber.js:134)
    at Subscriber._next (Subscriber.js:77)
    at Subscriber.next (Subscriber.js:54)
    at MapSubscriber._next (map.js:41)
    at MapSubscriber.Subscriber.next (Subscriber.js:54)
    at angularfire2.js:49
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)

**Comment by twinssbc** [comment]
@rajkanase As the error indicates, this.myCalendar is undefined. Could you change it properly so that it could call loadEvents method?

**Comment by jcmendes9898** [comment]
@twinssbc , @marabesi  @Manduro  @tobika  @lcaprini   I'm having the same issue after calling a modal page to add events as so:
`    modal.present();
    modal.onWillDismiss().then(() => { this.loadingController.loadingControllerPresent() })
    await modal.onDidDismiss().then(async x => {
      if (x.data) {
        let tmp: DiasFerias = x.data
        this.diaAdicionadoArray.push(tmp)
        this.events.push(tmp);
        this.myCalendar.loadEvents()
      }
      this.loadingController.loadingControllerDismiss()
    })`

As you can see i return value from modal, and add that value to eventSource. It adds correctly to the array of eventSource but it do not load the event on calendar. If I open and close the modal again, it loads the previous event but not the current.... Not understanding what is going on.
This is my calendar component `@ViewChild(CalendarComponent, null) myCalendar: CalendarComponent;`

**UPDATE** i think i found the problem:
Using this: 
`    var date = new Date(2020,2,11)
    let add = {
      allDay: false,
      title: "Férias",
      startTime: new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), 1)),
      endTime: new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), 11)),
      cor: "diaAdicionado",
    }
    this.diaAdicionadoArray.push(add)`

using directly numbers on var date it updates Calendar.
If i send a variable it will not as i explain above

**Comment by twinssbc** [comment]
@jcmendes9898 If that's the case, you need to check if tmp is a valid event, are the startTime and endTime fields of tmp really Date object?

**Comment by jcmendes9898** [comment]
@twinssbc It all checks, on my console.logs(). i follow the properties and all check. If it wasn't a date object  it would not load never. It just seems that it not reload component.

`add: {"allDay":false,"title":"Férias","startTime":"2020-03-11T01:00:00.000Z","endTime":"2020-03-11T11:00:00.000Z","cor":"anoAtual"}
ferias.page.ts:215 modal: {"allDay":false,"title":"Férias","startTime":"2020-03-16T01:00:00.000Z","endTime":"2020-03-16T11:00:00.000Z","cor":"diaAdicionado"}`

The add is with number like new Date(2020,2,11) and the modal is the one who is not loading

**Comment by jcmendes9898** [comment]
@twinssbc Can you sen an example of how you do it? You have a date in string. How would you proceed to add it to eventSource?

**Comment by twinssbc** [comment]
@jcmendes9898 
It depends on what format of your date string it is. Normally you can use the native Date.parse() function to parse the string into a Date object.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

If the format is unusual, you want want to parse it by yourself or use other third party tool.
