### ISSUE TITLE
Increase selectedTime precision in onTimeSelected

### ISSUE THREAD

**Issue by Titoch** [twinssbc/Ionic2-Calendar#275]
Hello,
In Week and Day views, it's possible to display events until 15 minutes precision using stepMinute=15.

Please, would it be possible to also adapt the time precision of event.selectedTime parameter of onTimeSelected() to stepMinute ?

The selectedTime would be adapted to the clicked position and rounded to stepMinute.

For example, if stepMinute is 15 : precision would be also 15 minutes : hh:00 | hh:15 | hh:30 | hh:45 and not only hh:00 as actually.

Then when user adds an event it would be possible to propose an event's startTime closer to the real clcked position.

**Comment by twinssbc** [comment]
@Titoch I don't think that kind of precision is necessary in a mobile device. The height of each cell is quite small.

**Comment by Titoch** [comment]
@twinssbc I aggree you for smartphone, But I think it's not the case on laptop browser with a mouse pointer and maybe also on tablet.

In fact my initial problem came from the fact that the onTimeSelected's parameter can supply a selectedTime out of a range of the supplied events in the same parameter.

For example : 
for function : onTimeSelected = (event: { selectedTime: Date, events: IEvent[] })
It's possible to obtain following values :
   -> event.selectedTime = 12h00
   -> event.events[0].startTime = 12h30.

The selectedTime is then out of the event's time range.
It can be a little confusing.

**Comment by twinssbc** [comment]
@Titoch 
The selected time is the hour on that cell. And the startTime is for individual events.
I don't think its confusing.
I still don't think it's necessary to select a time with that accuracy. Usually when user click on a cell, a time picker should be popped up to allow user adjust the time to second level.

**Comment by twinssbc** [comment]
@Titoch I got you, some one is working on a PR, let's see how it goes.
But one thing to be clear, even you use 15mins precision, you will still get 
-> event.selectedTime = 12h15
-> event.events[0].startTime = 12h18
It's not confusing. It's just different fields refer to different things. selectedTime means the time on the selected cell. The startTime is related to the individual events.

**Comment by Titoch** [comment]
@twinssbc 
Actually I'm limiting the precision of events to the calendar's one => 15min.
So (in my case) I can not have startEvent at 12:18. Events times minutes  are rounded to 15minutes (00 / 15 / 30 / 45).

But no matter. I modified my code's behavior to take into account the events starting during the following selectedTime hour (for example from 12:00 to 13:00, then startTime : 12:18 is taken into account).
I do no more use the supplied events in weekview and dayview (I launch my own search if needed). Only events supplyed in Monthview mode are ok in my case.
