### ISSUE TITLE
Detect eventType and show colors in days of month view.

### ISSUE THREAD

**Issue by Bohmaster** [twinssbc/Ionic2-Calendar#277]
Hi! I'm needing something like this:

Let's say some day of the month has multiple events. I want to check the type of those events and show in different colors if that day has one of more type of event inside.

I have 3 types of events. If day 20 has 6 events I only want to show the single type of events once. If in that day I have 3 events with type "A" I only want to show once that type "A" is in that day. If I have 20 events with all three events, I only want to show 3 div's with 3 different colors representing every event.

If I could get access to **view.dates[row*7+col].events** inside my component I could make it work. But I think I cant.

I hope you understand. Regards

**Comment by twinssbc** [comment]
@Bohmaster You could get access to the events.
If you use a custom template like this
```
        <template #template let-view="view" let-row="row" let-col="col">
            <div [ngClass]="getCustomClass(view.dates[row*7+col].events])"{{view.dates[row*7+col].label}}</div>
        </template>

        <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>
```
Then  you could implement getCustomClass in your component.

**Comment by Bohmaster** [comment]
Thank you for the response! I was on vacation so I missed the notification. I'll try it an will let you know how it was.
