### ISSUE TITLE
select multiple dates with pan/swipe gesture

### ISSUE THREAD

**Issue by uflicido-colina-MSD** [twinssbc/Ionic2-Calendar#280]
When you select a date in the calendar, by default, you do it by clicking a date.  I want to use another gesture.I want that the pan gesture to trigger the calendar onchange event emitter and execute the optionReason($event) method. Simply putting the same method in the two event will not enable the pan gesture to select a date.

.html
<div (pan)="optionReason($event)"> 
<ion-calendar  [(ngModel)]="dateMulti" (onChange)="optionReason($event)" (monthChange)="onMonthChange($event)"  [options]="optionsMulti" [type]="type" [format]="'YYYY-MM-DD'" ></ion-calendar>
</div>

.ts
pan(event: any){
//I want to trigger the  onchange event here and execute the method below.
  console.log("Pan!");

optionReason(){
console.log("reason option box appears");
  }

Thanks for the help.

**Comment by twinssbc** [comment]
@urfli911 The calendar doesn't have onchange event. I think you could use a custom template and add your gesture callback. You could get more details from the View Customisation section in README.

**Comment by urfli911** [comment]
I want to select multiple dates by dragging the mouse. All dates along the cursor's path will be selected. Here's the example https://fiddle.sencha.com/#fiddle/oi1&view/editor
I want to do it with typescript ionic app project. Thanks.

**Comment by twinssbc** [comment]
@urfli911 As I explained in the comment above, you need to use custom template. It requires quite big amount of code to achieve this drag and drop effect.
