### ISSUE TITLE
Feature Request: Add half and quarter hours in day/week view

### ISSUE THREAD

**Issue by centos94** [twinssbc/Ionic2-Calendar#282]
Hello!
I was trying to edit the code and make a pull request for this, but i get stucked in the event positioning.

What i was trying to do is let the user select the calendar visualization by hour, half our or quarter hour.
I was able to edit in _dayview.js_ and _weekview.js_ the method **createDateObjects** to show the rows like i need
<img src="https://user-images.githubusercontent.com/16610799/35442696-6f43aaa4-02a8-11e8-9280-532ddcb901e5.png" alt="WeekView" height="400" /><img src="https://user-images.githubusercontent.com/16610799/35442697-6f5f6668-02a8-11e8-8ad9-f2e3307db728.png" alt="DayView" height="400" />

What i've done here is adding a new property "minuteRange" into calendar template e passing it throught the weekview and day view.
Here the code i've edited 

[Code.zip](https://github.com/twinssbc/Ionic2-Calendar/files/1668047/Code.zip)

The problem here is that i'm not figuring out how to edit **onDataLoaded**, **calculatePosition** and **calculateWidth** methods to set events on the right line.
I have not really got what you do there, so i have no idea which changes are needed.

I hope you can help me in this!
Thank you in advance

**Comment by twinssbc** [comment]
@centos94 Actually you should modify the ts code, instead of the js code in the node_modules folder.
The js files are compiled using the ts code. The ts code are really the source code.
Once you've done the change, you could run `npm run build-prod` to generate the compiled files.

**Comment by centos94** [comment]
@twinssbc yes, sorry, i have write the wrong extension. If you open the [EditedCode.zip](https://github.com/twinssbc/Ionic2-Calendar/files/1672700/EditedCode.zip) there are the ts code files that i've edited

**Comment by centos94** [comment]
There is some way to handle this functionality? I'm not able to handle the event different size based on the selected range (15 or 30 minutes).

**Comment by twinssbc** [comment]
@centos94 Your feature requires relatively big code change. I'm a bit busy right now, probably starting from the week after next week, I could spend some time on this.

**Comment by centos94** [comment]
@twinssbc i understand.
I imagined that this wouldn't be easy.
I'll be certainly wait for this feature. If you could tell me something about it I can meantime try to figure out my self.

Thank you anyway for your time and thank you for the amazing plugin you shared with us.

**Comment by centos94** [comment]
Hello @twinssbc, I'm sorry for bother you. Have you already had time to watch for my request?
Thanks a lot.

**Comment by twinssbc** [comment]
@centos94 Yes, I almost finished the code change, now testing it. Probably will release it early next week.

**Comment by centos94** [comment]
@twinssbc awesome! Thank you so much!

**Comment by twinssbc** [comment]
@centos94 I have released the version supports half or quarter hours. You just need to add  [timeInterval]="30" in your html. You could get more details from README. Feel free to give a try.

**Comment by centos94** [comment]
@twinssbc thank you so much. I'll try it soon as possible!

**Comment by centos94** [comment]
@twinssbc tested and works like a charm! Thank you again!
