### ISSUE TITLE
I found this issue when i can add the module in my app

### ISSUE THREAD

**Issue by parmarkaushik15** [twinssbc/Ionic2-Calendar#283]
Error: Template parse errors:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    <ng-template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ERROR ->][ngOutletContext]="{view: views[0], row: row, col: col}">
                                </ng-templa"): ng:///NgCalendarModule/MonthViewComponent.html@17:32
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("          [ngClass]="getHighlightClass(views[0].dates[row*7+col])">
                                [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ngOu"): ng:///NgCalendarModule/MonthViewComponent.html@16:32
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("template [ngTemplateOutlet]="monthviewInactiveDisplayEventTemplate"
                                [ERROR ->][ngOutletContext]="{view: views[0], row: row, col: col}">
                                </ng-templa"): ng:///NgCalendarModule/MonthViewComponent.html@35:32
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("                           <td *ngFor="let col of [0,1,2,3,4,5,6]">
                                [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewInactiveDisplayEventTemplate"
                             "): ng:///NgCalendarModule/MonthViewComponent.html@34:32
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    <ng-template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ERROR ->][ngOutletContext]="{view: views[1], row: row, col: col}">
                                </ng-templa"): ng:///NgCalendarModule/MonthViewComponent.html@56:32
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("          [ngClass]="getHighlightClass(views[1].dates[row*7+col])">
                                [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ngOu"): ng:///NgCalendarModule/MonthViewComponent.html@55:32
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("template [ngTemplateOutlet]="monthviewInactiveDisplayEventTemplate"
                                [ERROR ->][ngOutletContext]="{view: views[1], row: row, col: col}">
                                </ng-templa"): ng:///NgCalendarModule/MonthViewComponent.html@74:32
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("                           <td *ngFor="let col of [0,1,2,3,4,5,6]">
                                [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewInactiveDisplayEventTemplate"
                             "): ng:///NgCalendarModule/MonthViewComponent.html@73:32
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    <ng-template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ERROR ->][ngOutletContext]="{view: views[2], row: row, col: col}">
                                </ng-templa"): ng:///NgCalendarModule/MonthViewComponent.html@95:32
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("          [ngClass]="getHighlightClass(views[2].dates[row*7+col])">
                                [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ngOu"): ng:///NgCalendarModule/MonthViewComponent.html@94:32
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("template [ngTemplateOutlet]="monthviewInactiveDisplayEventTemplate"
                                [ERROR ->][ngOutletContext]="{view: views[2], row: row, col: col}">
                                </ng-templa"): ng:///NgCalendarModule/MonthViewComponent.html@113:32
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("                           <td *ngFor="let col of [0,1,2,3,4,5,6]">
                                [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewInactiveDisplayEventTemplate"
                             "): ng:///NgCalendarModule/MonthViewComponent.html@112:32
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("/ion-slides>
            <ng-template [ngTemplateOutlet]="monthviewEventDetailTemplate"
            [ERROR ->][ngOutletContext]="{showEventDetail:showEventDetail, selectedDate: selectedDate, noEventsLabel: noEve"): ng:///NgCalendarModule/MonthViewComponent.html@122:12
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
                </ion-slide>
            </ion-slides>
            [ERROR ->]<ng-template [ngTemplateOutlet]="monthviewEventDetailTemplate"
            [ngOutletContext]="{showEv"): ng:///NgCalendarModule/MonthViewComponent.html@121:12
    at syntaxError (http://localhost:8100/build/vendor.js:91327:34)
    at TemplateParser.parse (http://localhost:8100/build/vendor.js:115190:19)
    at JitCompiler._parseTemplate (http://localhost:8100/build/vendor.js:124618:37)
    at JitCompiler._compileTemplate (http://localhost:8100/build/vendor.js:124593:23)
    at http://localhost:8100/build/vendor.js:124495:62
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:8100/build/vendor.js:124495:19)
    at http://localhost:8100/build/vendor.js:124365:19
    at Object.then (http://localhost:8100/build/vendor.js:91316:77)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:124364:26)

**Comment by parmarkaushik15** [comment]
My  app.module.ts file

import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    NgCalendarModule,
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

**Comment by parmarkaushik15** [comment]
Where i can put this 4 line ?
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';

I can run using ionic serve

**Comment by ketars** [comment]
npm install ionic2-calendar@0.4.2 --save solve this problem

**Comment by timofeysie** [comment]
I had the same issue occur after updating to Ionic 3.9 which uses Angular 5.0.  Doing ```npm install ionic2-calendar@0.4.2 --save``` did not resolve the situation.

**Comment by twinssbc** [comment]
@timofeysie You mean using ionic2-calendar@0.4.2 version doesn't help? Do you still get this exact same error?

> Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'

**Comment by timofeysie** [comment]
Yes, I was using version 0.4.2.  However, I switched back to my upgrade branch today to confirm and the project built and ran.  I can only assume that the previous version was cached and breaking the build yesterday.  Sorry for the trouble.

**Comment by iligzar** [comment]
@twinssbc ,
**Error**
[12:48:53]  typescript error  (" <calendar [ERROR ->][monthviewEventDetailTemplate]="templateApptCustom" [startingDayWeek]="2"   [startingDayMonth]="1" [eve") 

[12:48:53]  typescript error 
            (" <calendar [monthviewEventDetailTemplate]="templateApptCustom" [ERROR ->][startingDayWeek]="2" 
            [startingDayMonth]="1" [eventSource]="eventSource" [calendarMode]="calendar.mod") 

[12:48:53]  typescript error 
            (" <calendar [monthviewEventDetailTemplate]="templateApptCustom" [startingDayWeek]="2" [ERROR 
            ->][startingDayMonth]="1" [eventSource]="eventSource" [calendarMode]="calendar.mode" [currentDate]="cale") 

[12:48:53]  typescript error 
            ("ar [monthviewEventDetailTemplate]="templateApptCustom" [startingDayWeek]="2" [startingDayMonth]="1" [ERROR 
            ->][eventSource]="eventSource" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate" (onTi") 

[12:48:53]  typescript error 
            ("late]="templateApptCustom" [startingDayWeek]="2" [startingDayMonth]="1" [eventSource]="eventSource" [ERROR 
            ->][calendarMode]="calendar.mode" [currentDate]="calendar.currentDate" (onTitleChanged)="onViewTitleChan") 

[12:48:53]  typescript error 
            ("rtingDayWeek]="2" [startingDayMonth]="1" [eventSource]="eventSource" [calendarMode]="calendar.mode" [ERROR 
            ->][currentDate]="calendar.currentDate" (onTitleChanged)="onViewTitleChanged($event)" [dateF") 

[12:48:53]  typescript error 
            ("ode" [currentDate]="calendar.currentDate" (onTitleChanged)="onViewTitleChanged($event)" [ERROR 
            ->][dateFormatter]="calendar.dateFormatter" [locale]="calendar.locale" step="30" spaceBetween="10" class") 

[12:48:53]  typescript error 
            (" (onTitleChanged)="onViewTitleChanged($event)" [dateFormatter]="calendar.dateFormatter" [ERROR 
            ->][locale]="calendar.locale" step="30" spaceBetween="10" class="calendar"> </calendar> ") 

[12:48:53]  typescript error 
            (" [ERROR ->]<calendar [monthviewEventDetailTemplate]="templateApptCustom" [startingDayWeek]="2" 
            [startingDayMonth") 

Error: The Angular AoT build failed. See the issues above
    at /home/MYApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step /home/MYApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/home/MYApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/home/MYApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>

**package.json**

"dependencies": {
    "@angular/animations": "^6.0.2",
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/compiler-cli": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/forms": "5.0.1",
    "@angular/http": "5.0.1",
    "@angular/platform-browser": "^5.2.11",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@ionic-native/app-preferences": "^4.7.0",
    "@ionic-native/background-mode": "^4.7.0",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/firebase": "^4.7.0",
    "@ionic-native/http": "^4.7.0",
    "@ionic-native/keyboard": "^4.7.0",
    "@ionic-native/local-notifications": "^4.7.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/sqlite": "^4.7.0",
    "@ionic/storage": "^2.1.3",
    "acorn": "^5.5.3",
    "cordova-android": "6.3.0",
    "cordova-plugin-advanced-http": "^1.11.1",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-file": "^5.0.0",
    "cordova-plugin-firebase": "^1.0.5",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.3.1",
    "date-fns": "^1.29.0",
    "emulate": "1.0.2",
    "intl": "^1.2.5",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-calendar": "^0.4.3",
    "ionicons": "^3.0.0",
    "localforage": "^1.7.1",
    "localforage-cordovasqlitedriver": "^1.7.0",
    "moment": "^2.22.1",
    "rollup": "^0.52.3",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "x2js": "~3.1.1",
    "zone.js": "0.8.18"
  },

**Comment by iligzar** [comment]
@twinssbc , i'm fix it.
add _NgCalendarModule_ to _pagename_.module.ts  
imports: [
    IonicPageModule.forChild(SchedulesPage),
    NgCalendarModule
  ],
