### ISSUE TITLE
Customise background color event in dayly and weekly view

### ISSUE THREAD

**Issue by davart87** [twinssbc/Ionic2-Calendar#285]
Hello,
I want to know how can I customise background color event in week and dayly view.
Without override the existing [ngStyle] ?

Thanks

**Comment by twinssbc** [comment]
@davart87 You could just override styles on the css class.
For example, each event has a calendar-event-inner class, you just need to set the background-color on it.
```
.calendar-event-inner {
          background-color: red;
        }
```

If you want to set different background color based on different kind of events, then you need to take a look at the View Customisation section in README to define some customized template.
