### ISSUE TITLE
Can we set from date and to date into ion2-calendar?(Specific to date range feature)

### ISSUE THREAD

**Issue by krunal9421** [twinssbc/Ionic2-Calendar#287]
I am having two date which i want to set in ion2-calendar. But I am unable to set two date into date range feature.

**Comment by twinssbc** [comment]
@krunal9421 I don't quite understand your question. What date range feature are you referring to?

**Comment by krunal9421** [comment]
@twinssbc yes, I want to set two specific dates into date range feature.

**Comment by twinssbc** [comment]
@krunal9421 What is date range feature?

**Comment by krunal9421** [comment]
![screenshot-www libhive com-2018 02 09-08-35-22](https://user-images.githubusercontent.com/33853304/36009853-3ba29b16-0d74-11e8-928b-20ebcaf7bf58.jpeg)
like the picture above we can select two dates in single calendar.
I am asking can we set two dates into ion2-calendar.

**Comment by twinssbc** [comment]
@krunal9421 This is not the repository of ion2-calendar.
You could create issue under
https://github.com/HsuanXyz/ion2-calendar

**Comment by twinssbc** [comment]
@jayzyaj The date range feature discussed here is not related to my project. You could check 
https://github.com/HsuanXyz/ion2-calendar
