### ISSUE TITLE
Can add icon in weekview and dayview ? 

### ISSUE THREAD

**Issue by ramaprakoso** [twinssbc/Ionic2-Calendar#289]
I was sucess to add icon on monthview like this 

![capture](https://user-images.githubusercontent.com/6641354/35787208-1f070978-0a5f-11e8-8d0e-def87d574529.PNG)

But i found problem when try to add icon into weekviw and dayview, because in weekview and dayview only show title. 
![image](https://user-images.githubusercontent.com/6641354/35787239-506aa7a4-0a5f-11e8-8424-07314c08a962.png)

is there a solution to this problem ? thank you

**Comment by twinssbc** [comment]
@ramaprakoso Yes, you can. Take a look at weekviewNormalEventTemplate and dayviewNormalEventTemplate options in README.
