### ISSUE TITLE
Can I change default configuration?

### ISSUE THREAD

**Issue by marticrespi** [twinssbc/Ionic2-Calendar#29]
Hi,

I would like to know if this is possible:

1) Show day titles in another language.
2) Disable past days
3) Set start day of week to monday.
4) Disable the saturdays and sundays.

Someone can help me?

Thanks!

**Comment by marticrespi** [comment]
> startingDayWeek
Control week view starting from which day.
Default value: 0

I have this in my ts file

    calendar = {
    	mode: 'month',
    	currentDate: new Date(),
    	startingDayWeek : 1
    };

And in my html file

    <calendar [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [startingDayWeek] = "calendar.startingDayWeek"
    [currentDate]="calendar.currentDate"
    (onCurrectDateChanged)="onCurrentDateChanged($event)"
    (onRangeChanged)="reloadSource(startTime, endTime)"
    (onEventSelected)="onEventSelected($event)"
    (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)"
    step="30">
    </calendar>

If the default value is 0 (sunday) with 1 should show me the calendar starting in monday, isnt it?

**Comment by twinssbc** [comment]
@marticrespi 
1. The DatePipe in Angular2 uses Intl to achieve i18n. The title should already be translated to your local language. But I also found that Intl doesn't do the good job for some language. Did you meet any difficulty to format the title?
2&4 I just added markDisabled option in the latest 0.0.16 version. Feel free to have a try.
3. You can put [startingDayWeek]="1" in the html file.

**Comment by marticrespi** [comment]
Hi @twinssbc 

I have tried again and anything has changed.

    <calendar [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    		[startingDayWeek] = 1
    [currentDate]="calendar.currentDate"
    (onCurrectDateChanged)="onCurrentDateChanged($event)"
    (onRangeChanged)="reloadSource(startTime, endTime)"
    (onEventSelected)="onEventSelected($event)"
    (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)"
    step="30">
    </calendar>

But my calendar still start on sunday. And your variable defined as viewTitle is well translated, but days of week is still in english. I use Int 1.2.5 as you suggested

Here is my calendar

https://i.imgbox.com/2vUxizjW.png

I just updated your library, i will try markDisabled option and let you know.

Thanks for your great job!

Kind Regards!

**Comment by marticrespi** [comment]
Hi @twinssbc 

Reviewing your sourcode in src/calendar.ts file:

    <div [ngSwitch]="calendarMode">
    <monthview *ngSwitchCase="'month'"
    	[formatDay]="formatDay"
    	[formatDayHeader]="formatDayHeader"
    	[formatMonthTitle]="formatMonthTitle"
    	[startingDayMonth]="startingDayMonth"
    	[showEventDetail]="showEventDetail"
    	[noEventsLabel]="noEventsLabel"
    	[eventSource]="eventSource"
    	[markDisabled]="markDisabled"
    	(onRangeChanged)="rangeChanged($event)"
    	(onEventSelected)="eventSelected($event)"
    	(onTimeSelected)="timeSelected($event)"
    	(onTitleChanged)="titleChanged($event)">
    </monthview>
    <weekview *ngSwitchCase="'week'"
    	[formatWeekTitle]="formatWeekTitle"
    	[formatWeekViewDayHeader]="formatWeekViewDayHeader"
    	[formatHourColumn]="formatHourColumn"
    	[startingDayWeek]="startingDayWeek"
    	[allDayLabel]="allDayLabel"
    	[hourParts]="hourParts"
    	[eventSource]="eventSource"
    	[markDisabled]="markDisabled"
    	(onRangeChanged)="rangeChanged($event)"
    	(onEventSelected)="eventSelected($event)"
    	(onTimeSelected)="timeSelected($event)"
    	(onTitleChanged)="titleChanged($event)">
    </weekview>
    <dayview *ngSwitchCase="'day'"
    	[formatDayTitle]="formatDayTitle"
    	[formatHourColumn]="formatHourColumn"
    	[allDayLabel]="allDayLabel"
    	[hourParts]="hourParts"
    	[eventSource]="eventSource"
    	[markDisabled]="markDisabled"
    	(onRangeChanged)="rangeChanged($event)"
    	(onEventSelected)="eventSelected($event)"
    	(onTimeSelected)="timeSelected($event)"
    	(onTitleChanged)="titleChanged($event)">
    </dayview>
    </div>

In month case template, I think you forget to include [startingDayWeek]="startingDayWeek" as weekview, because if I try it with CalendarMode='week' it starts on monday, in fact if I use month calendar mode, always set as sunday as default value.


Kind regards!

**Comment by twinssbc** [comment]
@marticrespi There's startingDayMonth option for month view

**Comment by marticrespi** [comment]
You're right @twinssbc , but we was always talking about "startingDayWeek" I thought they are not the same option.

Another thing than I have seen:

If I don't set an eventSource (default = null, removing [eventSource]="eventSource" in html file) or I set showEventDetail=false, should not it exclude ion-list div (ion-list events) when is rendering the calendar? Is it include anyway?

https://i.imgbox.com/PWWaFtrF.png

**Comment by twinssbc** [comment]
If you set [showEventDetail]="false", the event detail list won't display.

**Comment by marticrespi** [comment]
Yes @twinssbc, but the div returned not fit properly, its remembering the size of events list.

With  [showEventDetail]="false" It shows this:

https://i.imgbox.com/cVavrBTN.png

But for me should be displayed like this:

https://i.imgbox.com/0HXTYNVy.png

**Comment by twinssbc** [comment]
@marticrespi 
Yes, I set the view container to 100% height to support the scrolling list in the week and day view. I added some css class to the view container in the version 0.0.17. So you can change the height of monthview-container class. 
In this version, I also make the disabled date not selected.
Feel free to have a try.

**Comment by marticrespi** [comment]
Hi @twinssbc 

Both changes works like a charm! You are doing a great job!

I only use monthview because I need to show a selectable checkbox list. If your EventSource could include a boolean property like isAvailable and EventList displays a checkbox to be selectable I could use your monthview with Events, meantime I have to use the monthview without events but I would like to use your fully library. 

Perhaps you can consider it as enhancement for the future.

By the way, could you investigate something about "Intl" to can fully translate the calendar in all languages? It's very strange ..

Many thanks for your work!

Kind regards,
Marti.

**Comment by marticrespi** [comment]
Hi @twinssbc 

You have marked disabled date as not selectable, but when you click on it, the day is changing, it fires the function onTimeSelected(ev) and current selected date changes. It would be possible avoid this?

Or is there any function to get the current selected date property disabled to know it status?

Thanks.

**Comment by marticrespi** [comment]
Hi @twinssbc 

If I am 22nd december and slide to january, it goes to 22nd directly, but 22nd january for me is disabled (I have disabled sundays). I think that when you slides you are doing `AddMonth (1)` directly, but is possible to check disabled property before addMonth and goes, for example, to next or previous avaiable day?

**Comment by twinssbc** [comment]
@marticrespi I added logic to not select disabled date when moving to previous/next month. Going to next/previous available day is a too specific requirement. Also considering some user requires disable all past days until today, there will be no available days. So I just simply not select the disabled date. 
Feel free to have a try.

**Comment by marticrespi** [comment]
@twinssbc 

Works perfectly! I said previous or next available day to say something, your logic applied is perfect, not change selected date if the day in next/previous month is disabled.

**Comment by marticrespi** [comment]
Hi @twinssbc 

Could you investigate about Intl translation? I have viewTitle well translated in spanish but day names are in english..

Many thanks!

**Comment by twinssbc** [comment]
@marticrespi I fixed the day headers in version 0.1.2. Could you have a try?

**Comment by marticrespi** [comment]
Hi @twinssbc 

I had modified forcing my locale to es-ES with following code in app.module.ts

    import { LOCALE_ID } from '@angular/core';

    providers: [
    // other providers
      { provide: LOCALE_ID, useValue: "es-ES" }, //replace "es-ES" with your locale
    ]

I have removed this code and with your new version works without above code.

I have a little problem with header style

https://i.imgbox.com/3aPQqfJE.png

in spanish is translated with final dot), only I have to overwrite ,small class with a minor % value

		small {
 		   font-size: 69%;
		}

https://i.imgbox.com/Y7Gxu00G.png

Many thanks for all your hard work!

**Comment by twinssbc** [comment]
@marticrespi Is "EEEEE" supported by the Angular2 DatePipe? From below page, I can see it only supports "EEE" and "EEEE"
https://angular.cn/docs/ts/latest/api/common/index/DatePipe-class.html

To only display the first capital letter, you probably need to modify the source code to update the expression like below

```
    <th *ngFor="let dayHeader of view.dayHeaders">
        <small>{{dayHeader.toUpperCase().substring(0,1)}}</small>
    </th>
```

**Comment by marticrespi** [comment]
Yes @twinssbc you're right, but in angular.io domain shows that with E only should show the first letter

https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html

But don't worry, I will decrease the small % class and I will use your default format! I dont want modify your source code, because I will have to change on every update! 

Many thanks!

**Comment by RS-Shekhawat** [comment]
@twinssbc Can I add next previous buttons in the calendar directive

**Comment by twinssbc** [comment]
@RS-Shekhawat, where do you want to add next, previous button? If you want to add them in the header bar, Ionic framework already provides that capability.
If you want to embed them into the calendar, you may need some customization of the view or the code.
But it already provided the default swipe interaction, not sure if extra navigation button is a bit duplicate.

**Comment by RS-Shekhawat** [comment]
Actually @twinssbc I want to convert swipe interaction with next previous button so user can see next month or previous month through these buttons so in that calendar could I customize its config options like "calendar = {
      mode: 'month',
      currentDate: new Date()
  };"

**Comment by RS-Shekhawat** [comment]
Actually @twinssbc I want to convert swipe interaction with next previous button so user can see next month or previous month through these buttons so in that calendar could I customize its config options like "calendar = {
      mode: 'month',
      currentDate: new Date()
  };"

is any options there for next, previous button? Or where we need to change the code could you help me for this.

Thanks!

**Comment by twinssbc** [comment]
@RS-Shekhawat
The header is the Ionic header bar or the one in the calendar itself.
If it's the Ionic header bar, then it's easy. You can add the button and change the calendar.currentDate in the click callback. The calendar will navigate to the date you set.
If you want to add a header in the calendar, then source code change is required.

**Comment by twinssbc** [comment]
@RS-Shekhawat You can take a look at the Today button logic in the demo page.
That button is used to set the calendar to today. Basically you just need to set the calendar to a date in next or previous month.

**Comment by RS-Shekhawat** [comment]
Thanks, @twinssbc It is very helpful suggestion for me its working nice

Thank you so much !!

**Comment by chanphillip** [comment]
Hi
I couldn't make the i18n work. I want to force it to be in English.
I've added `{ provide: LOCALE_ID, useValue: "en-US" }` to app.module.ts providers, but it is still showing the week days in my local language.

**Comment by dualshote** [comment]
Same for me in France : 
`{ provide: LOCALE_ID, useValue: "fr-FR" }` Thx guys 👍

**Comment by twinssbc** [comment]
@dualshote Do you have problem to display the calendar in French or not?

**Comment by EdgarBaeza13** [comment]
How can i translate the values of the calendar to spanish? I've already tried the same that all of you say in the comennts but it doesn´t work

**Comment by twinssbc** [comment]
@EdgarBaeza13 Could you provide your code?

**Comment by SergiCanal** [comment]
Hi @twinssbc thanks for that amazing component.
Do you know if there is any way to translate the calendar to Catalan?

Thank you very much!

**Comment by twinssbc** [comment]
@SergiCanal I believe so, you could refer to **Localization** section in README for more details. If you have further question, please create a separate issue.

**Comment by JaumeBoschAnglada** [comment]
> Hi @twinssbc thanks for that amazing component. Do you know if there is any way to translate the calendar to Catalan?
> 
> Thank you very much!

Hi Sergi, did you success on translate the calendar to Catalan?
