### ISSUE TITLE
Any option to hide weekends in week view

### ISSUE THREAD

**Issue by Vohidjon** [twinssbc/Ionic2-Calendar#290]

**Comment by twinssbc** [comment]
@Vohidjon Unfortunately no such option to support hiding weekends.

**Comment by mautenrieth** [comment]
Hi all,

is it still not possible to hide the weekend days in week view? (i.e. with the attribut weekend like in https://fullcalendar.io/docs/weekends).
If no, does anyone know which files have to be changed? 

Thx in advance!
Cheers, Max
