### ISSUE TITLE
In weekview, the event at 11:00am to 11:30am spreads over till 12:00am

### ISSUE THREAD

**Issue by anytimegorgeous** [twinssbc/Ionic2-Calendar#291]
First all, what an amazing module you have built. Thank you for sharing!
So, I noticed there's a very peculiar error that happens in week view. When a half an hour event is added at 11:00 - 11:30, weekview displays it incorrectly. Instead it displays it as a 11:00-12:00am event. In month view and day view this is not a problem and the correct event is displayed.
Can you please fix this or just me how can I fix it myself?

Thanks,
Sia

**Comment by twinssbc** [comment]
@anytimegorgeous 
So by default, the event is display on an hour interval, which means event it's an event starting from 11:00-11:01, it will occupy the whole slot.
If you set the 'step' option to 15 or 30, to display the event in 15 or 30 mins interval.
But it seems from your description, you already set the 'step' option to 30? What's the exact startTime and endTime of your event? Do you mean in dayview, the event actually didn't displayed as 11:00-12:00 event?

**Comment by anytimegorgeous** [comment]
@twinssbc
I understand that. I have set the 'step' to 30.
The exact time of my event is 11pm to 11:30 pm. You can replicate the error yourself by creating any event from 11pm-11:30pm. The error only occurs at this time, it works fine otherwise.
In the dayview and monthview there is no error.  It correctly displays the event from 11pm to 11:30pm. However, in weekview it displays it as 1 hour event from 11pm to 12am. The error only happens in weekview for events that range from 11pm to 11:30pm.
I think the error is an edge case scenario caused by the date change at 12am. I am not sure though.

**Comment by twinssbc** [comment]
@anytimegorgeous 
Actually below code works for me. Is it possible that you have some value on second or millisecond part?
```
    var start1 = new Date(Date.UTC(2018, 1,12));
    var end1 = new Date(Date.UTC(2018, 1, 12));
    start1.setHours(11,0,0,0);
    end1.setHours(11,30,0,0);

    events.push({
      title: 'test1',
      startTime: start1,
      endTime: end1,
      allDay:false
    });
```

**Comment by anytimegorgeous** [comment]
Please set hours to 23:00. 11:00pm has the problem not am.
    start1.setHours(23,0,0,0);
    end1.setHours(23,30,0,0);

**Comment by twinssbc** [comment]
@anytimegorgeous I can confirm this is a bug, will fix it in the next version.

**Comment by anytimegorgeous** [comment]
Thank you so much! The fix will be really helpful for me!

I have one more question unrelated to this -

In this code 
<calendar  (onTimeSelected)="onTimeSelected($event)" </calendar> 

Can (onTimeSelected) be extended to other gestures like 'press' gesture or 'swipe' gesture? Currently it only works for 'click' or 'tap' gesture.

**Comment by twinssbc** [comment]
@anytimegorgeous No, it doesn't support other gesture. But you could use custom template and add other gesture support in the template.

**Comment by twinssbc** [comment]
@anytimegorgeous I have fixed this bug in the latest version. Feel free to give a try.

**Comment by anytimegorgeous** [comment]
Thank you so much. This is much appreciated!!
