### ISSUE TITLE
setting starttime and endtime calendar activity 

### ISSUE THREAD

**Issue by ramaprakoso** [twinssbc/Ionic2-Calendar#293]
can i read date in current time  (timestamp) ? 
![image](https://user-images.githubusercontent.com/6641354/35968795-6de4ab0a-0cf7-11e8-8dfb-7a58fea5ae3d.png)
the date is suitable in current date, but the calendar time in hour starting from 00.00, can i change , following current time (timestamp) ? thank you

**Comment by twinssbc** [comment]
@ramaprakoso Sorry, are you using this calendar control? The screenshot you provided seems like a date picker?
