### ISSUE TITLE
Customize hour column in day view 

### ISSUE THREAD

**Issue by Nik01992** [twinssbc/Ionic2-Calendar#294]
Hey thanks for the great work man.I would like to customize the hour view column in day and week view.Below is my requirements:
I would like to show every hour like 1:10,1:20,1:40,2:00. currently i cant split my hours.
Please help with this.if there is any way.I have tried formatDayViewHourColumn too.But no help.
Thanks

**Comment by twinssbc** [comment]
@Nik01992 Sorry, it doesn't provide this kind of customization. It seems you don't want to evenly split the hour, like every 15 mins or 30 mins?

**Comment by Nik01992** [comment]
can we do that..?? evenly split the hour..??

**Comment by twinssbc** [comment]
@Nik01992 You just want to display the hour column like 12:00, 12:30 or, you want the events could be placed as half hour. If that's the latter case, there's already a "step" option allows you to do this.

**Comment by Nik01992** [comment]
i want to display the hour column like 12:00,12:30
