### ISSUE TITLE
expand the weekly column html

### ISSUE THREAD

**Issue by ramaprakoso** [twinssbc/Ionic2-Calendar#295]
excuse me, i want to resize the default column wide, to more wider like this 
![image](https://user-images.githubusercontent.com/6641354/36138582-8979adec-10cc-11e8-9ce9-503f5d685a02.png)
can custom the css and html ? thank you

**Comment by twinssbc** [comment]
@ramaprakoso So the first hour column is fixed, and the rest column occupies the rest space evenly.
Which column do you want to resize? 
The first hour column is 50px width by default, you could override the css to change the width as below.

```
        .calendar-hour-column {
          width: 30px;
        }

        .weekview-allday-label {
          width: 50px; 
        }

        .weekview-allday-content-wrapper {
          margin-left: 30px;
        }

        [dir="rtl"] .weekview-allday-content-wrapper {
          margin-right: 30px;
        }
```

**Comment by ramaprakoso** [comment]
thank you mr, i want resize all column in week day column and hour column, i try hour column success to change , but days not yet .

**Comment by twinssbc** [comment]
@ramaprakoso How do you want to resize the day column? As I said the other columns will occupy the rest space evenly.
