### ISSUE TITLE
Select style on monthly view depending on the events

### ISSUE THREAD

**Issue by jalogar** [twinssbc/Ionic2-Calendar#296]
Hello,

I'm trying to use the calendar to show a monthly view. As usually there are many events per fay, I'd like to, instead of showing all the events of the day, change the style of the day depending on the events of that day. Is it possible? Could you please advice me?

Thanks in advance

**Comment by twinssbc** [comment]
@jalogar Yes, you could use the monthviewDisplayEventTemplate option.
For example,

In html,
```
        <template #template let-view="view" let-row="row" let-col="col">
            <div [ngClass]="getCustomClass(view.dates[row*7+col].events)">{{view.dates[row*7+col].label}}</div>
        </template>

        <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>
```
In component, you just need to implement the getCustomClass method, the argument is the events on that day.

**Comment by jalogar** [comment]
Thanks for the response, it worked fine. For the record, correct element is **ion-template** instead of template.
