### ISSUE TITLE
Changing of color in dayview event task

### ISSUE THREAD

**Issue by robertrobertlow** [twinssbc/Ionic2-Calendar#297]
Hi, can I change the color for the event in each hour? 
I really not sure how to do it.
Anything helps thankyou.

**Comment by twinssbc** [comment]
@robertrobertlow Do you mean the color of each event or the color of this hour cell? Customizing the color of hour cell is not supported yet. To customize the color of each event, you could take a look at dayviewNormalEventTemplate option in README.

**Comment by robertrobertlow** [comment]
I meant each hour could have many events. So I would like to change the color of each event in the hour.

**Comment by robertrobertlow** [comment]
I applied, " <template #template let-displayEvent="displayEvent">
            <div class="calendar-event-inner">{{displayEvent.event.title}}</div>
        </template>"

However, there is an error of "[Angular  "let-" is only supported on ng-template elements]"

**Comment by twinssbc** [comment]
@robertrobertlow This is because the template syntax is changed back and forth between Angular versions. You could use ng-template to get rid of the error.

You could assign a custom property to each event.
Then use below way to trigger a custom method to return the css class based on that property.
```
        <ng-template #template let-displayEvent="displayEvent">
            <div class="calendar-event-inner" [ngClass]="getCustomClass(displayEvent.event.customProperty)">{{displayEvent.event.title}}</div>
        </ng-template>
```

**Comment by robertrobertlow** [comment]
Sorry I am really new to ionic. I do not understand the meaning of custom property and ng-template
