### ISSUE TITLE
API load events

### ISSUE THREAD

**Issue by robertrobertlow** [twinssbc/Ionic2-Calendar#298]
Hi twinssbc, How can I display my events data from API into the calendar?

**Comment by twinssbc** [comment]
@robertrobertlow I assume you mean your API will retrieve the data from the backend? The calendar only cares about the eventSource array, you just need to transform your backend data and fill them into the eventSource array. You could get some idea from the sample and the README.

**Comment by robertrobertlow** [comment]
So does that means, I do not need endTime? SInce I do not need endTime

**Comment by twinssbc** [comment]
@robertrobertlow Yes, you need endTime. Why you don't need endTime? An event must have a start time and end time?
