### ISSUE TITLE
Want to open popup on click on Date block 

### ISSUE THREAD

**Issue by Anujmoglix** [twinssbc/Ionic2-Calendar#299]
I want to Open popup when i click on any date . SO i can handle some ajax call with that . But i am not able to get any method for that . Can anyone suggest me for that.

**Comment by twinssbc** [comment]
@Anujmoglix Have you tried onTimeSelected method?

**Comment by Anujmoglix** [comment]
I did with click function , actually at that i want to do this to share event data . that issue has been fixed ,

**Comment by Anujmoglix** [comment]
I did with click function , actually at that i want to do this to share event data . that issue has been fixed ,
