### ISSUE TITLE
Want to remove previous date and next date from calendar.

### ISSUE THREAD

**Issue by Anujmoglix** [twinssbc/Ionic2-Calendar#300]
Hi,
  I want to remove previous date and next date from calendar , because i don't want to swipe  calendar from clicking on previous month date or next month date. I am handling that with  function  .So can any on guide me for that ?

**Comment by twinssbc** [comment]
@Anujmoglix You could use markDisabled method to disable the dates in previous/next month.

**Comment by Anujmoglix** [comment]
Hi ,
 I tried that but it is just disabling that date but i am able to click on that. I want not to click on disabled date .
![selection_098](https://user-images.githubusercontent.com/26056096/36482258-b8adb06e-1738-11e8-9265-a49a5610c8d1.png)

**Comment by Anujmoglix** [comment]
Still waiting for your solution . it would be good if that previous and next month date will not show .

**Comment by twinssbc** [comment]
@Anujmoglix Yes, you will still be able to click it, but it won't jump to the previous/next month. In the onTimeSelected method, you could simply skip that event, if it's disabled.
To not display the dates, you need to use custom template, monthviewDisplayEventTemplate.

```
    onTimeSelected(ev) {
        if (ev.disabled) {
                //skip
        }
    }
```

**Comment by Anujmoglix** [comment]
I really don't know what you have shared with me but i did it with some css , I just disabled it but it is not removing my whole problem , Now one issue is that bottom line ,It is adding one more row because data is there ,

**Comment by twinssbc** [comment]
@Anujmoglix The month view always have 6 rows. You may think the last row is not necessary for this month, but in some month, the calendar will need to occupy 6 rows. Unfortunately it can't be fixed by just adjusting the height and margin-top in css to remove that gap. So I suggest still display the dates, but using some css to show that date is disabled, such as grey text or grey background.
