### ISSUE TITLE
Is step="value" working?

### ISSUE THREAD

**Issue by Astacius** [twinssbc/Ionic2-Calendar#301]
I am trying to set the week view every 2 hours instead of 1, what am I suppose to do with step to achieve this?
I have already tried:
```
step="60"
step="120"
step="30"
step="15"
[step]="30"
```
etc.

**Comment by twinssbc** [comment]
@Astacius 2 hours is not supported. Only 15, 30 and 60. For example,
```
    <calendar ...
              step="30">
    </calendar>
```

**Comment by Astacius** [comment]
Hello, is there any way to achieve week view every 2 hour?

**Comment by twinssbc** [comment]
@Astacius Unfortunately it's not possible unless modifying the source code.

**Comment by Astacius** [comment]
Could you tell me which file should I edit?

**Comment by twinssbc** [comment]
@Astacius To achieve your requirement requires quite big amount of code change.
If you really want to modify the source code, you could start with weekview.ts.
createDateObjects method is responsible for generating the data objects to be used to render the weekview table.
onDataLoaded method is the main method to decide how to place the events on the weekview table.
You may search for "24", as the weekview logic is based on 24 hours, for example, it will generate 24 rows. If you use 2 hours as interval. You may adjust it accordingly.

**Comment by twinssbc** [comment]
@Astacius I have released a new version could meet your requirement. You could add [timeInterval]="120" in your html. More details could be found in README. Feel free to have a try.

**Comment by Astacius** [comment]
Thank you so much for this

**Comment by Astacius** [comment]
@twinssbc I have installed version 0.3.14 and it seems not working? This is my code:
`  <calendar [eventSource]="events" [startingDayWeek]="1" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate"
    (onCurrentDateChanged)="onCurrentDateChanged($event)" (onEventSelected)="onEventSelected($event)" (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)" [scrollToHour]=6 [monthviewEventDetailTemplate]="monthEventsDetail"
    [weekviewNormalEventTemplate]="weekEvents" [dayviewNormalEventTemplate]="dayEvents" step="60" [timeInterval]="120">
  </calendar>`

**Comment by twinssbc** [comment]
@Astacius I will fix it.

**Comment by Astacius** [comment]
@twinssbc Hello. How is it going?

**Comment by vitorlgomes** [comment]
I'm not getting the 2 hours interval when setting it to 120, @Astacius @twinssbc  you got it ?

**Comment by Astacius** [comment]
@vitorlgomes nope, it doesn't work

**Comment by twinssbc** [comment]
@Astacius @vitorlgomes I just published the fix. Feel free to have a try.

**Comment by Astacius** [comment]
@twinssbc but the last commit was 22 days ago, how then?

**Comment by Astacius** [comment]
@twinssbc now everything works fine, thanks!
