### ISSUE TITLE
Change dynamically color in dayview and weekview event task

### ISSUE THREAD

**Issue by GrazianoMarco** [twinssbc/Ionic2-Calendar#302]
Hi, can I change dinamically the color of events in dayview and weekview?
I can change monhtview in this way but i can't in the other.
This is my code for monthview.

<ng-template #templateMonth let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
  <ion-list *ngIf="showEventDetail" no-lines>
    <ion-item color="{{event.color}}" *ngFor="let event of selectedDate?.events" (click)="onEventSelected(event)">
      <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}} - {{event.endTime|date: 'HH:mm'}}
      </span>
      <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn"><span style="height: 10px;width:25px;" class="{{color}}"></span>24H</span>
      <span *ngIf="event.title" class="event-detail"> | {{event.title}} -</span>
      <span *ngIf="event.description" class="event-description"> {{event.description}}</span>
    </ion-item>
    <ion-item *ngIf="selectedDate?.events.length==0">
      <div class="no-events-label">{{noEventsLabel}}</div>
    </ion-item>
  </ion-list>
</ng-template>

**Comment by twinssbc** [comment]
@GrazianoMarco 
You could use weekviewNormalEventTemplate and dayviewNormalEventTemplate
You could give your event a custom field, for example, customProperty.
Then in the template, pass it to getCustomClass to generate some dynamic css class.
```
 <ng-template #template let-displayEvent="displayEvent">
            <div class="calendar-event-inner" [ngClass]="getCustomClass(displayEvent.event.customProperty)">{{displayEvent.event.title}}</div>
        </ng-template>
```

**Comment by GrazianoMarco** [comment]
Thank for your answer.
I try to use your code in mine but ionic give me an error "_co.getCustomClass is not a function".
My code is:
<ng-template #templateWeek let-displayEvent="displayEvent">
  <div class="calendar-event-inner" [ngClass]="getCustomClass(displayEvent.event.color)">{{displayEvent.event.title}}</div>
</ng-template>
 where "displayEvent.event.color" is he color I like to use for background es . "Pink"

**Comment by twinssbc** [comment]
@GrazianoMarco You need to implement getCustomClass in your component ts file.

**Comment by GrazianoMarco** [comment]
@twinssbc Sorry but I can't undestrand what you mean

**Comment by twinssbc** [comment]
@GraziaoMarco
getCustomClass should be a method in your component.
Let's say your html look as below
```
 <ng-template #template let-displayEvent="displayEvent">
            <div class="calendar-event-inner" [ngClass]="getCustomClass(displayEvent.event.customProperty)">{{displayEvent.event.title}}</div>
        </ng-template>
```
In your component file, you need to implement getCustomClass.
```
    getCustomClass(someParameter) {
        return 'red';
    }
```

This method doesn't have to be called getCustomClass, it could be any name.
Hope the Angular doc could give you an idea.
https://angular.io/api/common/NgClass

**Comment by sidoineAdanz** [comment]
that works for me. thanks

**Comment by jyothimarkal** [comment]
Hi,
am facing the same problem and not able to add custom design and events to weeklyview.
