### ISSUE TITLE
DateTime format for eventsource

### ISSUE THREAD

**Issue by ghost** [twinssbc/Ionic2-Calendar#303]
Hi, I have push my date time (from API) into the events. However, it is not showing. I had looked into the format of yours and I guess it's my format wrongly set. Can you elaborate your dateTime? Thankyou.

"startTime = new Date(date.getFullYear(), date.getMonth(), date.getDate() + startDay, 0, date.getMinutes() + startMinute);" 

my typescript

        loadEvents() {
            this.eventSource = this.getJSON();
        }

       getJSON(){
        .......
        var events = [];
        for (let i = 0; i < data.length; i++) {
          console.log('appt JSON: ' + JSON.stringify(data[i]));

          var date = data[i].date;
          var time = data[i].time;
          var startDate = data[i].startDate;

          console.log('this is the date: ' + new Date(date));
          console.log('this is the date: ' + time);
          console.log('this is the date: ' + new Date(startDate));
          console.log('this is the status: ' + status);
          console.log('');

          events.push({
            title: events,
            startTime: date,
            endTime: date ,
            allDay: false,
          })
          console.log(events);
        } 
       }

![githubhelp](https://user-images.githubusercontent.com/35058130/36650675-aa824d38-1adf-11e8-96b3-18c1d54e1422.png)

**Comment by twinssbc** [comment]
@robertrobertlow you need to set a Date object to startTime and endTime. It seems it is a String right now?

**Comment by robertrobertlow** [comment]
Yes, thankyou so much, how why does the calendar events does not appear in dailyview and weekly view? Anything I missed out

**Comment by robertrobertlow** [comment]
Update: I have tried to do some changes and the output does not display. Anything I done wrongly?
```
 var date = data[i].date;
 var time = data[i].time;
 var startTime = moment(date).format('L') +' '+time;
 console.log(startTime);

 var endTime = moment(startTime).add(15,'minutes').calendar();
 console.log(endTime);
          events.push({
            title: 'Patient Id: ' + patientId + ',' + ' ' + ' ' + ' ' + 'Status: '+ status,
            startTime: new Date(startTime),
            endTime: new Date(endTime),
            allDay: false,
          })
          this.eventSource = events;
          console.log(events);
        }  
```

**Comment by twinssbc** [comment]
@robertrobertlow Could you provide the complete source code about how do you load the events?
Does it work in month view?
What if you create some dummy events instead of fetching event from the API, does it work?

**Comment by sdhin** [comment]
sir i want a full source code @ghost
