### ISSUE TITLE
Show blank calendar, while rotate device.

### ISSUE THREAD

**Issue by Sudalaiyandi** [twinssbc/Ionic2-Calendar#305]
I used ionic2-calendar in my project.When i rotate device, it shows as blank calendar.In Android os, after show advertisement it shows as blank calendar.
How to solved this issue.
![simulator screen shot - iphone 5s - 2018-03-03 at 20 13 48](https://user-images.githubusercontent.com/24268120/36935613-f374ce3c-1f1f-11e8-8fb6-72667961e8f0.png)
![simulator screen shot - iphone 5s - 2018-03-03 at 20 14 14](https://user-images.githubusercontent.com/24268120/36935614-f3a084d2-1f1f-11e8-9601-96bdc706d0af.png)

**Comment by twinssbc** [comment]
@Sudalaiyandi It's likely some css related issue. Did you use some styles only take effect when your screen is horizontal? You could use Chrome Developer Tools to connect to your remote device to check any layout problem.

**Comment by Sudalaiyandi** [comment]
I applied css in calendar.I inspect the page, style doesn't modified.

**Comment by twinssbc** [comment]
@Sudalaiyandi If the style doesn't change, what DOM element is in that blank space in the horizontal mode?

**Comment by slzr** [comment]
@Sudalaiyandi How did you set these styles to the calendar? it looks nice

**Comment by Sudalaiyandi** [comment]
@slzr Thanks.Using table this calendar is designed, I override that style property in my own css class.
