### ISSUE TITLE
disabling the current date while swiping to the next or previous month...

### ISSUE THREAD

**Issue by rajkishoreandia** [twinssbc/Ionic2-Calendar#307]
@twinssbc can you help me disabling the color of today's date while I am swapping to the previous and next month.

**Comment by twinssbc** [comment]
@rajkishoreandia The selected color is controlled by below css. You could override it to achieve your desired effect.
```
        .monthview-selected {
          background-color: #009900;
          color: white;
        }
```

**Comment by rajkishoreandia** [comment]
thanx i got it
