### ISSUE TITLE
i want to highlight the date when the session ll be morning....how to do that@twinssbc

### ISSUE THREAD

**Issue by rajkishoreandia** [twinssbc/Ionic2-Calendar#310]
this is my api data in json...[
    {
        "title": "leave",
        "date": "2017-11-03",
        "reason": "",
        "allDay": true,
        "session": "all",
        "description": "Casual Leave"
    },
    {
        "title": "leave",
        "date": "2018-01-13",
        "reason": "not well",
        "allDay": false,
        "session": "Morning Session",
        "description": "Casual Leave"
    }
]
this is my home.ts code
import { Component   } from '@angular/core';
import { NavController } from 'ionic-angular';
import { AttendanceProvider } from '../../providers/attendance/attendance';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
  providers: [AttendanceProvider]
})
export class HomePage {
    viewTitle;
    isToday: boolean;
    calendar = {
        mode: 'month',
        currentDate: new Date()
    };
    eventSource: any =[];
    public  week_end_leaves =[];
  // these are the variable used by the calendar.
  constructor(public navController: NavController,public atp:AttendanceProvider) { 
        this.eventSource.push();
        this.getAttendanceDetails();
        // this.getWeekendData();
  }

  
onViewTitleChanged(title) {
    this.viewTitle = title;
}
onEventSelected(event) {
    console.log('Event selected:' + event.startTime + '-' + event.endTime + ',' + event.title+','+event.session);
}
changeMode(mode) {
    this.calendar.mode = mode;
}
today() {
    this.calendar.currentDate = new Date();
}
onTimeSelected(ev) {
    console.log('Selected time: ' + ev.selectedTime + ', hasEvents: ' +
        (ev.events !== undefined && ev.events.length !== 0) + ', disabled: ' + ev.disabled);
}
onCurrentDateChanged(event: Date) {
    var today = new Date();
    today.setHours(0, 0, 0, 0);
    event.setHours(0, 0, 0, 0);
    this.isToday = today.getTime() === event.getTime();
}

onRangeChanged(ev) {
    console.log('range changed: startTime: ' + ev.startTime + ', endTime: ' + ev.endTime);
}

  getAttendanceDetails() {
    this.atp.getAttendanceDetails().subscribe((data) => {
        data = data.map((item) =>{
            item.startTime = new Date(item.date);
             item.endTime = new Date( item.date);
             item.allDay=false;
            return item;
      }
   );
       this.eventSource = data;
       console.log(this.eventSource);
   });
}

**Comment by twinssbc** [comment]
@rajkishoreandia I don't quite understand your question. What is session II? In which view you want to highlight the date?
