### ISSUE TITLE
Is it possible to choose the order of the days on the calendar?

### ISSUE THREAD

**Issue by Nmaster88** [twinssbc/Ionic2-Calendar#315]
What i mean is, 
on the calendar by default are order this way:
Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday
But i want a different order:
Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday

How can this be done?

**Comment by Daskus1** [comment]
You can do it by changing 
```
startingDayWeek
```

**Comment by Nmaster88** [comment]
Where do i really put that?
In the calendar property?
    calendar = {
        locale: 'pt',
        mode: 'month',
startingDayWeek:1,
...
};

Or directive?

              <calendar 
              [locale]="calendar.locale"
              [eventSource]="eventSource"
              [calendarMode]="calendar.mode"
              [currentDate]="calendar.currentDate"
              [startingDayWeek]="1"
              (onCurrentDateChanged)="onCurrentDateChanged($event)"
              (onRangeChanged)="reloadSource(startTime, endTime)"
              (onEventSelected)="onEventSelected($event)"
              (onTitleChanged)="onViewTitleChanged($event)"
              (onTimeSelected)="onTimeSelected($event)"
              step="30">
            </calendar>

I tried both and it still doesn't work.
(If i'm doing it right maybe it's because of the version i'm using 0.2.18.)
