### ISSUE TITLE
is it possible to disable weekends?

### ISSUE THREAD

**Issue by onurkayaio** [twinssbc/Ionic2-Calendar#316]
Hello, i just want to disable weekends but can not find any property for that.
Can someone help? thanks.

code:

`<calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            [showEventDetail]="calendar.showEventDetail"
            [locale]="calendar.locale"
            [lockSwipes]="true"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            [startingDayWeek]="1"
            [startHour]="8"
            [endHour]="25"
            formatWeekViewDayHeader="EEE"
            formatHourColumn="hh:mm"
            class="calendar">
  </calendar>`

**Comment by twinssbc** [comment]
@onurkayaio In which view do you want to disable the weekends. "Disable" means not able to click it or hide it?

**Comment by Sudalaiyandi** [comment]
@onurkayaio In Calendar tag add this property as `[markDisabled]="markDisabled"`,                            
  in your ts file 
`markDisabled = (date: Date) => {
        let dateFormatted = this.datePipe.transform(date, "EEE")
        if (dateFormatted == "Fri" || dateFormatted == "Sat") {
            return true
        }
        else {
            return false
        }
    };`

It's worked for me.Check it.

**Comment by Hung9n3** [comment]
> markDisabled = (date: Date) => { let dateFormatted = this.datePipe.transform(date, "EEE") if (dateFormatted == "Fri" || dateFormatted == "Sat") { return true } else { return false } };

could you please let me know what is your datePipe ?
