### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by ThomasKientz** [twinssbc/Ionic2-Calendar#32]
Is it possible to set the calendar to a specific or local language ?

**Comment by twinssbc** [comment]
@ThomasKientz The DatePipe in Angular2 by default uses the Intl library. So the title should already display in your local language. But it's possible that Intl doesn't support localization that well for your language.

**Comment by chanphillip** [comment]
Hi
I'm trying restrict the language to be in English.
I've added this into app.module.ts but it did not work.

    { provide: LOCALE_ID, useValue: "en-US" }

Any advice?

**Comment by twinssbc** [comment]
@chanphillip I will take a look. Is it working in other place of your application?

**Comment by chanphillip** [comment]
@twinssbc Yes it's working in other place.

**Comment by twinssbc** [comment]
@chanphillip I have released version 0.2.2 which supports overriding the language using LOCALE_ID. Feel free to have a try.
