### ISSUE TITLE
how to show all events of each month in a list 

### ISSUE THREAD

**Issue by rajkishoreandia** [twinssbc/Ionic2-Calendar#320]
i want to show all the events of each individual month at the time of loading the calendar in month view @twinssbc

**Comment by twinssbc** [comment]
@rajkishoreandia I assume this is a separate list, not part of the calendar? You just bind an array to a ion-list, and set the events into that array.

**Comment by rajkishoreandia** [comment]
can u give some code

**Comment by twinssbc** [comment]
@rajkishoreandia Tbh, this is not the scope of the calendar control. 
You could take a look at below document to learn how to use ion-list.
https://ionicframework.com/docs/api/components/list/List/
