### ISSUE TITLE
Cannot read property 'dayHeaders' of undefined

### ISSUE THREAD

**Issue by robertolocal** [twinssbc/Ionic2-Calendar#326]
Occurs when update ionic to latest version. I already the bellow code in app.modules and in mypage.module and not work:

`import { registerLocaleData } from '@angular/common';`
`import localePt from '@angular/common/locales/pt';`
`registerLocaleData(localePt);`

**Comment by twinssbc** [comment]
@robertolocal Did you import intl? Which version of Angular, Ionic and Calendar are you using?

**Comment by GabrieleCicconetti** [comment]
i have the same problem after followed the locale instruction. Ionic 3.9.2, Angular 5.2.11 and last version of calendar :)
