### ISSUE TITLE
Show Events in MonthView inside a Table-Cell of a Day

### ISSUE THREAD

**Issue by Ahmadre** [twinssbc/Ionic2-Calendar#327]
Hello,

first thank you for this great calendar!

Second: I want to display my events for a Day (in the Month Mode) in the corresponding Tablecell as a little list (limited up to 3 items), like the Google Calendar for instance:
![unbenannt](https://user-images.githubusercontent.com/18512224/39670360-4742cbb2-5103-11e8-8745-0d4628e6022d.PNG)

Can i change your template here in the tablecell or how can i achieve this?

Thanks :)

**Comment by Ahmadre** [comment]
Just solved it by myself after looking deeper in your code. I didn't know that view.dates has got the events array. so i just iterated through it:
`<ng-template #template let-view="view" let-row="row" let-col="col">
          {{view.dates[row*7+col].label}}
          <div no-padding *ngFor="let event of view.dates[row*7+col].events">
            <ion-card no-padding>
              <ion-label>{{event.title}}</ion-label>
            </ion-card>
          </div>
      </ng-template>`

Thank you soo much 👍

**Comment by twinssbc** [comment]
@Ahmadre Just an advise that, you may want to limit the events displayed in each cell, for example, at most 3 events, if there are too many events.

**Comment by Ahmadre** [comment]
By the way: i recognized, that the month calendar is shrinking & growing in relation to how many events are assigned to a cell. How can i avoid that or how can i fix the cells but don't break the responsive design you've made? I tried to position the events absolute, but that ruins everything. Thanks im advise :)

greetings an german dev

**Comment by starkos0** [comment]
@Ahmadre Hi, would you mind to share your code? I'm trying to implement a similar calendar has the example you showed (the google calendar i mean), but i can't manage to make it.
