### ISSUE TITLE
onEventSelected not triggers anything

### ISSUE THREAD

**Issue by mcfdez** [twinssbc/Ionic2-Calendar#328]
I implemented the trigger onEventSelected in my app but it not does nothing when I press an event.

All other triggers works perfectly.

The template:

`
        <div *ngSwitchCase="'calendar'">
            <calendar [eventSource]="eventsCalendar"
                      [calendarMode]="calendar.mode"
                      [currentDate]="calendar.currentDate"
                      [formatDayHeader]="calendar.formatDayHeader"
                      [startingDayMonth]="1"
                      [locale]="calendar.locale"
                      (onEventSelected)="onEventSelected($event)"
                      (onTitleChanged)="onCalendarChange($event)"
                      step="30">
            </calendar>
        </div>`

And the ts file:

`   onEventSelected(event) 
    {
        console.log('something!');
    }`

Angular version: 5.0.3
Ionic version: 3.9.2

**Comment by twinssbc** [comment]
@mcfdez You mean onTitleChanged is actually triggered, only onEventSelected method is not triggered? Is there any error printed instead? And in which view did you meet this problem?

**Comment by mcfdez** [comment]
Effectively, onTitleChanged works and onEventSelected does not work. In the console I do not see any error, nor in the app itself. The problem is happening in a monthly type view, when I click on some day that has an event.

**Comment by twinssbc** [comment]
@mcfdez In month view, onEventSelected is triggered when you click the individual event displayed in the event detail section below the calendar table. When you click a date in the table, only onTimeSelected method is triggered.
