### ISSUE TITLE
Hide unused weekly rows

### ISSUE THREAD

**Issue by en-sevilla** [twinssbc/Ionic2-Calendar#329]
Hi,

which approach would you recommend to hide unsued rows in weekly view? We'd like to let only one hour before and after the events in order to simplify the representation, and hide any other row, as shown in the following image:

![image](https://user-images.githubusercontent.com/8984122/39709066-2487866e-5219-11e8-8783-a23f6bf9c0a3.png)

Thanks for your amazing work and best regards

**Comment by twinssbc** [comment]
@en-sevilla There are startHour and endHour options that can hide some hours. The idea is to only display the working hours. But it doesn't have some option to hide hours in the middle. Another way is you could try weekviewNormalEventSectionTemplate option, it allows you to provide a custom template for each time slot. It can't make you hide a certain time slot, but you could change the background to mark it as grey, for example.

**Comment by en-sevilla** [comment]
@twinssbc ok, thanks! I will try and If achieve something, will post here.

best regards
