### ISSUE TITLE
Pushing new events 

### ISSUE THREAD

**Issue by ThomasKientz** [twinssbc/Ionic2-Calendar#33]
What's the proper way to add events to eventSource and refresh the calendar to display them ?

**Comment by twinssbc** [comment]
When a user click a cell, the timeSelected callback will be triggered. You can navigate to a new page to let user fill in the new event details, then navigate back to the calendar.

**Comment by ThomasKientz** [comment]
I'm creating an all day event (with success) when the user select a day with "timeSelected" callback (so he can select multiple days, without leaving the calendar). But I'm having real issues to refresh the calendar with the new events added without destroying and creating again the calendar !

Thanks anyway !

**Comment by ThomasKientz** [comment]
I finally achieve this with a workaround 
```
resetCalendar() {
      this.eventSource = []
      setTimeout(() => {
        this.eventSource = this.myEvents
      },100);
}
```
I must lack js skills...

**Comment by twinssbc** [comment]
This workaround looks strange.
You can directly set eventSource to this.myEvents?
Did you get below error?

Expression has changed after it was checked

**Comment by RedEars** [comment]
@ThomasKientz I had the same problem. Your workaround worked, thanks!

**Comment by twinssbc** [comment]
I've exposed an instance method 'loadEvents', you no longer need to assign a new array to eventSource if you directly modify the element in the eventSource array.
