### ISSUE TITLE
Calendar shows wrong slide in a dayview when events spans several days and lockSwipes is applied

### ISSUE THREAD

**Issue by ryaa** [twinssbc/Ionic2-Calendar#330]
This problem is intermittent but reproducible very often on Android devices. In the browser or on iOS devices this does not happen (at least not often)

The corner case causing the problem is that when: 
a) there are events which span two days (start on current day and ends on the next day) and which needs to be displayed in the dayview (current day). 
b) swiping/navigation (lockSwipes property) needs to be disabled.

As i see, when the components renders it tries to position such events so that they span in different days (first part is in the current day and the rest on the next day) and when lockSwipes is set (with a timeout delay as the component document suggest) the component dayview ends on the wrong day (looks like automatic swiping occurs but ends on a wrong slide). If the swiping is not disabled the component manages to show the right day (slide).

I tried different fixes but none of them ideal:
1) in the dayview template add class="swiper-no-swiping" to all which disables the swiping on the swiper library level.
This seems to be a solid fix but there are two drawbacks. First, if the class name is changed in the swiper library in the future this will break the fix. The second is that this is a custom fix the component.
2) trim timeslots start and end time not to cross the day boundaries (if the timeslot end time is the next day make it to be the end of today etc.). This works but only when lockSwipes prop is set with 1000 ms delay or more. If it is less then that the problem is intermittent and is still reproducible
3) set lockSwipes prop in the calendar component with very large delay 2000+ ms. Then the problem does not seem to appear but this does not guarantee that it won't occur on another devices. Plus the user is able to swipe to another day within this 2000 ms delay.

Are there any suggestions how to handle the above described corner case?

Thanks

**Comment by ryaa** [comment]
Probably another option to try is to remove  loop="true" (https://github.com/twinssbc/Ionic2-Calendar/issues/314) but i did not try it yet.

**Comment by Anujmoglix** [comment]
Hi ,
  I want to do lockswipe() here .where i can do that code . i am not able to get ion-slide from code

**Comment by twinssbc** [comment]
@Anujmoglix Try this
```
var mySwiper = document.querySelector('.swiper-container')['swiper'];
    mySwiper.slideNext();
```

**Comment by Anujmoglix** [comment]
Hi @twinssbc 
   Thanks for your response. I have did it by changing inside node module monthview.js and added class there .Btw thanks . I will check this as well .
