### ISSUE TITLE
Add dots to monthview

### ISSUE THREAD

**Issue by aces-tm** [twinssbc/Ionic2-Calendar#332]
Is there an option to add dots above number in top right corner. I have 3 different types of events and by programmatically adding class I want to control if dots show or not. 

I was able to draw a dot inside the box, but it stays in the middle and not able to move it around. I am not sure how to add custom class either. 

```
    .monthview-primary-with-event[_ngcontent-c1]:before{
        position: absolute;
        content: '';
        background-color:#FF0000;
        border-radius:50%;
        width: 5px;
        height: 5px;
        pointer-events: none;
    }
```

Thank you

**Comment by aces-tm** [comment]
@twinssbc Thanks for the response. How do I access events on that particular day? For example, on each day I have 3 possible types of events and I'd like to put do something like `if event.type1 apply cssClass`.  Thank you

**Comment by twinssbc** [comment]
@aces-tm Just use view.dates[row*7+col].events, it's an array.

**Comment by aces-tm** [comment]
@twinssbc Perfect, I will post the code once I finish it. Thank a lot and excellent support as usual!

**Comment by aces-tm** [comment]
Here is the code that works for me

In scss I made this adjustment:
```
    .monthview-primary-with-event[_ngcontent-c1]{
        background-color: transparent;
        color: color($colors, dark);
        padding: 0px 0px 8px 0px !important;
    }

    .monthview-secondary-with-event[_ngcontent-c1]{
        padding: 0px !important;
    }

    .monthview-label {
        margin-bottom: 8px;
    }
```
My template looks like this: 

```
  <ng-template #monthviewDisplayEventTemplate let-view="view" let-row="row" let-col="col">
      <ng-template ngFor let-event [ngForOf]="view.dates[row*7+col].events">
        <span [ngStyle]="monthViewDots(event, view.dates[row*7+col].label)"></span>
      </ng-template>
      <div [ngStyle]="monthViewLabel(view.dates[row*7+col].events)">{{view.dates[row*7+col].label}}</div>

  </ng-template>
```
And my classes that I call from ngStyle look like this:

```
  public monthViewDots(event, label) {
    if (this.previousLabel !== label) {
      this.eventType1 = 0;
      this.eventType2 = 0;
      this.eventType3 = 0;
      this.previousLabel = label;
    }

    let color = '';
    if (event.practice) {
      this.eventType1++;
      color = '#03A9F4';
    } else if (event.match) {
      color = '#8BC34A';
      this.eventType2++;
    } else {
      color = '#FFC107';
      this.eventType3++;
    }

    if (if type of event doesn't exist return empty, else add dot) {
      return {};
    } else {
      return {
        'border-radius': '50%',
        'height': '7px',
        'width': '7px',
        'background': color,
        'display': 'inline-block'
      };
    }

  }

  public monthViewLabel(events) {
    if (!events.length) {
      return {
        'margin-top': '11px'
      };
    }
  }
```

**Comment by aces-tm** [comment]
@twinssbc Do you recommend using `.monthview-primary-with-event` instead of `.monthview-primary-with-event[_ngcontent-c1]`?

**Comment by aces-tm** [comment]
@twinssbc Is there better way to loop through the event than what I am doing?

```
  <ng-template #monthviewDisplayEventTemplate let-view="view" let-row="row" let-col="col">
      <ng-template *ngIf="view.dates[row*7+col].events.length" ngFor let-event [ngForOf]="view.dates[row*7+col].events">
        <span [ngStyle]="monthViewDots(event, view.dates[row*7+col].label)"></span>
      </ng-template>
      <div [ngStyle]="monthViewLabel(view.dates[row*7+col].events)">{{view.dates[row*7+col].label}}</div>

  </ng-template>
```

When there are events only on 1 day of the month the calendar loops through the same event 10+ times and therefore doesn't display it properly. If there are events on more than 1 day it works fine.


Thanks

**Comment by twinssbc** [comment]
@aces-tm Why do you need to put ng-template inside ng-template?
You mentioned that if the events on more than 1 day, it works fine.
I'm not sure if it's related to below logic.
What's the intention here to check label?
```
public monthViewDots(event, label) {
    if (this.previousLabel !== label) {
      this.eventType1 = 0;
      this.eventType2 = 0;
      this.eventType3 = 0;
      this.previousLabel = label;
    }
```

**Comment by aces-tm** [comment]
So I found a very simple solution

```
html:

  <ng-template #monthviewDisplayEventTemplate let-view="view" let-row="row" let-col="col">
      <span *ngIf="!view.dates[row*7+col].events.length" class="no-events"></span>

      <div *ngIf="view.dates[row*7+col].events.length">
          <span *ngIf="eventExists(view.dates[row*7+col].events, 'practice')" class="practice"></span>
          <span *ngIf="eventExists(view.dates[row*7+col].events, 'match')" class="match"></span>
          <span *ngIf="eventExists(view.dates[row*7+col].events, 'tournament')" class="tournament"></span>
      </div>
      <!-- <div [innerHtml]="monthViewLabel(view.dates[row*7+col].events)"></div> -->
      <div>{{view.dates[row*7+col].label}}</div>

  </ng-template>

.ts:

  eventExists(events, type) {
    for (let i = 0; i < events.length; i++) {
      const event = events[i];
      if (type === 'practice' && event.practice) return true;
      else if (type === 'match' && event.match) return true;
      else if (type === 'tournament' && event.competition) return true;
    }
  }
```

Thanks for your help

**Comment by gidhin** [comment]
hi

im facing issue to get the events value in ts file.
 
my  html template

<ng-template #monthviewDisplayEventTemplate let-view="view" let-row="row" let-col="col">
        <div>{{view.dates[row*7+col].label}}</div>
        <div [ngClass]="getCustomClass(view.dates[row*7+col].events)" class="event-type-bubble">
            <span class="meeting"></span>
            <span class="activity"></span>
            <span class="deviation"></span>
        </div>
    </ng-template>

my TS file

 getCalendarDetailList() {
        this.baseClass.presentLoader();
        let businessid = this.baseClass.businessId
        this.startUpHelper.getCalendarList(businessid).then((result) => {
            this.items = <Array<Object>>result;
            for (let data of this.items) {
                this.eventSource.push({
                    id: data.id,
                    title: data.title,
                    startTime: new Date(data.start),
                    endTime: new Date(data.start),
                    type: data.type,
                    allDay: false,
                    eventColor: data.color
                });
                this.myCalendar.loadEvents();
            }
            this.baseClass.closeLoader();
        }, (err) => {
            this.baseClass.closeLoader();
        });
    }

    getCustomClass(events: any) {
        console.log("events bind",events);
        let count = events.length;
        let aCount = 0;
        let mCount = 0;
        let dCount = 0;
        if (events && count > 0) {
            events.forEach(element => {
                if (element.type == 'ACTIVITY') {
                    aCount += 1;
                }
                if (element.type == 'MEETING') {
                    mCount += 1;
                }
                if (element.type == 'DEVIATION') {
                    dCount += 1;
                }
                if (aCount > 0 && mCount > 0 && dCount > 0) {
                    return 'all';
                }

            });
            if (aCount > 0 && mCount > 0 && dCount > 0) {
                return 'all';
            }
            if (aCount > 0 && mCount > 0) {
                return 'a-m';
            }
            if (aCount > 0 && dCount > 0) {
                return 'a-d';
            }
            if (mCount > 0 && dCount > 0) {
                return 'm-d';
            }

            return (aCount > 0) ? 'activity' : (mCount > 0) ? 'meeting' : (dCount > 0) ? 'deviation' : '';

        }
        return '';
    }

**Comment by aces-tm** [comment]
I simplified my code.... try this 
```
  <ng-template #monthviewDisplayEventTemplate let-view="view" let-row="row" let-col="col">
      <span *ngIf="!view.dates[row*7+col].events.length" class="no-events"></span>

      <div *ngIf="view.dates[row*7+col].events.length">
          <span *ngIf="eventExists(view.dates[row*7+col].events, 'practice')" class="practice"></span>
          <span *ngIf="eventExists(view.dates[row*7+col].events, 'match')" class="match"></span>
          <span *ngIf="eventExists(view.dates[row*7+col].events, 'tournament')" class="tournament"></span>
      </div>
      <div>{{view.dates[row*7+col].label}}</div>

  </ng-template>
```

and TS file 

```
  eventExists(events, type) {
    for (let i = 0; i < events.length; i++) {
      const event = events[i];
      if (type === 'practice' && event.practice) return true;
      else if (type === 'match' && event.match) return true;
      else if (type === 'tournament' && event.competition) return true;
    }
  }
```

scss (example)
```
    .practice {
        border-radius: 50%;
        height: 8px;
        width: 8px;
        background: #03A9F4;
        display: inline-block;
    }
```

Let me know if this helps

**Comment by gidhin** [comment]
@aces-tm  Thank you for you code. I try with your code but not working for me. if any version have problem, i try with 0.4.2 and 0.4.4 then also not working.

event source data bind in the template but cant get in events, that's my issue 

<ng-template #monthviewDisplayEventTemplate let-view="view" let-row="row" let-col="col">
        <div>{{view.dates[row*7+col].label}}</div>
        <div [ngClass]="getCustomClass(view.dates[row*7+col].events)" class="event-type-bubble">
            <span class="meeting"></span>
            <span class="activity"></span>
            <span class="deviation"></span>
        </div>
    </ng-template>

TS file
 getCalendarDetailList() {
        this.baseClass.presentLoader();
        let businessid = this.baseClass.businessId
        this.startUpHelper.getCalendarList(businessid).then((result) => {
            this.items = <Array<Object>>result;
            for (let data of this.items) {
                this.eventSource.push({
                    id: data.id,
                    title: data.title,
                    startTime: new Date(data.start),
                    endTime: new Date(data.start),
                    type: data.type,
                    allDay: false,
                    eventColor: data.color
                });
                this.myCalendar.loadEvents();
            }
            this.baseClass.closeLoader();
        }, (err) => {
            this.baseClass.closeLoader();
        });
    }

 getCustomClass(events: any) {
        let count = events.length;
        let aCount = 0;
        let mCount = 0;
        let dCount = 0;
        if (events && count > 0) {
            events.forEach(element => {
                if (element.type == 'ACTIVITY') {
                    aCount += 1;
                }
                if (element.type == 'MEETING') {
                    mCount += 1;
                }
                if (element.type == 'DEVIATION') {
                    dCount += 1;
                }
                if (aCount > 0 && mCount > 0 && dCount > 0) {
                    return 'all';
                }

            });
            if (aCount > 0 && mCount > 0 && dCount > 0) {
                return 'all';
            }
            if (aCount > 0 && mCount > 0) {
                return 'a-m';
            }
            if (aCount > 0 && dCount > 0) {
                return 'a-d';
            }
            if (mCount > 0 && dCount > 0) {
                return 'm-d';
            }

            return (aCount > 0) ? 'activity' : (mCount > 0) ? 'meeting' : (dCount > 0) ? 'deviation' : '';

        }
        return '';
    }

events not getting the value in the getCustomClass(events: any) function

**Comment by twinssbc** [comment]
@gidhin Not sure if it's just rendering issue. The template should use row*7+col, but in your pasted code, it is using row7+col

**Comment by gidhin** [comment]
@twinssbc thank you, i have try with  row*7+col but still i am get the issue. i found that value is not getting in "view.dates[row*7+col].events", can you tell me the what format should use for eventSource

this is are the value i pushed to eventSource

data.start = "2018-03-20T00:00:00"
 startTime : new Date(data.start)  

this.eventSource.push({
                    id: data.id,
                    title: data.title,
                    startTime: new Date(data.start) ,
                    endTime: new Date(data.start) ,
                    type: data.type,
                    allDay: true,
                    eventColor: data.color
                });
if i give current dataTime "new date()" its display the value
what mistake i did in the code.

thank you

**Comment by twinssbc** [comment]
@gidhin Sorry, I don't quite understand your issue. According to your pasted code, it seems the startTime and endTime are the same?

**Comment by gidhin** [comment]
@twinssbc Thank you for your reply. I find out the issue.

i changed the code like this. Now events are binding.


startTime: new Date(data.start),
endTime:  new Date(new Date(data.start).setHours(23)),

what mistake i did was startTime  and endTime have "Fri Jul 20 2018 00:00:00 GMT+0530 (India Standard Time)" this. so i add sethours(23) in the endTime

**Comment by Siva021** [comment]
<calendar
        [eventSource]="calendarEvents"
        [calendarMode]="calendar.mode"
        [currentDate]="calendar.currentDate"
        (onEventSelected)="onEventSelected($event)"
        (onTitleChanged)="onViewTitleChanged($event)"
        (onTimeSelected)="onTimeSelected($event)"
        [monthviewEventDetailTemplate]="template">
    </calendar>
    <ng-template #template let-currentDate='calendar.currentDate' let-view="view" let-row="row" let-col="col">
       <p>{{'View : ' | translate}} {{view}}</p>
        <p>{{'row : ' | translate}} {{row}}</p>
        <p>{{'col : ' | translate}} {{col}}</p></ng-template>

I have code something like this, but i dont have starttime and endtime in event source. I want to bind with calendar with my own data instead of default
 title: data.title,
startTime: new Date(data.start) ,
endTime: new Date(data.start) ,
type: data.type,
allDay: true,
eventColor: data.color 
is it possible?

**Comment by twinssbc** [comment]
@Siva021 Unfortunately startTime and endTime is the mandatory fields which will be used internally.
