### ISSUE TITLE
Restrict swipe

### ISSUE THREAD

**Issue by Anujmoglix** [twinssbc/Ionic2-Calendar#334]
Hi,
  Thanks for the plugin . I want to restrict swiping and want  to show only arrow button for next and previous month . I don't want to swipe from the calendar because i want to implement some function with that  . Is it possible to restrict swiping with gesture ?

**Comment by Anujmoglix** [comment]
Hi ,
  I  got the solution  as Using <ion-slide class="swiper-no-swiping"> worked perfectly as a workaround and after updation in console it is working fine . but i wanna know that  how to use it ?  
`<ion-slides _ngcontent-c1="" class="swiper-no-swiping slides slides-md slides-0" ng-reflect-loop="true" ng-reflect-dir="" ng-reflect-space-between="0">`

**Comment by twinssbc** [comment]
@Anujmoglix I think you could try get the DOM element then dynamically set the class on it.
