### ISSUE TITLE
(onTimeSelected) event is called whenever I enter month view

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#335]
(onTimeSelected) event is called whenever I enter month view and also when I change from one  month to the other. I want that function to be called only when we select a particular date or time. How can I do that? Can I achieve my requirement from any other event?

**Comment by twinssbc** [comment]
@KishoreKoushik There's an **autoSelect** option. You could set it to false.

**Comment by KishoreRadhakrishna** [comment]
@twinssbc Great. This Worked for me. thanks
