### ISSUE TITLE
Event on month callender is showing missing one day from data had been provide

### ISSUE THREAD

**Issue by Xsur** [twinssbc/Ionic2-Calendar#338]
please help me to slove this, i had ionic calender with month template, i want to put event every ranged changed on calender i allredy succesfull on get data from db but when i put the event on calender, marked event on calender is showing less than one day from data that i provide

this is the callender view
![image](https://user-images.githubusercontent.com/25731857/40588392-f2acde66-6206-11e8-9c44-7f6dbbb709e0.png)

and this is the data that i get from DB

![image](https://user-images.githubusercontent.com/25731857/40588409-1b6b58a0-6207-11e8-9b39-a46c29538caf.png)

the callender showing the data minus one day from the provided data it must be marked at day 25 until day 26 but its marked at days 24 until 25

thks before, and sorry about my bad english...

**Comment by twinssbc** [comment]
@Xsur So your screenshot shows the payload you get from the database. How do you convert it to an event that can be used by the calendar? Especially how do you convert the start_date and end_date string to the Date object?  Is it possible that piece of logic is wrong?

**Comment by twinssbc** [comment]
@Xsur It's because you set allDay field to true. If you want to create all day event, the startTime and endTime needs to be converted to UTC time. But I suppose you want to create normal event? So allDay field needs to be false.

**Comment by Xsur** [comment]
OMG, thks @twinssbc btw sorry for my little miss here still new at ionic here..first time try ionic calender..
