### ISSUE TITLE
How to show day name with day in month view

### ISSUE THREAD

**Issue by kumarlinga** [twinssbc/Ionic2-Calendar#339]
@twinssbc  How to show day name with day only in month view? like below image

![image](https://user-images.githubusercontent.com/39696252/40610528-5a25f2d8-6290-11e8-9d7e-b59061d41c4d.png)

**Comment by twinssbc** [comment]
@kumarlinga I'm afraid it's not possible to customize the monthview like that. I think you could simply use a list to achieve your requirement.
