### ISSUE TITLE
Run demo locally

### ISSUE THREAD

**Issue by pookdeveloper** [twinssbc/Ionic2-Calendar#340]
How can i run demo locally ? thanks!

**Comment by twinssbc** [comment]
@pookdeveloper For the code in master branch, you can directly open the index.html page. This is how the demo URL works. For the code in v3/v4 branch, you need to copy the code in the demo page into an Ionic project, then run "ionic serve" to run it.

**Comment by pookdeveloper** [comment]
@twinssbc  to run locally if I directly open the fikle index.html i get the error cross domain:

![image](https://user-images.githubusercontent.com/3384734/40978109-0873f860-68d3-11e8-80de-f9853b11b65f.png)

How you open the file , you put the code in a server?  Thanks

**Comment by pookdeveloper** [comment]
@twinssbc ok I know, I use visual studio code, and your WebStorm, its internally generate a server, that's why you access from. Thanks
