### ISSUE TITLE
How can I change the 15 min time slot to 30 min and vise versa dynamically

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#341]
Hi want my calendar to have either 15 min or 30 min time slots depending on the time slot. But its not happening as per my requirement. My code is as below.

 calendar = {
        mode: 'day',
        currentDate: new Date(),
        timeInterval: this.is15minSlotsenabled ? 15 : 30,
        startingDayMonth: 1,
        startingDayWeek: 1,
        startHour: 0,
        endHour: 24,
        scrollToHour: 14,
        formatDayTitle: 'dd/MM/yyyy',
        formatWeekTitle: 'dd-dd,yyyy',
        formatHourColumn: 'H:mm',
        hourSegments: this.is15minSlotsenabled ? 4 : 2,
}

getDaySettings() {
        let daySettings = {
            currentDay : this.calendar.currentDate,
            MemberEmployerIds : this.selectedemployerids,
        }
        console.log(daySettings);
        this.http.post<any>(this.serverAddress + ENV.GET_DAY_SETTINGS, daySettings)
            .subscribe(result => {
                console.log(result);
                this.is15minSlotsenabled = result.Is15MinSlotEnabled;
            });
    }

I tried calling getDaySettings() function both after and before page loads.

**Comment by twinssbc** [comment]
@KishoreKoushik hourSegments is the internal field, it is calculated based on timeInterval, so you can't control it externally. timeInterval is set during the calendar initialization phase, so it can't be changed dynamically. Also if you hard code timeInterval, does it take effect?

**Comment by KishoreKoushik** [comment]
Yes. If I hard code, it takes effect

**Comment by twinssbc** [comment]
@KishoreKoushik As I mentioned the timeInterval takes effect when the calendar is rendering.
Your problem is getDaySettings call is an async method, you can't control if the calendar renders first or the result returns first.
The solution is you could use some thing like *ngIf="!loading" to hide the calendar at the beginning, in the callback set loading to false. Then the calendar will start rendering.
