### ISSUE TITLE
Change Time format from 24 hour to 12 hour in onTimeSelected.

### ISSUE THREAD

**Issue by fahmisaad** [twinssbc/Ionic2-Calendar#343]
Hi, i want to change time format from 24 hours to 12 hour in onTimeSelected.
Is there any ways to do it?

for example current it shows 12:00 - 14:00 , i want to display 12:00 am - 2:00 pm.

Any help will be a huge help for me. Thanks

Can refer below image.

![capture](https://user-images.githubusercontent.com/11407590/41115561-7749ccc2-6aba-11e8-9601-9d0b79d11654.PNG)

**Comment by twinssbc** [comment]
@fahmisaad You could use monthviewEventDetailTemplate to change the style of that event detail section part.
Below template is the default one. As you can see it is using HH:mm in the Date pipe, you could change it to any format you want.

```
        <ng-template #template let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
            <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
                <ion-item *ngFor="let event of selectedDate?.events" (click)="eventSelected(event)">
                        <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                            -
                            {{event.endTime|date: 'HH:mm'}}
                        </span>
                    <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn">{{allDayLabel}}</span>
                    <span class="event-detail">  |  {{event.title}}</span>
                </ion-item>
                <ion-item *ngIf="selectedDate?.events.length==0">
                    <div class="no-events-label">{{noEventsLabel}}</div>
                </ion-item>
            </ion-list>
        </ng-template>

        <calendar ... [monthviewEventDetailTemplate]="template"></calendar>
```

**Comment by NimaiMalle** [comment]
Forgive me if this is a naive question.  In Ionic, if I past the `ng-template` mark-up into my page html file along with the calendar declaration, what do I do about these errors?
![image](https://user-images.githubusercontent.com/334278/43057793-dc851b56-8e09-11e8-8e22-7658205cef52.png)
As you can see, `eventSelected(event)` and `allDayLabel` are undefined, because this is a copy of the default template code that comes from the calendar's codebase.  Do I need to duplicate the code/declaration of those as well?

**Comment by twinssbc** [comment]
@NimaiMalle Correct, you need declare eventSelected and allDayLabel in your own component.
