### ISSUE TITLE
For 15min time slot the cell is not covering half

### ISSUE THREAD

**Issue by Divyea** [twinssbc/Ionic2-Calendar#344]
Hi,
I had the set the calendar for 15min slot and added an event it taken correctly and again i change the time slot to 30min then the 15min slot activity should be half of the cell. Instead it is covering full cell.

![image](https://user-images.githubusercontent.com/40061130/41156304-f788ffc8-6b3e-11e8-99ba-82188fd48fe4.png)
[Issue.docx](https://github.com/twinssbc/Ionic2-Calendar/files/2084194/Issue.docx)

**Comment by twinssbc** [comment]
@Divyea Did you set "step" option to 15?

**Comment by Divyea** [comment]
Yes in the back end I am setting it to 15min slot. But it is covering full cell. I want to make it half cell coloured. I also attached the screenshot of both 15min and 30min display in the issue.docx file which is  attached in the above conversation.

**Comment by twinssbc** [comment]
@Divyea You mean you fetch the settings form the backend? Could you show you code how do you fetch it and set it in the app side?
