### ISSUE TITLE
scrollToHour is not working in week view

### ISSUE THREAD

**Issue by Divyea** [twinssbc/Ionic2-Calendar#345]
@twinssbc 
Hi,
In day view and week view i need to set the focus to 7AM. i set scrollToHour : 14 but it is applying for day view at the first time and if i changed the view to other view and return to day view it is not working instead it is showing the focus at 3.30 and In week view it always points to 3.30.

<calendar [eventSource]="eventSource" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate" [timeInterval]="calendar.timeInterval"
    [startingDayMonth]='calendar.startingDayMonth' [startHour]='calendar.startHour' [endHour]='calendar.endHour' 
    [formatWeekTitle]='calendar.formatWeekTitle' 
    [startingDayWeek]="calendar.startingDayWeek" 
	[scrollToHour]='calendar.scrollToHour' 
     step="30">
  </calendar>

 calendar = {
        mode: 'day',
        currentDate: new Date(),
        timeInterval: ENV.is15minSlotsenabled ? 15 : 30,
        startingDayMonth: 1,
        startingDayWeek: 1,
        startHour: 0,
        endHour: 24,
        scrollToHour: 14,
}

[Focusto7.docx](https://github.com/twinssbc/Ionic2-Calendar/files/2086827/Focusto7.docx)

**Comment by twinssbc** [comment]
@Divyea Unfortunately I can't reproduce it, it always points to 7AM at my side. Did you custom the styles, for example, change the height? After you change the view to other view, do you perform some action in that view?

**Comment by arulmanoa** [comment]
@twinssbc how to implement the calendar screen like below-attached file

![screen for calen](https://user-images.githubusercontent.com/30864164/41397655-88593044-6fd2-11e8-8508-f11bf14855ac.png)

**Comment by twinssbc** [comment]
@arulmanoa Unfortunately this calendar cannot meet your requirement.
