### ISSUE TITLE
How can i load Datetime as local singapore time in calendar?

### ISSUE THREAD

**Issue by arulmanoa** [twinssbc/Ionic2-Calendar#346]
How can I load DateTime as local Singapore time on the calendar?

**Comment by twinssbc** [comment]
@arulmanoa The calendar displays the event using your local time zone. If you are in Singapore timezone right now, then no need to do anything.

**Comment by arulmanoa** [comment]
Sorry, I got UTC time zone calendar

**Comment by twinssbc** [comment]
@arulmanoa Sorry, I don't quite get your requirement. Do you have any problem to display the events in the correct time slot? Do you mean your event time is stored as UTC time?
