### ISSUE TITLE
Weekview and dayview only shows allday row

### ISSUE THREAD

**Issue by efezter** [twinssbc/Ionic2-Calendar#347]
Hello 

No matter what I did calendar does not show hours. It only shows allday row. Can you please help me on this?     

 <calendar  #CalendarComponent 
          [startHour]="8" [endHour]="19"  
              [eventSource]="eventSource"
              [calendarMode]="calendar.mode"
              [currentDate]="calendar.currentDate"
              (onCurrentDateChanged)="onCurrentDateChanged($event)"
              (onRangeChanged)="reloadSource(startTime, endTime)"
              (onTitleChanged)="onViewTitleChanged($event)">
        </calendar>

**Comment by Xiralv** [comment]
Hi I have the same issue with this one also.

**Comment by Titoch** [comment]
I think you jsute have to remove brackets '[' and ']' around startHour and endHour as values (8 and 19) are not variables of your component but directly numbers.

**Comment by Xiralv** [comment]
Hi @Titoch in my problem is I uninstalled and install again the ionic2-calendar in my local project and when i run my project its still and navigate both WeekView and DayView it only shows the **all day row** 

This is my html project

  <calendar [eventSource]="eventSource" 
  [calendarMode]="calendar.mode" 
  [currentDate]="calendar.currentDate" 
  (onCurrentDateChanged)="onCurrentDateChanged($event)" 
  (onEventSelected)="onEventSelected($event)" 
  (onTitleChanged)="onViewTitleChanged($event)" 
  (onTimeSelected)="onTimeSelected($event)"
   step="30">
  </calendar>

**Comment by efezter** [comment]
@Titoch 

I mistakenly forgot them there. removed them but unfortunatelly nothing has changed.

**Comment by Xiralv** [comment]
I just resolve this issue in my app scss. i have there a .ion-slide class i just removed it. it affects the ion slide of the ionic2-calendar

**Comment by efezter** [comment]
@Xiralv good to hear. Un fortunatelly that was not my case.

**Comment by Xiralv** [comment]
@efezter Maybe some of your pages  in .scss has some .ion-slides class try to remove it and test it if its still showing only allday row for both weekdayview and dayview

**Comment by twinssbc** [comment]
@efezter Could you inspect your DOM elements using developer tools to find out why the rest rows are not displayed or hidden. It's likely due to some conflict in the CSS.

**Comment by napisani** [comment]
@efezter @twinssbc 
Hi All - I was running into the same thing because of the following css
.weekview-normal-event-container {
  position: absolute;
left:0;
top:0;
bottom:0;
right:0;
} /* this css effectively hid the div containing all of the time specific rows */ 
below is my current fix/hack

:host ::ng-deep .weekview-normal-event-container {
  position: relative;
}

:host ::ng-deep .dayview-normal-event-container {
  position: relative;
}

**Comment by ErickTechuso** [comment]
I have the same issue, only shows allday row in week and day view, i try to change the css but still hide

**Comment by brluizfelippe** [comment]
I was facing the exact same issue. What I did to make calendar day view mode work correctly is quite simple. I have placed the calendar component inside a `<ion-grid>` tag. Once I removed it from it and placed it directly inside the `<ion-content>` I got it working as expected.

**Comment by jonny1811** [comment]
I have the same problem. I think this happens when I put the calendar inside a div tag and try to change from month to week mode as well as day mode.
Example: https://stackblitz.com/edit/ionic-ceyyvd?file=pages/home/home.html

**Comment by twinssbc** [comment]
@jonny1811 you need to set the height of that div as 100%

```
<ion-content>
  <div style="height:100%">
    <calendar [eventSource]="eventSource"
              [calendarMode]="calendar.mode"
              [currentDate]="calendar.currentDate"
              (onCurrentDateChanged)="onCurrentDateChanged($event)"
              (onEventSelected)="onEventSelected($event)"
              (onTitleChanged)="onViewTitleChanged($event)"
              (onTimeSelected)="onTimeSelected($event)"
              step="30">
    </calendar>
  </div>
</ion-content>
```

**Comment by sapabg** [comment]
I had the same problem. The <calendar> tag needs to be inside <ion-content> and it works.
