### ISSUE TITLE
All day activity taking one day prior in all the three views

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#348]
In all the three views, only all day events is displaying one day prior. But normal events looks fine.
 example my startDate is "2018-05-07T00:00:00" and event is displayed on 06th of May

I have used custom all day template event

 <ng-template #dayalldaytemplate let-displayEvent="displayEvent">
    <div class="calendar-event-inner" [ngClass]="alldayeventindayview(displayEvent.event.jobCategoryId)">{{displayEvent.event.title}}</div>
  </ng-template>

 alldayeventindayview() {
    return 'alldayeventindayview';
  }

 .alldayeventindayview{
        overflow: hidden;
        background-color: #ffc0cb;
        color: white;
        height: 220%;
        width: 100%;
        padding: 2px;
        line-height: 15px;
    }

<img width="199" alt="all day event" src="https://user-images.githubusercontent.com/22149302/41535602-80cc7376-7320-11e8-8a55-48b07952d67d.png">

**Comment by twinssbc** [comment]
@KishoreKoushik, for all day event you need to convert it to UTC time. You could find detailed explanation in the Event Source section in README.
