### ISSUE TITLE
How can i separate my day calendar view?

### ISSUE THREAD

**Issue by arulmanoa** [twinssbc/Ionic2-Calendar#349]
How can I separate my day calendar view like below screens? I have 4 staffs, at the same time I have split my columns like this

![screen for calen](https://user-images.githubusercontent.com/30864164/41536982-c36cfbb6-7324-11e8-81cd-73de0b57791d.png)

**Comment by arulmanoa** [comment]
Sorry to re-open it, if its possible to do the above screen please ping me

**Comment by andrejwright** [comment]
@twinssbc @arulmanoa do you know if this ever got added as a feature? I am interested in this as well!

**Comment by AvniAnay** [comment]
I have the same requirement , It would be great if it gets supported.
