### ISSUE TITLE
The demo url does not work on Safari on iPhone with iOS 9.3.4

### ISSUE THREAD

**Issue by EnricoPicci** [twinssbc/Ionic2-Calendar#35]
I try to launch the demo site (https://twinssbc.github.io/Ionic2-Calendar/demo/) on Safari on iPhone with iOS 9.3.4 but I do not see anything.
Is there a reason for this?
Thanks in advance

**Comment by twinssbc** [comment]
@EnricoPicci If you enable debug console in Safari, or you connect your iPhone to your desktop to do the remote debugging, can you see any error printed out in the console?

**Comment by EnricoPicci** [comment]
Thanks for getting back to me.

I tried on Safari on a Mac and I actually get an error.

The first lines printed on the console are:

[Error] Failed to load resource: the server responded with a status of 404
(Not Found) (system.js.map, line 0)
[Error] EXCEPTION: Error in ./CalendarComponent class CalendarComponent -
inline template:35:16 caused by: Can't find variable: Intl
handleError (demo:52)
(anonymous function) (demo:119)
invoke (zone.min.js:1:15942)
onInvoke (demo:48)
invoke (zone.min.js:1:15896)
run (zone.min.js:1:13330)
(anonymous function) (zone.min.js:1:11429)
invokeTask (zone.min.js:1:16571)
onInvokeTask (demo:39)
invokeTask (zone.min.js:1:16514)
runTask (zone.min.js:1:13936)
a (zone.min.js:1:10550)
invoke (zone.min.js:1:17720)
[Error] ORIGINAL EXCEPTION: Can't find variable: Intl
handleError (demo:54)
(anonymous function) (demo:119)
invoke (zone.min.js:1:15942)
onInvoke (demo:48)
invoke (zone.min.js:1:15896)
run (zone.min.js:1:13330)
(anonymous function) (zone.min.js:1:11429)
invokeTask (zone.min.js:1:16571)
onInvokeTask (demo:39)
invokeTask (zone.min.js:1:16514)
runTask (zone.min.js:1:13936)
a (zone.min.js:1:10550)
invoke (zone.min.js:1:17720)
[Error] ORIGINAL STACKTRACE:
handleError (demo:57)
(anonymous function) (demo:119)
invoke (zone.min.js:1:15942)
onInvoke (demo:48)
invoke (zone.min.js:1:15896)
run (zone.min.js:1:13330)
(anonymous function) (zone.min.js:1:11429)
invokeTask (zone.min.js:1:16571)
onInvokeTask (demo:39)
invokeTask (zone.min.js:1:16514)
runTask (zone.min.js:1:13936)
a (zone.min.js:1:10550)
invoke (zone.min.js:1:17720)
[Error] intlDateFormat@
https://twinssbc.github.io/Ionic2-Calendar/demo/:22:24
https://twinssbc.github.io/Ionic2-Calendar/demo/:53:63
https://twinssbc.github.io/Ionic2-Calendar/demo/:83:28
forEach@[native code]
dateFormatter@https://twinssbc.github.io/Ionic2-Calendar/demo/:81:22
format@https://twinssbc.github.io/Ionic2-Calendar/demo/:189:41
transform@https://twinssbc.github.io/Ionic2-Calendar/demo/:101:55
createDateObject@https://twinssbc.github.io/Ionic2-Calendar/demo/:108:72
getViewData@https://twinssbc.github.io/Ionic2-Calendar/demo/:127:63
populateAdjacentViews@
https://twinssbc.github.io/Ionic2-Calendar/demo/:115:86
refreshView@https://twinssbc.github.io/Ionic2-Calendar/demo/:284:63
ngOnInit@https://twinssbc.github.io/Ionic2-Calendar/demo/:48:37
detectChangesInternal
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectContentChildrenChanges@
https://twinssbc.github.io/Ionic2-Calendar/demo/:350:44
detectChangesInternal
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectViewChildrenChanges@
https://twinssbc.github.io/Ionic2-Calendar/demo/:358:44
detectChangesInternal
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectViewChildrenChanges@
https://twinssbc.github.io/Ionic2-Calendar/demo/:358:44
detectChangesInternal@
https://twinssbc.github.io/Ionic2-Calendar/demo/:343:51
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:144:45
_viewInsert@https://twinssbc.github.io/Ionic2-Calendar/demo/:422:65
_viewInsert@https://twinssbc.github.io/Ionic2-Calendar/demo/:111:54
_transition@https://twinssbc.github.io/Ionic2-Calendar/demo/:408:41
_postViewInit@https://twinssbc.github.io/Ionic2-Calendar/demo/:321:41
_viewTest@https://twinssbc.github.io/Ionic2-Calendar/demo/:374:39
_nextTrns@https://twinssbc.github.io/Ionic2-Calendar/demo/:218:46
_queueTrns@https://twinssbc.github.io/Ionic2-Calendar/demo/:200:35
push@https://twinssbc.github.io/Ionic2-Calendar/demo/:70:43
load@https://twinssbc.github.io/Ionic2-Calendar/demo/:99:34
select@https://twinssbc.github.io/Ionic2-Calendar/demo/:172:37
initTabs@https://twinssbc.github.io/Ionic2-Calendar/demo/:132:36
ngAfterViewInit@https://twinssbc.github.io/Ionic2-Calendar/demo/:110:34
detectChangesInternal
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectViewChildrenChanges@
https://twinssbc.github.io/Ionic2-Calendar/demo/:358:44
detectChangesInternal@
https://twinssbc.github.io/Ionic2-Calendar/demo/:343:51
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:144:45
_viewInsert@https://twinssbc.github.io/Ionic2-Calendar/demo/:422:65
_transition@https://twinssbc.github.io/Ionic2-Calendar/demo/:408:41
_postViewInit@https://twinssbc.github.io/Ionic2-Calendar/demo/:321:41
_viewTest@https://twinssbc.github.io/Ionic2-Calendar/demo/:374:39
_nextTrns@https://twinssbc.github.io/Ionic2-Calendar/demo/:218:46
_queueTrns@https://twinssbc.github.io/Ionic2-Calendar/demo/:200:35
push@https://twinssbc.github.io/Ionic2-Calendar/demo/:70:43
ngAfterViewInit@https://twinssbc.github.io/Ionic2-Calendar/demo/:77:34
detectChangesInternal
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectViewChildrenChanges@
https://twinssbc.github.io/Ionic2-Calendar/demo/:358:44
detectChangesInternal@
https://twinssbc.github.io/Ionic2-Calendar/demo/:343:51
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:144:45
ngOnInit@https://twinssbc.github.io/Ionic2-Calendar/demo/:47:65
detectChangesInternal
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:332:47
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:437:60
detectChanges@https://twinssbc.github.io/Ionic2-Calendar/demo/:144:45
https://twinssbc.github.io/Ionic2-Calendar/demo/:491:109
forEach@[native code]
tick@https://twinssbc.github.io/Ionic2-Calendar/demo/:491:57
_loadComponent@https://twinssbc.github.io/Ionic2-Calendar/demo/:469:30
bootstrap@https://twinssbc.github.io/Ionic2-Calendar/demo/:460:40
https://twinssbc.github.io/Ionic2-Calendar/demo/:362:110
forEach@[native code]
_moduleDoBootstrap@https://twinssbc.github.io/Ionic2-Calendar/demo/:362:61
https://twinssbc.github.io/Ionic2-Calendar/demo/:326:57
invoke@
https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:15941
onInvoke@https://twinssbc.github.io/Ionic2-Calendar/demo/:48:55
invoke@
https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:15895
run@https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:13329
https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:11428
invokeTask@
https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:16570
onInvokeTask@https://twinssbc.github.io/Ionic2-Calendar/demo/:39:59
invokeTask@
https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:16513
runTask@
https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:13935
a@https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:10549
invoke@
https://cdn.rawgit.com/angular/zone.js/v0.6.21/dist/zone.min.js:1:17719
handleError (demo:58)
(anonymous function) (demo:119)
invoke (zone.min.js:1:15942)
onInvoke (demo:48)
invoke (zone.min.js:1:15896)
run (zone.min.js:1:13330)
(anonymous function) (zone.min.js:1:11429)
invokeTask (zone.min.js:1:16571)
onInvokeTask (demo:39)
invokeTask (zone.min.js:1:16514)
runTask (zone.min.js:1:13936)
a (zone.min.js:1:10550)
invoke (zone.min.js:1:17720)

**Comment by twinssbc** [comment]
This error means failed to find the Intl library which is used for i18n.
Strangely I don't get this error in my Safari.
Could you check the Network tab in the Web Inspector that if intl.js is loaded and where is it loaded?
Thanks.

**Comment by panduit-psh** [comment]
I am experiencing the same issue both in Safari **on iOS 9.0.2** and a deployed ionic2 app on iOS 9.0.2. Both give the same error when I inspect in Web Inspector.

Demo error:
[Error] EXCEPTION: Error in ./CalendarComponent class CalendarComponent -
inline template:35:16 caused by: Can't find variable: Intl

App error:
[Error] EXCEPTION: Error in ./CalendarComponent class CalendarComponent -
inline template:65:16 caused by: Can't find variable: Intl

For the demo error, intl.js is halfway down the Network tab loaded from unpkg.com

**Comment by panduit-psh** [comment]
Figured it out. This relates to:

https://github.com/angular/universal/issues/516

**Comment by twinssbc** [comment]
@EnricoPicci @panduit-psh Are you able to fix this issue.
I did some research and found Intl issue seems to be solved in Safari 10+, so I'm not able to reproduce it.
I just added the Intl dependency back in the demo pages, could you check if the demo pages work for Safari 9.3?

Regarding the issue happens in Ionic serve or deployed version, could you try below things?
1. Check if Intl module appears in the npm repository
2. Check if the final built version contains the Intl module code.
3. Try adding below lines in your main ts file.

```
import 'intl';
import 'intl/locale-data/jsonp/en';
```

**Comment by EnricoPicci** [comment]
**@twinssbc** 
Now the demo works smoothly on my Safari 9.1.1 (on the Mac) as well as on my iPhone Safari (iOs 9.3.4).
The only point is that it is pretty slow to load (some seconds before seeing the calendar).
I will try a local demo to see if it is a network or server problem.
Thanks
