### ISSUE TITLE
Hide lines in the event block

### ISSUE THREAD

**Issue by Divyea** [twinssbc/Ionic2-Calendar#350]
Hi,

Can we hide the lines in the event block, i.e i want event to have full background without hour separation lines.

![image](https://user-images.githubusercontent.com/40061130/41577776-6306b022-73ac-11e8-8178-b1e21c52951b.png)

**Comment by twinssbc** [comment]
@Divyea Are you giving some transparency to your background color? If you take a look at the Demo page, it actually won't display the underlying lines.
