### ISSUE TITLE
Enhancement Request - Repeated Events

### ISSUE THREAD

**Issue by vohrahul** [twinssbc/Ionic2-Calendar#352]
Is there any way (or any plan) to have repeated events in this calendar plugin?

For example, if I have a data that says, a particular event happens every Monday and Friday starting from 1st June 2018. How can we achieve this?

I want to avoid making a custom array if there's a way in this plugin to achieve this.

**Comment by twinssbc** [comment]
@vohrahul Currently no plan to support repeated events internally. Because repeated event could be very flexible, for example, repeat every day, Wednesday bi-weekly, the first Thursday in every month... I think it's better to let user make custom array and pass to the calendar.

**Comment by vohrahul** [comment]
@twinssbc Thanks for the quick reply. It would be a great feature to add. But I understand you may have other priorities. Great plugin though.

**Comment by vancuren** [comment]
@vohrahul 

I accomplished this using ionic2-calendar with moment and moment-recur-ts. It takes some setting up but works like a charm once configured.

[moment-recur-ts](https://www.npmjs.com/package/moment-recur-ts) is a forked version of an older moment-recur no longer maintained.

**Comment by vohrahul** [comment]
> @vohrahul
> 
> I accomplished this using ionic2-calendar with moment and moment-recur-ts. It takes some setting up but works like a charm once configured.
> 
> [moment-recur-ts](https://www.npmjs.com/package/moment-recur-ts) is a forked version of an older moment-recur no longer maintained.

If I remember correctly, I did a more custom approach and modified the plugin a little in my local. Now I realise I should have forked and made a commit. Don't have the source code now. :(
