### ISSUE TITLE
onCurrentDateChanged triggered twice

### ISSUE THREAD

**Issue by Xiralv** [twinssbc/Ionic2-Calendar#354]
Hi Im facing a problem in the calendar. when I swipe on the day view the onCurrentDateChanged triggered twice

**Comment by twinssbc** [comment]
@Xiralv Is it possible you explicitly set the current date somewhere when onCurrentDateChanged is triggered?

**Comment by Xiralv** [comment]
Yes this is my bad sorry. You can close it now thanks
