### ISSUE TITLE
Display three days / tow days each time

### ISSUE THREAD

**Issue by Shtibel** [twinssbc/Ionic2-Calendar#356]
Hi there,
I want to display a week day mode but only 3 or 2 days each time.
How can I do it

See the image.
Thank you

![image](https://user-images.githubusercontent.com/24429607/42738641-a7b61896-888f-11e8-9b01-f14649ba9008.png)

**Comment by twinssbc** [comment]
@Shtibel Unfortunately, this calendar is not capable to display like that. When swiping to the previous/next view, the calculation is always based on the whole week.

**Comment by Shtibel** [comment]
OK,
Can it be done with queryMode?
Or is this option expected if future versions?

The 3 day mode is standard in google calendar.
I it more visual to see 3 day mode where more text and data can be displayed.
I think it will be grate to have this option and I think it is pretty simple to implement.

Hop you will consider to add it to the next version.
Thank to in advanced :-) 

See this print screen 

![screenshot_2018-07-17-16-42-03_2](https://user-images.githubusercontent.com/24429607/42821189-ac9d02e6-89e0-11e8-9a1b-654a5d442f66.png)


![screenshot_2018-07-17-16-40-42](https://user-images.githubusercontent.com/24429607/42821216-b9cea0b4-89e0-11e8-85e8-ed0f7f0acdf7.png)
