### ISSUE TITLE
Set format of formatWeekViewDayHeader with HTML

### ISSUE THREAD

**Issue by Shtibel** [twinssbc/Ionic2-Calendar#358]
Hi,
How can I add HTML to the formatWeekViewDayHeader ?

I want it to look like this:
![image](https://user-images.githubusercontent.com/24429607/42748535-3581e7dc-88e9-11e8-81a7-f0e29ecf32d4.png)

So i try to do this:
`[formatWeekViewDayHeader]="<div class='my-day'>d</div><div class='my-day-name'>EEE</div>"`

But it dose not work.

**Comment by twinssbc** [comment]
@Shtibel The formatWeekViewDayHeader allows you to return custom text, but it doesn't support raw HTML content.

**Comment by Shtibel** [comment]
Thank you for your answer,
Can you please add an example how to do it with the formatWeekViewDayHeader?

**Comment by twinssbc** [comment]
@Shtibel 
```
<calendar ... formatWeekViewDayHeader="EEE"></calendar>
```

**Comment by KishoreKoushik** [comment]
@Shtibel Could you achieve what you wanted. If yes, can you please let me know, how you did it ?

**Comment by twinssbc** [comment]
@KishoreKoushik You could use "EEE d" to display the date part. As I explained, it's not possible to customize the content to put date under week.

**Comment by rbertolig** [comment]
Hi!, just wanted to share a simple workaround I used to display the day number under the week day name on the week view:
just need to set the `formatWeekViewDayHeader="d"` and add one row with the seven cols before the 'calendar' tags, ex:
```
    <ion-toolbar *ngIf="calendar.mode==='week'" class="ion-no-border">
        <ion-row class="ion-no-border" style="padding-left: 65px; margin: auto; text-align: center;">
            <ion-col>MON</ion-col>
            <ion-col>TUE</ion-col>
            <ion-col>WED</ion-col>
            <ion-col>THU</ion-col>
            <ion-col>FRI</ion-col>
            <ion-col>SAT</ion-col>
            <ion-col>SUN</ion-col>
        </ion-row>
    </ion-toolbar>
```
I use it inside the page header that is why also used the ion-toolbar, that way the week day title can be customized with colors and fonts etc, using css / style. See attached.
![Snap 2020-07-02 at 02 46 39](https://user-images.githubusercontent.com/63571703/86325669-d067fe00-bc16-11ea-85c6-4c15a1234777.png)
