### ISSUE TITLE
How to show 2 and a half Days of the calendar and scroll to show the others days per week

### ISSUE THREAD

**Issue by shomronh** [twinssbc/Ionic2-Calendar#359]
Hello

I would like to know if it's possible to show for example 2 and a half days of the calendar and then if the user want to, he can scroll to the left/right to see the other days as well.

This functionality should be possible for weeks and month of course

Hopefully there is a quick solution for that 

Thanks a lot

Shomron.

**Comment by twinssbc** [comment]
@shomronh It's not possible. The calculation logic in the calendar is always based on the whole month or week.
