### ISSUE TITLE
Performance in Android API 23. Wrong me.slider.getActiveIndex()

### ISSUE THREAD

**Issue by rgarciape** [twinssbc/Ionic2-Calendar#36]
Hi!!

I´m running the app with **ionic run android** command using API23 of Android and the app behaviour is diferent that when I run the application with **ionic serve**.

The issue appears just when the app is started due to the active index of slider components is 2 (me.slider.getActiveIndex()).

When I obtain this index testing in the device is 2, and when I test it in the browser is 0 (the expected value)

Could you know why this result?

**Comment by tryadelion** [comment]
sounds like a possible cause of the android load times
