### ISSUE TITLE
Remove the divider between the day headings in week view

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#361]
Hi,
 How can I remove the divider line between the day headers in the week view

**Comment by twinssbc** [comment]
@KishoreKoushik The calendar itself doesn't expose such option. You could  override the CSS style.

**Comment by KishoreKoushik** [comment]
yea. I tried using the css. But it removes the divider for the entire calendar. Not just for week header

**Comment by twinssbc** [comment]
@KishoreKoushik You probably use a quite generic CSS selection rule. You could try a more strict rule to only limit the scope on the day header element.
