### ISSUE TITLE
Weekview - startingDayWeek set 1, do not show the allDay event on Monday

### ISSUE THREAD

**Issue by Bogdan45** [twinssbc/Ionic2-Calendar#365]
Hi,
when i set the startingDayWeek to 1 the Monday allDay Event will not displayed in the weeklyView. And other allDay events will be 1 day earlier then they should.

Version 0.4.4

**Comment by twinssbc** [comment]
@Bogdan45 How do you generate the allDay event? Did you use UTC time? I don't think it's related to startingDayWeek. It's probably because you just use the way same as normal event to generate the all day event. When calendar calculates it, it shifts couple hours to the previous day.
