### ISSUE TITLE
Update current View

### ISSUE THREAD

**Issue by Anujmoglix** [twinssbc/Ionic2-Calendar#367]
Hi ,
  I have one requirement that i want to show popup on click on any date then after updating calendar will update . Everything is work fine but i am using event and updating it so view is moving to default date ( current date) like august but  i want to be on that month where i was previously like september.

```
 this.events.subscribe('reloadPage1',() => {
         // this.getVenueList();
          var firstDate =new Date( this.changedDate.getFullYear(),  this.changedDate.getMonth(), 1);
          this.showEvents(this.myVenue,this.mySpace,this.formatDate2(firstDate));
          var mySwiper = document.querySelector('.swiper-container')['swiper'];
          //mySwiper.slideNext();
          //mySwiper.slidePrev();
      });
```

**Comment by twinssbc** [comment]
@Anujmoglix Let's say if you bind the current date in HTML like [currentDate]="calendar.currentDate", then you could set the calendar.currentDate to a date in September, the calendar will navigate to that month automatically.
