### ISSUE TITLE
Highlight current day in day view and week view

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#369]
I want to display current date with a color in all day column in day view and column view. How can I do that?
 Currently I am using the custom template and changing the background of all day if there is any all day event. How can I do that for current day even if there is no event.

**Comment by twinssbc** [comment]
@KishoreKoushik You could use weekviewAllDayEventSectionTemplate and weekviewNormalEventSectionTemplate. They are for the table part of the weekview instead of the individual event itself. So it should meet your requirement. Corresponding options are also available for day view.
