### ISSUE TITLE
#week on title incorrect

### ISSUE THREAD

**Issue by mgarciadash** [twinssbc/Ionic2-Calendar#37]
On Week view, # of week says this week is #52 of 2016, but isnt in fact is #1 of 2017.

**Comment by twinssbc** [comment]
@mgarciadash I have fixed this bug in version 0.1.1. Thanks for reporting it.

**Comment by mgarciadash** [comment]
Thanks to You !!

**Comment by mgarciadash** [comment]
Btw ...  Maybe the question not belongs here, but ...
How can i hide "all Day" row in weekView ???

**Comment by twinssbc** [comment]
There's no option exposed to hide "all Day" row.
You need to modify the source code.
