### ISSUE TITLE
Event dots misplaced when Daylight Savings Timezone months in Month view

### ISSUE THREAD

**Issue by sundaramoorthyjeeva** [twinssbc/Ionic2-Calendar#370]
I am using Ionic2-Calendar in my Ionic mobile application. As of the documentation instruction I passed start and end date of an event. I passed the below from and to date objects to the calendar.

**From** : Wed Feb 14 2018 00:00:00 GMT -1100
**To** : Wed Feb 14 2018 23:59:59 GMT -1100

My expected output is to place the event dot on Feb 14. But the event dot placed on the next day. That means Feb 15. 

Here I attached the output screen for your reference.

**Note** : This issue is occurring in the Daylight Saving Timezone months only. Kindly assist for this issue.

![image](https://user-images.githubusercontent.com/5718408/43641837-bf6f2100-9742-11e8-9e7e-3a47037a4d9c.png)

**Comment by twinssbc** [comment]
@sundaramoorthyjeeva So the calendar is using the current local timezone of your device to place the events. It may appear in another day if the timezone is different. Also it seems you want to create an all day event, the calendar provides that type of event, you could directly use it.

**Comment by gjwade** [comment]
@sundaramoorthyjeeva i am a newer with ionic, could you paste the code how to display event dots and the left/right arrow in the header,3q
