### ISSUE TITLE
Rendering inactive day and week view templates

### ISSUE THREAD

**Issue by Brand0n** [twinssbc/Ionic2-Calendar#371]
Hi there. Firstly just want to say thanks for the awesome calendar, I really enjoy the flexibility of it. I'm using it in remote queryMode with day and week views for displaying assigned jobs to technicians. 

I'm pulling data for 3 consecutive days / weeks depending on what mode you're in, with the idea that I'll be able to show the next and previous slide when you swipe left or right for a better user experience while still keeping the returned data from the server to a minimum. 

Problem is the events only seem to render for the day you're on, and "pop" in once you release after a swipe. I see you have a template for the inactive month views, monthviewInactiveDisplayEventTemplate, is it possible to please get the same thing for day and week views?

**Comment by radious15** [comment]
Hello!

Thanks a lot for the awesome calendar, it really helps and the customization options are the best!

I have the same requirement as Brand0n, I am trying to get rid of the delay between switching from one week/day to another and the display of the events.

Would it be possible to have the same monthViewInactiveDIsplayEventTemplate for week and day? 
My ultimate goal if I cannot get rid of the delay would be to add an app-shell when you swipe with 4 or 5 "fake" events.

Thanks a lot and have a great day!
Radious

**Comment by twinssbc** [comment]
@radious15 I get the idea, will spend some time on it.

**Comment by radious15** [comment]
@twinssbc thank you! I disabled the swipe for now :)

**Comment by twinssbc** [comment]
@radious15 I added disabled template options in version 0.5.5. Feel free to give a try. You could find more information in README.
