### ISSUE TITLE
Not compatible with ionic v 4 

### ISSUE THREAD

**Issue by hugoblanc** [twinssbc/Ionic2-Calendar#372]
Due to the new version of RxJS, the way to import Observable is not correct anymore:

> [ng] node_modules/ionic2-calendar/calendar.service.d.ts(1,10): error TS2305: Module '"C:/programming/studay/node_modules/rxjs/Observable"' has no exported member 'Observable'.

`import { Observable } from "rxjs/Observable";` should be  `import { Observable } from "rxjs";`

I don't know for the rest of the plugin

**Comment by marticrespi** [comment]
@hugoblanc  he shoud upgrade this part, but you can pass this error installing rxjs-compat

`npm i rxjs-compat --save`

This is not a problem with ionic v4, the real problem with ionic 4 is that this library is based on ionic 3 and you when try to serve or build the project shows these errors:

`[ng] ERROR in node_modules/ionic2-calendar/dayview.d.ts(1,24): error TS2307: Cannot find module 'ionic-angular'.
[ng] node_modules/ionic2-calendar/monthview.d.ts(2,24): error TS2307: Cannot find module 'ionic-angular'.
[ng] node_modules/ionic2-calendar/weekview.d.ts(1,24): error TS2307: Cannot find module 'ionic-angular'.`

This is the main reason that it's not compatible with ionic v4.

@twinssbc , is planned to upgrade from `ionic-angular`(3) to `@ionic/angular`(4)?

**Comment by twinssbc** [comment]
@marticrespi Yes, I will upgrade the dependency.

**Comment by marticrespi** [comment]
@twinssbc perfect! Will you wait to oficial release, right? 

Many thanks!

**Comment by twinssbc** [comment]
@marticrespi I'm waiting for the official release.

**Comment by deemi47** [comment]
Me also waiting , can i get simple steps for installing this on Ionic4?

**Comment by iamanandacharya** [comment]
@twinssbc 
Hi please updating this issue.
when it will be compatible with v4?

**Comment by mathisschuelingkamp** [comment]
@twinssbc Could you please give us an update on this? Really waiting for it

**Comment by twinssbc** [comment]
I have released 0.5.0 version to support Ionic v4. The only incompatible feature is **dir** option which is removed from the ion-slides in Ionic v4.
Feel free to have a try.

**Comment by mathisschuelingkamp** [comment]
@twinssbc Works great now, thank you! Love this calendar since ionic1
