### ISSUE TITLE
Do not want the current day to be selected

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#373]
Hi. I do not want the current date to be selected, whenever I swipe to and fro in the month view. But whenever I click on a date it should get selected. I f I use [autoSelect]="false", it is not selecting the date when swiping through the months but its not selecting even if I click on any date.

**Comment by twinssbc** [comment]
@KishoreKoushik I could confirm that the date will be selected if I click on any date when autoSelect is set to false.

**Comment by KishoreKoushik** [comment]
@twinssbc yea current day will be highlighted but in click of other date it is not highlighted but it will be selected in the background. Only thing is used will not know it's selected

**Comment by twinssbc** [comment]
@KishoreKoushik Did you override some css style or used some custom template? By default, the selected date will be highlighted with green background color.

**Comment by KishoreKoushik** [comment]
No. I am not using any custom template. I am just using the calendar tag straight forward. I have attached the view. Suppose today is 30th, it will highlight 30th of every month. I want it to highlight 30th of only current month.


<img width="203" alt="screenshot_1" src="https://user-images.githubusercontent.com/22149302/44852217-4cdad000-ac80-11e8-8048-e0921ebd3cd5.png">

**Comment by twinssbc** [comment]
@KishoreKoushik By default, the cell selected will have the monthview-selected css class and its background color of this class will be green. You could override the style to make it transparent. The current day will have the monthview-current css class. You could override the style to pick up a proper background color.

**Comment by KishoreKoushik** [comment]
Can you please guide me how to do that? I want only the today to be
selected, but not in all the months.
