### ISSUE TITLE
Is there a posibility to add text in the month-view days cells ?

### ISSUE THREAD

**Issue by kasback** [twinssbc/Ionic2-Calendar#374]
Hi ! first i want to thank you for your usefull and great plugin.
I wanted to know if there is a way to add some text in the month view <td>'s programatically, something like this : 
![image](https://user-images.githubusercontent.com/38462714/44789839-88e53680-ab95-11e8-9c88-1dee664cb262.png)
thanks.

**Comment by twinssbc** [comment]
@kasback Yes, you could take a look at monthviewDisplayEventTemplate option in README. It allows you specify a custom template for each cell content.

**Comment by kasback** [comment]
Can you please provide an simple example , like if i want to add the event name to the cell from your loadEvents() function.

**Comment by twinssbc** [comment]
@kasback 
So you could have a template like below in your HTML
```
  <ng-template #monthviewtemplate let-view="view" let-row="row" let-col="col">
    {{view.dates[row*7+col].label}}{{view.dates[row*7+col].events[0]?.eventName}}
  </ng-template>
```
To use it, 
```
  <calendar ... [monthviewDisplayEventTemplate]="monthviewtemplate"></calendar>
```

And in your loadEvents function, you could set the proper value to the eventName property.
