### ISSUE TITLE
Calendar monthview not updating when the previous day is clicked on the previous month

### ISSUE THREAD

**Issue by jayzyaj** [twinssbc/Ionic2-Calendar#378]
When I try to click on the previous day of the previous month. For example today is **Sept 11 9:59 AM** here on **Philippines**. Then I try to click on the **previous day** that day is on **august** which is the **previous month**. I would like also to change the monthview of the calendar to August automatically when I click on the day the belongs to that month.

**Comment by twinssbc** [comment]
@jayzyaj The calendar should automatically switch to the previous month, I can achieve that from the demo page. Did you do any customization? Is there any error printed in the console?

**Comment by jayzyaj** [comment]
@twinssbc sorry I did some customization that affected the calendar. It is working now. But can I ask just one question before closing this issue. How can I call the slide to the next month and previous month programmatically?
