### ISSUE TITLE
Calendar not show events in iOS

### ISSUE THREAD

**Issue by MoisesGT** [twinssbc/Ionic2-Calendar#380]
Calendar display events in Android and browser, but can not show events on iphone,
Actually, I receive calendar events from my API in the title change event to optimize the performance of my application, but the events are not shown in iOS.

**This is my code in calendar.html**

<calendar [eventSource]="eventSource" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate" (onEventSelected)="onEventSelected($event)" (onTitleChanged)="onViewTitleChanged($event)" (onTimeSelected)="onTimeSelected($event)" step="30" class="calendar" [noEventsLabel]="calendar.noEventsLabel">
</calendar>

**This is my code in calendar.ts**

**//I get the events from my API**
let customDate = '';
      this.viewTitle = title;
       let partDate = title.split(' ');
        **// I get my custom date in format "YYYY-MM-DD", 
        // I get the title of clendar for example "September 2018" and i make a split and convert name 
        //month in number whith getMonth() function** 
        customDate = `${partDate[1]}-${this.getMonth(partDate[0])}-${'01'}`;

**//This promise get the events from my API**

this.calendarService.getEvents(customDate.toString()).then(data => {
      console.log("Calendar data" + data);
      this.loadEvents(data);
    }).catch(err => {
      console.log(err.error); 
    });

**//The load events method**
  loadEvents(eventsData) {
    if (eventsData) {
      let events = [];
      for (const monthEvent of eventsData) {
        let eventData:any = {};
        const startTime = new Date(monthEvent.starting_date); 
        const endTime = new Date(monthEvent.ending_date);

        eventData.startTime = startTime;
        eventData.endTime = endTime;
        eventData.title = monthEvent.name_event;
        eventData.center = monthEvent.centers;

        if(startTime.getDay() === endTime.getDay()){
          eventData.allDay = false; 
        }else{
          eventData.allDay = true; 
        }
        events.push(eventData);
      }
      setTimeout(() => {
        this.eventSource = events;
        console.log("Events: " + this.eventSource);
      });
    }
  }
I can get my API events but for some reason they are not shown in iOS but in Android and in the browser

I need solve this problem please,

**Comment by indraraj26** [comment]
i am having the same issue @twinssbc  Please look into this issue

**Comment by twinssbc** [comment]
@indraraj26 Could you check if the startTime and endTime you passed in is valid? There's some date parsing function not supported in Safari.

**Comment by indraraj26** [comment]
@twinssbc i can see you already added intl support to your ionic2 calendar but it doesn't seems to work, even i have added intl in main.ts still i cant see event in ios but it works perfectly in android/google chrome.

version of your plugin:

> "ionic2-calendar": "^0.4.6"

version of intl

>   "intl": "^1.2.5",

version of ionic

>  "ionic-angular": "3.9.2",

this is how i am parsing date for eventSource
code:
````
 calEvents.forEach(function (value) {
          value.startTime = new Date(Date.parse(value.startTime));
          value.endTime = new Date(Date.parse(value.endTime));
          console.log(value.startTime);
          console.log(value.endTime);
          value.date = value.followup_date.split(' ');
          console.log(value.date)
          events.push(value);
        });
````
Output:
````

````

**Comment by twinssbc** [comment]
@indraraj26 The problem is not related to Intl, but Date.parse function.
Check below discussion.
https://stackoverflow.com/questions/6427204/date-parsing-in-javascript-is-different-between-safari-and-chrome

**Comment by indraraj26** [comment]
Dear @twinssbc , 

Thank you for your awesome plugin for free :) 
Let me try stackoverflow solution will get back you with response if that work.

**Comment by twinssbc** [comment]
@indraraj26 No, it accepts a Date object. You need to convert the string to Date.

**Comment by vagnersabadi** [comment]
If someone is having invalid date issues only in IOS one solution I found was to apply replace within new Date()
``  array.data.map((a: any) => {
        this.eventSource.push({
          title: a.title,
          **_startTime: new Date(a.start_at.replace(/-/g, "/")),
          endTime: new Date(a.end_at.replace(/-/g, "/")),_**
          allDay: false,
        });
      });``


works on both android and IOS

**Comment by mike-pin1** [comment]
If you are doing this
`startTime: new Date('2019-09-19T10:30.000Z')`

This format is not supported in Safari. You'll have to replace '-' with '/', remove the T and everything after the dot (.000Z)
`startTime: new Date(('2019-09-19T10:30.000Z').replace(/-/g, '/').replace('T', ' ').replace(/\..*|\+.*/, ''))`

**Comment by timstoute** [comment]
I'm still stuck with this; my start_date timestamp comes out of Firestore like this:

Timestamp {seconds: 1571769000, nanoseconds: 0}

And then

startTime: (doc["start_date"]).toDate(),

works properly in Chrome / Android, but I cannot get it working in Safari / IOS.

Using Angular / TypeScript / Ionic 4 - I've tried the replacements suggested above with no success. Any advice appreciated.

**Comment by vagnersabadi** [comment]
try using lib momentjs. Example


```javascript
let startTime = new Date(moment(ev.startDate).toDate());
let endTime = new Date(moment(ev.endDate).toDate());
this.calendarEvents = this.calendarEvents.concat({
          title: ev.title,
          start: startTime,
          end: endTime,
          allDay: false,
          color: color,
          draggable: false,
          id: (this.calendarEvents.length),
          editable: false,
        });
```

**Comment by timstoute** [comment]
@vagnersabadi  thanks for the nudge to use momentjs. This is what worked for me:

 let startTimeMomentObj = moment(doc["start_date"].toDate(), 'MMMM Do YYYY, h:mm:ss a')
 let endTimeMomentObj = moment(doc["end_date"].toDate(), 'MMMM Do YYYY, h:mm:ss a')

let event = {
            startTime: startTimeMomentObj.toDate(),
            endTime: endTimeMomentObj.toDate(),
            ...
}
