### ISSUE TITLE
Events Display in Day View is not correct

### ISSUE THREAD

**Issue by mowaiskalam** [twinssbc/Ionic2-Calendar#382]
Hi, I am using this tool in my app. First of all, it's great, Thanks for making it.

The problem I am facing is about the events displaying in day event is not correct. The events are not matching with the correct minute line. Like if event time in any day is **9:30 am - 11:15 am** then same day another event is **11:45 am - 13:15 am**, there should be a gap between these two events in day view but currently no gap is showing between them.

I just checked the demo, for making sure that it should not be because of my CSS.

Here are the attached images from the available demo:

**Month View** (for checking the event time of the selected date)
![image](https://user-images.githubusercontent.com/17184822/46248837-3f0f9a80-c438-11e8-9b2c-0f0e79467b9f.png)

**Day View**
![image](https://user-images.githubusercontent.com/17184822/46248840-65353a80-c438-11e8-9ae6-3fdd5f116dc0.png)

I need it urgently as my app is near to complete I just found this bug. Any help would be highly appreciated.

Thanks

**Comment by mowaiskalam** [comment]
@twinssbc any reply on this?

Thanks

**Comment by twinssbc** [comment]
@mowaiskalam I think this is because you set the **step** option to 30, which means the event ends at 11:15 will occupy the first half of the hour, and the event starts at 11:45 will occupy the second half of the hour. You could try set the step option to 15.

**Comment by mowaiskalam** [comment]
@twinssbc Thanks for letting me know about **step** option, it works for me. But I am confused about its usage now. When I set it to **1** my events are placing with the gap, when I set it to **10** it works for me as excepted. But the problem is my event can be off any time, but cannot overlap, can you suggest me that what I should set in **step** option which works in every case for me.

Thanks for the reply btw!

**Comment by twinssbc** [comment]
@mowaiskalam The supported values of **step** are only 15, 30 and 60 (by default). Although setting it to smaller value may work, that's not officially supported. The reason to have step option is to be able to place the event accurately in one hour. But it doesn't make sense to place it too accurately, for example, at one minute level, as user can't tell the difference from a mobile device. 
So I'm afraid it can't meet your requirement. The calendar is designed to support multiple events happen at the same time, it will work out the placement automatically.

**Comment by mowaiskalam** [comment]
Hmm. Thanks for the information. I will check it with my scenarios. Closing this, since the issue is supposed to be resolved when setting 5 in step option. Thanks
