### ISSUE TITLE
event.title multiline or HTML

### ISSUE THREAD

**Issue by rodrigoguariento** [twinssbc/Ionic2-Calendar#384]
Dears, does someone know if is possible to write two or more lines (or HTML formatted) for each event.title (inside eventSource)? Thanks!

**Comment by twinssbc** [comment]
@rodrigoguariento By default, if the text exceeds the width, it will automatically wrap the text into next line. If you want to make the content formatted, you could use the customized template.

For example, below is the default template,
```
        <ng-template #template let-displayEvent="displayEvent">
            <div class="calendar-event-inner">{{displayEvent.event.title}}</div>
        </ng-template>
```

You could give event two properties, title1, title2, then use any HTML format you want to display them.

**Comment by rodrigoguariento** [comment]
I'm using Ionic 3, and into html page I have:

`  <calendar
    [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate"
    [locale]="calendar.locale"
    (onEventSelected)="onEventSelected($event)"
    (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)"
    (onCurrentDateChanged)="onCurrentDateChanged($event)"
    (onRangeChanged)="reloadSource(startTime, endTime)"
    step="30"
    class="calendar"></calendar>
`

To add events, I just push objects into eventSource array. Then, what would be the solution under this situation? Thanks.

**Comment by twinssbc** [comment]
@rodrigoguariento You could have your event object looks like 
```
        events.push({
          startTime: startTime,
          endTime: endTime,
          allDay: false,
          student: 'studentA',
          teacher: 'teacherB'
        });
```

Then in HTML, you could use below
```
        <ng-template #template let-displayEvent="displayEvent">
            <div class="calendar-event-inner">{{displayEvent.event.student}}<br>{{displayEvent.event.teacher}}</div>
        </ng-template>

        <calendar ... [weekviewNormalEventTemplate]="template"></calendar>
```

**Comment by rodrigoguariento** [comment]
Thanks!
