### ISSUE TITLE
not working ionic2 demo Link 

### ISSUE THREAD

**Issue by timepass-ok** [twinssbc/Ionic2-Calendar#385]
https://twinssbc.github.io/Ionic2-Calendar/demo/

**Comment by twinssbc** [comment]
@shashical Which browser are you using to view the demo page? Any error printed out in the console?

**Comment by shashical** [comment]
Ubuntu mozila firefox with no console

**Comment by twinssbc** [comment]
@shashical I tried in Firefox, it's working. You could open the console in the "Web Developer" menu.

**Comment by twinssbc** [comment]
@shashical What popup window? #217 is not related to this.
