### ISSUE TITLE
Using monthviewEventDetailTemplate to change only event.title

### ISSUE THREAD

**Issue by rodrigoguariento** [twinssbc/Ionic2-Calendar#386]
Dears, I would like to change only "title" of each event displayed this kind of view. For example: show "student_name" and "teacher_name" instead of "title" alone for each line.

Looking for "monthviewEventDetailTemplate"...

`
<ng-template #template let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
...
</ ng-template>

<calendar ... [monthviewEventDetailTemplate]="template"></calendar>
`

... I haven't found what is the content of **(...)** in this example (inner ng-template tags) to reproduce the same list, changing only what I need. Does someone know how to make this changes that I need?

**Comment by twinssbc** [comment]
@rodrigoguariento Here is the default one. You could update it accordingly.
```
        <ng-template #monthviewDefaultEventDetailTemplate let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
            <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
                <ion-item *ngFor="let event of selectedDate?.events" (click)="eventSelected(event)">
                        <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                            -
                            {{event.endTime|date: 'HH:mm'}}
                        </span>
                    <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn">{{allDayLabel}}</span>
                    <span class="event-detail">  |  {{event.title}}</span>
                </ion-item>
                <ion-item *ngIf="selectedDate?.events.length==0">
                    <div class="no-events-label">{{noEventsLabel}}</div>
                </ion-item>
            </ion-list>
        </ng-template>
```

**Comment by ghost** [comment]
Hi,
Where can I found the default ones for daily and weekly events?
Thanks and great job for ionic2-calendar!

**Comment by twinssbc** [comment]
@cyber-greg It is in 
https://github.com/twinssbc/Ionic2-Calendar/blob/v5/src/calendar.ts
