### ISSUE TITLE
Change `startHour` and `endHour` on day change

### ISSUE THREAD

**Issue by mowaiskalam** [twinssbc/Ionic2-Calendar#388]
Hi, I have a scenario. If we are on day view, my clients want to narrow down the calendar by setting `startHour` and `endHour` field to the nearest event, Like:

> Calendar will start one hour before the first appointment and will end one hour after last appointment (is case it is before 11pm). For example: in a given day, the first appointment starts at 2pm and the last appointment ends at 5:30pm. The calendar hours in this day should range from 1pm to 7pm

I tried doing this on the day change event but no luck, startHour and endHour not changing instantly. 

Also, I have a scenario to not show the calendar when no events are there on a day, but we don't have any hide calendar property, and we cannot set startHour and endHour to 0.

Please, Let me know how can i acheive the above scenarios. Thanks

**Comment by twinssbc** [comment]
@mowaiskalam Unfortunately it doesn't support changing startHour and endHour on the fly. They are used when the day view is initialized at the first time, later if you swipe to other day, the initialization code won't be triggered again. Also bear in mind, your events probably is fetched asynchronously, so once you fetch the events, the day view is already rendered. So you also can't change the startHour and endHour afterwards.

You could simply use ngIf to hide and show the calendar.

**Comment by mowaiskalam** [comment]
Hi, Thanks for the information. If I use ngIf to hide the calendar. I have to bind its events again when I will show it. Don't you think we should have hide option as well because It is not good to re-render complete calendar every time on day change.

**Comment by twinssbc** [comment]
@mowaiskalam If you don't want the calendar gets re-rendered every time, you could bind a variable to [hidden].

**Comment by mowaiskalam** [comment]
Thanks for the info. Although, I achieve using [ngClass].
