### ISSUE TITLE
'typings' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by clementino36** [twinssbc/Ionic2-Calendar#39]
Hi,

Whenever I am running `npm install ionic2-calendar --save`, I am getting the following:

> ionic2-calendar@0.1.1 postinstall C:\Users\Emixis\Documents\Ionic2\Apps\MainApp\node_modules\ionic2-calendar
> typings install
> 
> 'typings' is not recognized as an internal or external command,
> operable program or batch file.

I ran npm install typings --global successfully.
I have added "typings": "2.1.0" to my package.json's dependencies.
The PATH to my npm folder is correct.

Thanks

**Comment by twinssbc** [comment]
@clementino36 This looks like some environment configuration issue.
The post install script simply runs "typings install" command.
If you run "typings --version" in your command line prompt, what's the output?
If it still displays the same error, that means typings executable has not been found in the system.
Could you check if typings module appears in your npm folder? And what's the path of typings executable? It should be searchable from the PATH.

**Comment by clementino36** [comment]
The output is the same indeed.
Do you mean in my project's npm folder ? No typings folder there nor in `AppData\Roaming\npm`.
I do have a typings folder in my project's folder (next to src, www, etc...).
Not I am getting what you mean by the path of typings executable, I have nothing related to typings in my PATH, only 3 lines there:

> C:\Program Files (x86)\Microsoft VS Code\bin
> %USERPROFILE%\AppData\Local\Microsoft\WindowsApps
> C:\Users\Emixis\AppData\Roaming\npm

**Comment by unional** [comment]
Should not use `postinstall` to do `typings install`. The consumer do not necessary have `typings` installed globally.

Please use `prepublish`.

**Comment by clementino36** [comment]
I got it working!
Refer to [#753](https://github.com/typings/typings/issues/753)
