### ISSUE TITLE
Separate click event on click of day headings in week view

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#390]
Do we have a separate click event for click on day headings in week view rather than onEventSelected and onTimeSelected.

**Comment by twinssbc** [comment]
@KishoreKoushik In the latest version, 0.4.5, if you click the day header in weekview, onCurrentDateChanged and onTimeSelected events will be triggered.

**Comment by KishoreKoushik** [comment]
@twinssbc Both the events return selected date with time 12. How can we make out user has clicked on the header ?

**Comment by twinssbc** [comment]
@KishoreKoushik I think you could just use onCurrentDataChanged event, it will only be triggered when user clicked the header in the week view.

**Comment by KishoreKoushik** [comment]
@twinssbc I am using onTimeSelected event also. Even onCurrentDataChanged events returns the same data as the onTimeSelected

selectedTime: Wed Nov 07 2018 12:00:00 GMT+0530 (India Standard Time) {endTime: 1541574000000}

I am unable to differentiate

**Comment by twinssbc** [comment]
@KishoreKoushik You want to do something when the day header is clicked, right? Then you just need to add logic in onCurrentDateChanged event, and ignore the onTimeSelected event triggered at the same time.

**Comment by newzhongdan** [comment]
thanks you for add the funcionality :D what archive i can edit for add week days on dayview? is necesary for change of day (example jump from sunday to friday) :P

**Comment by twinssbc** [comment]
@newzhongdan Sorry, I don't quite get your question. What do you mean add week days on dayview?
