### ISSUE TITLE
ionic2-calendar Can't bind to 'eventSource'

### ISSUE THREAD

**Issue by eggysudianto** [twinssbc/Ionic2-Calendar#392]
I'm try use this ionic-calendar in blank project and it work.
but when I implement this plugin to my project, it not work with error.

`VM40:37 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'eventSource' since it isn't a known property of 'calendar'. ("
<ion-content class="has-header">

    <calendar [ERROR ->][eventSource]="eventSource"

              [calendarMode]="calendar.mode"
"): ng:///AgendaPageModule/AgendaPage.html@28:14
Can't bind to 'calendarMode' since it isn't a known property of 'calendar'. ("
    <calendar [eventSource]="eventSource"

              [ERROR ->][calendarMode]="calendar.mode"

              [currentDate]="calendar.currentDate"
"): ng:///AgendaPageModule/AgendaPage.html@30:14
Can't bind to 'currentDate' since it isn't a known property of 'calendar'. ("
              [calendarMode]="calendar.mode"

              [ERROR ->][currentDate]="calendar.currentDate"

              (onCurrentDateChanged)="onCurrentDateChanged($eve"): ng:///AgendaPageModule/AgendaPage.html@32:14
'calendar' is not a known element:
1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<ion-content class="has-header">

    [ERROR ->]<calendar [eventSource]="eventSource"

              [calendarMode]="calendar.mode"
"): ng:///AgendaPageModule/AgendaPage.html@28:4
Error: Template parse errors:
Can't bind to 'eventSource' since it isn't a known property of 'calendar'. ("
<ion-content class="has-header">

    <calendar [ERROR ->][eventSource]="eventSource"

              [calendarMode]="calendar.mode"
"): ng:///AgendaPageModule/AgendaPage.html@28:14
Can't bind to 'calendarMode' since it isn't a known property of 'calendar'. ("
    <calendar [eventSource]="eventSource"

              [ERROR ->][calendarMode]="calendar.mode"

              [currentDate]="calendar.currentDate"
"): ng:///AgendaPageModule/AgendaPage.html@30:14
Can't bind to 'currentDate' since it isn't a known property of 'calendar'. ("
              [calendarMode]="calendar.mode"

              [ERROR ->][currentDate]="calendar.currentDate"

              (onCurrentDateChanged)="onCurrentDateChanged($eve"): ng:///AgendaPageModule/AgendaPage.html@32:14
'calendar' is not a known element:
1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<ion-content class="has-header">

    [ERROR ->]<calendar [eventSource]="eventSource"

              [calendarMode]="calendar.mode"`

how to fix that? I'm sure the code calendar is same with my blank project

**Comment by twinssbc** [comment]
@eggysudianto Did you import the calendar module?

**Comment by stefanvangastel** [comment]
Same issue here, imported the calendar module in `app.module.ts`:

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule, 
    NgCalendarModule, 
    IonicModule.forRoot(), 
    AppRoutingModule],
  providers: [
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by twinssbc** [comment]
@stefanvangastel Are you using PageModule? If so, you need to import the calendar module in the page module file.

**Comment by karouAhmed** [comment]
@twinssbc i have the same problem ,how to import the calendar module in the module file please ??

**Comment by twinssbc** [comment]
@karouAhmed What error did you get? Are you using the PageModule?

**Comment by Ultimate-System** [comment]
I have solved it in the following way

**mypage.module.ts**

`import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  declarations: [
    MyPage
  ],
  imports: [
    IonicPageModule.forChild(MyPage),
    NgCalendarModule
  ],
  entryComponents: [
    MyPage
  ]
})
export class MyPageModule {}`

**mypage.ts**

`import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-mypage',
  templateUrl: 'mypage.html',
})
export class MyPage{

  eventSource;
  viewTitle;

  isToday:boolean;
  calendar = {
      mode: 'month',
      currentDate: new Date()
  };

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

}`

**mypage.html**
`<ion-header>

  <ion-navbar>
    <ion-title>cita</ion-title>
  </ion-navbar>

</ion-header>


<ion-content>
  <calendar
  [eventSource]="eventSource"
  [calendarMode]="calendar.mode"
  [currentDate]="calendar.currentDate"
  step="30">
  </calendar>
</ion-content>`

**Comment by Ultimate-System** [comment]
I have solved it in the following way

**mypage.module.ts**
```
import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  declarations: [
    MyPage
  ],
  imports: [
    IonicPageModule.forChild(MyPage),
    NgCalendarModule
  ],
  entryComponents: [
    MyPage
  ]
})
export class MyPageModule {}
```

**mypage.ts**

```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-mypage',
  templateUrl: 'mypage.html',
})
export class MyPage{

  eventSource;
  viewTitle;

  isToday:boolean;
  calendar = {
      mode: 'month',
      currentDate: new Date()
  };

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

}
```


**mypage.html**

```
<ion-header>

  <ion-navbar>
    <ion-title>My Page</ion-title>
  </ion-navbar>

</ion-header>


<ion-content>
  <calendar
  [eventSource]="eventSource"
  [calendarMode]="calendar.mode"
  [currentDate]="calendar.currentDate"
  step="30">
  </calendar>
</ion-content>
```
