### ISSUE TITLE
Can im set steps or timeinterval of WeekView to 40 minutes?

### ISSUE THREAD

**Issue by AlonsoFon** [twinssbc/Ionic2-Calendar#394]
Hello, my english is not very good but im will try to explain my problem...

Im need to make weekView steps or time interval accept 40 minutes, if im set it at options the calendar take another effect... 

steps 40 minutes should show the weekview hours were below:

8:00
8:40
9:20
10:00
10:40
11:20
12:00

How are showing if i set steps or time interval 40 minutes:
8:00
8:40
9:00
9:40
10:00
10:40
11:00
11:40
12:00

Have how do what im need and make the steps works correctly?

**Comment by twinssbc** [comment]
@AlonsoFon Unfortunately it doesn't support 40 mins as the interval. As the README explains, it should be the factor or multiple of 60, which means 60%timeInterval=0 or timeInterval%60=0.
