### ISSUE TITLE
Disable date picker time slots

### ISSUE THREAD

**Issue by patrickritskes** [twinssbc/Ionic2-Calendar#395]
Hi guys,

Nice work on this plugin!
I've got a question about disabling an already chosen time when creating a new event, a timeslot.

For example:
Say my client creates a new event tomorrow from:
10:00 till 11:00, 
and wants to add another event on that day from:
11:00 till 12:00
is there a possibility to disable the previous time slot in the date time picker, and not double book on the same time on the same day?

Hope this all is clear!

**Comment by twinssbc** [comment]
@patrickritskes It seems your question is related to the date time picker, not this calendar component?

**Comment by patrickritskes** [comment]
Ah ok thanks!
I will take a look over there
