### ISSUE TITLE
Current Month view export

### ISSUE THREAD

**Issue by patrickritskes** [twinssbc/Ionic2-Calendar#396]
Hi there,

Right now i'm busy with a event PDF export, all is working well!

But the idea is to do a monhtly PDF export from the current month view (let's say November) with all it's available events from that specific month.

How can this be done?
I already did a try with the onRangeChanged event with queryMode to 'remote' with no luck

**Comment by twinssbc** [comment]
@patrickritskes The calendar accepts the events you passed in, so you should already know the available events within the time range, no need to let the calendar tell you the available events.

**Comment by newzhongdan** [comment]
you need get the arrays of the month (array 7* 4 or 5), maybe is not possible... you use pdfmake?

**Comment by newzhongdan** [comment]
the ng-template contain the arrays 

`<ng-template #template let-view="view" let-row="row" let-col="col">
            {{view.dates[row*7+col].label}}
        </ng-template>

        <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>`
see de doc...

if you get the view (console.log(view.dates)); maybe solve your problem, i don't know how to do that.

**Comment by patrickritskes** [comment]
I will give it a try, many thanks for your approach!
Will let you know asap

Op di 18 dec. 2018 15:52 schreef x <notifications@github.com>:

**Comment by newzhongdan** [comment]
ok, i get the arrays

add the template month in your html, and use Viewchild 
my code

`... all import...
export class HomePage {
  @ViewChild('templatemonth') elemElem;
... other code
`
use "console.log(this.elemElem);"  in some function (button for example) for get data, and you see all arrays of the month, the info is confused, but you can build a calendar

<img width="1187" alt="captura de pantalla 2018-12-18 a la s 12 23 52" src="https://user-images.githubusercontent.com/801562/50163723-d78f1b80-02bf-11e9-9133-07ab52fd4254.png">

**Comment by patrickritskes** [comment]
Ah ok I see! Looks promising!

Op di 18 dec. 2018 16:24 schreef x <notifications@github.com>:

**Comment by patrickritskes** [comment]
Got it al working now, nice PDF export of my montly viewed events!

Only 1 thing left:
if you have a montview of December, you still got some days from November
and Januari in the actual monthview unfortunately!


Op di 18 dec. 2018 om 17:19 schreef Patrick Ritskes <
patrickritskes@gmail.com>:

**Comment by twinssbc** [comment]
@patrickritskes You could use onCurrentDateChanged callback. That date definitely falls into the current displayed month.

**Comment by patrickritskes** [comment]
@twinssbc/Ionic2-Calendar
<reply@reply.github.com>
I
only get the selected date back when using onCurrentDateChanged! not the
whole calendar range, am I missing something here?

Op wo 19 dec. 2018 om 16:16 schreef twinssbc <notifications@github.com>:

**Comment by twinssbc** [comment]
@patrickritskes I thought you just want to know what's the current month?

**Comment by newzhongdan** [comment]
he need print the calendar in a pdf, using html2canvas isnt posibble (create a screenshot), then he needs get all arrays to create the calendar using only arrays
