### ISSUE TITLE
Runtime Error Cannot read property 'event_title' of undefined

### ISSUE THREAD

**Issue by ahmedwsi** [twinssbc/Ionic2-Calendar#399]
Hello I have issue with my calendar: this my loadEvents function, it returns results successfully, but there is run time error: Runtime Error Cannot read property 'event_title' of undefined

`loadEvents() {
    this.data = this.http.get("http://********/get_events.php");
    this.data.subscribe(result => {
      for (var i=0; i <= result['events'].length; i++) {
        this.eventSource.push({
          title: result['events'][i].event_title,
          startTime: new Date(result['events'][i].event_date),
          endTime: new Date(result['events'][i].event_date),
          
          allDay: false
        }); 
      }
      
    })
  }`

This is my array structure:

`{"events":[{"event_id":"72","event_title":"","event_place":"","event_date":"2018-09-23","event_organizer":"","enabled":""}}`

**Comment by twinssbc** [comment]
@ahmedwsi As the error indicates, you are referencing to some undefined variable. Could you check if result['events'][i] always refers to a valid object?

**Comment by twinssbc** [comment]
@ahmedwsi 
I don't think this for loop is correct. If i equals result['events'].length, it will return undefined result.
```
for (var i=0; i <= result['events'].length; i++) {
```

Also your code is pushing elements to the eventSource array directly. Take a look at the **loadEvents** instance method in README. You need to manually call the loadEvents method.

**Comment by ahmedwsi** [comment]
Thanks, I changed the for loop to : 

`this.data.subscribe(data => { 
      this.data = data['events'];  
      data['events'].forEach((val, index) => {
        this.eventSource.push({
          id: val.event_id,
          title: val.event_title, 
          startTime: new Date(val.event_date),
          endTime: new Date(val.event_date),
          allDay: false
        }); 
      });
    });`

Its works okay now, thanks again.
