### ISSUE TITLE
Custom styling in Ionic 4

### ISSUE THREAD

**Issue by mathisschuelingkamp** [twinssbc/Ionic2-Calendar#403]
Hey @twinssbc, thanks for making this plugin and thanks for your update to use it in Ionic 4.

Since Ionic 4 is using shadow dom to prevent scss manipulation of the elements, i see no possibility to change the .monthview-current and .monthview-primary-with-event style like background-color, width and padding because i don't found variables for that.

How can we customize these elements?
Thank you!

**Comment by twinssbc** [comment]
@mathisschuelingkamp You could add styles in the global.scss like below.

```
.monthview-primary-with-event {
  background-color: red !important;
}
```

**Comment by mathisschuelingkamp** [comment]
Thanks @twinssbc, that worked! :)
