### ISSUE TITLE
ionic2-calendar issue

### ISSUE THREAD

**Issue by aceshiryu** [twinssbc/Ionic2-Calendar#404]
Hi! I am actually having this kind of an error and it seems that I will install the @ionic/angular. It doesn't solve the problem until such time, an error will pop out that Object(...) is not a function and I don't know also to which error is it referring to. I tried to reinstall the plugin and it's not working again. I got the latest version of the calendar, 0.5.1 .

![screen shot 2019-01-17 at 3 43 43 pm](https://user-images.githubusercontent.com/30274943/51302906-c0824b80-1a6e-11e9-95e2-2c3bbf0ddde3.png)

Right after reinstalling, this will happen:

![screen shot 2019-01-17 at 3 54 51 pm](https://user-images.githubusercontent.com/30274943/51303416-405ce580-1a70-11e9-92dd-1663739dd877.png)

I installed, and another appeared. This is where I stuck.

![screen shot 2019-01-17 at 3 59 39 pm](https://user-images.githubusercontent.com/30274943/51303677-06d8aa00-1a71-11e9-85bc-2f384b872468.png)

I will be very grateful for you help. Thanks!

INFO:
![screen shot 2019-01-17 at 4 04 07 pm](https://user-images.githubusercontent.com/30274943/51303872-9b430c80-1a71-11e9-9a58-c33140712eff.png)

**Comment by dtgfranca** [comment]
I'm same problem here

**Comment by twinssbc** [comment]
Could you paste your package.json?

**Comment by aceshiryu** [comment]
> Could you paste your package.json?

Here's my package.json

{
  "name": "ionic-app-base",
  "version": "0.0.0",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@angular/router": "^7.2.1",
    "@ionic-native/android-permissions": "^4.18.0",
    "@ionic-native/core": "^4.15.0",
    "@ionic-native/diagnostic": "^4.18.0",
    "@ionic-native/sms": "^4.18.0",
    "@ionic-native/splash-screen": "~4.15.0",
    "@ionic-native/status-bar": "~4.15.0",
    "@ionic/angular": "^4.0.0-rc.2",
    "@ionic/storage": "2.2.0",
    "cordova-android": "7.1.4",
    "cordova-plugin-android-permissions": "1.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sms-plugin": "1.0.0",
    "cordova.plugins.diagnostic": "4.0.10",
    "intl": "^1.2.5",
    "ionic-angular": "^3.9.2",
    "ionic2-calendar": "^0.5.1",
    "ionicons": "3.0.0",
    "moment": "^2.23.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.1",
    "typescript": "~2.6.2"
  },
  "cordova": {
    "plugins": {
      "cordova-sms-plugin": {},
      "cordova-plugin-android-permissions": {},
      "cordova.plugins.diagnostic": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}

**Comment by twinssbc** [comment]
@aceshiryu Your dependency is not correct. Try to start a new Ionic 4 project. You will see the angular version is at least 7.1

**Comment by aceshiryu** [comment]
> @aceshiryu Your dependency is not correct. Try to start a new Ionic 4 project. You will see the angular version is at least 7.1

Is there another way that I can resolve this? I already uploaded an APK for this project. I am not using Ionic 4 for now, the project is currently Ionic 3.9

**Comment by dtgfranca** [comment]
@aceshiryu I figured out thus:
I made a fork ionic2-calendar and I installed @ionic/angular. After this, I runned "npm build" and published on site npm and I updated in my project ionic3. Now it's work

**Comment by aceshiryu** [comment]
I think I upgraded my ionic cli to ionic 4.

I read this issue, https://github.com/twinssbc/Ionic2-Calendar/issues/372 , and you've released a version that will support Ionic 4. Do I need to install something? I really liked your calendar, I really appreciate it but I can't work on it. Sorry for the inconvenience.

**Comment by twinssbc** [comment]
@aceshiryu I don't think your current package.json is correct. If you want to use the Ionic 4, you need to install the calendar 0.5.x version. And Ionic 4 has dependency on Angular 7.1.4. You also need to make sure Angular version is correct in your package.json.
I suggest you start a new project using the ionic cli, then take a look at the package.json of that new project.

**Comment by aceshiryu** [comment]
Good. I got, it's now working but I need to redo some of the designs for this. I just created new project (Ionic 4, not Ionic 3) and tried the ionic2-calendar, it works. Maybe it's time to do the new Ionic 😁 thanks!

**Comment by aceshiryu** [comment]
Hello sir! Does the ionic2-calendar supports on Ionic 3.9? I tried
recreating an app with Ionic 3.9 framework then sets the NgCalendarModule,
it asks for an installation of @ionic/angular. @ionic/angular is for Ionic
4 right? I followed your steps starting to recreate the app first.

**Comment by twinssbc** [comment]
@aceshiryu If you want to use Ionic 3.9, you should use the 0.4.x version of calendar component.

**Comment by aceshiryu** [comment]
Is that npm install ionic2-calendar@0.4.9 ?

**Comment by aceshiryu** [comment]
I mean 0.4.6 ?

**Comment by twinssbc** [comment]
yes
