### ISSUE TITLE
Typescript Error Cannot find module '@ionic/angular'.

### ISSUE THREAD

**Issue by AdiPathak97** [twinssbc/Ionic2-Calendar#405]
Hello, I have tried to import this plugin into my application but am getting the runtime error of : Cannot find module '@ionic/angular'.

I am using version 0.4.x of the calendar, unlike a similar issue where the user had used 0.5.x version of the calendar. The module cnnot be found only in the ionic2-calendar/dayview.d.ts, ionic2-calendar/weekview.d.ts and ionic2-calendar/monthview.d.ts files. Any help will be highly appreciated.

**Comment by AdiPathak97** [comment]
I have tried using the command "npm install @ionic/angular" as this directory was itself missing in the node_modules folder of my project directory. However, after doing this, I am getting hundreds of typescript errors. Some of them are syntax errors (eg : missing ; in @ionic/core/dist/types/components.d.ts) which were not present before. Any help is appreciated.

**Comment by twinssbc** [comment]
@AdiPathak97 I'm bit confused about the calendar version you are using. Version 0.5.x relies on Ionic 4 , which you should import @ionic/angular. Version 0.4.x relies on Ionic 3, which you should import ionic-angular. Could you confirm the exact version you are using?

**Comment by AdiPathak97** [comment]
At the beginning, I had used ```npm install ionic2-calendar --save```. Later I realised this installs latest version, so uninstalled it. 

Then I had used the command ```npm install ionic2-calendar@0.4.x --save```. It displayed : +ionic2-calendar@0.4.6 after installation. However, after you mentioned this, I checked the version again, and realised that node has installed ionic2-calendar v0.5.1, due to which I'm getting the error. I uninstalled using ```npm uninstall ionic2-calendar --save``` to remove dependencies, and reinstalled ionic2-calendar v0.4.6. 

However, after checking version of node2-calendar again, its still showing ionic2-calendar version as 0.5.1. Can you please suggest a solution to correctly install v0.4.x of ionic2-calendar?

**Comment by AdiPathak97** [comment]
It works now. Guess both v0.4.6 and 0.5.1 are present in node now. Thanks for replaying.

**Comment by Fagundesbf** [comment]
eu estou com o mesmo tipo de erro ! pode me dizer o que fez?
