### ISSUE TITLE
Disabling a day specific day in monthview

### ISSUE THREAD

**Issue by FrancescoPaiola** [twinssbc/Ionic2-Calendar#406]
Hi, i'm trying to disable a particular day using markDisabled runtime.
`this.markDisabled(my_date);` seems not working as mentioned here https://github.com/twinssbc/Ionic2-Calendar/issues/239#issuecomment-348651396.

The claim is to implement a disable date logic based on a date returned from a get query.
This date variable is not immediately available, so i can't use it on view load in markDisabled callback.

Thanks in advance.

**Comment by twinssbc** [comment]
@FrancescoPaiola As I explained in the issue 239, the markDisabled is only triggered when the view is initialized, it won't be triggered afterwards.

1. If you could stay in another page, then navigate back once your get query returns, then you could store your disabled date and use it in the markDisabled method. Once you navigate back, the calendar will be re-rendered, so the markDisabled method will be called.
2. If you don't want to navigate to other page. You could use a customized template to implement your own disable logic.

**Comment by FrancescoPaiola** [comment]
Ok but what i'm actually asking is how to implement a customized template to do that.

**Comment by FrancescoPaiola** [comment]
Thank you so much i'll try it immediately!

**Comment by aligassan** [comment]
> monthviewDisplayEventTemplate

very. useful. Thank you. But l need to change the color date that has an event in past.
Now we have the same color for all disabled dates. what if that date has events in past?
