### ISSUE TITLE
How to show 'no events' just one time in the calendar plugin? 

### ISSUE THREAD

**Issue by agiratech-sankar** [twinssbc/Ionic2-Calendar#407]
I am attaching the sample code that we worked. If any bug in the below code please reply. We are just a beginner to ionic

  <calendar [calendarMode]="calendar.mode" [currentDate]="calendar.currentDate" (onCurrentDateChanged)="onCurrentDateChanged($event)"
    (onEventSelected)="onEventSelected($event)" (onTitleChanged)="onViewTitleChanged($event)" (onTimeSelected)="onTimeSelected($event)"
    step="30" [monthviewEventDetailTemplate]="template">
  </calendar>

  <ng-template #template let-showEventDetail="eventSource" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">

    <h6 text-uppercase class="para-font">Scheduled Events <span *ngIf="clientName">- {{clientName}}</span></h6>

    <div class="card-master" [ngStyle]="{ 'height.px': cardHeight }">
      <div *ngFor="let event of eventSource">
        <div *ngIf="
              ((event.startTime | date: 'MM-dd-yyyy') ===
              (selectedDate.date | date: 'MM-dd-yyyy')); then hari 
            ">
          <div *ngIf="hideDiv1">
            <ion-card>
              <ion-item>
                <ion-avatar item-start>
                  <img src="assets/imgs/calendar.jpeg" />
                </ion-avatar>
                <h2 text-capitalize>
                  
                  {{ event.title }}
                </h2>
                <p class="para-font">
                  
                  {{ event.startTime | date: "dd-MM-yyyy HH:mm" }} |
                  {{ event.endTime | date: "dd-MM-yyyy HH:mm" }}
                </p>

                <p class="para-font">
                  
                  {{ event.venue }}
                </p>
              </ion-item>

              <ion-row>
                <ion-col col-6>
                  <button ion-button icon-start clear small>
                    <ion-icon name="person"></ion-icon>
                    {{ event.client_name }}
                  </button>
                </ion-col>
                <ion-col col-6>

                  <ion-col col-4>
                    <button ion-button icon-start clear small (click)="onEventSelected(event)">
                      <ion-icon name="create"></ion-icon>
                    </button>
                  </ion-col>

                  <ion-col col-4>
                    <button ion-button icon-start clear small (click)="onEventDelete(event)">
                      <ion-icon name="md-trash"></ion-icon>
                    </button>
                  </ion-col>
                </ion-col>
              </ion-row>
            </ion-card>
          </div>
        </div>
        
      </div>
    </div>
    <ng-template #hari>
        {{noEventsLabel}}
    </ng-template>

**Comment by twinssbc** [comment]
@agiratech-sankar 

The problem is you put **hari** inside ngFor, that's why it's repeated.
```
<div *ngFor="let event of eventSource">
    <div *ngIf="
          ((event.startTime | date: 'MM-dd-yyyy') ===
          (selectedDate.date | date: 'MM-dd-yyyy')); then hari 
        ">
```
You could try use *ngIf to check if eventSource has element, if it has, then use the above block, otherwise display the no event label.

**Comment by manzooralam** [comment]
How i will remove no events in calendar when no event is present

**Comment by twinssbc** [comment]
@manzooralam You could use showEventDetail option.

**Comment by manzooralam** [comment]
Thanks @twinssbc  
for suggested,
[showEventDetail]="false"

**Comment by manzooralam** [comment]
How to set width and height of calendar component ?

**Comment by twinssbc** [comment]
@manzooralam Could you provide more code? Where do you add class="calendar"? And where do you  set the width and height?
