### ISSUE TITLE
Is it possible for you to expose a method for sliding between months ?

### ISSUE THREAD

**Issue by jloria13** [twinssbc/Ionic2-Calendar#409]
I can't retrieve the swiper element from TS, so if you could expose a method to go back and forth between months would be great, I need it to call it from a button.

**Comment by twinssbc** [comment]
@jloria13 You should be able to retrieve the swiper element by using below code
```
var mySwiper = document.querySelector('.swiper-container')['swiper'];
    mySwiper.slideNext();
```

**Comment by jloria13** [comment]
Dumb mistake I made, thank you
