### ISSUE TITLE
Broken with Ionic RC5

### ISSUE THREAD

**Issue by Daskus1** [twinssbc/Ionic2-Calendar#41]
The components are not working anymore since I upgraded to RC5. This is probably due to the breaking changes on the slides component

**Comment by twinssbc** [comment]
Yes, I'm aware of the breaking change.
It's not just simply API change, it seems the underlying logic to handle looped slides is different, I haven't found a solution to fix the different behavior yet. It may take some time.

**Comment by twinssbc** [comment]
@Daskus1 I have found the way to fix the breaking chagne in RC5. The latest 0.2.0 version is compatible with Ionic 2.0.0-rc.5. Feel free to have a try.

**Comment by Daskus1** [comment]
Just tried it and it works, thanks.
Is it possible that this version is slower? The loading when swiping was always a bit long but now it feels like it takes even more...

**Comment by Daskus1** [comment]
There is a bug I found with this version:
When selecting a day in monthview the view slides randomly to the next/previous month. 
At first I thought it would only be in my project but then I tried it with the demo and the same thing happened.

**Comment by twinssbc** [comment]
@Daskus1 I have fixed the bug in version 0.2.1. Also the extra slowness is also caused by this bug.
The speed should be better now. Feel free to have a try.
