### ISSUE TITLE
select year

### ISSUE THREAD

**Issue by rajkishoreandia** [twinssbc/Ionic2-Calendar#410]
How some body can select the year or can switch between years and can go to the particular month

**Comment by twinssbc** [comment]
@rajkishoreandia This calendar only supports month, week, day views. You could implement your own year selection logic. To navigate to a particular month, you just need to set the currentDate to a day in that month.

**Comment by rajkishoreandia** [comment]
Thanks for the quick response @twinssbc .I have a date 198-10-03 and i want to slide the calendar to that particular year's month.Could you guide me how to do ?

**Comment by dev2612** [comment]
I am also looking for the same functionality. @rajkishoreandia, how did you solve this?

**Comment by kamalessence** [comment]
I am also looking for the same functionality. @rajkishoreandia, Can you please let me know how did you solve this?

**Comment by rajkishoreandia** [comment]
you can write your own function in html like (click)="selectYear($event)" and then in your ts file write the logic like
selectYear(){
    console.log('in selectYear');
    let year=[2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050]
    let alert = this.alertCtrl.create({
        title: ' select Year',
        cssClass: 'ion-alert',
      });
      alert = this.alertCtrl.create();
alert.setTitle(' select Year');
      for(let tempyear=0;tempyear<year.length;tempyear++){
      alert.addInput({ type: 'radio',label:JSON.stringify(year[tempyear]), value: JSON.stringify(year[tempyear]),checked:this.selectedYear==JSON.stringify(year[tempyear])});
    }
      alert.addButton({
        text: this.translate.instant('app.ok'),
        handler: data => {
        this.selectedYear=data;
    console.log('this.selectedYear',this.selectedYear);
          this.selectMonth();
          alert.dismiss();
          return false;
        }
      });
      alert.addButton(this.translate.instant('app.cancel'));
      alert.present();
      return;
  
}
selectMonth() {
    let month=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

    let alert = this.alertCtrl.create({
      title: ' select month',
      cssClass: 'ion-alert',
    });
    alert = this.alertCtrl.create();
    alert.setTitle(this.translate.instant('emp_create_attendance.placeholder1'));
    for(let tempyear=0;tempyear<month.length;tempyear++){
        alert.addInput({ type: 'radio',label:month[tempyear], value: JSON.stringify(tempyear+1),checked:this.selectedMonth==month[tempyear]});
      }
    alert.addButton({
      text: this.translate.instant('app.ok'),
      handler: data => {
        console.log('data',data)
        switch (data) {
          case '1':
          this.selectedMonth='Jan';
          break;
          case '2':
          this.selectedMonth = 'Feb';
          break;
          case '3':
            this.selectedMonth = 'Mar';
            break;
          case '4':
            this.selectedMonth = 'Apr';
            break;
          case '5':
            this.selectedMonth = 'May';
            break;
          case '6':
            this.selectedMonth = 'Jun';
            break;
          case '7':
            this.selectedMonth = 'Jul';
            break;
          case '8':
            this.selectedMonth = 'Aug';
            break;
          case '9':
            this.selectedMonth = 'Sep';
            break;
            case '10':
            this.selectedMonth = 'Oct';
            break;
            case '11':
            this.selectedMonth = 'Nov';
            break;
            case '11':
            this.selectedMonth = 'Dec';
            break;
          default:
            break;
        }
    console.log('this.selectedMonth',this.selectedMonth);
    console.log('date',this.selectedYear+'-'+data+'-'+this.todayDate);
    var startDate =this.selectedYear+'-'+data+'-'+this.todayDate;
    this.goToSelectedYear(new Date(startDate));
        alert.dismiss();
        return false;
      }
    });
    alert.addButton(this.translate.instant('app.cancel'));
    alert.present();
    return;
  }
