### ISSUE TITLE
 Ionic2-Calendar, Cannot read property 'getTime' of undefined 

### ISSUE THREAD

**Issue by Mo5005** [twinssbc/Ionic2-Calendar#411]
![11](https://user-images.githubusercontent.com/39675817/53771804-51f53200-3ee4-11e9-965c-c512ed07ac5d.JPG)

I have a problem with AddEvent in the ionic2-Calendar and it shows the following error
please someone has a solution for it

here this Code for AddEvent:

` modal.onDidDismiss().then(data => {
      if (data) {
        try {
          let eventData = data;

          eventData.data.startTime = new Date(data.data.startTime);
          eventData.data.endTime = new Date(data.data.endTime);

          let events = this.eventSource;
          events.push(eventData);
          this.eventSource = [];
          this.eventSource = events;

          // setTimeout(() => {
          //   this.eventSource = events;
          console.log(this.eventSource)
          // });
        } catch (error) {
          console.log(error)

        }
      }
    }).catch(error => {
      console.log(error)

    })`

and the html code is 
`<calendar    
    [eventSource]="eventSource"

    class="calendar-header" 
    [calendarMode]="calendar.mode" 
    [currentDate]="calendar.currentDate"
    (onEventSelected)="onEventSelected($event)" 
    (onTimeSelected)="onTimeSelected($event)" 

    step="30" 
   ></calendar>`

**Comment by Mo5005** [comment]
@ionic4
@_ionic2-calendar

**Comment by Mo5005** [comment]
i am having the same issue @twinssbc Please look this issue

**Comment by twinssbc** [comment]
@Mo5005 This doesn't seem to be correct. Each element in events should have startTime and endTime fields, instead of having another data field.

```
      eventData.data.startTime = new Date(data.data.startTime);
      eventData.data.endTime = new Date(data.data.endTime);

      let events = this.eventSource;
      events.push(eventData);
```

**Comment by Mo5005** [comment]
So where is my mistake in this case?
 here also have a start and end time for each event

**Comment by Mo5005** [comment]
I do not have the error anymore but the events are not displayed, why?

`  async presentModal() {
    const modal = await this.modalController.create({
      component: ModalPage,
      componentProps: {
        selectedDay: this.selectedDay,
        value: 123
      }
    });
    modal.present();
    modal.onDidDismiss().then(data => {
      if (data) {
        try {
          let eventData = data;

          console.log(data.data.startTime)
          eventData.data.startTime = new Date(data.data.startTime);
          eventData.data.endTime = new Date(data.data.endTime);

          let events = this.eventSource;
          events.push(eventData);
          this.eventSource = [];
          this.eventSource = events;

          // setTimeout(() => {
          //   this.eventSource = events;
          console.log(this.eventSource)
          // });
        } catch (error) {
          console.log(error)

        }
      }
    }).catch(error => {
      console.log(error)

    })

  }`


`<calendar    
    [eventSource]="eventSource"
     class="calendar-header" 
    [calendarMode]="calendar.mode" 
    [currentDate]="calendar.currentDate"
    (onEventSelected)="onEventSelected($event)" 
    (onTimeSelected)="onTimeSelected($event)" 
    step="30"
     >   
    
    </calendar>`

**Comment by twinssbc** [comment]
@Mo5005 I still don't think your eventSource array is populated correctly.
It should be like 
```
[{
                    title: 'Event 1'
                    startTime: startTime1,
                    endTime: endTime1,
                    allDay: false,
}, {
                    title: 'Event 2',
                    startTime: startTime2,
                    endTime: endTime2,
                    allDay: false,
}]
```
Instead of having data in the middle.

**Comment by Mo5005** [comment]
my eventSource looks like that

`import { Component, OnInit } from '@angular/core';
import { NavParams, ModalController } from '@ionic/angular';
import * as moment from 'moment';
import { OverlayEventDetail } from '@ionic/core';

@Component({
  selector: 'app-modal',
  templateUrl: './modal.page.html',
  styleUrls: ['./modal.page.scss'],
})
export class ModalPage implements OnInit {

  datei: any
  showReservation: Array<any>

  event = {
    startTime: new Date().toISOString(),
    endTime: new Date().toISOString(),
    allDay: false,
    title: ''
  };

  minDate = new Date().toISOString();


  constructor(
    private navPra: NavParams,
    private modalController: ModalController
  ) {
    let preselectedDate = moment(this.navPra.get('selectedDay')).format();
    this.event.startTime = preselectedDate;
    this.event.endTime = preselectedDate;
    // console.log(preselectedDate)
    this.showReservation = this.navPra.get('reservation')
    // if (this.showReservation != null ){
    //   this.showR()
    // }

  }

  ngOnInit() {
    this.datei = this.navPra.get('value')

  }

  closeModal() {

    this.modalController.dismiss()
  }

  save() { 
    this.modalController.dismiss(this.event);
  }`

**Comment by Mo5005** [comment]
my eventSource looks like that

`import { Component, OnInit } from '@angular/core';
import { NavParams, ModalController } from '@ionic/angular';
import * as moment from 'moment';
import { OverlayEventDetail } from '@ionic/core';

@Component({
  selector: 'app-modal',
  templateUrl: './modal.page.html',
  styleUrls: ['./modal.page.scss'],
})
export class ModalPage implements OnInit {

  datei: any
  showReservation: Array<any>

  event = {
    startTime: new Date().toISOString(),
    endTime: new Date().toISOString(),
    allDay: false,
    title: ''
  };

  minDate = new Date().toISOString();


  constructor(
    private navPra: NavParams,
    private modalController: ModalController
  ) {
    let preselectedDate = moment(this.navPra.get('selectedDay')).format();
    this.event.startTime = preselectedDate;
    this.event.endTime = preselectedDate;
    // console.log(preselectedDate)
    this.showReservation = this.navPra.get('reservation')
    // if (this.showReservation != null ){
    //   this.showR()
    // }

  }

  ngOnInit() {
    this.datei = this.navPra.get('value')

  }

  closeModal() {

    this.modalController.dismiss()
  }

  save() { 
    this.modalController.dismiss(this.event);
  }`

**Comment by twinssbc** [comment]
@Mo5005 Just to confirm you solved the issue?

**Comment by Mo5005** [comment]
the problem is not solved :(

**Comment by Mo5005** [comment]
first the events are not shown under the calendar  as in the photo

![Unbenannt1](https://user-images.githubusercontent.com/39675817/54159264-e44d8680-444c-11e9-8f6f-0870444ee3b6.JPG)

**Comment by twinssbc** [comment]
@Mo5005 As I said, don't put the "data" field there. 
The calendar accepts below format
```
[{
  data: {
                    title: 'Event 1'
                    startTime: startTime1,
                    endTime: endTime1,
                    allDay: false,
  }
}, {
   data: {
                   title: 'Event 2',
                    startTime: startTime2,
                    endTime: endTime2,
                    allDay: false,
  }
}]
```
Instead of
```
[{
                    title: 'Event 1'
                    startTime: startTime1,
                    endTime: endTime1,
                    allDay: false,
}, {
                    title: 'Event 2',
                    startTime: startTime2,
                    endTime: endTime2,
                    allDay: false,
}]
```

**Comment by dmmd10** [comment]
How was the problem solved?
I have the same problem too

**Comment by dmmd10** [comment]
How was the problem solved?
I have the same problem too
@Mo5005

**Comment by Saddi993** [comment]
still facing same issue

**Comment by dmmd10** [comment]
Yes, i have not found a solution Gesendet von Mail für Windows 10 Von: Saad AhmedGesendet: Freitag, 3. Juli 2020 22:17An: twinssbc/Ionic2-CalendarCc: dmmd10; CommentBetreff: Re: [twinssbc/Ionic2-Calendar] Ionic2-Calendar, Cannot read property 'getTime' of undefined (#411) still facing same issue—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dmmd10** [comment]
help @Mo5005
