### ISSUE TITLE
can not activate already activated outlet 

### ISSUE THREAD

**Issue by rajneshkis13** [twinssbc/Ionic2-Calendar#412]
into ionic 4 ionic2-calender is not working in ios device
giving errors in some of ios version like 6s

showing blank screen only with error
please help.
![simulator screen shot - iphone 6 - 2019-03-06 at 18 30 03](https://user-images.githubusercontent.com/32674573/54010985-e38bca80-4196-11e9-9053-b1833465c3b5.png)

**Comment by twinssbc** [comment]
@rajneshkis13 Could you use Developer Tools to check what error printed in the console?
