### ISSUE TITLE
[bug] onTimeSelected is always return 12:00 or 00:00 instead of currenttime

### ISSUE THREAD

**Issue by indraraj26** [twinssbc/Ionic2-Calendar#413]
When i click on date on calendar it emits this on onTimeSelected , I get actual date but time always stay at 12:00 or 00:00
Is there anyway to emit actual time on onTimeSelected ?

Log: 
```
time selected event 
{selectedTime: Wed Mar 13 2019 12:00:00 GMT+0530 (India Standard Time), events: Array(0), disabled: false}
disabled: false
events: []
selectedTime: Wed Mar 13 2019 12:00:00 GMT+0530 (India Standard Time) {}
__proto__: Object
```

log:
````
Selected time: Tue Mar 19 2019 00:00:00 GMT+0530 (India Standard Time), hasEvents: false, disabled: false
````

stackblitz: [https://stackblitz.com/edit/ionic-calendar-scheduler?file=pages%2Fhome%2Fhome.ts](url)

Thank you

**Comment by twinssbc** [comment]
@indraraj26 When onTimeSelected is triggered in month view, the hour of selected time is 12:00:00. When onTimeSelected is triggered in the week view and day view, the hour is the slot actually selected.
Are you expecting different behavior?

**Comment by indraraj26** [comment]
@twinssbc actually it should trigger current time suppose i want to add event i get proper date but time is always 12:00 or 00:00 so user has to edit time everytime he add event .

what was the reason to add 12:00 in month view ? may be i am not aware of that

**Comment by twinssbc** [comment]
@indraraj26 The reason I set it to 12:00 is to avoid the timezone difference. Actually you don't need to use the hour part of the selected time, you could easily get the current time by yourself.

**Comment by indraraj26** [comment]
Thank you @twinssbc for response. yes i did that with new Date() later join the time with eventSelectedTime.
