### ISSUE TITLE
Cannot find module “/@ionic-native”

### ISSUE THREAD

**Issue by kotran88** [twinssbc/Ionic2-Calendar#414]
when I just add 
import { NgCalendarModule } from 'ionic2-calendar';
and NgCalendarModule to imports 
on app.module.ts , 
It has error saying Cannot find module “/@ionic-native” when I typed ionic serve

I'm using ionic 3...
what's wrong with code?

**Comment by indraraj26** [comment]
which version of ionic3 and ionic2-calendar are you using ?

**Comment by kotran88** [comment]
Ionic:

   ionic (Ionic CLI)  : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.3.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 12 other plugins)

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61

**Comment by kotran88** [comment]
"ionic2-calendar": "^0.5.2",

**Comment by twinssbc** [comment]
@kotran88 If you are using 0.5.2 version of the calendar, you need to upgrade your Ionic version to 4.0

**Comment by hicham-alsayed-ahmad** [comment]
and i i want to use with ionic 4.1.2 ??

**Comment by twinssbc** [comment]
@hicham-alsayed-ahmad Also 0.5.x version.
