### ISSUE TITLE
color based on event type

### ISSUE THREAD

**Issue by abdulkadhir** [twinssbc/Ionic2-Calendar#415]
Hi, @twinssbc thanks for the plugin.
I want to different background color for the different event type.
 I'm using **[monthviewEventDetailTemplate]**.
I also tried **[monthviewDisplayEventTemplate]** but it shows only the dates with event 
thanks

**Comment by twinssbc** [comment]
@abdulkadhir You could use monthviewDisplayEventTemplate. 
Suppose you have a field called eventType, you could use ngClass or ngStyle to generate the custom css style based on the eventType.

**Comment by abdulkadhir** [comment]
thanks @twinssbc
