### ISSUE TITLE
day view display time and event in horizontal line

### ISSUE THREAD

**Issue by rajneshkis13** [twinssbc/Ionic2-Calendar#416]
in ionic 2 calendar i need to display time and event in horizontal line
for now in day view displaying like below

![Screenshot 1940-12-27 at 12 06 47 PM](https://user-images.githubusercontent.com/32674573/54511251-6a4e5d80-4976-11e9-9643-1f67ab2c9d24.png)

i need like this type of view

![Screenshot 1940-12-27 at 12 08 11 PM](https://user-images.githubusercontent.com/32674573/54511295-89e58600-4976-11e9-866b-723ec9c09c2b.png)

**Comment by twinssbc** [comment]
@rajneshkis13 This is not supported. Also bear in mind, the calendar is supposed to be run in a mobile device. The height is bigger than the width.
