### ISSUE TITLE
AllDay true, grafically rendered on day before

### ISSUE THREAD

**Issue by eugenioghio** [twinssbc/Ionic2-Calendar#417]
### Issue type
Select all that apply
- [ ] Bug
- [ ] Enhancement
- [ ] Task
- [x] Question
- [ ] Other

### Description
Grafically my allDay event starts the day before and last one day more than supposed to.

My allDay events, in the event source, are reported with the correct date and time, the time being 00:00. 

It is only a rendering problem that persist in all views.

I experienced this issued, first time,creating a single day allDay event, with starTime on the day the event shound took place and endTime the day after.
That because I read on an issue that the startTime/endTime must not coincide. 
But I then discovered that the problem persist on multiple day long, allDay, events.

In single day, allDay, scenario
If I were to have the startTime/endTime coincide the event is rendered on a day early, but al least it's one day long as supposed to.

### Steps to Reproduce
When I create an allDay event i set the dates like this:
```
if (myEvent.allDay) {
      const start = myEvent.startTime;
      const end = myEvent.endTime;

      const startMoment = moment(start).startOf('day'); //startOf('day') set time to 00:00
      const endMoment = moment(end).startOf('day').add(1, 'day');

      console.log('start time', start);
      console.log('end time', end);

      myEvent.startTime = startMoment.toDate();
      myEvent.endTime = endMoment.toDate();
    }
```
The console.log from the eventSource array, which display the correct dates
```
allDay: true
description: ""
endTime: Thu Mar 28 2019 00:00:00 GMT+0100 (Ora standard dell’Europa centrale) {}
startTime: Wed Mar 27 2019 00:00:00 GMT+0100 (Ora standard dell’Europa centrale) {}
title: "All Day Test"
```
### Version
Everything up to latest date.

![calendar1](https://user-images.githubusercontent.com/43818195/55066705-96f12c00-507e-11e9-90c3-45243a1e6b30.png)

**Comment by twinssbc** [comment]
@eugenioghio The all day event has to be as a UTC date which time is set to 0:00 AM. For example
```
var startTime = new Date(Date.UTC(2014, 4, 8));
```
You could get more information in **EventSource** section of README.

**Comment by eugenioghio** [comment]
Thanks for the help.
I updated my code to create a new UTC date at 00:00, still no joy
```
if (myEvent.allDay) {
      const start = myEvent.startTime;
      const end = myEvent.endTime;

      const startMoment = moment.utc(moment(start).startOf('day'));
      const endMoment =  moment.utc(moment(end).startOf('day').add(1, 'day'));

      console.log('start utc', startMoment.utc().valueOf());// this logs: start utc 1553641200000
      console.log('end utc', endMoment.utc().valueOf()); //                 end utc 1553727600000

      myEvent.startTime = new Date(startMoment.utc().valueOf());
      myEvent.endTime = new Date(endMoment.utc().valueOf());
      // those logs
     // start time Wed Mar 27 2019 00:00:00 GMT+0100 (Ora standard dell’Europa centrale)
     // end time Thu Mar 28 2019 00:00:00 GMT+0100 (Ora standard dell’Europa centrale)
    }
```
Why is it not enough?

**Comment by eugenioghio** [comment]
I parsed the utc numbers that I logged, and actually, the early day problem is due to the difference between GMT and my time zone.

The same problem does not apply to the normal events.

How to tell the calendar to use one timezone once and for all?

**Comment by twinssbc** [comment]
@eugenioghio 
I suspect the way you create UTC time is not that correct.
If I use below line to create the date
```
new Date(Date.UTC(2014, 4, 8))
```
The time is Thu May 08 2014 08:00:00 GMT+0800 (CST) 
I'm in the GMT+8 time zone, so the time part minus the time zone offset is exactly 0:00 AM.

**Comment by samtest2511** [comment]
> @eugenioghio
> I suspect the way you create UTC time is not that correct.
> If I use below line to create the date
> 
> ```
> new Date(Date.UTC(2014, 4, 8))
> ```
> 
> The time is Thu May 08 2014 08:00:00 GMT+0800 (CST)
> I'm in the GMT+8 time zone, so the time part minus the time zone offset is exactly 0:00 AM.


How to solve this situation. Please help as I am facing this with IST

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
I don't see why an `allDay` event needs to be in UTC. More than that the time is 00:00:00 and a boolean that shows something else like 'Full day' should be everything. Why UTC and not the timezones that all the other events are using?
This only makes it more complicated.

**Comment by twinssbc** [comment]
@MatthiasVanMeerbeek-r0670805 This is because you may see the event you created is today's in your timezone, but when calculating in a device at different timezone, that event may appear in previous day. That's why I need a standard way to construct all day event to overcome the impact of different timezone.
