### ISSUE TITLE
In the month view previous months templates are rendered.

### ISSUE THREAD

**Issue by Ashwaniproctur** [twinssbc/Ionic2-Calendar#419]

**Comment by Ashwaniproctur** [comment]
In the month view previous months templates are rendered.
For example now currently in the April month and in to the month view on some days there are events and I'm showing some information of event on that day by using custom template now when I'm swipe to next month then it is working fine after again swiping in to the the July month the events information from the April month is got displayed on July month days same happens after swiping two more months.
Is there is any solution for this?

**Comment by twinssbc** [comment]
@Ashwaniproctur This is the known issue. Checkout the Known Issue section in README.
