### ISSUE TITLE
Incomplete data

### ISSUE THREAD

**Issue by xyboox** [twinssbc/Ionic2-Calendar#42]
Hi,
to be quick about it, please have a look at this youtube: [screenrecorded](https://youtu.be/wqfeKKNxRCc) about the behaviour of the calendar in my app. Can't figure why I can't select any of the days except ones in the first slide and why only 3 slides populated?
Any idea where the issue might be? My code is identical with the one in the demo.

My machine system info:
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v5.12.0
Xcode version: Xcode 8.2.1 Build version 8C1002

Thank you.

**Comment by twinssbc** [comment]
@xyboox The current version doesn't work with Ionic Framework 2.0.0-rc.5.
The slides API has breaking changes in rc.5 and there are a lot of issues opened in the ionic repository.

**Comment by xyboox** [comment]
Understood @twinssbc . Thanks!

**Comment by marticrespi** [comment]
Hi @twinssbc 

What's about update angular version?

Is it still incompatible to upgrade above 2.0.1?

Thanks!

**Comment by twinssbc** [comment]
@marticrespi Since the current Ionic rc version always specify a certain Angular version in the POM.
I suggest do the same.
For example, if you want to use Ionic 2.0.0-rc.4, then upgrade Angular to 2.2.1, but not higher. Because we don't know if Ionic will break or not.

**Comment by twinssbc** [comment]
@xyboox I have found the way to fix the breaking change in rc.5. The latest 0.2.0 version is compatible with Ionic 2.0.0-rc.5. Feel free to have a try.

**Comment by xyboox** [comment]
Thanks @twinssbc , it seems to be working, but I just found another issue: let's say the calendar is loaded in month view to Jan. 2017. It will also show the days from 1st of Feb to 11th of Feb, which is correct. Now, if you tap on any of those days belonging to Feb, it will have the day selected correctly and also will slide to February, which is also correct. Problem is next, when regardless of the day you try to select, it will slide to the next month view. Always. If needed, I can provide a video showing it, just let me know. Can you please look into this? Thanks!

**Comment by twinssbc** [comment]
@xyboox I have fixed the bug in version 0.2.1. Feel free to have a try.

**Comment by xyboox** [comment]
After a quick test seems to be all working right. Will test more extensively tonight and let you know should any issue pop up. Thanks @twinssbc !
