### ISSUE TITLE
wan to display week number in month view 

### ISSUE THREAD

**Issue by rajneshkis13** [twinssbc/Ionic2-Calendar#420]
I want to display week number as first column in month calender view  

or range in calender header section
like april 2019  has week number from 14,15,16,17,18    then in header 14-18.

please help

**Comment by twinssbc** [comment]
@rajneshkis13 Displaying the week number as the first column is not supported. If you want to display the week number in the header, you could use the dateFormatter option, just implement the formatMonthViewDayHeader method.
