### ISSUE TITLE
Calendar resets to current month

### ISSUE THREAD

**Issue by mijke75** [twinssbc/Ionic2-Calendar#421]
I have a page with ion-segment in the header. The first segment shows the ionic2-calendar, the second segment shows a list of all events in that month.

I keep track of which month is shown in the calendar segment and update the list on the other segment. When I go back a month in time and go to the list it shows the correct events.

However, when I go back to the calendar it resets itself to the current month. I want it to stay in the selected month. Is this behavior by default or did I do something wrong?

<ion-header>
  <ion-toolbar>
    <ion-segment [(ngModel)]="view">
      <ion-segment-button value="calendar">Calendar</ion-segment-button>
      <ion-segment-button value="list">List</ion-segment-button>
    </ion-segment>
  </ion-toolbar>
</ion-header>

<ion-content class="monthly-log-content">
  <div *ngIf="view=='calendar'">

    <calendar
            [monthviewDisplayEventTemplate]="monthtemplate"
            [monthviewEventDetailTemplate]="eventtemplate"
            [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            startHour="0"
            endHour="24"
            step="30"
            startingDayMonth="1"
            startingDayWeek="1">
    </calendar>
</div>

  <div *ngIf="view=='list'">
    ...
  </div>
</ion-content>

**Comment by twinssbc** [comment]
@mijke75 The month displayed depends on the currentDate value. Do you reset the currentDate value when you go back?

**Comment by mijke75** [comment]
@twinssbc 

Thanks for your reply. I tried to do that, but it keeps jumping back to the current Month. I added the following code:

  // Change current month/week/day
  next() {
    var swiper = document.querySelector('.swiper-container')['swiper'];
    swiper.slideNext();
    
    var newDate = dayjs(this.myCal.currentDate).add(1, 'month').format('YYYY-MM-DD');
    // newDate is indeed the date for the next month
    this.myCal.currentDate = new Date(newDate);
  }

**Comment by twinssbc** [comment]
@mijke75 Could you paste the code of your whole HTML and ts? When is the next() method get triggered?

**Comment by mijke75** [comment]
**monthly-log.page.html**

<ion-header>
  <ion-toolbar color="primary">

    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>

    <ion-segment [(ngModel)]="view">
      <ion-segment-button value="calendar">
        Calendar
      </ion-segment-button>
      <ion-segment-button value="list">
        List
      </ion-segment-button>
    </ion-segment>

    <ion-buttons slot="end">
      <ion-button (click)="today()" *ngIf="view=='calendar'">
        <ion-icon slot="icon-only" name="today"></ion-icon>
      </ion-button>
      <ion-button routerLink="/app/future-log/new-entry">
        <ion-icon slot="icon-only" name="add"></ion-icon>
      </ion-button>

    </ion-buttons>

  </ion-toolbar>
</ion-header>

<ion-content class="monthly-log-content">

  <div *ngIf="view=='calendar'">

    <app-image-shell animation="spinner" class="loading-calendar" [data]="collection?.title"></app-image-shell>

    <ion-row ngClass="month-header">
      
      <ion-col size="2" text-left>
        <ion-button fill="clear" (click)="back()">
          <ion-icon name="arrow-back" slot="icon-only"></ion-icon>
        </ion-button>
      </ion-col>

      <ion-col ngClass="title" size="8" text-center>
        {{ viewTitle }}
      </ion-col>

      
      <ion-col size="2" text-right>
        <ion-button fill="clear" (click)="next()">
          <ion-icon name="arrow-forward" slot="icon-only"></ion-icon>
        </ion-button>
      </ion-col>
    </ion-row>

    <ng-template #monthtemplate let-view="view" let-row="row" let-col="col">
      <span class="calendar-day {{ view.dates[row*7+col].events[0]?.color }}">{{view.dates[row*7+col].label}}</span>
      <br>
      <div ngClass="event-bullet"></div>
    </ng-template>

    <ng-template #eventtemplate let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
      <ion-list #slidingList *ngIf="showEventDetail">

        <ion-item ngClass="entry"  *ngFor="let entry of selectedDate?.events" (click)="gotoEntry(entry?.entryID)">
          <ion-label ngClass="{{entry?.status}}">
            <h3>
              <span class="signifier {{entry?.signifier}}"></span>
              <span class="bullet {{entry?.bullet}}"></span>
              <app-text-shell animation="bouncing" [data]="entry?.log"></app-text-shell>
            </h3>
          </ion-label>
        </ion-item>

      </ion-list>
    </ng-template>

    <calendar
            [monthviewDisplayEventTemplate]="monthtemplate"
            [monthviewEventDetailTemplate]="eventtemplate"
            [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            startHour="0"
            endHour="24"
            step="30"
            startingDayMonth="1"
            startingDayWeek="1">
    </calendar>
  </div>





  <div *ngIf="view=='list'">
    <ion-list lines="none">
      <ion-item-group>

        <ion-item-divider ngClass="collection" sticky  *ngIf="collection?.title != ''">
          <ion-label>
            {{collection?.title}}
          </ion-label>
        </ion-item-divider>

        <ion-item-sliding *ngFor="let entry of collection?.entries">

          <ion-item ngClass="entry" routerLink="/app/monthly-log/entry/{{entry?.entryID}}">
            <ion-label ngClass="{{entry.status}}">
              <h3>
                <span class="signifier {{entry?.signifier}}"></span>
                <span class="bullet {{entry?.bullet}}"></span>
                {{entry?.log}}
              </h3>
            </ion-label>
          </ion-item>

          <ion-item-options>
            <ion-item-option color="primary" (click)="markDone(slidingItem, entry?.entryID)">
              Mark Done
            </ion-item-option>

            <ion-item-option color="secondary" (click)="markIrrelevant(slidingItem, entry?.entryID)">
              Mark Irrelevant
            </ion-item-option>

            <ion-item-option color="danger" (click)="deleteEntry(slidingItem, entry?.entryID, entry?.log)">
              Delete
            </ion-item-option>
          </ion-item-options>

        </ion-item-sliding>

      </ion-item-group>
    </ion-list>

  </div>

</ion-content>


**monthly-log.page.ts**

import { CalendarComponent } from 'ionic2-calendar/calendar';
import { Component, ViewChild, OnInit, Inject, LOCALE_ID } from '@angular/core';
import {Router, ActivatedRoute} from "@angular/router";

import { formatDate } from '@angular/common';
import {IndexCollectionsEntriesListingModel} from "../../models/index-collections-entries-listing.model";
import * as dayjs from 'dayjs';

@Component({
  selector: 'app-monthly-log',
  templateUrl: './monthly-log.page.html',
  styleUrls: [
    './styles/monthly-log.page.scss',
    './styles/monthly-log.shell.scss'
  ],
})
export class MonthlyLogPage implements OnInit {

  index: IndexCollectionsEntriesListingModel;
  collection: any;
  collectionId: any;
  identifier: string;

  slidingItem: any;
  view: string = 'calendar';

  eventSource = [];
  viewTitle: string = '';

  calendar = {
    mode: 'month',
    currentDate: new Date(),
  };

  @ViewChild(CalendarComponent) myCal: CalendarComponent;


  constructor(
    private router: Router,
    private route: ActivatedRoute,
    @Inject(LOCALE_ID) private locale: string
  ) {

    this.collectionId = this.route.snapshot.paramMap.get('collectionId');

    if(this.collectionId == null || this.collectionId > 0) {
      let year = this.calendar.currentDate.getFullYear();
      let month = this.calendar.currentDate.getMonth();
      month++;
      let showMonth = month.toString();
      if(month < 10) {
        showMonth = '0' + month;
      }

      this.identifier = year.toString() + '-' + showMonth;
    }
  }

  ngOnInit() {

  }


  ionViewWillEnter() {

    if (this.route && this.route.data) {
      // We resolved a promise for the data Observable
      const promiseObservable = this.route.data;
      console.log('Route Resolve Observable => promiseObservable: ', promiseObservable);

      if (promiseObservable) {
        promiseObservable.subscribe(promiseValue => {
          const dataObservable = promiseValue['data'];
          console.log('Subscribe to promiseObservable => dataObservable: ', dataObservable);

          if (dataObservable) {
            dataObservable.subscribe(observableValue => {
              const pageData: IndexCollectionsEntriesListingModel = observableValue;
              // tslint:disable-next-line:max-line-length
              console.log('Subscribe to dataObservable (can emmit multiple values) => PageData (' + ((pageData && pageData.isShell) ? 'SHELL' : 'REAL') + '): ', pageData);
              // As we are implementing an App Shell architecture, pageData will be firstly an empty shell model,
              // and the real remote data once it gets fetched
              if (pageData) {
                this.index = pageData;

                if (!pageData.isShell) {
                  this.setEntries();
                }

              }
            });
          } else {
            console.warn('No dataObservable coming from Route Resolver promiseObservable');
          }
        });
      } else {
        console.warn('No promiseObservable coming from Route Resolver data');
      }
    } else {
      console.warn('No data coming from Route Resolver');
    }

  }

  setEntries() {

    this.eventSource = [];

    this.index.collections.forEach( collection => {

      if(collection.collectionID == this.collectionId || collection.identifier == this.identifier) {
        this.collection = collection;

        let year = parseFloat(collection.identifier.split('-')[0]);
        let month = parseFloat(collection.identifier.split('-')[1]);
        month--;

        this.identifier = collection.identifier;
        this.calendar.currentDate = new Date(Date.UTC(year,month,1));
      }

      collection.entries.forEach(entry => {

        let eventCopy = {
          entryID: entry.entryID,
          log: entry.log,
          startTime:  new Date(entry.startTime),
          endTime: new Date(entry.endTime),
          allDay: false,
          desc: entry.description,
          bullet: entry.bullet,
          signifier: entry.signifier,
          status: entry.status,
          subcount: entry.subcount,
          subentries: entry.subentries
        }

        if (eventCopy.allDay) {
          let start = eventCopy.startTime;
          let end = eventCopy.endTime;

          eventCopy.startTime = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate()));
          eventCopy.endTime = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth(), end.getUTCDate() + 1));
        }

        this.eventSource.push(eventCopy);
        this.myCal.loadEvents();

      });
    });

    if(!this.collection) {
      this.collection = {title: ' '};
    }

  }

  // Change current month/week/day
  next() {

    let tmp = new Date(this.identifier);
    this.identifier = dayjs(tmp).add(1, 'month').format('YYYY-MM');

    var newDate = dayjs(this.myCal.currentDate).add(1, 'month').format('YYYY-MM-DD');
    this.myCal.currentDate = new Date(newDate);

    this.loadList();

    // var swiper = document.querySelector('.swiper-container')['swiper'];
    // swiper.slideNext();
  }

  back() {

    let tmp = new Date(this.identifier);
    this.identifier = dayjs(tmp).add(-1, 'month').format('YYYY-MM');

    var newDate = dayjs(this.myCal.currentDate).add(1, 'month').format('YYYY-MM-DD');
    this.myCal.currentDate = new Date(newDate);

    this.loadList();

    // var swiper = document.querySelector('.swiper-container')['swiper'];
    // swiper.slidePrev();
  }

  loadList() {
    this.collection = {title: ' '};
    this.index.collections.forEach( collection => {

      if(collection.identifier == this.identifier) {
        this.collection = collection;

      }
    });
  }

// Change between month/week/day
  changeMode(mode) {
    this.calendar.mode = mode;
  }

// Focus today
  today() {
    this.calendar.currentDate = new Date();
  }

// calendar date changed
  onCurrentDateChanged = (ev: Date) => {
    console.log('Currently viewed date: ' + ev);
  };

// Selected date reange and hence title changed
  onViewTitleChanged(title) {
    this.viewTitle = title;
  }

// Calendar event was clicked
  async onEventSelected(event) {

  }

// Time slot was clicked
  onTimeSelected(ev) {

  }

  gotoEntry(entryId) {
    this.router.navigateByUrl( "/app/monthly-log/entry/" + entryId);
  }

  markDone(slidingItem, entryId) {
    // Needs work
  }

  markIrrelevant(slidingItem, entryId) {
    // Needs work
  }

  deleteEntry(slidingItem, entryId, entryLog) {
    // Needs work
  }

}

**Comment by mijke75** [comment]
next() and back() are triggered from the calendar header in the HTML.

I hope I did something stupid and you can point it to me, since this is keeping me busy for a while :)

Thanks in advance for looking at it.

**Comment by twinssbc** [comment]
@mijke75 It seems you are setting this.myCal.currentDate. But actually you are binding to this.calendar.currentDate. Could you try using that variable?

**Comment by mijke75** [comment]
Thank you! That's the solution. Thank you so much for taking a look at it!
