### ISSUE TITLE
showEventDetail not updating after update the eventSource ?

### ISSUE THREAD

**Issue by karouAhmed** [twinssbc/Ionic2-Calendar#422]
@twinssbc  The showEventDetail not updating after updating the eventSource ,the lastest values still below ... Solution please !!!

**Comment by twinssbc** [comment]
@karouAhmed Do you want to set the showEventDetail dynamically? This is not supported. It only takes effect on the initialization phase.

**Comment by karouAhmed** [comment]
@twinssbc can i initialize it ?

**Comment by twinssbc** [comment]
Just set the showEventDetail option when declaring the calendar in HTML.
```
    <calendar [eventSource]="eventSource"
              [calendarMode]="calendar.mode"
              [currentDate]="calendar.currentDate"
              (onCurrentDateChanged)="onCurrentDateChanged($event)"
              (onTitleChanged)="onViewTitleChanged($event)"
              (onTimeSelected)="onTimeSelected($event)"
              (onEventSelected)="onEventSelected($event)"
              **[showEventDetail] = false**
              step="30"
    ></calendar>
```

**Comment by karouAhmed** [comment]
@twinssbc No, i want to reset it every time if it possible please !!

**Comment by twinssbc** [comment]
@karouAhmed As I said it only takes effect during initialization phase. If you just want to show nothing if there's no event, you could simply set **noEventsLabel** to empty string. Or you could try using **monthviewEventDetailTemplate** to create a custom view of event detail section which could be shown/hidden based on your own variable.

**Comment by karouAhmed** [comment]
@twinssbc Can you give me an exemple of monthviewEventDetailTemplate,i'am beginner in this , please ...

**Comment by twinssbc** [comment]
@karouAhmed This is the default template of the month view event detail section. The default logic is the selectedDate.events will be set when you select a date in the month view. You don't need to initialize it.

**Comment by karouAhmed** [comment]
@twinssbc When i update the evenSource,it not updated,and it will show me the lastest events and upated events , even i delete them !!

**Comment by twinssbc** [comment]
@karouAhmed How do you update the eventSource?

**Comment by karouAhmed** [comment]
@twinssbc I set it null everytime and push the new event ...But thats methode not working !!

**Comment by twinssbc** [comment]
@karouAhmed Could you provide the code of your method? If you just push the event into the eventSource array, it won't work. Take a look at the "EventSource" section in README.

**Comment by karouAhmed** [comment]
![image](https://user-images.githubusercontent.com/39932045/56420718-5eb8c400-629f-11e9-8cc9-1ea48df3fc9d.png)

**Comment by twinssbc** [comment]
@karouAhmed You don't need to call loadEvents in the forEach loop, you could call it after the whole eventSource array is filled.
Also is it only the event detail section not display the newly loaded events? The other sections could display the events?

**Comment by karouAhmed** [comment]
@twinssbc I don't unsderstand your question !!

**Comment by twinssbc** [comment]
@karouAhmed Could you provide a screenshot?

**Comment by karouAhmed** [comment]
![sd](https://user-images.githubusercontent.com/39932045/56500684-2cf86500-650c-11e9-9f1f-a0c5496f55eb.PNG)
![sq](https://user-images.githubusercontent.com/39932045/56500685-2cf86500-650c-11e9-9287-da58ebbbbd3d.PNG)
when i add an other one ...

**Comment by twinssbc** [comment]
@karouAhmed Could you debug to see why the eventSource array contains duplicated records after you fill the array in your loading callback?

**Comment by karouAhmed** [comment]
@twinssbc I find the mistake ...the 'rdvs' arrays it not initialized ,evey update it take the old values and the newest ... Sorry for wasting your time ...Thanks 😊
