### ISSUE TITLE
[help] weekviewHeaderTemplate

### ISSUE THREAD

**Issue by StefanVerresen** [twinssbc/Ionic2-Calendar#423]
**1) Is it possible to only get the particular days in a week like in the example below with the WeekviewHeaderTemplate?**

![image](https://user-images.githubusercontent.com/32302024/56371130-d386f200-61fc-11e9-858c-f0dd8732d251.png)

**2) If it is possible, how do I use it in my code?**

`ng-template #template let-viewDate="viewDate"> `
`<div class="custom-day-header"> {{ viewDate.dayHeader }} </div>`  
`</ng-template>` 

`<calendar[calendarMode]="calendar.mode"`
` [currentDate]="calendar.currentDate">`
` [step]="30">`
` [timeInterval]="30">`
` [weekviewHeaderTemplate]="template">`
`</calendar>`

**Comment by twinssbc** [comment]
@StefanVerresen I'm not sure which part do you want to display as the screenshot you provided.
There are quite a few of week view related templates that can be used for customization. Feel free to get more explanation and usage in README.

**Comment by StefanVerresen** [comment]
I would like to implement a weekly view like the screenshot above.
I would guess it is the 'weekviewHeaderTemplate' right?µ
And If so, how would I implement a template in my code, I find no direct examples of the usage of templates in the readme or in the examples so I was wondering how to exactly code it.

**Comment by twinssbc** [comment]
@StefanVerresen I'm afraid this calendar doesn't support your requirement. Your layout is more similar to the month view, but only with one week. But the whole month view is swiped on month basis. It doesn't support navigation between weeks.

**Comment by StefanVerresen** [comment]
Yes only the headers of the weekview, without all the 'hours' partition below where the events are located. Even without the navigation between the weeks, just a nice representation of the weeks would be great :)

**Comment by twinssbc** [comment]
@StefanVerresen In this case, I suggest you write your own page, as you won't be utilize most of the features of this calendar.

**Comment by akshaykatale99** [comment]
@twinssbc can we have the events data in weekviewHeaderTemplate

**Comment by twinssbc** [comment]
@akshaykatale99 No, only viewDate is passed to the weekviewHeaderTemplate.

**Comment by pixolopr** [comment]
`
    <div class="scrollable-calender">
        <ng-template #template let-viewDate="viewDate">
            <div class="single-date" (click)="dateClick(viewDate.date)"
                [ngClass]="{'active-date': getDateCode(viewDate.date) == activeDate}">
                <div class="custom-day-header date-title"> {{ viewDate.dayHeader.substring(0, 3) }} </div>
                <div class="custom-day-header date-value"> {{ viewDate.dayHeader.substring(3, 6) }} </div>
            </div>
        </ng-template>
        <div class="floating-background">
            <div></div>
        </div>


        <calendar [weekviewHeaderTemplate]="template" [eventSource]="eventSource" [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate" (onTitleChanged)="onViewTitleChanged($event)" startHour="0"
            endHour="0">
        </calendar>
    </div>


    <p class="todays-date">{{dietDate|fullDate}}</p>
    `
