### ISSUE TITLE
Week and day view template makes end time of events wrong

### ISSUE THREAD

**Issue by MaryemZOBI** [twinssbc/Ionic2-Calendar#425]
Hi,
I'm trying to implement week and day view template in my calendar to customize  events color, without template the calendar works fine with right interval (or time range)  but when I use the template  Customisation   that gives just the to each event 1 hour as duration
Example:
without day template Custm:
![err](https://user-images.githubusercontent.com/38964877/56753304-27cf2c00-673f-11e9-9b7f-9cd990fb3bcd.PNG)

with day template Custm:
![sol](https://user-images.githubusercontent.com/38964877/56753326-31f12a80-673f-11e9-9711-1814c21d16ff.PNG)
I have this problem for both day and view templates Customization

thanks in advance

**Comment by twinssbc** [comment]
@MaryemZOBI Could you provide your template code? The default template is using some css style to set the height of each event, you may need to apply the same logic.

**Comment by MaryemZOBI** [comment]
thanks for replaying , here is my full code [https://github.com/MaryemZOBI/ionic-app](url) , I have no idea about seting height  of each event can you give some code or example how I can solve that problem .

**Comment by twinssbc** [comment]
@MaryemZOBI  I copied your code in my demo code, it is working, and no need to set the height separately. I suspect that you didn't set the startTime and endTime correctly, so that the height is not calculated correctly. You could refer to the demo code and modify it to support your own field in the event.

**Comment by MaryemZOBI** [comment]
I think the startTime and endTime are correct if not, why when I eliminate the Day and week templates the height of each event shows correctly

**Comment by twinssbc** [comment]
ok, make sense. Then could you clean up your code a bit to make it easy for debugging? I can't directly  run your code.

Below is my sample,

HTML
```
    <ng-template #template let-displayEvent="displayEvent" >
        <div class="calendar-event-inner" [ngStyle]="{'background-color': displayEvent.event.eventColor}">{{displayEvent.event.title}}</div>
    </ng-template>

    <calendar
            [weekviewNormalEventTemplate]="template2"
            [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            startHour="8"
            endHour="19"
            step="30"
            startingDayWeek="1">
    </calendar>
```

event format in ts
```
                var startMinute = Math.floor(Math.random() * 24 * 60);
                var endMinute = Math.floor(Math.random() * 180) + startMinute;
                startTime = new Date(date.getFullYear(), date.getMonth(), date.getDate() + startDay, 0, date.getMinutes() + startMinute);
                endTime = new Date(date.getFullYear(), date.getMonth(), date.getDate() + endDay, 0, date.getMinutes() + endMinute);
                events.push({
                    title: 'Event',
                    startTime: startTime,
                    endTime: endTime,
                    allDay: false,
                    eventColor: 'blue'
                });
```
