### ISSUE TITLE
Ionic2-calendar does not save data

### ISSUE THREAD

**Issue by Majedmadamani** [twinssbc/Ionic2-Calendar#427]

**Comment by Majedmadamani** [comment]
Can someone please help me fix the issue

**Comment by twinssbc** [comment]
@Majedmadamani What do you mean "save data"? The calendar only displays the events stored in the eventSource array. It doesn't write events to anywhere.

**Comment by Majedmadamani** [comment]
Like if I exit the app when testing on the phone and open it again the event that I added before I exit did not apear

**Comment by abnet3** [comment]
am facing the same issue. is their any method to achieve this?

**Comment by twinssbc** [comment]
@abnet3 The calendar is only for displaying the events, not for saving events.

**Comment by Majedmadamani** [comment]
How would you save them though can you teach us in a specific way please

**Comment by twinssbc** [comment]
@Majedmadamani You could send your newly added events to the backend, then the backend stores them into the database. When you open the calendar next time, it fetches events from the backend and fill into the eventSource array.

**Comment by Majedmadamani** [comment]
Thanks for help

**Comment by Majedmadamani** [comment]
I still have another question, I use admob pro plugin but when I test the app on an debug apk it does not show ads I don’t use test ads too

**Comment by Majedmadamani** [comment]
@twinssbc I was able to store the data to firebase database base but I was not able to push when the page reloads. This is my ts file page 
`import { CalendarComponent } from 'ionic2-calendar/calendar';
import { Component, ViewChild, OnInit, Inject, LOCALE_ID } from '@angular/core';
import { AlertController } from '@ionic/angular';
import { formatDate } from '@angular/common';
import { AngularFirestore } from '@angular/fire/firestore';
import { AngularFireAuth } from '@angular/fire/auth';


@Component({
 selector: 'calendar-home',
 templateUrl: './calendar.page.html',
 styleUrls: ['./calendar.page.scss'],
})
export class CalendarPage implements OnInit {

 event = {
   title: '',
   desc: '',
   startTime: '',
   endTime: '',
   allDay: false,
 };
 event1 = {
  title: this.event.title,
  startTime:  new Date(this.event.startTime),
  endTime: new Date(this.event.endTime),
  allDay: this.event.allDay,
  desc: this.event.desc,
};

 minDate = new Date().toISOString();

 eventSource = [];


 calendar = {
   mode: 'month',
   currentDate: new Date(),
 };

 selectedDate = new Date();


 viewTitle = '';

 @ViewChild(CalendarComponent) myCal: CalendarComponent;

 constructor(private db: AngularFirestore, private alertCtrl: AlertController, @Inject(LOCALE_ID) private locale: string,
             private afAuth: AngularFireAuth, ) {
              this.db.collection(`users/${this.afAuth.auth.currentUser.uid}/evnets`).snapshotChanges().subscribe(colSnap => {
                this.eventSource = [];
                colSnap.forEach(snap => {
                  // tslint:disable-next-line:prefer-const
                  let event1: any = snap.payload.doc.data();
                  event1 = snap.payload.doc.id;
                  this.event.startTime = event1.startTime.toDate();
                  this.event.endTime = event1.endTime.toDate();
                  console.log(this.event);
                  this.eventSource.push(this.event);
                });
              });
  }

 ngOnInit() {
   this.resetEvent();
 }

   // Create the right event format and reload source
   addEvent() {
     // tslint:disable-next-line:prefer-const
     let event = {
       title: this.event.title,
       startTime:  new Date(this.event.startTime),
       endTime: new Date(this.event.endTime),
       allDay: this.event.allDay,
       desc: this.event.desc,
     };
     this.db.collection(`users/${this.afAuth.auth.currentUser.uid}/evnets`).add({
       event
     });

     if (event.allDay) {
       // tslint:disable-next-line:prefer-const
       let start = event.startTime;
       // tslint:disable-next-line:prefer-const
       let end = event.endTime;

       event.startTime = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate()));
       event.endTime = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth(), end.getUTCDate() + 1));


     }

     this.eventSource.push(event);
     this.myCal.loadEvents();
     this.resetEvent();
   }
changeMode(mode) {
     this.calendar.mode = mode;
   }

 // Change current month/week/day
next() {
 // tslint:disable-next-line:prefer-const
 let swiper = document.querySelector('.swiper-container')['swiper'];
 swiper.slideNext();
}

back() {
 // tslint:disable-next-line:prefer-const
 let swiper = document.querySelector('.swiper-container')['swiper'];
 swiper.slidePrev();
}

// Focus today
today() {
 this.calendar.currentDate = new Date();
}
// Calendar event was clicked
async onEventSelected(event) {
 // Use Angular date pipe for conversion
 // tslint:disable-next-line:prefer-const
 let start = formatDate(event.startTime, 'medium', this.locale);
 // tslint:disable-next-line:prefer-const
 let end = formatDate(event.endTime, 'medium', this.locale);

 const alert = await this.alertCtrl.create({
   header: event.title,
   subHeader: event.desc,
   message: 'From: ' + start + '<br><br>To: ' + end,
   buttons: ['OK']
 });
 alert.present();
}

// Selected date reange and hence title changed
onViewTitleChanged(title) {
 this.viewTitle = title;
}

// Time slot was clicked
onTimeSelected(ev) {
 // tslint:disable-next-line:prefer-const
 let selected = new Date(ev.selectedTime);
 this.event.startTime = selected.toISOString();
 selected.setHours(selected.getHours() + 1);
 this.event.endTime = (selected.toISOString());
}

 resetEvent() {
   this.event = {
     title: '',
     desc: '',
     startTime: new Date().toISOString(),
     endTime: new Date().toISOString(),
     allDay: false
   };
 }

}
` 
and this is my html file
`<ion-header>
  <ion-toolbar color="primary">
    <ion-title>
      {{ viewTitle }}
    </ion-title>
    <ion-buttons slot="end">
      <ion-button (click)="today()">Today</ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
 
<ion-content>
 
  
  <ion-card>
    <ion-card-header tappable (click)="collapseCard = !collapseCard">
      <ion-card-title>New Event</ion-card-title>
    </ion-card-header>
    <ion-card-content *ngIf="!collapseCard">
 
      <ion-item>
        <ion-input type="text" placeholder="Title" [(ngModel)]="event.title"></ion-input>
      </ion-item>
      <ion-item>
        <ion-input type="text" placeholder="Description" [(ngModel)]="event.desc"></ion-input>
      </ion-item>
      <ion-item>
        <ion-label>Start</ion-label>
        <ion-datetime displayFormat="MM/DD/YYYY HH:mm" pickerFormat="MMM D:HH:mm" [(ngModel)]="event.startTime" [min]="minDate"></ion-datetime>
      </ion-item>
      <ion-item>
        <ion-label>End</ion-label>
        <ion-datetime displayFormat="MM/DD/YYYY HH:mm" pickerFormat="MMM D:HH:mm" [(ngModel)]="event.endTime" [min]="minDate"></ion-datetime>
      </ion-item>
      <ion-item>
        <ion-label>All Day?</ion-label>
        <ion-checkbox [(ngModel)]="event.allDay"></ion-checkbox>
      </ion-item>
      <ion-button fill="outline" expand="block" (click)="addEvent()" [disabled]="event.title == ''">Add Event</ion-button>
 
    </ion-card-content>
  </ion-card>
 
  <ion-row>
    
    <ion-col size="4">
      <ion-button expand="block" [color]="calendar.mode == 'month' ? 'primary' : 'secondary'" (click)="changeMode('month')">Month</ion-button>
    </ion-col>
    <ion-col size="4">
      <ion-button expand="block" [color]="calendar.mode == 'week' ? 'primary' : 'secondary'" (click)="changeMode('week')">Week</ion-button>
    </ion-col>
    <ion-col size="4">
      <ion-button expand="block" [color]="calendar.mode == 'day' ? 'primary' : 'secondary'" (click)="changeMode('day')">Day</ion-button>
    </ion-col>
 
    
    <ion-col size="6" text-left>
      <ion-button fill="clear" (click)="back()">
        <ion-icon name="arrow-back" slot="icon-only"></ion-icon>
      </ion-button>
    </ion-col>
 
    
    <ion-col size="6" text-right>
      <ion-button fill="clear" (click)="next()">
        <ion-icon name="arrow-forward" slot="icon-only"></ion-icon>
      </ion-button>
    </ion-col>
  </ion-row>
 
  <calendar 
  [eventSource]="eventSource" 
  [calendarMode]="calendar.mode" 
  [currentDate]="calendar.currentDate"
  (onEventSelected)="onEventSelected($event)"
  (onTitleChanged)="onViewTitleChanged($event)"
  (onTimeSelected)="onTimeSelected($event)" 
  startHour="6"
  endHour="20"
  step="30"
  startingDayWeek="1">
  </calendar>
 
</ion-content>`

**Comment by twinssbc** [comment]
@Majedmadamani You could use loadEvents instance method. More details in README.

**Comment by Majedmadamani** [comment]
There is no link to read me
