### ISSUE TITLE
monthviewDisplayEventTemplate styling

### ISSUE THREAD

**Issue by henleywc** [twinssbc/Ionic2-Calendar#428]
Hi, 

I'm trying to remove the all the border from the month view template but after apply the css all the border still persist. may i know what is the right way to achieve that? thanks~
![Untitled](https://user-images.githubusercontent.com/10055664/57388221-57277380-71ea-11e9-9d69-765594875c9e.png)

**Comment by twinssbc** [comment]
@henleywc You could add below css in global.scss.

```
.monthview-datetable td, .monthview-datetable th{
  border: none !important;
}
```

**Comment by henleywc** [comment]
@twinssbc  thanks a lot for the help.
