### ISSUE TITLE
onTimeSelected wants to add new class name in selected date

### ISSUE THREAD

**Issue by rajneshkis13** [twinssbc/Ionic2-Calendar#429]
i want to highlight selected date only in some cases.
Like 02-05-2019 i click then there is a classs monthview-selected but i want to add new class if some condition comes true.

please help

**Comment by twinssbc** [comment]
@rajneshkis13 You could use **monthviewDisplayEventTemplate** to apply your own template. The template could use ngClass to enable your own conditions.

**Comment by rajneshkis13** [comment]
i am not so clear how to do 
can you suggest by snippet

**Comment by twinssbc** [comment]
@rajneshkis13 
You could add ngClass in your template12.
For example,
```
       <ng-template #template let-view="view" let-row="row" let-col="col">
            <div [ngClass]="{'someCSSClass': someCondition}">{{view.dates[row*7+col].label}}</div>
        </ng-template>
```

Then in the onTimeSelected method, trigger that someCondition.

**Comment by rajneshkis13** [comment]
this will not color the whole column 
![Screenshot 1941-02-20 at 6 18 23 PM](https://user-images.githubusercontent.com/32674573/57528479-0fbaf780-7350-11e9-9b85-7855aab33e85.png)

i need color in full td

![Screenshot 1941-02-20 at 6 20 12 PM](https://user-images.githubusercontent.com/32674573/57528567-485ad100-7350-11e9-9af5-03731a51c3b2.png)

**Comment by twinssbc** [comment]
@rajneshkis13 That's because your div doesn't occupy the whole height of the cell. You may need to spend some time on tuning your css styles.
