### ISSUE TITLE
February ends the 31 instead of 28.

### ISSUE THREAD

**Issue by ThomasKientz** [twinssbc/Ionic2-Calendar#43]
Test with ionic2-calendar v0.2.0.

February should end on the 28th, not the 31. I think it's just about the display cause it's sliding as it  should to march when I selected the 29+ of Feb.

<img width="342" alt="capture d ecran 2017-01-24 a 09 45 32" src="https://cloud.githubusercontent.com/assets/10157845/22232145/3a73d6a0-e21a-11e6-876d-a8ea55bd05f9.png">

Great work by the way, this calendar is very useful to me ;)

**Comment by twinssbc** [comment]
@ThomasKientz I have fixed the bug in version 0.2.1. Feel free to have a try.
