### ISSUE TITLE
I don't know how to push the events when the users reopens the calendar 

### ISSUE THREAD

**Issue by Majedmadamani** [twinssbc/Ionic2-Calendar#432]
`import { CalendarComponent } from 'ionic2-calendar/calendar';
import { Component, ViewChild, OnInit, Inject, LOCALE_ID } from '@angular/core';
import { AlertController } from '@ionic/angular';
import { formatDate } from '@angular/common';
import { AngularFirestore } from '@angular/fire/firestore';
import { AngularFireAuth } from '@angular/fire/auth';
import { Platform, ToastController, IonList } from '@ionic/angular';
import { StorageService, Item } from '../../services/storage.service';

@Component({
 selector: 'calendar-home',
 templateUrl: './calendar.page.html',
 styleUrls: ['./calendar.page.scss'],
})
export class CalendarPage implements OnInit {
    items: Item[] = [];

  // tslint:disable-next-line:no-angle-bracket-type-assertion
  newItem: Item = <Item> {};

 event = {
   title: '',
   desc: '',
   startTime: '',
   endTime: '',
   allDay: false,
 };

 minDate = new Date().toISOString();

 eventSource = [];

 calendar = {
   mode: 'month',
   currentDate: new Date(),
 };

 selectedDate = new Date();

 viewTitle = '';

 @ViewChild(CalendarComponent) myCal: CalendarComponent;
 @ViewChild('mylist')mylist: IonList;

 constructor(private db: AngularFirestore, private alertCtrl: AlertController, @Inject(LOCALE_ID) private locale: string,
             private storageService: StorageService, private plt: Platform, private toastController: ToastController ) {
              this.plt.ready().then(() => {
                this.loadItems();
              });
             }

 ngOnInit() {
   this.resetEvent();
 }
 loadItems() {
  this.storageService.getItems().then(items => {
    this.items = items;
  });
}

   // Create the right event format and reload source
   addEvent() {
     // tslint:disable-next-line:prefer-const
     let eventCopy = {
       title: this.event.title,
       startTime:  new Date(this.event.startTime),
       endTime: new Date(this.event.endTime),
       allDay: this.event.allDay,
       desc: this.event.desc,
     };
     this.newItem.startTime = new Date(this.event.startTime);
     this.newItem.endTime = new Date(this.event.endTime);
     this.newItem.title = this.event.title;
     this.newItem.desc = this.event.desc;
     this.newItem.allDay = this.event.allDay;

     this.storageService.addItem(this.newItem).then(item => {
       // tslint:disable-next-line:no-angle-bracket-type-assertion
       this.newItem = <Item> {};
       this.showToast('item added');
       this.loadItems(); // Or add it to the array directly
     });

     if (eventCopy.allDay) {
       // tslint:disable-next-line:prefer-const
       let start = eventCopy.startTime;
       // tslint:disable-next-line:prefer-const
       let end = eventCopy.endTime;

       eventCopy.startTime = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate()));
       eventCopy.endTime = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth(), end.getUTCDate() + 1));

     }

     this.eventSource.push(eventCopy);
     this.myCal.loadEvents();
     this.resetEvent();
   }
changeMode(mode) {
     this.calendar.mode = mode;
   }

 // Change current month/week/day
next() {
 // tslint:disable-next-line:prefer-const
 let swiper = document.querySelector('.swiper-container')['swiper'];
 swiper.slideNext();
}
  // DELETE
  deleteItem(item: Item) {
    // tslint:disable-next-line:no-shadowed-variable
    this.storageService.deleteItem(item.id).then(item => {
      this.showToast('Item removed!');
      this.mylist.closeSlidingItems(); // Fix or sliding is stuck afterwards
      this.loadItems(); // Or splice it from the array directly
    });
  }

back() {
 // tslint:disable-next-line:prefer-const
 let swiper = document.querySelector('.swiper-container')['swiper'];
 swiper.slidePrev();
}

// Focus today
today() {
 this.calendar.currentDate = new Date();
}
// Calendar event was clicked
async onEventSelected(event) {
 // Use Angular date pipe for conversion
 // tslint:disable-next-line:prefer-const
 let start = formatDate(event.startTime, 'medium', this.locale);
 // tslint:disable-next-line:prefer-const
 let end = formatDate(event.endTime, 'medium', this.locale);

 const alert = await this.alertCtrl.create({
   header: event.title,
   subHeader: event.desc,
   message: 'From: ' + start + '<br><br>To: ' + end,
   buttons: ['OK']
 });
 alert.present();
}

// Selected date reange and hence title changed
onViewTitleChanged(title) {
 this.viewTitle = title;
}

// Time slot was clicked
onTimeSelected(ev) {
 // tslint:disable-next-line:prefer-const
 let selected = new Date(ev.selectedTime);
 this.event.startTime = selected.toISOString();
 selected.setHours(selected.getHours() + 1);
 this.event.endTime = (selected.toISOString());
}

 resetEvent() {
   this.event = {
     title: '',
     desc: '',
     startTime: new Date().toISOString(),
     endTime: new Date().toISOString(),
     allDay: false
   };
 }
 async showToast(msg) {
  const toast = await this.toastController.create({
    message: msg,
    duration: 2000
  });
  toast.present();
}

}`
that's my ts file and this is my service ts file
`import { Injectable } from '@angular/core';
import { Storage } from '@ionic/storage';

export interface Item {
  id: number;
  title: string;
  desc: string;
  startTime: Date;
  endTime: Date;
  allDay: boolean;
  eventCopy: '';
}

const ITEMS_KEY = 'my-items';

@Injectable({
  providedIn: 'root'
})
export class StorageService {

  constructor(private storage: Storage) { }

  // CREATE
  addItem(item: Item): Promise<any> {
    return this.storage.get(ITEMS_KEY).then((items: Item[]) => {
      if (items) {
        items.push(item);
        return this.storage.set(ITEMS_KEY, items);
      } else {
        return this.storage.set(ITEMS_KEY, [item]);
      }
    });
  }

  // READ
  getItems(): Promise<Item[]> {
    return this.storage.get(ITEMS_KEY);
  }

  // UPDATE
  updateItem(item: Item): Promise<any> {
    return this.storage.get(ITEMS_KEY).then((items: Item[]) => {
      if (!items || items.length === 0) {
        return null;
      }

      // tslint:disable-next-line:prefer-const
      let newItems: Item[] = [];

      // tslint:disable-next-line:prefer-const
      for (let i of items) {
        if (i.id === item.id) {
          newItems.push(item);
        } else {
          newItems.push(i);
        }
      }

      return this.storage.set(ITEMS_KEY, newItems);
    });
  }

  // DELETE
  deleteItem(id: number): Promise<Item> {
    return this.storage.get(ITEMS_KEY).then((items: Item[]) => {
      if (!items || items.length === 0) {
        return null;
      }

      // tslint:disable-next-line:prefer-const
      let toKeep: Item[] = [];

      // tslint:disable-next-line:prefer-const
      for (let i of items) {
        if (i.id !== id) {
          toKeep.push(i);
        }
      }
      return this.storage.set(ITEMS_KEY, toKeep);
    });
  }
}
`

it does save but it does not show them after can someone help

**Comment by twinssbc** [comment]
@Majedmadamani Could you clean up your code? Just focus on loading events from backend.

**Comment by Majedmadamani** [comment]
Thank you I solved it
