### ISSUE TITLE
Ionic 4 calendar

### ISSUE THREAD

**Issue by harpreet2602** [twinssbc/Ionic2-Calendar#433]
Can you share the same example with ionic 4 ?

**Comment by twinssbc** [comment]
@harpreet2602 The example code is here
https://github.com/twinssbc/Ionic2-Calendar/tree/master/demo
It is based on Ionic 2, but it's almost the same. Just the dependency version and module name may be different.

**Comment by harpreet2602** [comment]
Sure, I have integrated it in ionic4 app...
Is there a way I can show the month and year on the top on calendar, such that clicking on it, it shows the stepper with all the months and clicking the month selects that particular month. Toggling it, it changes the month and year in the calendar.
Something like this <MAY, 2019>

**Comment by twinssbc** [comment]
@harpreet2602 Yes, the calendar binds to currentDate variable. So when you change the currentDate, the calendar will jump to that month. The way you described to select/toggle the month is not part of the calendar. You need to implement it by yourself.

**Comment by harpreet2602** [comment]
@twinssbc , great.
Which event is triggered when we swipe to change the month on the calendar?

**Comment by harpreet2602** [comment]
@twinssbc , 
Also, when I call "this.myCalendar.loadEvents();" from the function "onTimeSelected" it goes in loop and "onTimeSelected" gets called endless. Is this a bug ? 

My use case is:
> On calendar swipe "onTimeSelected" function is called. From this function I am calling another fucntion which is loading the events from firebase and pushing the data to eventSource. But it did not updated the calendar with the events. And, nothing on the calendar is shown. 
> Hence, I called  "this.myCalendar.loadEvents();" after pushing the data in eventStore . And, after calling this, "onTimeSelected" is getting called recursively.

**Comment by twinssbc** [comment]
@harpreet2602 You should set the events in the onRangeChanged method instead of onTimeSelected method.

**Comment by harpreet2602** [comment]
@twinssbc , onRangeChanged does not solve my purpose. 
Hence, I used onViewTitleChanged method from where I am calling firebase based on the month that I get after swiping the calendar but the issue is calendar is not automatically showing the events even after "this.eventSource = events"


`listEventRef.once("value").then((meetingSnapshot) => {
      this.eventSource = [];
      this.meetingData =  meetingSnapshot;

      let eventData = {};
      let events = this.eventSource;

      this.meetingData.forEach((data) => {

        events.push({
          title: data.val().calTitle,
          notes: data.val().calNotes,
          room: data.val().calPlace,
          startTime: new Date(data.val().calStartTime),
          endTime: new Date(data.val().calEndTime),
          allDay: data.val().callsAllDay
        });

        setTimeout(() => {
          this.eventSource = events;
        });

	 })

      //this.myCalendar.loadEvents();
}`

**Comment by twinssbc** [comment]
Your logic seems a bit incorrect.
You just need to fill an event array and assign it to eventSource.
```
  let eventData = {};
  let events = [];

  this.meetingData.forEach((data) => {
    events.push({
      title: data.val().calTitle,
      notes: data.val().calNotes,
      room: data.val().calPlace,
      startTime: new Date(data.val().calStartTime),
      endTime: new Date(data.val().calEndTime),
      allDay: data.val().callsAllDay
    });
  });

this.eventSource = events;
```
If the events don't appear in the calendar, could you check if you are actually getting the current month's events?

**Comment by harpreet2602** [comment]
@twinssbc , I indeed did the code change as you suggested but the calendar does not load the data. In logs I can see that I actually get the month data.
But after adding "this.myCalendar.loadEvents();" it loads the event... 

Attaching screen-shot, the data is loaded but not reflecting on the calendar. Either adding loadEvents in the code.
![image](https://user-images.githubusercontent.com/7014110/58195288-3cbec100-7ce5-11e9-8c72-2df1ca729f6e.png)

OR, clicking on any date in the calendar loads all the event data. for that month, below
![image](https://user-images.githubusercontent.com/7014110/58195405-80b1c600-7ce5-11e9-9401-fdb055d5a704.png)
