### ISSUE TITLE
Marking Multiple Days with event not working on IOS

### ISSUE THREAD

**Issue by StevenMitrais** [twinssbc/Ionic2-Calendar#434]
I found the solution for IOS in your last answer you make but it's not working only on IOS platform when you scatter the event on other days, only working if you just set the moment event in one day.

Here is my reference : https://github.com/twinssbc/Ionic2-Calendar/issues/77

But in android I found no issue, here's my code :

`data.data.forEach(async res=>{
				events.push(await {
					title: res.title,
					desc: res.description,
					startTime: moment(new Date(res.time).toISOString()).toDate(),
					endTime: moment(moment(new Date(res.time).toISOString()).toDate().getTime()+15*60*1000).toDate(),
					allDay: false
				})
			})`

Note : res.time format is = YYYY-MM-DD HH:mm:ss

**Comment by twinssbc** [comment]
@StevenMitrais What do you mean "not working"? Do you see any error printed in the console?

**Comment by StevenMitrais** [comment]
there is no error in the console.
Its not working when i set the events with different dates.

But if I set all event's date in the same day, suddenly it appears.

Only occur on IOS platform, perfectly fine on Android

**Comment by twinssbc** [comment]
That's a bit weird. Could you try using native JavaScript method to construct the startTime and endTime? Just try to see if it's the problem with momentjs.

**Comment by StevenMitrais** [comment]
I'll try that.

Anyway if you have the working code or data sample for this particular issue, I'm more than happy to take a look.

Multiple events w/ different dates were scattered around on the calendar in Android platform, that was really nice, I only hope this features can work on IOS.

**Comment by twinssbc** [comment]
You could check the createRandomEvents method in 
https://github.com/twinssbc/Ionic2-Calendar/blob/master/demo/pages/home.ts

**Comment by StevenMitrais** [comment]
Hey Thank You very Much dude.
Its Working Now
Appreciate for your help

**Comment by StevenMitrais** [comment]
Actually I Solve that by changing my original DateFormat which is

> YYYY-MM-DD HH:mm:ss

into 

> YYYY-MM-DDTHH:mm:ss

Then suddenly it work because safari only accept certain date Format
Weird
