### ISSUE TITLE
Is it possible to synchronize with google calendar?

### ISSUE THREAD

**Issue by evilword666** [twinssbc/Ionic2-Calendar#436]
I would like to know if it is possible to synchronize with the Google calendar, since I would like to add my events to the events that I have in the Google calendar.
How could I do it?

**Comment by twinssbc** [comment]
@evilword666 This calendar only cares about the events in the eventSource array. It doesn't provide direct connection with other sources. You need to write your own code to fetch the events from Google calendar, convert them and fill into the eventSource array.
