### ISSUE TITLE
Event allDay showing on wrong date and event not showing with specific endTime

### ISSUE THREAD

**Issue by MatthiasVanMeerbeek-r0670805** [twinssbc/Ionic2-Calendar#437]
**Version info**
- _"@ionic/angular": "^4.1.0"_
- _"ionic2-calendar": "^0.5.2"_

**Issue [PART 1]**
_First part is the same as #417_
 
Hello,
I have a problem when I'm using the `allDay` of an event. The event is shown on the day before. So it is an event for the 27th, but it is shown on the 26th.

![image](https://user-images.githubusercontent.com/28530170/58258819-b69d8b80-7d73-11e9-9f70-3c6bc8d792bc.png)

My event object looks like this:
```
{
  "id": "4f55f724-5747-414b-baca-07846ee05a68",
  "title": "Title",
  "creatorId": "72a7df00-b144-4019-872a-b243d3739bdc",
  "startTime": "Mon May 27 2019 00:00:00 GMT+0200 (Central European Summer Time)",
  "endTime": "Mon May 27 2019 00:00:00 GMT+0200 (Central European Summer Time)",
  "allDay": true
}
```
_`startTime` and `endTime` are Date objects._

When I try to convert this date to UTC I get returned the 26th... 

**Issue [PART 2]**
When I set `allDay` to `false` the event isn't visible on neither of both dates (so not on the 26th and not on the 27th or any other day).
When I update `endTime` by increasing the seconds to `30` so that `endTime` is `"Mon May 27 2019 00:00:30 GMT+0200 (Central European Summer Time)"` it is still not visible. When I keep increasing the seconds, the event suddenly is visible (on the correct date, the 27th) when the seconds are equal to `52` like so: `"Mon May 27 2019 00:00:52 GMT+0200 (Central European Summer Time)"`.

What is causing this problem or am I just doing something wrong?
Thank you in advance!

**Comment by twinssbc** [comment]
@MatthiasVanMeerbeek-r0670805 
For issue 1, it seems the startTime and endTime are the same? The endTime should be at least one day after startTime. And you need to construct it to UTC date.

For issue 2, yes, if the startTime and endTime are just within one minute, it won't be displayed. That small interval is used to handle the rounding issue during the float number calculation. And I'm afraid there's also no reasonable use case that you will have an event just last for less than one minute.

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
No offense, but it makes no sense that you need to set the next day as `endTime`. What is `allDay` for then? `allDay` should handle it. You should even be able to set no time at all (not possible because of the Date object, but just in case) and just set `allDay` to true to say that the event is a full day long. And why UTC? I have seen the documentation, but I just don't get it why it has to be UTC...

**Comment by twinssbc** [comment]
@MatthiasVanMeerbeek-r0670805 Because allDay event could also last couple days, not just one day.
For the UTC question, I have explained in https://github.com/twinssbc/Ionic2-Calendar/issues/417#issuecomment-495271779
It is to make sure the event falls in the current day no matter in what timezone.

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
@twinssbc
Alright I managed to get it to work, but I have 2 more questions:

Does it really need to be a full day, so `startTime` is f.e. _26th 00:00:00_ and `endTime` _27th 00:00:00_ to be able to work or be correct for an `allDay`? Because if so, it is kind of weird to have this (it is in dutch, but you should be able to understand what I mean):
![IonicCalendar_Overview](https://user-images.githubusercontent.com/28530170/58314835-9d96e800-7e10-11e9-9554-1db9870f024d.png)
This would give me this in my event-detail page:
![IonicCalendar_MultipleDays](https://user-images.githubusercontent.com/28530170/58314901-c0c19780-7e10-11e9-820e-6f2fe064b901.png)
The event is from _the 28th_ till _the 31st (31 included)_, but I need(?) to set the `endTime` to _the 1st of June 00:00:00_ to get it to work(?).

Would it be possible to set `endTime` to the _"correct date"_, but with a time set to _23:59:59_ like so (?):
![IonicCalendar_OneDay](https://user-images.githubusercontent.com/28530170/58315012-f797ad80-7e10-11e9-866d-b1e797f176ff.png)
As far as I can tell, it works as you can see in the first image. Or will this give me problems/errors in the future?

**Comment by twinssbc** [comment]
@MatthiasVanMeerbeek-r0670805 Do you mean you don't use an allDay event, just a normal event with startTime set to 00:00:00 and endTime set to 23:59:59. It will work in your timezone. But when some other people see that event, it will likely span two days.

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
Thank you for your answer and sorry for all my questions.

No both events shown above are with `allDay` to true.

**Comment by twinssbc** [comment]
@MatthiasVanMeerbeek-r0670805 So I fetch the year, month, and day part of startTime and endTime to check the event falls on which day. Because it's an all day event, it doesn't care about the hour/minute/second part. As long as you can make the startTime and endTime fall in the correct time range, it should be fine.
But I still suggest use Date.UTC to construct the time. And when you store the all day event, you should also store it into UTC time. The ideal effect if an event last all day in your current time zone, the user in other time zone also should see that event last all day on the same day, and the day light saving adjustment should also not impact it.
