### ISSUE TITLE
Couldn't override css style.

### ISSUE THREAD

**Issue by ediasep** [twinssbc/Ionic2-Calendar#438]
I am trying to override CSS just like in the documentation.

```
.monthview-current {
	background: #000 !important;
}
```

The same thing happen for `monthview-primary-with-event`. I'm sure that the css file is correctly loaded as css for custom template are working correctly. Any ideas?

**Comment by StevenMitrais** [comment]
@twinssbc yeah, i also need to solve this issue

This below for CSS reference
https://github.com/twinssbc/Ionic2-Calendar#view-customization-option

**Comment by twinssbc** [comment]
Could you try to put your css in global.scss instead of the component scss file?

**Comment by StevenMitrais** [comment]
That work pretty well
Thank You

Btw @twinssbc  could you give advice on how to fully customize the weekView and dayView ?
I have my own design & want to implement only in dayView and weekView

**Comment by twinssbc** [comment]
@StevenMitrais You could take a look at the **Template Customization**. Basically just need to put your own design into the custom templates.

**Comment by StevenMitrais** [comment]
@twinssbc I already did.
I manage to remove all the lines and headers on weekView and dayView, but haven't found any way

Could you give an example how to **fully customized** that View ?

Thanks a lot

**Comment by StevenMitrais** [comment]
> @StevenMitrais You could take a look at the **Template Customization**. Basically just need to put your own design into the custom templates.

Hai @twinssbc 
Do you have any idea to completely change weekView or dayView template?
Let say dayView and weekView's template would be ion-list or my own customized template.

I already do my own design, but It merge w/ the default ionic2-calender design and functionality

Thank You

**Comment by rafaxplayer** [comment]
yo tengo el problema anterior , no se sobreescriben las clases css , he usado global.scss y tampoco funciona.
mi global.scsss:

```
/*
 * App Global CSS
 * ----------------------------------------------------------------------------
 * Put style rules here that you want to apply globally. These styles are for
 * the entire app and not just one component. Additionally, this file can be
 * used as an entry point to import other CSS/Sass files to be included in the
 * output CSS.
 * For more information on global stylesheets, visit the documentation:
 * https://ionicframework.com/docs/layout/global-stylesheets
 */


/* Core CSS required for Ionic components to work properly */

@import "~@ionic/angular/css/core.css";

/* Basic CSS for apps built with Ionic */

@import "~@ionic/angular/css/normalize.css";
@import "~@ionic/angular/css/structure.css";
@import "~@ionic/angular/css/typography.css";
@import '~@ionic/angular/css/display.css';

/* Optional CSS utils that can be commented out */

@import "~@ionic/angular/css/padding.css";
@import "~@ionic/angular/css/float-elements.css";
@import "~@ionic/angular/css/text-alignment.css";
@import "~@ionic/angular/css/text-transformation.css";
@import "~@ionic/angular/css/flex-utils.css";
@import "~@angular/material/prebuilt-themes/pink-bluegrey.css";
.monthview-selected {
    background-color: red;
}

.monthview-current {
    background-color: rebeccapurple;
}
```
Another question I have is that I would also like to know how I can make the list of events disappear completely, I do not need it, and if I use it I will use it in a different view, thanks

**Comment by twinssbc** [comment]
@rafaxplayer there's a **showEventDetail** option, just set it to false.

**Comment by rafaxplayer** [comment]
Thanks, that part worked perfectly,
but I still can't overshadow css classes.
My css in the previous post.

**Comment by twinssbc** [comment]
@rafaxplayer You need to add !important

```
.monthview-selected {
    background-color: red !important;
}

```

**Comment by rafaxplayer** [comment]
Thanks this worked fine for me but there are other types of changes that I cannot make because the css rules are not overwritten.
For example, a larger line height in the cells, this way I did it in global.scss

```
.table [_ngcontent-qpy-c3]> thead [_ngcontent-qpy-c3]> tr [_ngcontent-qpy-c3]> th [_ngcontent-qpy-c3],
.table [_ngcontent-qpy-c3]> tbody [_ngcontent-qpy-c3]> tr [_ngcontent-qpy-c3]> th [_ngcontent-qpy-c3],
.table [_ngcontent-qpy-c3]> tfoot [_ngcontent-qpy-c3]> tr [_ngcontent-qpy-c3]> th [_ngcontent-qpy-c3],
.table [_ngcontent-qpy-c3]> thead [_ngcontent-qpy-c3]> tr [_ngcontent-qpy-c3]> td [_ngcontent-qpy-c3],
.table [_ngcontent-qpy-c3]> tbody [_ngcontent-qpy-c3]> tr [_ngcontent-qpy-c3]> td [_ngcontent-qpy-c3],
.table [_ngcontent-qpy-c3]> tfoot [_ngcontent-qpy-c3]> tr [_ngcontent-qpy-c3]> td [_ngcontent-qpy-c3] {
     line-height: 30px! important;
}
```
Greetings

**Comment by twinssbc** [comment]
@rafaxplayer 
This syntax [_ngcontent-qpy-c3] is called view encapsulation.
https://coryrylan.com/blog/css-encapsulation-with-angular-components

It encapsulates the css style to the specific view.
When you override it globally, you need to remove that syntax, for example:

```
.table > tbody > tr > td {
  line-height: 30px! important;
}
```

**Comment by rafaxplayer** [comment]
Thanks i`m solved

**Comment by sivasakthithngapandian** [comment]
how to customize calender title ,the below code was i uesd but cannot get a result

[_nghost-nmm-c217] .title[_ngcontent-nmm-c217] .switch-btn[_ngcontent-nmm-c217] {
    --margin-top: 0;
    --margin-bottom: 0;
    --margin-start: auto;
    --margin-end: auto;
    width: 100%;
    font-size: 20px;
    font-family: 'Roboto';
    font-weight: bold;
    line-height: 32px;
    color: #19214a;
    background-color: aliceblue;
}

**Comment by sivasakthithngapandian** [comment]
[_nghost-nmm-c217] .title[_ngcontent-nmm-c217] .switch-btn[_ngcontent-nmm-c217] {
    --margin-top: 0;
    --margin-bottom: 0;
    --margin-start: auto;
    --margin-end: auto;
    width: 100%;
    font-size: 20px;
    font-family: 'Roboto';
    font-weight: bold;
    line-height: 32px;
    color: #19214a;
    background-color: aliceblue;
}

how to customize calendar title color and bakground color font ???

**Comment by twinssbc** [comment]
@sivasakthithngapandian you could put your styles in global.scss, and remove the view encapsulation tag.

**Comment by sivasakthithngapandian** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)

how to solve this error ?
arrow-forward and  arrow back , arrow dropdown was unvisible.

**Comment by sivasakthithngapandian** [comment]
zone-evergreen.js:1068 GET http://localhost:8100/svg/md-arrow-dropdown.svg 404 (Not Found)
zone-evergreen.js:1068 GET http://localhost:8100/svg/ios-arrow-back.svg 404 (Not Found)
zone-evergreen.js:1068 GET http://localhost:8100/svg/ios-arrow-forward.svg 404 (Not Found)

how to solve this error ? icons were invisibled

**Comment by twinssbc** [comment]
@sivasakthithngapandian this seems not related to the calendar. Looks like you are trying to use some icon, but failed to include the icon assets in your project?
