### ISSUE TITLE
Events for a short moment visible on another month

### ISSUE THREAD

**Issue by MatthiasVanMeerbeek-r0670805** [twinssbc/Ionic2-Calendar#439]
The title says everything: "Events for a short moment visible on another month"
It only occurs to events that are in the month May. They reappear for a moment when sliding between months. They appear again in August (2019), November(2019), January (2020), May (2020), August (2020), ...

Any idea? Even when I clear the `eventSource` list after sliding to a next month, they still appear...
Do I need to update the view somehow? I already use `this.myCalendar.loadEvents();`.

Problem:
![IonicCalendarGIF](https://user-images.githubusercontent.com/28530170/58321957-e4d8a500-7e1f-11e9-824d-fbdaa312927d.gif)
(All events are loaded beforehand, nothing is changed when switching months.)

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
Now I see that there already was an issue related to this problem. It seems like an Ionic Slide problem?
#5

**Comment by MatthiasVanMeerbeek-r0670805** [comment]
Maybe a solution can be found on this thread:
https://github.com/ionic-team/ionic-v3/issues/89

**Comment by twinssbc** [comment]
@MatthiasVanMeerbeek-r0670805 This is known issue that when using the looped slides, the first and last slide will be cached. I haven't found a solution so far.
