### ISSUE TITLE
template customization not working on ios simulator but working on browser

### ISSUE THREAD

**Issue by prasadmarathe** [twinssbc/Ionic2-Calendar#44]
I am not able to see the changes on simulator while applying css changes in calendar.js template.
 my code is -
"<div class="calendar-event-inner" [style.backgroundColor]=displayEvent.event.color>{{displayEvent.event.title}}</div>"
where  style.backgroundColor is converted to inline css e.g.( background-color: blue)  on browser. But not applied for ios simulator.

Please help.

**Comment by twinssbc** [comment]
@prasadmarathe You can still use the browser developer tool to remote debug the simulator or the device. Could you check if any error is printed out in the console?
Also did you add below lines to the **main.prod.ts**

```
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';
```

**Comment by prasadmarathe** [comment]
I have added mentioned code in main.prod.ts.
There is no error on console. Only inline css is not getting applied on simulator and applied while testing on browser. Did you find any syntax error in my mentioned code?

What could be the reason?

**Comment by twinssbc** [comment]
@prasadmarathe I tried in browser, IOS simulator and Android device, all working fine.
Below is my code snippet, could you check if there's any difference?

```
  <template #template let-displayEvent="displayEvent">
    <div class="calendar-event-inner" [style.backgroundColor]=displayEvent.event.color>{{displayEvent.event.title}}</div>
  </template>

  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            [weekviewNormalEventTemplate]="template"
            step="30">
  </calendar>
```
