### ISSUE TITLE
How can i override templates for weakview and dayview?

### ISSUE THREAD

**Issue by maik102** [twinssbc/Ionic2-Calendar#441]
I'm trying to change de labels for 'all day' and the hours from 'a.m' to 'A.M'. In addition i'm trying to make de hours cells with more width bc the default one is too small and the hours are over of the side cell. 
![calendarionic](https://user-images.githubusercontent.com/32304438/58873824-728d7d80-86c7-11e9-9ad3-d7d40e0ea0cd.png)

**Comment by twinssbc** [comment]
@maik102 The hour column could be formatted using **formatHourColumn** option. Actually the hour column is already displayed as "5AM" (upper case). Do you want to add "." in the label? In this case, I'm afraid **formatHourColumn** could also not help. Instead you could use **dateFormatter**. You could override the **formatWeekViewHourColumn** and **formatDayViewHourColumn** methods to return any text you want.

Regarding the width of the column, you could add below css styles in global.scss.

```
.calendar-hour-column, .weekview-allday-label, .dayview-allday-label {
  width: 70px !important;
}
```

**Comment by maik102** [comment]
thanks, another question. Can i display de weekview and dayview without the allday row? I don't see how to do it in README file.

**Comment by twinssbc** [comment]
@maik102 You could use below styles to hide allday row

```
.weekview-allday-table, .dayview-allday-table {
  display: none;
}

.weekview-normal-event-container {
  margin-top: 37px !important;
}

.dayview-normal-event-container {
  margin-top: 0 !important;
}
```
