### ISSUE TITLE
Display hours number instead of AM or PM.

### ISSUE THREAD

**Issue by Nitinchavda** [twinssbc/Ionic2-Calendar#442]
Hello There,

I'm using Ionic2-Calendar 0.4.5 version for Ionic app, is there any way to display hours number instead of 2PM to 14:00 ?.

Many Thanks,
Nitin

**Comment by twinssbc** [comment]
@Nitinchavda You could add formatHourColumn="hh:mm" when declaring calendar in the HTML.
