### ISSUE TITLE
İonic  3 calendar

### ISSUE THREAD

**Issue by tu81t** [twinssbc/Ionic2-Calendar#443]
How can ı display json api into calendar. I need realy help

**Comment by twinssbc** [comment]
You could refer to the demo code. The calendar doesnt care about how and where do you get your data, and in what format. You just need to fill the eventSource array with the correct format.

**Comment by tu81t** [comment]
my json api like this

{"data":[
{
    title:math
    starttime:10/07/2019
},
{
  title:art
startime:12/07/2019
}

}


end  my ts file

import { Component,ViewChild } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { NgCalendarModule } from 'ionic2-calendar';
import { CalendarComponent } from "ionic2-calendar/calendar";
import {CalenProvider} from '../../providers/calen/calen';

import 'rxjs/add/operator/map';

/**
 * Generated class for the ScheduleventPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-schedulevent',
  templateUrl: 'schedulevent.html',
})
export class ScheduleventPage {

  @ViewChild(CalendarComponent) myCalendar:CalendarComponent;
  eventSource;
  viewTitle;
  startTime;
 
  isToday: boolean;
  calendar = {
  mode: 'month',
  currentDate: new Date()
  };
  callist:any=[];
  
  constructor(public navCtrl: NavController,private calenprovider: CalenProvider) {
  
  this.getCalData();
  }
  
  getCalData(){
  
  this.calenprovider.getCalData().subscribe(data =>this.callist=data);
    }
  
    loadEvents: function(): {
        eventSource=this.callist
      this.eventSource.push({
          title: 'test',
          startTime: this.startTime,
         
          allDay: false
      });
      this.myCalendar.loadEvents();
  }
  onViewTitleChanged(title) {
  this.viewTitle = title;
  }
  onEventSelected(event) {
  console.log('Event selected:' + event.startTime + '-' + event.endTime + ',' + event.title);
  }
  changeMode(mode) {
  this.calendar.mode = mode;
  }
  today() {
  this.calendar.currentDate = new Date();
  }
  onTimeSelected(ev) {
  console.log('Selected time: ' + ev.selectedTime + ', hasEvents: ' +
  (ev.events !== undefined && ev.events.length !== 0) + ', disabled: ' + ev.disabled);
  }
  onCurrentDateChanged(event:Date) {
  var today = new Date();
  today.setHours(0, 0, 0, 0);
  event.setHours(0, 0, 0, 0);
  this.isToday = today.getTime() === event.getTime();
  }
  
  onRangeChanged(ev) {
  console.log('range changed: startTime: ' + ev.startTime + ', endTime: ' + ev.endTime);
  }
  markDisabled = (date:Date) => {
  var current = new Date();
  current.setHours(0, 0, 0);
  return date < current;
  };
  
  }

but ı am getting error in ts file.

html file
{{viewTitle}}

<button ion-button color= "black" [disabled]="isToday" (click)="today()">Today
<button ion-button color="black" (click)="changeMode('month')">Month
<button ion-button color="black"(click)="changeMode('week')">Week
<button ion-button color="black" (click)="changeMode('day')">Day
<button ion-button color="black"(click)="loadEvents()">Load Events



provider

import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import {Http, RequestOptions, Response, HttpModule} from '@angular/http';
import { HttpClientModule } from '@angular/common/http';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/do';

/*
  Generated class for the CalenProvider provider.

  See https://angular.io/guide/dependency-injection for more info on providers
  and Angular DI.
*/
@Injectable()
export class CalenProvider {
  private url: string = "http://127.0.0.1:8000/api/classes";

  constructor(public http: Http) {
    console.log('Hello CalenProvider Provider');
  }
  getCalData(){
    return this.http.get(this.url)
    .do(this.logResponse)
    .map(this.extractData)
    .catch(this.catchError)
    }

    private catchError(error: Response |any){
      console.log(error);
      return Observable.throw(error.json().error || "server Error.");
      
      }
      
      private logResponse(res : Response){
      console.log(res);
      
      }
      
      private extractData(res : Response){
      return res.json();
      }
      
      }
      
 ı am realy need help you

**Comment by tu81t** [comment]
can you respond me ı am so confused

**Comment by twinssbc** [comment]
@tu81t 
There are several places you need to modify.

1. Take a look at the **EventSource** in README. You need to at least pass 4 fields, title, startTime, endTime, allDay.
2. In your restful API callback, you seems assign data to callist. So in your HTML, you need to bind to callist to eventSource property.
3. If you get any error, please provide the error message, otherwise I don't have enough information to help you.
