### ISSUE TITLE
Dot Marking Based on Number of Event List in MonthView

### ISSUE THREAD

**Issue by StevenMitrais** [twinssbc/Ionic2-Calendar#444]
![Capture](https://user-images.githubusercontent.com/44386841/59411627-44f2b380-8dee-11e9-8e68-394cea4ae8b0.JPG)

Hai @twinssbc ,as you can see the images above I need to make dot indicator based on the events.

If in the current date's only have 1 event, It'll only show 1 dot, if more then show 2 dots.
Do you have any suggestion how to achieve that ?

`<ng-template #templatemonthviewDisplayEvent let-view="view" let-row="row" let-col="col">
        <div class="round-event">{{view.dates[row*7+col].label}}</div>
        <span class="dot dot-silver"></span>
        <span class="dot dot-gold"></span>
    </ng-template> `

That's how i customized it, but it always show 2 dots .

**Comment by twinssbc** [comment]
@StevenMitrais You could add ngIf condition based on the view.dates[row*7+col].events.length. Show dot-sliver span when the length > 0; show the dot-gold span when the length > 1.

**Comment by StevenMitrais** [comment]
> @StevenMitrais You could add ngIf condition based on the view.dates[row*7+col].events.length. Show dot-sliver span when the length > 0; show the dot-gold span when the length > 1.

Wow Thanks! That's working perfectly !
I think this is one of the most complete calendar library for javascript framework on the internet 💯 

@twinssbc  In addition, I have another question, you see the the dot's color it define by the confirm status property below code.

`{
						title: res.title,
						desc: res.description,
						startTime: startTime,
						endTime: endTime,
						allDay: false,
						**confirm_status:(can be 0 or 1, and it's define the color)**
					}`
And I need to define the dots based upon the **confirm_status**, how can I do that ?

I just realize there is another property in this particular code `view.dates[row*7+col].` besides label, how do I check that in HTML ? , I think you should put it on the README.MD.

Thank you for the answer anyway

**Comment by twinssbc** [comment]
@StevenMitrais The type of view is IMonthViewDisplayEventTemplateContext.
You could check the definition from below file.
https://github.com/twinssbc/Ionic2-Calendar/blob/master/src/calendar.ts
Since the type is nested at many levels, so I don't want to put too many details in README.

For your requirement, you could easily use ngClass, and bind to view.dates[row*7+col].events[0].confirm_status with some custom css class.

**Comment by StevenMitrais** [comment]
> @StevenMitrais The type of view is IMonthViewDisplayEventTemplateContext.
> You could check the definition from below file.
> https://github.com/twinssbc/Ionic2-Calendar/blob/master/src/calendar.ts
> Since the type is nested at many levels, so I don't want to put too many details in README.
> 
> For your requirement, you could easily use ngClass, and bind to view.dates[row*7+col].events[0].confirm_status with some custom css class.

Thanks!, You completely solve my problem

here is my code

`				<span *ngIf="view.dates[row*7+col].events.length && calendar.currentDate < view.dates[row*7+col].events[0].startTime && view.dates[row*7+col].events[0].confirm_status === 0" class="dot dot-silver"></span>
				<span *ngIf="view.dates[row*7+col].events.length && calendar.currentDate < view.dates[row*7+col].events[1]?.startTime && view.dates[row*7+col].events[1]?.confirm_status === 0" class="dot dot-silver"></span>
				
				<span *ngIf="view.dates[row*7+col].events.length && calendar.currentDate < view.dates[row*7+col].events[0].startTime && view.dates[row*7+col].events[0].confirm_status === '1'" class="dot dot-gold"></span>
				<span *ngIf="view.dates[row*7+col].events.length && calendar.currentDate < view.dates[row*7+col].events[1]?.startTime && view.dates[row*7+col].events[1]?.confirm_status === '1'" class="dot dot-gold"></span>

				<span *ngIf="view.dates[row*7+col].events.length && calendar.currentDate > view.dates[row*7+col].events[0].startTime" class="dot dot-grey"></span>
				<span *ngIf="view.dates[row*7+col].events.length > 1 && calendar.currentDate > view.dates[row*7+col].events[0].startTime" class="dot dot-grey"></span>`
