### ISSUE TITLE
how to set width and weight to same value?

### ISSUE THREAD

**Issue by en-sevilla** [twinssbc/Ionic2-Calendar#445]
Hi,

we are trying to stylize the month view in Ionic 4.

Now, we have the following size:

![image](https://user-images.githubusercontent.com/8984122/59849197-416ba900-9367-11e9-927d-a64dc6403632.png)

Width = 36 px is set dynamically depending on display width.
Height = 20px is set on "line-height: 20px;" rule (monthview.js line 510).

In order to have a circular shape, we need to set the width and weight of the table cell to the same value.

![image](https://user-images.githubusercontent.com/8984122/59849434-e38b9100-9367-11e9-8216-d397b5428ebc.png)

**How can we have a square size here?  in our example: 36x36 px., but it should change dynamically to adapt to different display width**

Thanks a lot for your amazing plugin.
Regards

**Comment by twinssbc** [comment]
@en-sevilla This actually is not related to the calendar plugin. It's a tricky CSS problem.
I didn't give a try, but below two solutions look quite promising.
http://www.mademyday.de/css-height-equals-width-with-pure-css.html
https://stackoverflow.com/questions/5445491/height-equal-to-dynamic-width-css-fluid-layout

**Comment by en-sevilla** [comment]
thank you @twinssbc , I tried the first link (http://www.mademyday.de/css-height-equals-width-with-pure-css.html), and It is near to work, it produces a 45x45px cell, but with other undesired effects:

FIRST STEP:
![image](https://user-images.githubusercontent.com/8984122/59878081-ae069800-93a7-11e9-8e0d-651dd8786b3b.png)

SECOND STEP:
![image](https://user-images.githubusercontent.com/8984122/59878092-b6f76980-93a7-11e9-91b6-3a943ab5c939.png)

My css skills are really bad! :(

**Comment by en-sevilla** [comment]
I also tried with the following solution, but no chance...
https://jsfiddle.net/ocp36uLb/32/
any idea to explore? 
thanks!

**Comment by twinssbc** [comment]
@en-sevilla Below is how I solve it. The idea is you can't directly set the width on td, otherwise the whole table width will not occupy the whole page. Instead, you need to create extra element inside the td and apply the css accordingly.

HTML
```
<ng-template #template let-view="view" let-row="row" let-col="col">
  <div class="box"><div class="content">{{view.dates[row*7+col].label}}</div></div>
</ng-template>

  <calendar [eventSource]="eventSource"
...
            [monthviewDisplayEventTemplate]="template"
            [monthviewInactiveDisplayEventTemplate]="template"
  ></calendar>
```

CSS (add to global.scss)
```
.monthview-datetable td {
  padding: 0 !important;
}

.box {
  position: relative;
}

.box:before {
  content:"";
  padding-top: 100%;
  display: block;
}

.content {
  position: absolute;
  top:0;
  bottom:0;
  left:0;
  right:0;
}
```

**Comment by en-sevilla** [comment]
@twinssbc great! now it works!! fantastic, thanks a lot!
