### ISSUE TITLE
Set event in a specific day after GET call

### ISSUE THREAD

**Issue by AugustoCorti** [twinssbc/Ionic2-Calendar#446]
Hi, 
I receive a list of events from my web service.
If i push these events in the eventSource array, all the events are placed on the current day.
Which parameter i have to set for put the events in their correct day? (The events that i get from my web service have a Date field with the day of the event but i don't know how to use it, where I have to put this value for set the correct day of the event).

Any help is appreciated, as I am new to Ionic and Angular
Thanks in advance.

**Comment by twinssbc** [comment]
@AugustoCorti You need to set the startTime and endTime field properly. Take a look at the **EventSource** section in README.
