### ISSUE TITLE
calendar.currentDate not updated in swipe of week view

### ISSUE THREAD

**Issue by severus1990** [twinssbc/Ionic2-Calendar#45]
I have added next and prev buttons the calendar week view. 

On click of them I am calling the below functions:

nextWeek() {
       this.calendar.currentDate = new Date(this.calendar.currentDate.setDate(this.calendar.currentDate.getDate() + 7));
     }

prevWeek(){
        this.calendar.currentDate = new Date(this.calendar.currentDate.setDate(this.calendar.currentDate.getDate() - 7));
     }

This is working fine. But when I swipe right or left, I am getting the next/previous weeks but the calendar.currentDate is not getting updated. i.e., if i click next button after a right swipe, Instead of getting the next week, the current week will load again.

Is there a way where the currentDate will get updated in swipe also?

**Comment by twinssbc** [comment]
@severus1990 
If your syntax is like below, it is one way binding, the calendar.currentDate won't be updated when the internal currentDate is updated by swiping.

```
[currentDate]="calendar.currentDate"
```

I exposed **onCurrentDateChanged** event, you can listen to this event and store the latest current date somewhere.

**Comment by severus1990** [comment]
thanks @twinssbc. I will try this. Is there a way to improve the performance of the calendar? In my case even after a prod build in ionic, the calendar is less responsive to clicks and swipes. The initial loading of calendar also takes some time. Please suggest a way to improve the performance.

**Comment by twinssbc** [comment]
@severus1990 I just tried the latest Ionic 2.0.0 final version. It seems the performance is improved a lot. Also are you testing in Android? It's a known issue that the JavaScript performance is worse in Android devices comparing to IOS. You may want to try Crosswalk plugin to further improve the performance, although it will increase the package size a lot.

**Comment by pinpointpanda** [comment]
I'm having the same issue - can't quite get to the bottom of it.

Was making the same mistake with my 'prev' and 'next' buttons, just updating this.calendar.currentDate, which won't work as explained above.

But my onDateChanged function is not firing.

Any ideas @twinssbc ?

**Comment by pinpointpanda** [comment]
Ohh. I wasn't paying close enough attention! 😄 
The function name was spelled wrong 😝 

@twinssbc I copied the code straight from the **Usage** section:
```
      <calendar [eventSource]="eventSource"
        [calendarMode]="calendar.mode"
        [currentDate]="calendar.currentDate"
        (onCurrectDateChanged)="onCurrentDateChanged($event)"
        (onRangeChanged)="reloadSource(startTime, endTime)"
        (onEventSelected)="onEventSelected($event)"
        (onTitleChanged)="onViewTitleChanged($event)"
        (onTimeSelected)="onTimeSelected($event)"
        step="30">
      </calendar>
```

There's a typo in there - it says on**Currect**DateChanged. Might want to update that at some point just to stop silly people like me who don't pay close attention.

Really great work on the calendar by the way, it's just what I was looking for 👍

**Comment by twinssbc** [comment]
My bad, I have fixed the README.

**Comment by nitinswamy** [comment]
Hi, @twinssbc 

I am using two arrows to navigate to nextMonth() and prevMonth() using these
 previousMonthButton() {
    this.calendar.currentDate = new Date(this.calendar.currentDate.setMonth(this.calendar.currentDate.getMonth() - 1));
  }  

  NextMonthButton() {
    this.calendar.currentDate = new Date(this.calendar.currentDate.setMonth(this.calendar.currentDate.getMonth() + 1));
  } 
 



but how do I set the default selector date to 1st of every month as opposed to the current date? 
Thanks in advance

**Comment by twinssbc** [comment]
@nitinswamy The selected date is the same as the current date. If you set the current date, that date will also be selected.
