### ISSUE TITLE
[help] Week view templates

### ISSUE THREAD

**Issue by prashantJadhav** [twinssbc/Ionic2-Calendar#450]
I want to change calendar week view to something like shown in below image 
can i use templates customization to achieve what is shown in the image for week header as well as event listing . 

![test](https://user-images.githubusercontent.com/1639873/60662846-157a1880-9e7b-11e9-947c-a7251178708d.jpg)

**Comment by twinssbc** [comment]
@prashantJadhav Sorry, the custom template is not flexible enough to suppose such layout.
