### ISSUE TITLE
startHour / startMinute

### ISSUE THREAD

**Issue by daviddea85** [twinssbc/Ionic2-Calendar#451]
HI there,

Firstly thanks for your calendar, is really cool. I would like to know if it's possible to modify the startHour to be 8:15 - 8:30 - 8:45 ... instead of only 8 (day and week view)

Thanks

**Comment by twinssbc** [comment]
@daviddea85 Yes, it's possible. Just add below options in your HTML code.
```
            timeInterval="15"
            formatHourColumn="HH:mm"
```

**Comment by daviddea85** [comment]
Hi @twinssbc I think I did not explain myself properly or I don't really understand your answer, actually startHour only accepts values from 0 to 23. I have the calendar configured as you said and startHour as 8, what I basically need is startHour at 8:30 for example. Thanks for your response.

**Comment by twinssbc** [comment]
@daviddea85 Ah, I thought you want to display the hour column in every half hour or 15 mins. Unfortunately it's not possible to set the startHour to 8:30, only integer value works.

**Comment by daviddea85** [comment]
Thanks for your response again, I will close the issue.
