### ISSUE TITLE
Repurpose Calendar as Gantt Chart?

### ISSUE THREAD

**Issue by nikilkumar9** [twinssbc/Ionic2-Calendar#453]
Hey guys, my schedule consists of events that usually go on for days at a time. 

Hence, I was wondering whether there was any way to take the left-hand column that shows the time, eliminate it and add it to date row? and then have events added on top of each other, if their times overlap. 

It is almost re-purposing the calendar app to be a **Gantt Chart**, which is exactly what I want. 

If no, anyone has any free alternatives for Gantt Charts for an Ionic 4 app?

**Comment by twinssbc** [comment]
@nikilkumar9 Sorry, it's not possible to achieve Gantt Chart style in this calendar control.
