### ISSUE TITLE
Ionic 4 Custom css

### ISSUE THREAD

**Issue by maciejunio** [twinssbc/Ionic2-Calendar#454]
Hello.
I used your plugin in Ionic 4. Everything works great, well done, but I would like to change css styles. I set it up in calendar.page.scss
`.monthview-selected {
     background-color: red;
}`
but it doesn't work. I think it could be because Angular is adding classes and overwrites my, like this 
`monthview-selected[_ngcontent-olq-c5]`

Can you help me ?

**Comment by rafaelbaiolim** [comment]
Try put the selector inside `global.scss` with `!important`: 

`.monthview-selected { background-color: #FF790A !important; } `

**Comment by maciejunio** [comment]
I tried

**Comment by rafaelbaiolim** [comment]
![app](https://user-images.githubusercontent.com/8842898/62796930-cf832680-bab0-11e9-85b9-3e383f25208b.jpg)
![globals](https://user-images.githubusercontent.com/8842898/62796931-d01bbd00-bab0-11e9-973d-8f344dda9084.jpg)

In my application is working fine :\

**Comment by maciejunio** [comment]
@rafaelbaiolim  Thank you, it works
