### ISSUE TITLE
How to remove an Event?

### ISSUE THREAD

**Issue by wapewape** [twinssbc/Ionic2-Calendar#455]
Hi.
I need to use this calendar in the weekly view and allow only one event per day.
If there is an event by clicking then delete it, if it does not exist add it
I just need to save the time

Thx

**Comment by twinssbc** [comment]
@wapewape You could implement onTimeSelected method. It has a events parameter which indicates the events happen on that day. You could add some logic to decide if you need to add or delete the event.

**Comment by wapewape** [comment]
Thx 

To contribute
// Time slot was clicked
  async onTimeSelected(ev) {
  const comprobate = (ev.events !== undefined && ev.events.length !== 0);
  if (comprobate) {
    const array = this.eventSource;
    const index = arreglo.indexOf(ev.events[0]); 
    arreglo.splice(index, 1); // 
    this.myCal.loadEvents();
  } else {
    console.log('Normal flow');
}

**Comment by dmmd10** [comment]
@wapewape 
can you show the complete code?
