### ISSUE TITLE
Calendar Month View Can't Read Midnight Date

### ISSUE THREAD

**Issue by StevenChandra** [twinssbc/Ionic2-Calendar#456]
Hai @twinssbc 

My calendar month's View can't detect event on this date
**Wed Aug 28 2019 00:00:00 GMT+0800**

or simply, It can't detect 00 AM
How can i Solve It ?

Thanks

**Comment by twinssbc** [comment]
@StevenMitrais What do you mean can't detect? Is there any error indicating failed to parse the date?

**Comment by StevenChandra** [comment]
@twinssbc 
I mean It's not showing on **templateMonthEventDetail**

**<calendar [eventSource]="eventSource" />**
The eventSource above contains startTime like **Wed Aug 28 2019 00:00:00 GMT+0800** , I realized It was only data contains 00:00:00 not showing in the list, The other hours is showing, can you help?

Thanks

**Comment by twinssbc** [comment]
@StevenMitrais Could you provide more details? Are you using a custom template?

**Comment by StevenChandra** [comment]
@twinssbc 
Yes, Im using custom templates

![11](https://user-images.githubusercontent.com/44386841/63986839-5489ba80-cb08-11e9-92f4-79d9429f6d13.JPG)

Above image is the customized month view, it shows no event, but actually It has 2 events that contains hours like this below, observe the hours, its **00 AM** which not showing unlike the other hours

![33](https://user-images.githubusercontent.com/44386841/63986877-7daa4b00-cb08-11e9-827a-a51fab15c066.JPG)

Below is my self-made dayView event, I actually consume the json myself and it shows correctly, the events should be showing like this in the **templateMonthEventDetail**

![Capture](https://user-images.githubusercontent.com/44386841/63986941-bc400580-cb08-11e9-8c6a-8ad9cacf23bf.JPG)

**Comment by StevenChandra** [comment]
Actually found the cause
It cant show if both **startTime & endTime** is same date value while **allDay** is set to **false**

so i just modified the endDate, add 1 hours, so it's not 00 AM anymore

Anyway, Thank you for your kind response
@twinssbc
