### ISSUE TITLE
Style wrong on swipe

### ISSUE THREAD

**Issue by coleweusthem** [twinssbc/Ionic2-Calendar#457]
I've created a template for my month view:
`<ng-template #template let-view="view" let-row="row" let-col="col" class="calendar-day-wrap">
          <div class="calendar-day" (click)="openModal(view.dates[row*7+col])" tappable>
            {{view.dates[row*7+col].label}}
            <div *ngIf="view.dates[row*7+col].events.length > 0"> 
              <img src="assets/images/appoin-icon-green-30x30.png"/>
            </div>
          </div>
        </ng-template>`

then I set the `.calendar-day` to have 'height: 10vh;' which looks how I want it. But when I swipe to the previous or next month, the height is gone until the slide is in place. How can I make the previous and next slide reflect the correct height? or is this a bug?

**Comment by coleweusthem** [comment]
I've added styles for them to my global styles, but this doesn't feel like the right way to do this. is there a better way I'm missing?

**Comment by twinssbc** [comment]
@coleweusthem There's monthviewInactiveDisplayEventTemplate that can set the styles for previous and next month. Sometimes adding styles to global styles is the correct solution. Because the css encapsulation in each component make it difficult to override styles.
