### ISSUE TITLE
Compile Error ionic serve --prod

### ISSUE THREAD

**Issue by mzaidipk** [twinssbc/Ionic2-Calendar#458]
When i try to serve a prod build then i get a bunch of errors. I am using the latest ionic / angular version. it works fine in regular serve. I am thinking it is an AOT issue but i dont know how to get around this. Any help is much appreciated.

`ERROR in node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(39,78): : Property 'hourColumnLabels' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(35,83): : Property 'initScrollPosition' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(70,78): : Property 'hourColumnLabels' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(66,83): : Property 'initScrollPosition' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(117,78): : Property 'hourColumnLabels' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(113,83): : Property 'initScrollPosition' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(150,78): : Property 'hourColumnLabels' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(146,83): : Property 'initScrollPosition' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(197,78): : Property 'hourColumnLabels' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(193,83): : Property 'initScrollPosition' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(230,78): : Property 'hourColumnLabels' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/weekview.d.ts.WeekViewComponent.html(226,83): : Property 'initScrollPosition' is private and only accessible within class 'WeekViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(28,74): : Property 'hourColumnLabels' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(24,107): : Property 'initScrollPosition' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(44,74): : Property 'hourColumnLabels' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(40,107): : Property 'initScrollPosition' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(79,74): : Property 'hourColumnLabels' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(75,107): : Property 'initScrollPosition' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(95,74): : Property 'hourColumnLabels' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(91,107): : Property 'initScrollPosition' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(130,74): : Property 'hourColumnLabels' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(126,107): : Property 'initScrollPosition' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(146,74): : Property 'hourColumnLabels' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/dayview.d.ts.DayViewComponent.html(142,107): : Property 'initScrollPosition' is private and only accessible within class 'DayViewComponent'.
[ng] node_modules/ionic2-calendar/calendar.d.ts.CalendarComponent.html(94,17): : Property 'hourParts' is private and only accessible within class 'CalendarComponent'.
[ng] node_modules/ionic2-calendar/calendar.d.ts.CalendarComponent.html(96,17): : Property 'hourSegments' is private and only accessible within class 'CalendarComponent'.
[ng] node_modules/ionic2-calendar/calendar.d.ts.CalendarComponent.html(123,17): : Property 'hourParts' is private and only accessible within class 'CalendarComponent'.
[ng] node_modules/ionic2-calendar/calendar.d.ts.CalendarComponent.html(124,17): : Property 'hourSegments' is private and only accessible within class 'CalendarComponent'.`

**Comment by twinssbc** [comment]
@mzaidipk ionic serve --prod works fine at my side. Which version of the calendar component are you using?

**Comment by mzaidipk** [comment]
this is snapshot of my package.json

`"dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/cdk": "~8.1.3",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/material": "^8.1.3",
    "@angular/material-moment-adapter": "^8.1.4",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/android-permissions": "^5.12.0",
    "@ionic-native/app-update": "^5.13.0",
    "@ionic-native/calendar": "^5.12.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.8.1",
    "body-parser": "^1.19.0",
    "cordova-android": "8.0.0",
    "cordova-ios": "5.0.1",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-calendar": "^5.1.4",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "ionic2-calendar": "^0.5.2",
    "moment": "^2.24.0",
    "morgan": "^1.9.1",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.1.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },`

**Comment by mzaidipk** [comment]
is there any update on this @twinssbc 
Also i don't see a main.prod.ts "Note for Ionic Build/Run command"is this applicable for the latest ionic / angular version. i tried pasting them in the environment.ts and environment.prod.ts but didnt work.
another thing from the error i found that i couldnt find a property hourSegments in the source code. only the compiled version of calendar.d.ts which i got from npm install has it but not anywhere in the source files. changing them to public in d,ts files in the installed package fixes the issue as per some suggestion i found online

**Comment by twinssbc** [comment]
@mzaidipk I will release a new version that exposes all these properties to be public.
hourSegments is in weekview.ts, you need to check the v5 branch.

**Comment by twinssbc** [comment]
@mzaidipk I published a new version 0.5.3 which contains the fix. Feel free to give a try.
