### ISSUE TITLE
custom css not working

### ISSUE THREAD

**Issue by bhandaribhumin** [twinssbc/Ionic2-Calendar#461]
css working on browser but when i try on device css not applied, also try to add css on app.scss but still not applied 

i refer https://github.com/twinssbc/Ionic2-Calendar#css-customization

```
.monthview-primary-with-event {
  background-color: transparent !important;
  color: #000000 !important;
  border-bottom: 2px solid color($colors, insider) !important;
}

.monthview-current {
  background-color: lightgray !important;
  color: #000000 !important;
}

.monthview-selected {
  background-color: color($colors, insider) !important;
  color: #ffffff !important;
}


.table-bordered>tfoot>tr>td {
  border: 0 !important;
}

.table-bordered {
  border: 0 !important;
}
``` 

i want to achieve below style :

![Event](https://user-images.githubusercontent.com/3336047/64318012-bf3e6880-cfd6-11e9-8876-9f955fb0dd4a.jpg)

**Comment by twinssbc** [comment]
@bhandaribhumin Could you try adding these styles in global.scss?

**Comment by bhandaribhumin** [comment]
@twinssbc yes but now i fixed using getCustomClass().
Thanks so much.
