### ISSUE TITLE
Events only show in current month not in previous or next month

### ISSUE THREAD

**Issue by MurugeshwaranAegham** [twinssbc/Ionic2-Calendar#465]
The events of current month are only highlighted in month view. when I swipe to the next or previous month that didn't show the events in that month

**Comment by twinssbc** [comment]
@MurugeshwaranAegham The calendar displays events stored in the eventSource array. When changing the month, you also need to change the eventSource array element accordingly.

**Comment by MurugeshwaranAegham** [comment]
I already added in eventSource Array.

**Comment by twinssbc** [comment]
@MurugeshwaranAegham How do you add the events in the eventSource array? If you just modify the array element directly, you need to call loadEvents to force refresh. See the **EventSource** section in README.
