### ISSUE TITLE
Update to Android, or something ? is causing problems with loading events.

### ISSUE THREAD

**Issue by BrettButcher** [twinssbc/Ionic2-Calendar#467]
I had a working calendar on browser (testing using Ionic Serve) and Android (ionic cordova run android  - with and without livereload).
Last week my phone (Samsung A8) was updated with a security patch but I can't positively state that was the 'event' when all changed. However.
I now find that when loading my events iam now getting this error just as the calendar loads the events:

**vendor.js:41877 ERROR Error: Uncaught (in promise): TypeError: event_1.startTime.getTime is not a function**

This error has shown up in the past when the startTime or endTime data has been in the wrong format or something similar.

The eventSource I am using is an appointment object that comes from the server returning StartTimeServer and EndTimeServer values. These are put into the startTime and endTime fields via a helper function called when the appointments come down like this:

`  fixAppointmentTimesFromServer(appointment: Appointment) {
    appointment.startTime = new Date(appointment.StartTimeServer);
    appointment.endTime =  new Date(appointment.EndTimeServer);
  }`

This doesn't seem to work any more, whereas it did... and still works fine on a browser.

As a test, I set the eventSource to a local object in the page 'eventysource':

`  // TEST
  eventysource = [
    {
      title: 'Test of Now',
      desc: 'wibble',
      startTime: this.startTime,
      endTime: addHours(this.startTime, 1),
      allDay: false
    },
    {
      title: 'Test of Now plus a couple of hours',
      desc: 'wobble',
      startTime: addHours(this.startTime, 3),
      endTime: addHours(this.startTime, 4),
      allDay: false
    }
  ];
`
This works.! Most of the time. It works on first load. However, seems a little 'fragile' and fails if I use the --livereload option. (after the first load). on or after a second load the calendar will display, but not change mode to week, day etc... It is stuck in its initial mode, and dowsnt show events.

So something odd is going on here.  Thoughts or comments please?

**Comment by BrettButcher** [comment]
I am commenting on my own post because I couldn't find enough coverage of this issue.
Ok, I know Javascript Dates are all a bit weird, but thought that a Date would at least be a Date? Well no, it appears not.
my appointments are coming from a server in ISO string form. I read that the eventSource for the calendar should use new Date() when setting them up... all fine so far. I did that and it worked in the browser, and in the phone. Hmm, an update on the phone and it stopped working.. only a security patch though..??
It smelled of the events and startTime and endTime data. In the end I took the   createRandomEvents() code from the demo. This worked so I ended up processing my ISO Dates as follows:

`  fixAppointmentTimesFromServer(appointment: Appointment) {

    const start = new Date(appointment.StartTimeServer);
    const end = new Date(appointment.EndTimeServer);
    appointment.startTime = new Date(Date.UTC(start.getFullYear(), start.getMonth(), start.getDate(), start.getHours(), start.getMinutes()));
    appointment.endTime = new Date(Date.UTC(end.getFullYear(), end.getMonth(), end.getDate(), end.getHours(), end.getMinutes()));
  }`

It seems that you need to go through the Date.UTC code to get this to work.

It would be good if the error messages were clearer. I'll leave this open for a while for any further comments from contributors, but feel free to close.

**Comment by twinssbc** [comment]
@BrettButcher I don't think it needs Date.UTC to fix your issue. There are some similar issues get reported, but it's due to the Safari browser doesn't work on certain date format. It's the first time the error happens on Android browser. 

Date constructor in javascript accepts many different parameters, I think the safest one is this
```
new Date(milliseconds)
```
This one should also work which is basically what you do with Date.UTC.
```
new Date(year, month, date, hours, minutes, seconds, ms)
```

The one using dateString really depends on the browser support.
```
new Date(datestring)
```

So I suggest you consider not passing a Date string from the backend.

**Comment by BrettButcher** [comment]
@twinssbc, thanks for coming back on this... I don't have a lot of choice re the server end, which is why I have server and  client versions of the time. However, I just found as well, that even saving to the device store with Ionic-Storage (after conversion and all ok... ), when bringing it back from the Ionic-Storage, I have to re-parse the server date again, as the previous (miillisecond - UTC derived) dates return from storage as 'string' date objects. Not the 'pure' object that went in. So, its not totally safe even when on the device... 

I do think it could be worth a section in the ReadMe as I think this is obviously going to become a more common issue.

Love the calendar though and really appreciate all the hard work that you and others have put into it.
Rgds Brett

**Comment by twinssbc** [comment]
@BrettButcher Thanks for the suggestion. I added it in the **common questions** section.
