### ISSUE TITLE
Unable to install ionic2 calendar

### ISSUE THREAD

**Issue by shahbaz17** [twinssbc/Ionic2-Calendar#47]
When running `npm install ionic2-calendar --save`

Shows these errors

npm ERR! Linux 4.9.5-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "ionic2-calendar" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ionic2-calendar@0.2.1 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ionic2-calendar@0.2.1 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic2-calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic2-calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic2-calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/myApp/npm-debug.log

**Comment by alexandretok** [comment]
Same issue here.

**Comment by alexandretok** [comment]
I was able to install using this command:

`npm install ionic2-calendar --save --ignore-scripts`

I don't know if this causes any other issues, because I couldn't get it running anyway.

**Comment by JoeHillyard** [comment]
Install typings globally first:

`npm install typings -g`

**Comment by alexandretok** [comment]
That worked for me!
