### ISSUE TITLE
Custom template without event section

### ISSUE THREAD

**Issue by anikinitek** [twinssbc/Ionic2-Calendar#473]
@twinssbc Please help me get below screen. to get that type screen. what i need to do . i tried so many ways. i don't want event section . help me to do this
![week view with custom screen](https://user-images.githubusercontent.com/38279492/68366765-1e953200-015a-11ea-8f94-c328f7a1cfc8.PNG)

**Comment by twinssbc** [comment]
@anikinitek Sorry, this calendar doesn't support customization like that.
