### ISSUE TITLE
Calendar support for Ionic React

### ISSUE THREAD

**Issue by rodrigogsn** [twinssbc/Ionic2-Calendar#475]
Hello guys! Is there a way to use this calendar with React?https://ionicframework.com/blog/announcing-ionic-react/

The calendar works so great in Ionic/Angular, but I'm not sure if it could be installed in Ionic React, or how I could help if it's not.

Thanks!

**Comment by twinssbc** [comment]
@rodrigogsn Sorry, it is built based on Ionic/Angular, no Ionic React version. Feel free to contribute one if you have time.

**Comment by bhandaribhumin** [comment]
@rodrigogsn hey bro did you find any alternative for ionic-react?
