### ISSUE TITLE
Make it readOnly

### ISSUE THREAD

**Issue by jcmendes9898** [twinssbc/Ionic2-Calendar#476]
Is it possible to make the events on the calendar read only and disable the selection of date?  the green square.

**Comment by twinssbc** [comment]
@jcmendes9898 You can't disable selection. But you can simply set the background color of the selected date to white by overriding below css.

```
        .monthview-selected {
          background-color: white;
          color: black;
        }
```

**Comment by jcmendes9898** [comment]
OK, thanks for the answer.
