### ISSUE TITLE
Cannot read property 'getFullYear' of undefined

### ISSUE THREAD

**Issue by alexandretok** [twinssbc/Ionic2-Calendar#48]
After installing the module using the regular command:

`npm install ionic2-calendar --save`

I get this error message as soon as the app loads:

EXCEPTION: Error in ./CalendarComponent class CalendarComponent - inline template:35:16 caused by: Cannot read property 'getFullYear' of undefined

I have debugged and found that the error occurs on line 160 on the file `monthview.js`.

In the following function the `currentDate` object parameter comes in as `undefined`:
```
MonthViewComponent.prototype.getRange = function (currentDate) {
        //-- NEXT LINE THROWS AN EXCEPTION BECAUSE currentDate IS undefined
        var year = currentDate.getFullYear(), month = currentDate.getMonth(), firstDayOfMonth = new Date(year, month, 1), difference = this.startingDayMonth - firstDayOfMonth.getDay(), numDisplayedFromPreviousMonth = (difference > 0) ? 7 - difference : -difference, startDate = new Date(firstDayOfMonth.getTime());
        if (numDisplayedFromPreviousMonth > 0) {
            startDate.setDate(-numDisplayedFromPreviousMonth + 1);
        }
        var endDate = new Date(startDate.getTime());
        endDate.setDate(endDate.getDate() + 42);
        return {
            startTime: startDate,
            endTime: endDate
        };
    };
```

**Comment by alexandretok** [comment]
I got it working after declaring and setting the `this.calendar.currentDate` inside the constuctor.

**Comment by amorriscode** [comment]
@alexandretok Can you show your constructor code? I'm getting a similar error and I cannot seem to figure it out.

**Comment by alexandretok** [comment]
Actually I later changed to outside the constructor, looks like this now:
```
export class AppointmentsPage {

  calendar: any = {
    currentDate: new Date()
  };

   // rest of the code...
}
```

And on the appointments.html :
```
      <calendar
              [currentDate]="calendar.currentDate"
              [startingDayMonth]="1"
              (onTimeSelected)="onTimeSelected($event)"
              (onCurrentDateChanged)="onCurrentDateChanged($event)">
      </calendar>
```

**Comment by amorriscode** [comment]
Still not working for me for some reason... here is everything I have:

*schedule.ts*
`import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-schedule',
  templateUrl: 'schedule.html'
})
export class Schedule {

  calendar: any = {
    currentDate: new Date()
  };

  constructor(public navCtrl: NavController) {

  }

}
`
*schedule.html*
`<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Schedule</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <calendar>
  </calendar>
</ion-content>
`

**Comment by alexandretok** [comment]
You got to set the property `[currentDate]="calendar.currentDate"` inside your `calendar` tag.
I believe your `schedule.html` should look like this:

```
<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Schedule</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <calendar [currentDate]="calendar.currentDate">
  </calendar>
</ion-content>
```
