### ISSUE TITLE
Ionic 3 Can't build/run the app

### ISSUE THREAD

**Issue by cr1pt0r0** [twinssbc/Ionic2-Calendar#482]
Hi, I'm having trouble building/running the app to my android phone. App is working fine when I did "ionic serve". Below are the errors that I'm encountering when I do "ionic cordova run android --prod"

![Untitled](https://user-images.githubusercontent.com/49737524/71270193-ec4b3700-238b-11ea-9faf-ccb4eeac87e1.png)

**Comment by twinssbc** [comment]
@cr1pt0r0 Which Ionic and Angular version are you using? Could you kindly check the * Dependency* section in README, it documents the corresponding version should be used.

**Comment by cr1pt0r0** [comment]
Nevermind. I was using someone else's ionic template. Creating a newly fresh ionic works well. Sorry for the cause. haha.
