### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\rafax\Desktop\gym-progress\node_modules\ionic2-calendar\index.js'

### ISSUE THREAD

**Issue by rafaxplayer** [twinssbc/Ionic2-Calendar#483]
Hi, I have this problem in ionic 4 I can't get ionic2-calendar to work, this is the console error:
ERROR in ./node_modules/ionic2-calendar/index.js
[ng] Module build failed: Error: ENOENT: no such file or directory, open 'C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ ionic2-calendar \ index.js'
[ng] at Object.openSync (fs.js: 443: 3)
[ng] at Object.readFileSync (fs.js: 343: 35)
[ng] at Storage.provideSync (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ enhanced-resolve \ lib \ CachedInputFileSystem.js: 98: 13)
[ng] at CachedInputFileSystem.readFileSync (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ enhanced-resolve \ lib \ CachedInputFileSystem.js: 259: 32)
[ng] at Observable.rxjs_1.Observable.obs [as _subscribe] (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ @ngtools \ webpack \ src \ webpack-input-host.js: 35: 51)
[ng] at Observable._trySubscribe (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ @ngtools \ webpack \ node_modules \ rxjs \ internal \ Observable.js: 44: 25)
[ng] at Observable.subscribe (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ @ngtools \ webpack \ node_modules \ rxjs \ internal \ Observable.js: 30: 22)
[ng] at SyncDelegateHost._doSyncCall (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ @ angular-devkit \ core \ src \ virtual-fs \ host \ sync.js: 22: 20)
[ng] at SyncDelegateHost.read (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ @ angular-devkit \ core \ src \ virtual-fs \ host \ sync.js: 49: 21)
[ng] at WebpackCompilerHost.readFileBuffer (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ @ngtools \ webpack \ src \ compiler_host.js: 147: 44)
[ng] at VirtualFileSystemDecorator.readFile (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ @ngtools \ webpack \ src \ virtual_file_system_decorator.js: 42: 54)
[ng] at processResource (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ loader-runner \ lib \ LoaderRunner.js: 202: 11)
[ng] at iteratePitchingLoaders (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ loader-runner \ lib \ LoaderRunner.js: 158: 10)
[ng] at runLoaders (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ loader-runner \ lib \ LoaderRunner.js: 365: 2)
[ng] at NormalModule.doBuild (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ webpack \ lib \ NormalModule.js: 281: 3)
[ng] at NormalModule.build (C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ webpack \ lib \ NormalModule.js: 427: 15)

This would be my page module.
import {NgModule} from '@ angular / core';
import {CommonModule} from '@ angular / common';
import {IonicModule} from '@ ionic / angular';
import {FormsModule} from '@ angular / forms';
import {RouterModule} from '@ angular / router';

import {HomePage} from './home.page';

import {NgCalendarModule} from 'ionic2-calendar';

@NgModule ({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
  
    RouterModule.forChild ([
      {
        path: '',
        component: HomePage
      }

  ]),
  NgCalendarModule
  ],
  declarations: [HomePage]
})
export class HomePageModule {}

And this is my view:
<ion-content class = "has-header">
    <div class = "ion-padding">
        <calendar [eventSource] = "eventSource" [calendarMode] = "calendar.mode" [currentDate] = "calendar.currentDate" (onEventSelected) = "onEventSelected ($ event)" (onTitleChanged) = "onViewTitleChanged ($ event)" ( onTimeSelected) = "onTimeSelected ($ event)" startHour = "6"
            endHour = "20" step = "30" startingDayWeek = "1">
        </calendar>
    </ Div>
</ion-content>
Here I get an error that there is no kemento calendar.
Any idea what can happen ?, thanks

**Comment by twinssbc** [comment]
@rafaxplayer As the error indicates,
"Error: ENOENT: no such file or directory, open 'C: \ Users \ rafax \ Desktop \ gym-progress \ node_modules \ ionic2-calendar \ index.js'"

Could you check your node_modules folder to see if index.js exists?
