### ISSUE TITLE
format date

### ISSUE THREAD

**Issue by rafaxplayer** [twinssbc/Ionic2-Calendar#488]
Hello I would like to know how I can format the dates of departure in events like onCurrentDateChanged ($ event)?
I need a 'd-M-yyy' pattern for my dates, thanks

**Comment by twinssbc** [comment]
@rafaxplayer If I understand correctly, you want to format your dates to a string? You could just use string operation or any other 3rd party library.

**Comment by rafaxplayer** [comment]
I do know that, but my question was whether calendar has functionality to avoid having to use third-party libraries.

**Comment by twinssbc** [comment]
@rafaxplayer The calendar itself doesn't have this functionality. But I also leverage the Angular DatePipe to do some formatting instead of using third-party library.
https://stackoverflow.com/questions/48183677/how-to-format-date-in-component-of-angular-5

**Comment by rafaxplayer** [comment]
Ok, solved, thanks for responding so soon.
