### ISSUE TITLE
MonthView wrong day selected

### ISSUE THREAD

**Issue by Daskus1** [twinssbc/Ionic2-Calendar#49]
When clicking on a day in monthview that is after march 26 the day before is selected. This is probably due to day light saving change.

**Comment by twinssbc** [comment]
@Daskus1 Which timezone are you in?

**Comment by Daskus1** [comment]
My timezone is Europe/Berlin

**Comment by twinssbc** [comment]
@Daskus1 I have fixed the bug in version 0.2.3. Feel free to have a try. Thanks for reporting it.

**Comment by sakshamg6** [comment]
Still getting this error in 0.2.5 version.
