### ISSUE TITLE
Calendar Styles. Remove borders of table inside component

### ISSUE THREAD

**Issue by jcmendes9898** [twinssbc/Ionic2-Calendar#491]
So i'm trying to remove the borders of the calendar, to remove the look like table view. When i inspect element i can remove the borders 
`.table-bordered[_ngcontent-jto-c5] > thead[_ngcontent-jto-c5] > tr[_ngcontent-jto-c5] > th[_ngcontent-jto-c5], .table-bordered[_ngcontent-jto-c5] > tbody[_ngcontent-jto-c5] > tr[_ngcontent-jto-c5] > th[_ngcontent-jto-c5], .table-bordered[_ngcontent-jto-c5] > tfoot[_ngcontent-jto-c5] > tr[_ngcontent-jto-c5] > th[_ngcontent-jto-c5], .table-bordered[_ngcontent-jto-c5] > thead[_ngcontent-jto-c5] > tr[_ngcontent-jto-c5] > td[_ngcontent-jto-c5], .table-bordered[_ngcontent-jto-c5] > tbody[_ngcontent-jto-c5] > tr[_ngcontent-jto-c5] > td[_ngcontent-jto-c5], .table-bordered[_ngcontent-jto-c5] > tfoot[_ngcontent-jto-c5] > tr[_ngcontent-jto-c5] > td[_ngcontent-jto-c5] {
    /* border: 1px solid #ddd; */
}`

Although I'm not getting the same result when i pass it to the css file. Any advices?

**Comment by twinssbc** [comment]
@jcmendes9898 The [_ngcontent-jto-c5] syntax is used for view encapsulation. When you overriding it, you could remove it, for example

```
.table-bordered > thread > tr > th {
    border: 1px solid #ddd !important;
}
```

**Comment by jcmendes9898** [comment]
I do place it on the .scss but notthing happens. I place it on the scss of the page as on the variable or on the global... It stays the same.

**Comment by jcmendes9898** [comment]
Ok, the way i found was to replace all.   .table-bordered > thead > tr > th {
    border: 0px solid #ddd !important;
  }
  .table-bordered > tbody > tr > th {
    border: 0px solid #ddd !important;
  }
  .table-bordered > tfoot > tr > th {
    border: 0px solid #ddd !important;
  }
  .table-bordered > thead > tr > td {
    border: 0px solid #ddd !important;
  }
  .table-bordered > tbody > tr > td {
    border: 0px solid #ddd !important;
  }
  .table-bordered > tfoot > tr > td {
    border: 0px solid #ddd !important;
  }

Thanks for the tip! I place it on the variables.scss file
