### ISSUE TITLE
week view header implementation indside day view

### ISSUE THREAD

**Issue by ktk312** [twinssbc/Ionic2-Calendar#495]
i cannot implement week view header inside day view. i want weekviewdayheader inside of day view

**Comment by ktk312** [comment]
@twinssbc

**Comment by twinssbc** [comment]
@ktk312 There is no day header in the day view, only week view has a header for each day.

**Comment by ktk312** [comment]
@twinssbc  i am stuck in a project which needs day view but along with week view header. i have tried all possible ways to do that but failed until now. any help would be appreciated Thanks

**Comment by ktk312** [comment]
![Capture](https://user-images.githubusercontent.com/46324095/73946085-2b6f2080-4917-11ea-9fa7-d439967a2e6e.PNG)

this is what i need to implement

**Comment by twinssbc** [comment]
@ktk312 This calendar doesn't contain such week view header in the day view.
You could implement one by yourself.
Basically you could add a table above the calendar element, the table needs to be filled with one week date. The date could be calculated by the current date.
