### ISSUE TITLE
Can I change color depend on property of event on month view.

### ISSUE THREAD

**Issue by gentixyann** [twinssbc/Ionic2-Calendar#497]
Hi, I'm looking for how can I set different color depend on property of event on month view.

My calendar is like this.

![スクリーンショット 2020-02-12 14 41 42](https://user-images.githubusercontent.com/25972149/74296105-cc425d80-4da7-11ea-9d48-ec4cbfe9f3f2.jpg)

```html
<ng-template #template let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
    ... 
    </ng-template>
 
    <calendar ... [monthviewEventDetailTemplate]="template"></calendar>
```

```css
.monthview-datetable td.monthview-primary-with-event {
  background-color:#feb9c3 !important;
  border-radius: 50%;
}
```

### For example, 

**Case A**
```
const event = {
title: 'Some Title',
startTime: startTime,
endTime: endTime,
item: 'item01'
}
```

**Case B**
```
const event = {
title: 'Some Title',
startTime: startTime,
endTime: endTime,
item: 'item02'
}
```
 
If event is **CaseB(event.item === 'item02')** ,
I want to change color of event on month view calendar. Now, I can see only pink if there are event of CaseB.

I found some issue like [this](https://github.com/twinssbc/Ionic2-Calendar/issues/158), but I am using **monthviewEventDetailTemplate**

Not monthviewDisplayEventTemplate...

Is there any solution??

**Comment by twinssbc** [comment]
@gentixyann yes, you need to use monthviewDisplayEventTemplate
Just like the discussion in the issue link you provided.
You could implement getEventClass logic to return a css class based on the events happen on that day. And you can use any event field to help generate the css class you want. Then you just need to apply proper style on the css class.
```
    <ng-template #template let-view="view" let-row="row" let-col="col">
        <div class={{getEventClass(view.dates[row*7+col].events)}}>{{view.dates[row*7+col].label}}</div>
    </ng-template>

    <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>

```

**Comment by gentixyann** [comment]
Thanks!
I got it. I understood about Template Customization !

![スクリーンショット 2020-02-13 21 02 21](https://user-images.githubusercontent.com/25972149/74413394-304a4c00-4ea4-11ea-9060-9191b94d350b.jpg)

```html
 <ng-template #monthView let-view="view" let-row="row" let-col="col">
    <div *ngIf="view.dates[row*7+col].events == ''">{{view.dates[row*7+col].label}}</div>
    <div *ngFor="let obj of view.dates[row*7+col].events">
      <div *ngIf="!obj.items">
        <div>{{view.dates[row*7+col].label}}</div>
      </div>
      <div *ngIf="obj.items">
        <div [ngStyle]="eventStyle">{{view.dates[row*7+col].label}}</div>
      </div>
    </div>
    </ng-template>

 <ng-template #eventDetail let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
    ... 
    </ng-template>

 <calendar ... [monthviewDisplayEventTemplate]="monthView" [monthviewEventDetailTemplate]="eventDetail"></calendar>
```

```javascript
eventStyle = {
    borderRadius: '50%',
    backgroundColor: '#ff944d',
  };
```

**Comment by seatechdev** [comment]
Building upon this - how do I just color code based on the number of the day.   For example, every Mon, Wed and Fri are coded orange?

I'm basically trying to figure out how do I extract if it is day 1, 3 or 5 of the week.  Similar to what Ionic does - in its [datetime](https://ionicframework.com/docs/api/datetime#advanced-date-constraints) component to disable the days.  In my case I don't want them to be disabled instead a different color.

**Comment by twinssbc** [comment]
> Building upon this - how do I just color code based on the number of the day. For example, every Mon, Wed and Fri are coded orange?
> 
> I'm basically trying to figure out how do I extract if it is day 1, 3 or 5 of the week. Similar to what Ionic does - in its [datetime](https://ionicframework.com/docs/api/datetime#advanced-date-constraints) component to disable the days. In my case I don't want them to be disabled instead a different color.

You could still use the same monthviewDisplayEventTemplate to make some customization.
view.dates[row*7+col].date is actually Date object, and then you can call getDay() to get the day in the week.

**Comment by seatechdev** [comment]
> > Building upon this - how do I just color code based on the number of the day. For example, every Mon, Wed and Fri are coded orange?
> > I'm basically trying to figure out how do I extract if it is day 1, 3 or 5 of the week. Similar to what Ionic does - in its [datetime](https://ionicframework.com/docs/api/datetime#advanced-date-constraints) component to disable the days. In my case I don't want them to be disabled instead a different color.
> 
> You could still use the same monthviewDisplayEventTemplate to make some customization. view.dates[row*7+col].date is actually Date object, and then you can call getDay() to get the day in the week.

Thanks!   But what if I want to set a rule i.e. for all days 1, 3 and 5 set the color code to Orange.  getDay can get me the day number of a given date.  But what if I don't know what date the first Monday of 2024 will be without manually looking at the calendar.  Basically, set all mon, wed, and friday to orange between now and lets say Jan 31st, 2024.    Will I need to do it programmatically by traversing through all the days and assessing if they are 1, 3 or 5 or can I just set some rule that between the range Feb 6th, 2023 and Jan 31st, 2024 market all 1,3 and 5 days as oarange?

**Comment by twinssbc** [comment]
> > > Building upon this - how do I just color code based on the number of the day. For example, every Mon, Wed and Fri are coded orange?
> > > I'm basically trying to figure out how do I extract if it is day 1, 3 or 5 of the week. Similar to what Ionic does - in its [datetime](https://ionicframework.com/docs/api/datetime#advanced-date-constraints) component to disable the days. In my case I don't want them to be disabled instead a different color.
> > 
> > 
> > You could still use the same monthviewDisplayEventTemplate to make some customization. view.dates[row*7+col].date is actually Date object, and then you can call getDay() to get the day in the week.
> 
> Thanks! But what if I want to set a rule i.e. for all days 1, 3 and 5 set the color code to Orange. getDay can get me the day number of a given date. But what if I don't know what date the first Monday of 2024 will be without manually looking at the calendar. Basically, set all mon, wed, and friday to orange between now and lets say Jan 31st, 2024. Will I need to do it programmatically by traversing through all the days and assessing if they are 1, 3 or 5 or can I just set some rule that between the range Feb 6th, 2023 and Jan 31st, 2024 market all 1,3 and 5 days as oarange?

You don't have to know the first Monday is which date. getDay() method tells you on specific day, it is Monday or Tuesday.
When template is applied, you could think it as traverse every day automatically and apply some of your logic.
Sample:
HTML
```
    <ng-template #template let-view="view" let-row="row" let-col="col">
        <div class={{getEventClass(view.dates[row*7+col].date)}}>{{view.dates[row*7+col].label}}</div>
    </ng-template>

    <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>
```

Component
```
    getEventClass(date:Date) {
        if(date.getDay() == 1 || date.getDay()==3 ||date.getDay() == 5) {
            return 'orange-date';
        } else {
            return 'red-date';
        }
    }
```

Then you will find the orange-date will appear in the rendered HTML, you could apply your own style.

**Comment by seatechdev** [comment]
Thank you for your help.  But I am still confused.  It seems like your code above requires you to know what the event date is.  Lets try another way.  Let's assume that I have an api that stores Red days in the backend.  

For User 1 - It returns Day 1, Day 3 and Day 5 to be the Red days.    The events table is  empty.  Basically there is nothing to push on the events array to show.  But based on the logic returned from the backend - I want Monday, Wednesday and Friday of every week for the next few years to show as Red.  

For User 2, the Red Days are Day 2 and Day 4.  Which means when User 2 sees the calendar their Tuesdays and Thursdays are Red.  

For User 3, Day 6 and Day 0 are the Red days.  Which means User 3 sees all  of their Saturdays and Sundays as Red.   

For User 4, It can be Day 1,2,5,6 and so on..

 I still want to be able to show regular events the way your package is designed.  But before that I want to color code the days based on the user choice, regardless of the fact if they have any events or not.

**Comment by twinssbc** [comment]
> Thank you for your help. But I am still confused. It seems like your code above requires you to know what the event date is. Lets try another way. Let's assume that I have an api that stores Red days in the backend.
> 
> For User 1 - It returns Day 1, Day 3 and Day 5 to be the Red days. The events table is empty. Basically there is nothing to push on the events array to show. But based on the logic returned from the backend - I want Monday, Wednesday and Friday of every week for the next few years to show as Red.
> 
> For User 2, the Red Days are Day 2 and Day 4. Which means when User 2 sees the calendar their Tuesdays and Thursdays are Red.
> 
> For User 3, Day 6 and Day 0 are the Red days. Which means User 3 sees all of their Saturdays and Sundays as Red.
> 
> For User 4, It can be Day 1,2,5,6 and so on..
> 
> I still want to be able to show regular events the way your package is designed. But before that I want to color code the days based on the user choice, regardless of the fact if they have any events or not.


Maybe in this way? put a isUserSelectedRedDay method in getEventClass, and pass the user and date. You have your API to know certain user picks which day. So should be able to tell true or false.
```
getEventClass(date:Date) {
        if(isUserSelectedRedDay(user, date) {
              return 'red-date';
        }
    }

```

**Comment by seatechdev** [comment]
For now, I am using the dateFormatter function to indicate if it is a Red day or not.  I tried using the ng-template route similar to what you mentioned, the methods that have been discussed [here](https://github.com/twinssbc/Ionic2-Calendar/issues/497) and [here](https://github.com/Bhavana1622/ionic2-calendar-event/blob/master/events.html).  I wish if there is an easier way just to add css in dateFormatter to color code the background of those days.    Angular-Calendar has this capability.  Please see the [kitchen sink](https://mattlewis92.github.io/angular-calendar/#/before-view-render).   May be there is a way to do it and I just haven't been able to figure out.  I even tried creating a separate class called background format to do something similar but had no success.
```
dateFormatter: {
        formatMonthViewDay: function (date: Date) {
          if(date.getDay() == 1 || date.getDay()==3 ||date.getDay() == 5) {
            return  date.getDate().toString() + ' R';
        } else {
            
            return date.getDate().toString();
        }

        },
        
      },



 backgroundFormat = {
      backgroundFormatter: { 
        formatMonthViewDay: function (date: Date) {
          if(date.getDay() == 1 || date.getDay()==3 ||date.getDay() == 5) {
            console.log('pink' + date.getDay())
            return  'bg-pink'
        } else {
            
            return  'default';
        }
        }
      }
     };

```
<img width="395" alt="Screenshot 2023-02-09 at 10 36 21 PM" src="https://user-images.githubusercontent.com/4111840/218020240-a997e795-337e-44f9-9cef-5013d288c0d6.png">

**Comment by twinssbc** [comment]
dateFormatter is passed to DatePipe, so the output is a String, can't be treated as a piece of HTML code.

**Comment by seatechdev** [comment]
Yes, I understand that.  I guess there is not way to dynamically format based on the day of the week before the calendar is rendered, similar to the angular calendar kitchen sink example [here](https://mattlewis92.github.io/angular-calendar/#/before-view-render).

**Comment by seatechdev** [comment]
I used the [comment above by the OP](https://github.com/twinssbc/Ionic2-Calendar/issues/497#issuecomment-585603626) to color code my dates dynamically.  However, It is not taking the full space for each date cell.  I tried setting height and width but  no success.  Are the variables different for these settings?

```
eventStyle = {
    backgroundColor: 'var(--ion-color-danger)',
    height: '100%',
    width: '100%'
  };
```

![Screenshot 2023-10-18 at 3 01 50 PM](https://github.com/twinssbc/Ionic2-Calendar/assets/4111840/82781614-d00d-4ad4-818e-f44e0333b440)

**Comment by seatechdev** [comment]
Also, how do I apply the same css for week and day view.    I tried applying it to ```<ng-template #weekviewNormalEventTemplate let-displayEvent="displayEvent">``` and  ``` <ng-template #dayviewNormalEventTemplate="displayEvent">``` but had no success.
