### ISSUE TITLE
update ionic version

### ISSUE THREAD

**Issue by sdore2021** [twinssbc/Ionic2-Calendar#498]
will module be able to support new version of ionic, I have to update to upgrade to new version?

**Comment by twinssbc** [comment]
@sdore2021 You mean Ionic 5.0? Yes, I will upgrade the module.

**Comment by sdore2021** [comment]
ok thanks.

**Comment by twinssbc** [comment]
@sdore2021 I tested to use the latest version in Ionic 5.0 project, it is working fine. Seems no break change.

**Comment by fruhland** [comment]
It works fine with Ionic 5 and Agular 8, but since I updated to Angular 9, I get compilation errors:

```
[ng] Compiling ionic2-calendar : main as commonjs
[ng] chunk {main} main.js, main.js.map (main) 2 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 677 bytes [initial] [rendered]
[ng] chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 525 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 101 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
[ng] Date: 2020-03-12T12:04:27.028Z - Hash: 8dea23b4f21e9e9d308d - Time: 11244ms
[ng] ERROR in Failed to compile entry-point ionic2-calendar (main as commonjs) due to compilation errors:
[ng] node_modules/ionic2-calendar/weekview.js:744:28 - error NG1010: encapsulation must be a member of ViewEncapsulation enum from @angular/core
[ng] 744             encapsulation: ViewEncapsulation.None
[ng]                                ~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic2-calendar/dayview.js:555:28 - error NG1010: encapsulation must be a member of ViewEncapsulation enum from @angular/core
[ng] 555             encapsulation: ViewEncapsulation.None
[ng]                                ~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic2-calendar/init-position-scroll.js:54:28 - error NG1010: encapsulation must be a member of ViewEncapsulation enum from @angular/core
[ng] 54             encapsulation: ViewEncapsulation.None
[ng]                               ~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic2-calendar/calendar.module.js:15:27 - error NG1010: Value at position 0 in the NgModule.declarations of NgCalendarModule is not a reference: [object Object]
[ng] 15             declarations: [
[ng]                              ~
[ng] 16                 MonthViewComponent, WeekViewComponent, DayViewComponent, CalendarComponent, initPositionScrollComponent
[ng]    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 17             ],
[ng]    ~~~~~~~~~~~~~
```

Is there something I need to do, or does the code have to be updated for compatibility with Angular 9?

**Comment by twinssbc** [comment]
@fruhland Try the 0.5.9 version, in that version I'm trying to make it compatible with Angular 9.

**Comment by tacur** [comment]
> @fruhland Try the 0.5.9 version, in that version I'm trying to make it compatible with Angular 9.

I still getting following ERROR:
"ERROR in node_modules/ionic2-calendar/calendar.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of CalendarPageModule, but could not be resolved to an NgModule class.

This likely means that the library (ionic2-calendar) which declares NgCalendarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy."

**Comment by javierec21** [comment]
With 0.5.9, ionic 5 and angular 9 I was having the same problem in my app. I've solved it (by now) disabling Ivy.

tsconfig.json =>
"angularCompilerOptions": { "enableIvy": false }

**Comment by twinssbc** [comment]
I published a new version 0.6.1. Feel free to give a try.

**Comment by fruhland** [comment]
Version 0.6.1 is working fine with Angular 9 and Ivy, Thanks!

**Comment by MathanM** [comment]
Hi,

I am getting the following error

ERROR in ./node_modules/ionic2-calendar/weekview.js 360:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 374:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 385:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 397:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 408:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 422:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 424:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 455:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 457:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 459:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 461:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 472:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 484:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 493:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 507:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 509:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 538:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 540:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 542:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 544:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1212:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1214:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1216:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1218:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1220:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1222:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1224:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1226:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1228:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 20:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 31:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 51:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 53:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 69:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 87:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 89:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 103:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 114:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 124:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 143:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 145:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 161:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 178:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 180:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 194:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 205:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 215:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 234:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 236:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 252:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 269:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 271:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 285:4-16
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 800:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 802:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 804:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 806:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 808:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 810:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 812:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 814:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 816:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 818:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 820:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 822:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 824:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 826:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 828:8-20
[ng] "export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/monthview.js 731:31-45
[ng] "export 'ɵɵloadQuery' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/weekview.js 1167:31-45
[ng] "export 'ɵɵloadQuery' (imported as 'i0') was not found in '@angular/core'
[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 734:31-45
[ng] "export 'ɵɵloadQuery' (imported as 'i0') was not found in '@angular/core'
[ng]     
[ng]     ERROR in node_modules/ionic2-calendar/calendar.d.ts(153,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic2-calendar/calendar.d.ts(154,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic2-calendar/calendar.d.ts(219,21): error TS2694: Namespace '"/Users/mathan-8100/ionic/smart-li/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng]     node_modules/ionic2-calendar/calendar.d.ts(220,18): error TS2314: Generic type 'ɵɵComponentDefWithMeta' requires 6 type argument(s).
[ng]     node_modules/ionic2-calendar/calendar.service.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng]     node_modules/ionic2-calendar/calendar.service.d.ts(25,21): error TS2694: Namespace '"/Users/mathan-8100/ionic/smart-li/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng]     node_modules/ionic2-calendar/dayview.d.ts(77,21): error TS2694: Namespace '"/Users/mathan-8100/ionic/smart-li/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng]     node_modules/ionic2-calendar/dayview.d.ts(78,18): error TS2314: Generic type 'ɵɵComponentDefWithMeta' requires 6 type argument(s).
[ng]     node_modules/ionic2-calendar/init-position-scroll.d.ts(15,21): error TS2694: Namespace '"/Users/mathan-8100/ionic/smart-li/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng]     node_modules/ionic2-calendar/init-position-scroll.d.ts(16,18): error TS2314: Generic type 'ɵɵComponentDefWithMeta' requires 6 type argument(s).
[ng]     node_modules/ionic2-calendar/monthview.d.ts(67,21): error TS2694: Namespace '"/Users/mathan-8100/ionic/smart-li/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng]     node_modules/ionic2-calendar/monthview.d.ts(68,18): error TS2314: Generic type 'ɵɵComponentDefWithMeta' requires 6 type argument(s).
[ng]     node_modules/ionic2-calendar/weekview.d.ts(85,21): error TS2694: Namespace '"/Users/mathan-8100/ionic/smart-li/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng]     node_modules/ionic2-calendar/weekview.d.ts(86,18): error TS2314: Generic type 'ɵɵComponentDefWithMeta' requires 6 type argument(s).


Here is my package.json

"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ionic-native/admob-free": "^5.25.0",
    "@ionic-native/camera": "^5.25.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/date-picker": "^5.25.0",
    "@ionic-native/file": "^5.25.0",
    "@ionic-native/file-opener": "^5.25.0",
    "@ionic-native/file-transfer": "^5.25.0",
    "@ionic-native/market": "^5.25.0",
    "@ionic-native/network": "^5.25.0",
    "@ionic-native/social-sharing": "^5.25.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.2.0",
    "cordova-plugin-admob-free": "^0.27.0",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-market": "^1.2.0",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-x-socialsharing": "^5.6.5",
    "cordova-sqlite-storage": "^5.0.0",
    "core-js": "^2.5.4",
    "html2canvas": "^1.0.0-rc.5",
    "ionic-cache": "^5.2.0",
    "ionic2-calendar": "^0.6.4",
    "moment": "^2.25.3",
    "pdfmake": "^0.1.65",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-datepicker": {},
      "cordova-plugin-market": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-network-information": {}
    }
  }

**Comment by twinssbc** [comment]
@MathanM If you want to use calendar version 0.6.4,  you need to use Ionic version >=5.1.0 and Angular version >= 9.1.0. You could get more information from the Dependency section in README.

**Comment by thierce** [comment]
Hi, any chance this can be resolved for Angular 10?

**Comment by twinssbc** [comment]
@thierce what error do you get for Angular 10?

**Comment by jym126** [comment]
Angular 17 error: 
"This likely means that the library (ionic2-calendar) which declares NgCalendarModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy."
![223326](https://github.com/twinssbc/Ionic2-Calendar/assets/52292125/811c245b-4a2e-4ad2-9ecb-fd50bc0fdadf)
