### ISSUE TITLE
How Can I Use load events with a remote API?

### ISSUE THREAD

**Issue by IsCruz** [twinssbc/Ionic2-Calendar#50]
Actualmente I'm working with ir, but when I click load events the gaps are empty.

**Comment by twinssbc** [comment]
@IsCruz 
I assume your load events sends a HTTP request to the backend? You need to manipulate the eventSource array in your callback.

**Comment by IsCruz** [comment]
Yep
I'M fetching data throught http

**Comment by twinssbc** [comment]
Do you set the queryMode to **remote**?
What if you add a breakpoint to your http callback, is it get triggered and fills eventSource?

**Comment by ngarland79** [comment]
I'm unable to get this to work with Angularfire2. I keep getting errors like this:

event_1.startTime.getTime is not a function

And if I set queryMode to "remote" I get this error:

self.context.reloadSource is not a function

**Comment by twinssbc** [comment]
@ngarland79
Could you check if the startTime you set is Date type?
And according to the error, reloadSource is not a function? How do you pass it to the calendar?

**Comment by ngarland79** [comment]
Figured it out. Times were not truly being sent as Date type. Thank you :-)

**Comment by Tusharbalar** [comment]
I want to load data from remote api, and i have applied queryMode as remote. calendar is not updating even if there is any change in eventSource. 

following is my html and ts code

**.html file**

```
<calendar [eventSource]="eventSource"
        [calendarMode]="calendar.mode"
        [currentDate]="calendar.currentDate"
        (onCurrentDateChanged)="onCurrentDateChanged($event)"
        queryMode="remote"
        rangeChanged="rangeChanged()"
        (onRangeChanged)="onRangeChanged($event)"
        (onEventSelected)="onEventSelected($event)"
        (onTitleChanged)="onViewTitleChanged($event)"
        (onTimeSelected)="onTimeSelected($event)"
        step="30">
</calendar>
```

**.ts file**

```
ngOnInit() {
      this.nl.showLoader();
      let eventMonth = getYear(new Date()) + "-" + (getMonth(new Date())+1);
      this.eventService.GetEvents(eventMonth).subscribe((res) => {
        this.nl.hideLoader();
        res.forEach((val, index) => {
          this.eventSource.push({
            startTime: new Date(val.start),
            endTime: new Date(val.end),
            title: val.title,
            allDay: false
          });
        });
      }, (err) => {
        console.log(err)
      });
    }
```

**Comment by twinssbc** [comment]
@Tusharbalar 
Could you try couple things to locate the real problem?
1. Could you debug to see if GetEvents is actually triggered? 
2. Do you call GetEvents in onRangeChanged callback?
3. What if you remove GetEvents method, just fill some dummy events in the eventSource, will it work?
4. Also I notice that you use this.eventSource, is "this" pointing to the correct scope?

**Comment by Tusharbalar** [comment]
Hello Sir,
Actually i forgot to call GetEvents within onRangeChanged() function
I did like this but not success.

Please help me

```
onRangeChanged(ev) {
      let eventMonth = getYear(new Date()) + "-" + (getMonth(new Date())+1);
      this.eventService.GetEvents(eventMonth).subscribe((res) => {
        this.nl.hideLoader();
        res.forEach((val, index) => {
          this.eventSource.push({
            startTime: new Date(val.start),
            endTime: new Date(val.end),
            title: val.title,
            allDay: false
          });
         console.log("Event source", this.eventSource);
        });
      }, (err) => {
        console.log(err)
      });
 }
```

Thank you

**Comment by twinssbc** [comment]
@Tusharbalar 
Have you tried other suggestions?

1. Could you debug to see if GetEvents is actually triggered?
2. What if you remove GetEvents method, just fill some dummy events in the eventSource, will it work?
3. Also I notice that you use this.eventSource, is "this" pointing to the correct scope?

**Comment by Tusharbalar** [comment]
@twinssbc 

1. Yes, GetEvents is called properly and you can refer the log to have a look whether this.eventSource array is used correctly or not
2. It works fine in local queryMode
3. Yes I have checked, 'this' is referring to correct scope

**Comment by twinssbc** [comment]
Yes, you can use markDisabled option.

**Comment by Tusharbalar** [comment]
Sir, actually i want to restrict the swap access to previous months from current date.

**Comment by twinssbc** [comment]
@Tusharbalar 
If the calendar is not updated after updating the eventSource, I think still something wrong with your callback logic. Could you try replacing your GetEvents method with some logic to directly adding some fake events to eventSource?

You can override the css style or use monthviewDisplayEventTemplate to customize the view.

**Comment by gdesplin** [comment]
@ngarland79 How did you solve getting the dates back to the right format?
