### ISSUE TITLE
Time range is not accurate.

### ISSUE THREAD

**Issue by benjoabrasado25** [twinssbc/Ionic2-Calendar#506]
Hi,

I tried to change the content of the event source. I printing the eventSource on console but it's not acting as expected. Please see this image.

![image](https://user-images.githubusercontent.com/32357669/75508202-503e4b80-5a1e-11ea-983d-066a135d643d.png)

Thank you in advance,

**Comment by twinssbc** [comment]
@benjoabrasado25 The float number has the accuracy problem, when I'm calculating the slot of each event, I can't simply use == to compare two date time, instead I have to use data1-data2 < eps. This means if you set the endTime exactly to 14:00:00, it becomes the edge case, it call fall to the previous or next slot. So I suggest you set it to 13:59:00
