### ISSUE TITLE
ERROR TypeError: event_1.startTime.getTime is not a function

### ISSUE THREAD

**Issue by SkinnyA** [twinssbc/Ionic2-Calendar#509]
Hello, im trying to format date from the api to UTC and it keeps me logging this error: 
ERROR TypeError: event_1.startTime.getTime is not a function

`import { Component, OnInit, ViewChild, Inject, LOCALE_ID } from '@angular/core';
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { AlertController } from '@ionic/angular';
import { formatDate } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import * as moment from 'moment';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit{

  event = {
    title: '',
    desc: '',
    startTime: '',
    endTime: '',
    allDay: false
  }
  eventSource = [];

  viewTitle= '';

  calendar = {
    mode: 'month',
    currentDate: new Date()
  }

  @ViewChild(CalendarComponent, {static: false}) myCal: CalendarComponent

  constructor(private alrtCrtl: AlertController, @Inject(LOCALE_ID) private locale: string, private http: HttpClient) {}

  ngOnInit(){
    this.getData();
  }

  getData(){
    this.http.get('http://localhost:3000/Pedidos').subscribe((resp: any) => {

      resp.forEach((entrada) =>{

        let eventos;
        eventos = {
          title: entrada.Asunto,
          startTime: entrada.FechaInicio,
          endTime: entrada.FechaFin,
          allDay: false,
          tipo: entrada.Tipo,
          idPedido: entrada.idPedido,
        }

        if(eventos.tipo === "Aereo"){
          eventos = {
            title: '✈️ ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('MMMM D, YYYY'),
            endTime: moment(entrada.FechaFin).format('MMMM D, YYYY'),
            allDay: false,
            id: entrada.idPedido,
          }
        }

        if(eventos.tipo === "Hotel"){
          eventos = {
            title: '🏨 ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('MMMM D, YYYY'),
            endTime: moment(entrada.FechaFin).format('MMMM D, YYYY'),
            allDay: false,
            id: entrada.idPedido,
          }
        }

        if(eventos.tipo === "Coche"){
          eventos = {
            title: '🚗 ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('MMMM D, YYYY'),
            endTime: moment(entrada.FechaFin).format('MMMM D, YYYY'),
            allDay: false,
            id: entrada.idPedido,
          }
        }

        if(eventos.tipo === "Tren"){
          eventos = {
            title: '🚆 ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('MMMM D, YYYY'),
            endTime: moment(entrada.FechaFin).format('MMMM D, YYYY'),
            allDay: false,
            id: entrada.idPedido,
          }
        }

        this.eventSource.push(eventos)
        this.myCal.loadEvents();
 
      });console.log("prueba " , this.eventSource);

    });
  }

  resetEvent(){
    this.event = {
      title: '',
      desc: '',
      startTime: new Date().toISOString(),
      endTime: new Date().toISOString(),
      allDay: false
    };
  }

  back(){
    var swiper = document.querySelector('.swiper-container')['swiper'];
    swiper.slidePrev();
  }

  next(){
    var swiper = document.querySelector('.swiper-container')['swiper'];
    swiper.slideNext();
  }

  onEventSelected(){
    console.log(this.eventSource[0].text);
  }

  onViewTitleChanged(title){
    this.viewTitle = title;
  }

}
`

Is the format UTC or its just another one?
This is what i recieve from my api (with data converted to UTC format)

0: {title: "✈️ 07:05 Madrid -- > Valencia", startTime: "September 14, 2018", endTime: "September 14, 2018", allDay: false, id: "183266"}

1: {title: "✈️ 07:05 Madrid -- > Valencia", startTime: "October 13, 2018", endTime: "October 13, 2018", allDay: false, id: "183268"}

2: {title: "✈️ 19:35 Valencia -- > Madrid", startTime: "September 12, 2018", endTime: "September 12, 2018", allDay: false, id: "183266"}

3: {title: "✈️ 12:05 Valencia -- > Madrid", startTime: "October 10, 2018", endTime: "October 10, 2018", allDay: false, id: "183268"}

4: {title: "🏨 Hotel Restel Test Prueba", startTime: "September 12, 2018", endTime: "September 16, 2018", allDay: false, id: "183262"}

5: {title: "🏨 Hotel Restel Test Prueba", startTime: "September 12, 2018", endTime: "September 15, 2018", allDay: false, id: "183267"}

6: {title: "🏨 Nh Valencia Center", startTime: "May 22, 2018", endTime: "May 23, 2018", allDay: false, id: "183268"}

7: {title: "🚗 Recogida 10:30:00 En Valencia", startTime: "August 8, 2018", endTime: "August 10, 2018", allDay: false, id: "173248"}

8: {title: "🚗 Recogida 10:30:00 En Valencia", startTime: "August 8, 2018", endTime: "August 9, 2018", allDay: false, id: "183265"}

**Comment by SkinnyA** [comment]
error solved.
Instead of creating a variable called eventos which will contain all the api data, it must be named as eventSource

**Comment by twinssbc** [comment]
@SkinnyA You can change the variable name, but also need to change the binding in HTML.
