### ISSUE TITLE
Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/UI002/WebstormProjects/untitled/arvix-ober/arvix-ober-html/app-ionic2/mynewapp/node_modules/.0.2.3@ionic2-calendar/calendar.ngfactory.js'

### ISSUE THREAD

**Issue by Gtanxingwen** [twinssbc/Ionic2-Calendar#51]
run in safrie 10.0.2 i should how to do

**Comment by Gtanxingwen** [comment]
@twinssbc

**Comment by Gtanxingwen** [comment]
Solution: add below lines in main.ts

import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';

**Comment by weitaoyang** [comment]
我也遇到了和你一样的问题
Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\yjbs\node_modules\._ionic2-calendar@0.2.4@ionic2-calendar\calendar.ngfactory.js'

我是以产品形式运行 ionic run browser --prod
main.ts里也加入那4个导入了，结果就报这个错，请问你如何运行的？
如果以dev模式运行，是正常的。

**Comment by weitaoyang** [comment]
@Gtanxingwen

**Comment by twinssbc** [comment]
@weitaoyang Could you confirm if you added below lines in main.prod.ts instead of main.ts?
```
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';
```

**Comment by weitaoyang** [comment]
Thank you for your reply, I have seen you write on the GitHub, has added a few of these in main.ts. But still report the error. @Gtanxingwen @twinssbc

**Comment by twinssbc** [comment]
@weitaoyang  Did you add these lines in main.ts or main.prod.ts?

**Comment by weitaoyang** [comment]
Yes, I did
I added these lines in main.ts
No file main.prod.ts
@twinssbc

**Comment by twinssbc** [comment]
@weitaoyang Does this path actually exist?
E:\yjbs\node_modules._ionic2-calendar@0.2.4@ionic2-calendar\calendar.ngfactory.js

**Comment by weitaoyang** [comment]
Non-existent

**Comment by weitaoyang** [comment]
Non-existent @twinssbc

**Comment by weitaoyang** [comment]
@twinssbc 
path is exist
calendar.ngfactory.js Non-existent

**Comment by twinssbc** [comment]
@weitaoyang That's weird, because there's only calendar.ngfactory.ts, not sure why it tries to find calendar.ngfactory.js.
I tried your command in my desktop, it works.
May I know which Ionic version are you using? And what's your Ionic cli version?
In theory, when you use Ionic to start a new project, it should have both main.ts and main.prod.ts.
Maybe you could try using a brand new project?

**Comment by weitaoyang** [comment]
@twinssbc 
Thanks again
it's ok!
I add config in tsconfig.json

"files": [
    "node_modules/._ionic2-calendar@0.2.4@ionic2-calendar/index.d.ts"
  ]

and not add below lines in main.ts

import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';

**Comment by twinssbc** [comment]
Ah ok, I guess you config your tsconfig to load JS be default.

**Comment by weitaoyang** [comment]
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  },

  "files": [
    "node_modules/._ionic2-calendar@0.2.4@ionic2-calendar/index.d.ts"
  ]
}
