### ISSUE TITLE
How to load events from an api

### ISSUE THREAD

**Issue by SkinnyA** [twinssbc/Ionic2-Calendar#510]
Hello
My question is how can i load events from an api because i dont know how to implement it. 
I have an object filled with data from the api but i cant see nothing in the agenda

`import { Component, OnInit, ViewChild, Inject, LOCALE_ID } from '@angular/core';
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { AlertController } from '@ionic/angular';
import { formatDate } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import * as moment from 'moment';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit{

  events = [];
  viewTitle= '';

  calendar = {
    mode: 'month',
    currentDate: new Date(),
  }

  event = {
    title: '',
    desc: '',
    startTime: '',
    endTime: '',
    allDay: false
  };
  

  @ViewChild(CalendarComponent ,{static: false}) myCal: CalendarComponent;

  constructor(private alrtCrtl: AlertController, @Inject(LOCALE_ID) private locale: string, private http: HttpClient) {}

  ngOnInit(){
    this.getData();
  }

  getData(){
    this.http.get('http://localhost:3000/Pedidos').subscribe((resp: any) => {

      resp.forEach((entrada) =>{

        let eventSource;
        eventSource = {
          title: entrada.Asunto,
          startTime: entrada.FechaInicio,
          endTime: entrada.FechaFin,
          allDay: false,
          tipo: entrada.Tipo,
          idPedido: entrada.idPedido,
        }

        if(eventSource.tipo === "Aereo"){
          eventSource = {
            title: '✈️ ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('YYYY-MM-DD'),
            endTime: moment(entrada.FechaFin).format('YYYY-MM-DD'),
            allDay: false,
            idPedido: entrada.idPedido,
          }
        }

        if(eventSource.tipo === "Hotel"){
          eventSource = {
            title: '🏨 ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('YYYY-MM-DD'),
            endTime: moment(entrada.FechaFin).format('YYYY-MM-DD'),
            allDay: false,
            idPedido: entrada.idPedido,
          }
        }

        if(eventSource.tipo === "Coche"){
          eventSource = {
            title: '🚗 ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('YYYY-MM-DD'),
            endTime: moment(entrada.FechaFin).format('YYYY-MM-DD'),
            allDay: false,
            idPedido: entrada.idPedido,
          }
        }

        if(eventSource.tipo === "Tren"){
          eventSource = {
            title: '🚆 ' + entrada.Asunto,
            startTime: moment(entrada.FechaInicio).format('YYYY-MM-DD'),
            endTime: moment(entrada.FechaFin).format('YYYY-MM-DD'),
            allDay: false,
            idPedido: entrada.idPedido,
          }
        }

        this.events.push(eventSource);
        this.myCal.loadEvents();
        // this.resetEvent();
        console.log(eventSource);
 
      });console.log(this.events);
      

    });
  }

  

  // resetEvent(){
  //   this.event = {
  //     title: '',
  //     desc: '',
  //     startTime: new Date().toISOString(),
  //     endTime: new Date().toISOString(),
  //     allDay: false
  //   };
  // }

  back(){
    var swiper = document.querySelector('.swiper-container')['swiper'];
    swiper.slidePrev();
  }

  next(){
    var swiper = document.querySelector('.swiper-container')['swiper'];
    swiper.slideNext();
  }

  // async onEventSelected(event){
  //   let start = formatDate(event.startTime, 'medium', this.locale);
  //   let end = formatDate(event.endTime, 'medium', this.locale);

  //   const alert = await this.alrtCrtl.create({
  //     header: event.title,
  //     subHeader: event.desc,
  //     message: 'From: ' + start + '<br><br>To: ' + end,
  //     buttons: ['OK']
  //   });
  //   alert.present();
  // }

  onEventSelected = (event) =>{
    console.log(event[0].title);
  }

  onViewTitleChanged(title){
    this.viewTitle = title;
  }

 
  // onTimeSelected(ev)
  // {
  //   let selected = new Date(ev.selectedTime);
  //   this.event.startTime = selected.toISOString();
  //   selected.setHours(selected.getHours() + 1);
  //   this.event.endTime = (selected.toISOString());
  // }
}
`
This is what my api returns but somehow i cant load it into the calendar agenda

{title: "✈️ 07:05 Madrid -- > Valencia", startTime: "2018-09-14", endTime: "2018-09-14", allDay: false, idPedido: "183266"}title: "✈️ 07:05 Madrid -- > Valencia"startTime: "2018-09-14"endTime: "2018-09-14"allDay: falseidPedido: "183266"
{title: "✈️ 07:05 Madrid -- > Valencia", startTime: "2018-10-13", endTime: "2018-10-13", allDay: false, idPedido: "183268"}
{title: "✈️ 19:35 Valencia -- > Madrid", startTime: "2018-09-12", endTime: "2018-09-12", allDay: false, idPedido: "183266"}
{title: "✈️ 12:05 Valencia -- > Madrid", startTime: "2018-10-10", endTime: "2018-10-10", allDay: false, idPedido: "183268"}
{title: "🏨 Hotel Restel Test Prueba", startTime: "2018-09-12", endTime: "2018-09-16", allDay: false, idPedido: "183262"}
{title: "🏨 Hotel Restel Test Prueba", startTime: "2018-09-12", endTime: "2018-09-15", allDay: false, idPedido: "183267"}
{title: "🏨 Nh Valencia Center", startTime: "2018-05-22", endTime: "2018-05-23", allDay: false, idPedido: "183268"}
{title: "🚗 Recogida 10:30:00 En Valencia", startTime: "2018-08-08", endTime: "2018-08-10", allDay: false, idPedido: "173248"}
{title: "🚗 Recogida 10:30:00 En Valencia", startTime: "2018-08-08", endTime: "2018-08-09", allDay: false, idPedido: "183265"}
{title: "🚆 12:40 Madrid Puerta De Atocha --> Valencia Joaquín Sorolla", startTime: "2018-07-30", endTime: "2018-07-30", allDay: false, idPedido: "183269"}

**Comment by stevenjose** [comment]
import { Component, OnInit, ViewChild } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { CalendarComponent } from 'ionic2-calendar/calendar';

//RxJs
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import { MensajeroProvider } from '../../providers';

/**
 * Generated class for the PagesConsultarHorarioPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: "page-pages-consultar-horario",
  templateUrl: "pages-consultar-horario.html"
})
export class PagesConsultarHorarioPage implements OnInit {
  event = {
    title: '',
    desc: '',
    startTime: new Date().toISOString,
    endTime: new Date().toISOString,
    allDay: false
  }

  minDate = new Date().toISOString();

  eventSource = [];
  eventSource2 = [];
  calendar = {
    mode: "month",
    currentDate: new Date()
  };
  viewTitle = "Horarios Públicos";
  @ViewChild(CalendarComponent) myCal: CalendarComponent;


  constructor(public navCtrl: NavController, public navParams: NavParams, public mensajeroApi: MensajeroProvider) {
    //this.addEvent();
  }

  ngOnInit(): void {
    this.loadEvents();
    var minDateS = new Date().toISOString();
    var fecha = new Date();
    //console.log(minDateS + ' ' + fecha);
    console.log('Formato fecha ', fecha);
  }

  addEvent() { 
    this.event = {
      title: 'pr',
      desc: '',
      startTime: new Date().toISOString,
      endTime: new Date().toISOString,
      allDay : false
    }

    this.eventSource2.push(this.event);
    this.eventSource.push(this.event);
    //this.myCal.loadEvents();
    console.log(this.event);
    console.log(this.eventSource2);
  }

  ionViewDidLoad() {
    console.log("ionViewDidLoad PagesConsultarHorarioPage");
  }

  onEventSelected() {}

  onViewTitleChanged() {}

  onTimeSelected() {}

  changueMode(mode) { 
    this.calendar.mode = mode;
  }

  loadEvents() {
    this.eventSource = [
      {
        "title": "Semana Santa Pre-Cargado",
        "startTime": new Date('2020-03-17T11:20:30Z'),
        "endTime": new Date(),
        "allDay": false
      }
    ]
   this.mensajeroApi.getHorariosPublicos()
      .then((res: any) => { 
        console.log(res.data);
        let fechaBD = "";
        let str = "";
        let strHoraInicio = "";
        let strHoraFin = "";
        let horaInicioBD = "";
        let horaFinBD = "";

        for (let data of res.data) {
          str = data.fecha;
          strHoraInicio = data.horaInicio;
          strHoraFin = data.horaFin;
          
          if (str != null) {
            fechaBD = str.substring(0, 11);
          }

          if (strHoraInicio != null) {
            horaInicioBD = strHoraInicio.substring(11, 19);
          }
          if (strHoraFin != null) {

            horaFinBD = strHoraFin.substring(11, 19);

          }

          this.eventSource.push({
            "title": data.titulo,
            "startTime": new Date(fechaBD+horaInicioBD),
            "endTime":   new Date(fechaBD+horaFinBD),
            "allDay": false
          });
        }

        
        console.log(this.eventSource);
        this.myCal.loadEvents();
      }).catch((err) => {
        console.error(err)
  });
    //this.myCal.loadEvents();
  }
  
}

**Comment by stevenjose** [comment]
Saludos te comparto el código funcional para que te fije que te falta. startTime y endTime son de tipo date asignarlo new Date(tufecha)
Formato de fecha = 2020-03-17T11:20:30Z

**Comment by stevenjose** [comment]
Guíate por la function loadEvents() que se cargan datos por defectos.

**Comment by SkinnyA** [comment]
Muchas gracias amigo! El problema de que no cargaba datos era porque estaba formateando la fecha en un formato erróneo. Al hacer el new Date(mifecha) ya lo cogió bien y me pintó los datos de la base de datos en el calendario.
Gracias por tu ayuda, un saludo!
