### ISSUE TITLE
Jalaali Calendar Support

### ISSUE THREAD

**Issue by manisi** [twinssbc/Ionic2-Calendar#512]
hi 
how to use calandar in  jalali calendar (shamsi or persian calendar)?
Thanks

**Comment by twinssbc** [comment]
@manisi Sorry, this calendar control doesn't support jalali calendar.

**Comment by manisi** [comment]
ُThanks.

‫‪twinssbc‬‏ <‪notifications@github.com‬‏> در تاریخ یکشنبه ۲۲ مارس ۲۰۲۰
ساعت ۱۱:۱۴ نوشت:‬
