### ISSUE TITLE
Date Time Format while using Firebase Realtime Database

### ISSUE THREAD

**Issue by kartiksolanki** [twinssbc/Ionic2-Calendar#514]
Hi, 
I am using ionic2-calender to retrieve events from firebase realtime database. What is the best format to save data and time inside firebase realtime database such that my eventsource from calendar app can read it properly?

**Comment by twinssbc** [comment]
@kartiksolanki The calendar only cares about the element in EventSource array has the necessary field in order to display it. You can store your data and time in whatever format you feel convenient in the database, just do the proper conversation when filling the EventSource array.

**Comment by louiemiranda** [comment]
Hi @twinssbc UTC will only be used `allDay` is `true`?

Then, the rest of the time should just be regular timezone time and not UTC? Am I correct?

Thank you
