### ISSUE TITLE
Cannot read property 'getTime' of undefined

### ISSUE THREAD

**Issue by kartiksolanki** [twinssbc/Ionic2-Calendar#516]
My Code is: 

this.newsService.getCalendar().valueChanges().subscribe(events=> { 
        this.eventSource = [];
        events.forEach(element => { 
          let tmp = [];
          tmp.push({ 
            title: element["title"], 
            startTime: new Date(element["startTime"]),
            endTime: new Date(element["endTime"]),
            allDay: element["allDay"]
          }); 
          console.log(tmp)
          this.eventSource.push(tmp);
        })
    },(err) =>{ 
        console.log(err) 
    })

Console.log of tmp is: 

title: "Kartik Solanki without AllDay"
startTime: Fri Mar 27 2020 14:00:00 GMT-0400 (Eastern Daylight Time)
endTime: Fri Mar 27 2020 16:00:00 GMT-0400 (Eastern Daylight Time) 
allDay: false

I am getting below error: 

Cannot read property 'getTime' of undefined
    at MonthViewComponent.push../node_modules/ionic2-calendar/monthview.js.MonthViewComponent.onDataLoaded (monthview.js:250)
    at MonthViewComponent.push../node_modules/ionic2-calendar/monthview.js.MonthViewComponent.ngOnChanges (monthview.js:99)
    at checkAndUpdateDirectiveDynamic (core.js:22118)
    at checkAndUpdateNodeDynamic (core.js:23379)
    at checkAndUpdateNode (core.js:23328)
    at debugCheckAndUpdateNode (core.js:23959)
    at debugCheckDirectivesFn (core.js:23919)
    at Object.eval [as updateDirectives] (CalendarComponent.html:68)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:23911)
    at checkAndUpdateView (core.js:23307)

Any idea what am I doing wrong here?

**Comment by twinssbc** [comment]
@kartiksolanki The tmp is already an array, but you push the whole array to eventSource, which makes it a nested array. Actually you just need to assign tmp to eventSource.

**Comment by kartiksolanki** [comment]
Perfect. I made it work by assigning tmp instead of pushing. Thanks a lot @twinssbc for developing this wonderful component. I have one more question:
How do I store startTime and endTime values in the database for ALLDAY events? 
My database structure looks like below in case of allday=false:

1-
 -- allday: false
 -- startTime:  "2020-03-27T17:00"
 -- endTime: "2020-03-27T18:00"
 -- title: "Demo Event with AllDay False"

So in case of AllDay = true, what should be my structure for startTime and endTime have?

**Comment by twinssbc** [comment]
@kartiksolanki I suggest you always store the numeric value (epoch time) into your database, instead of plain text date string. It's because, "2020-03-27T17:00", this string doesn't contain time zone information. What if the user who publishes the event and the user who consumes the event in different time zone?

For the allDay event, you need to use Date.UTC as below. So that no matter, the user in which timezone, it can always display the all day event on the current date.
var startTime = new Date(Date.UTC(2014, 4, 8));

To get the numeric value of a date, just call startTime.getTime()

**Comment by kartiksolanki** [comment]
@twinssbc : Even after converting datetime to epoch, I am NOT able to display AllDay = 
"true" events. Below is how my events look like:

- 1 - 
 ---- title: "Epoch with 6 to 9"
 ---- startTime: 1585418400000 //Saturday, March 28, 2020 6:00:00 PM
 ---- endTime: 1585429200000 //Saturday, March 28, 2020 9:00:00 PM
 ---- allDay: false
- 2 - 
 ---- title: "AllDay Event"
 ---- startTime: 1585353600000 //Saturday, March 28, 2020 12:00:00 AM
 ---- endTime: 1585429200000 //Sunday, March 29, 2020 12:00:00 AM
 ---- allDay: false

The first event with set time is displayed inside my app but the all day events is not displaying. Any idea what am I doing wrong here?

**Comment by twinssbc** [comment]
@kartiksolanki The startTime and endTime still needs to accept a Date object. So once you got the epoch value from your database, you need to convert it into Date object. For example,
startTime: new Date(1585418400000)

**Comment by kartiksolanki** [comment]
@twinssbc : Perfect. Silly me, I kept startTime: new Date(1585418400000) inside allday=false condition while storing in tmp. I removed the condition and it worked. Thank a lot @twinssbc for the help. I appreciate that.
