### ISSUE TITLE
Can't bind to 'loop' since it isn't a known property of 'ion-slides'.

### ISSUE THREAD

**Issue by pxlxinzhao** [twinssbc/Ionic2-Calendar#52]
I follow Readme trying to put calendar in my app. I end up with following error: 

polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'loop' since it isn't a known property of 'ion-slides'.
1. If 'ion-slides' is an Angular component and it has 'loop' input, then verify that it is part of this module.
2. If 'ion-slides' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        <div>
            <ion-slides #monthSlider [ERROR ->][loop]="true" (ionSlideDidChange)="onSlideChanged()">
                <ion-slide>
                   "): MonthViewComponent@2:37 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'loop' since it isn't a known property of 'ion-slides'.

I do check the slides api that says loop is an input property:

loop	 -- boolean --	If true, continuously loop from the last slide to the first slide.

My ionic version is 2.1.4
What's happening ? Please help, thank you!

**Comment by twinssbc** [comment]
Could you provide your code snippet that using the calendar control?

**Comment by pxlxinzhao** [comment]
Well, i cleaned up my project, reinstall the dependencies and somehow it worked.
Thanks for the response anyway.
