### ISSUE TITLE
Not able to complile in Android

### ISSUE THREAD

**Issue by kartiksolanki** [twinssbc/Ionic2-Calendar#522]
Hi I am trying to compile my code in Android and it is giving be following error:

[ng] ERROR in node_modules/ionic2-calendar/calendar.d.ts(153,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ionic2-calendar/calendar.d.ts(154,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ionic2-calendar/calendar.d.ts(219,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng] node_modules/ionic2-calendar/calendar.d.ts(220,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] node_modules/ionic2-calendar/calendar.module.d.ts(10,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDefWithMeta'.
[ng] node_modules/ionic2-calendar/calendar.module.d.ts(11,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDef'.
[ng] node_modules/ionic2-calendar/calendar.service.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
[ng] node_modules/ionic2-calendar/calendar.service.d.ts(25,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng] node_modules/ionic2-calendar/calendar.service.d.ts(26,22): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDef'.
[ng] node_modules/ionic2-calendar/dayview.d.ts(77,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng] node_modules/ionic2-calendar/dayview.d.ts(78,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] node_modules/ionic2-calendar/init-position-scroll.d.ts(15,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng] node_modules/ionic2-calendar/init-position-scroll.d.ts(16,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] node_modules/ionic2-calendar/monthview.d.ts(67,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng] node_modules/ionic2-calendar/monthview.d.ts(68,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] node_modules/ionic2-calendar/weekview.d.ts(85,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
[ng] node_modules/ionic2-calendar/weekview.d.ts(86,21): error TS2694: Namespace '"/Users/wearesas/Desktop/dragon-ridge/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDefWithMeta'.
[ng] 
[ng] ℹ ｢wdm｣: Failed to compile.

Any idea what is going wrong???

**Comment by twinssbc** [comment]
could you provide the version of angular, ionic and ionic2-calendar package you are using? each calendar version has different dependency of angular and ionic.

**Comment by kartiksolanki** [comment]
Never mind, I solved it. It was a version mismatch only. Thanks a lot.
