### ISSUE TITLE
Ionic Issue

### ISSUE THREAD

**Issue by Tintedshadows** [twinssbc/Ionic2-Calendar#523]
I am trying to install and use this calendar in my app but it fails to compile.

./node_modules/ionic2-calendar/calendar.js 21:4-16
"export 'ɵɵadvance' (imported as 'i0') was not found in '@angular/core'

[ng] ERROR in ./node_modules/ionic2-calendar/dayview.js 718:31-45
[ng] "export 'ɵɵloadQuery' (imported as 'i0') was not found in '@angular/core'

Module page:

import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    EventsPageRoutingModule,
    NgCalendarModule
  ],
  declarations: [EventsPage]
})
export class EventsPageModule {}

Project Info:

Ionic:

   Ionic CLI                     : 6.1.0
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.2
   @capacitor/core : 1.5.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 7 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.5.0
   npm    : 6.9.0

**Comment by twinssbc** [comment]
could you provide the version of angular and ionic2-calendar package you are using? Each calendar version has different dependency of angular and ionic.

**Comment by Tintedshadows** [comment]
I believe the angular is 8.2.14 

 "dependencies": {
        "@angular/common": "~8.2.14",
        "@angular/core": "~8.2.14",
        "@angular/forms": "~8.2.14",
        "@angular/platform-browser": "~8.2.14",
        "@angular/platform-browser-dynamic": "~8.2.14",

I am using the most up-to-date version of the calendar.

**Comment by marcelo-ansaldi-baltazar** [comment]
My app also fails to compile, it throws the following error:

[ng] ERROR in node_modules/ionic2-calendar/calendar.d.ts:153:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 153     get currentDate(): Date;
[ng]             ~~~~~~~~~~~
[ng] node_modules/ionic2-calendar/calendar.d.ts:154:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 154     set currentDate(val: Date);

project info: 
"@angular/common": "~8.1.2",
"@angular/core": "~8.1.2",
"@angular/forms": "~8.1.2",
"@angular/platform-browser": "~8.1.2",
"@angular/platform-browser-dynamic": "~8.1.2",

I'm also using the latest version of the calendar.

![image](https://user-images.githubusercontent.com/26723811/79308666-0246af80-7ec7-11ea-9b35-84a096db58c0.png)
 maybe this helps

**Comment by twinssbc** [comment]
the latest version of calendar requires Angular 9. could u try version 0.5.8 or 0.5.9?

**Comment by Tintedshadows** [comment]
Okay that fixed my issue. 

Thanks for your help!
