### ISSUE TITLE
Issue with Highlighted Day on Click

### ISSUE THREAD

**Issue by rawadymario** [twinssbc/Ionic2-Calendar#526]
When I click on any day in the month of April, the day before is highlighted.
All the other months are working fine, this bug is only happening in the month of April.

It seems that the bug is related to the user timezone because my Current timezone is **+2 Beirut**. When I changed my timezone to **+1 Madrid**, the bug was fixed (The day I click in April is highlighted), but when I changed my timezone back to **+2 Beirut**, the bug reappeared (The day before the day I click in April is highlighted).

Did this happen to anyone else? If yes, how to solve it? Thx

Please check this video explaining my issue:
https://drive.google.com/file/d/1W_AdhGRv0dV7-c3B_fpCH94dziHM8Yuv/view?usp=sharing

**Comment by twinssbc** [comment]
@rawadymario I tried testing the calendar in +1 and +2 timezone, seems no such behavior. Maybe you could provide more details about what happened when you select a date in the calendar? Maybe you could show how do you declare the calendar in your HTML code, and what kind of logic you add in the component ts file.

**Comment by rawadymario** [comment]
@twinssbc When u set the calendar for +2 was it in a Middle Eastern Area (Try Beirut +2)

[Image 1](https://drive.google.com/open?id=18rZVvRXZCko7XQWVRjwcJrCOq--rVk1x)
[Image 2](https://drive.google.com/open?id=1vRSqbCwyKUEVkfYHaurLPOpuZD6bTVMO)
[Image 3](https://drive.google.com/open?id=1e1e8qO079_HQjmhrYBAEfL45wlJhg_nc)

- In the first image, I am calling the Module and Importing it in my Module File
- In the second image, I am defining the Calendar Element in my HTML File
- In the third image, I am defining the calendar object in my Controller File

**Comment by twinssbc** [comment]
. @rawadymario So I can see currentDate is bound to the this.selectedDate. How do you calculate the selectedDate?

**Comment by rawadymario** [comment]
@twinssbc 
`public selectedDate = new Date();
calendar = {
    mode: 'month',
    currentDate: this.selectedDate
  }`

**Comment by rawadymario** [comment]
I debugged the code and figured out where the issue is.
In file **monthview.js** > Line **229** > Function **MonthViewComponent.prototype.getRange**

I used **console.log** on **startDate** and **endDate**. Because of Daylight Saving, the Month of April is returning **startDate = Sun Mar 29 2020 01:00:00 GMT+0300 (Eastern European Summer Time)** and **endDate = Sun May 10 2020 01:00:00 GMT+0300 (Eastern European Summer Time)**.

Because the Time/Hour is 01 instead of 00, this is causing the issue.

[Image 01](https://drive.google.com/file/d/1D9R8BhxL7BTfuc9YZ9hw0d4gySX5Sz2b/view)
[Image 02](https://drive.google.com/file/d/1bLIKcc6uYM5X4q4iYFlz0rtNPtHcwfYt/view)
[Image 03](https://drive.google.com/file/d/1j5Imjao1wCXPmvc4ry7zraleFiNz9_Ik/view)

Image 01: Timezone Set to **+1 Vienna** (No Errors)
Image 02: Timezone Set to **+2 Athens** (No Errors)
Image 03: Timezone Set to **+2 Beirut** (U can see that the Hour is 01 instead of 00 and this is causing the Error when Clicking)

The error is happening in Rendering the Table when clicking on a Cell and calling the function **getHighlightClass(views[0].dates[row*7+col])**. When the conflict is happening, the col value is calculated wrong and thus the highlighted cell will be wrong!

Hope this Helps.

**Comment by twinssbc** [comment]
@rawadymario OK, I'm able to reproduce it, will take a look how to fix it.

**Comment by rawadymario** [comment]
@twinssbc Thank you!
Honestly, I tried to fix it but I was not able to.

**Comment by twinssbc** [comment]
@rawadymario I refactored the code to solve the DST problem. Could you try the latest version?

**Comment by rawadymario** [comment]
@twinssbc It looks like the bug was fixed. Thank you!
