### ISSUE TITLE
Uncaught ReferenceError: __importDefault is not defined

### ISSUE THREAD

**Issue by chewCCS** [twinssbc/Ionic2-Calendar#528]
Hi,

I installed the calendar with updated package.json settings and managed to compile with ionic serve. However it ran a blank screen, and under Chrome Developer Tools, there are errors:

Uncaught ReferenceError: __importDefault is not defined
    at Module../src/app/app.component.ts (app.component.ts:9)
    at __webpack_require__ (bootstrap:84)
    at Module../src/app/app.module.ts (app.component.ts:12)
    at __webpack_require__ (bootstrap:84)
    at Module../src/main.ts (environment.ts:16)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:84)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)

1) I only imported the NgCalendarModule in home.module.ts, and added <calendar> directive in the home.page.html. Everything else in the src folder stays untouched.

2) my package json is shown below:

{
  "name": "calendar",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^9.1.2",
    "@angular/core": "^9.1.2",
    "@angular/forms": "^9.1.2",
    "@angular/platform-browser": "^9.1.2",
    "@angular/platform-browser-dynamic": "^9.1.2",
    "@angular/router": "^9.1.2",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "core-js": "^2.5.4",
    "ionic2-calendar": "^0.6.2",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "^9.1.1",
    "@angular/compiler": "^9.1.1",
    "@angular/compiler-cli": "^9.1.1",
    "@angular/language-service": "^9.1.1",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.8.3"
  },
  "description": "An Ionic project"
}

Appreciate your help, pls.

**Comment by twinssbc** [comment]
@chewCCS you probably need to upgrade @angular-devkit/build-angular.
Check this question:
https://stackoverflow.com/questions/57662571/uncaught-referenceerror-importdefault-is-not-defined

**Comment by chewCCS** [comment]
@twinssbc thanks. Changed it to
"@angular-devkit/build-angular": "^0.901.1",

I now have an issue of 
"Uncaught (in promise) Could not establish connection. Receiving end does not exist. (content.js:2)"

As well as a bunch of 

ERROR TypeError: Cannot read property 'mode' of undefined
    at HomePage_Template (template.html:21)
    at executeTemplate (core.js:12046)
    at refreshView (core.js:11893)
...

and

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'mode' of undefined
TypeError: Cannot read property 'mode' of undefined
    at HomePage_Template (template.html:21)
    at executeTemplate (core.js:12046)
...

By the way, I only added 2 things after creating the project:
1. included the NgCalendarModule in home.module.ts
2. added the calendar directive in home.page.html

I suppose just adding these two items I can run "ionic serve" and see a basic calendar, right?

**Comment by chewCCS** [comment]
@twinssbc hi boss. I used the scripts provided by Simon Grimm from Devdactic and I am now able to see a calendar (finally :3)

There are still some errors like such:
ERROR TypeError: ctx.onViewTitleChanged is not a function
    at HomePage_Template_calendar_onTitleChanged_29_listener (template.html:75)
    at executeListenerWithErrorHandling (core.js:21888)
.....

Will continue to work on it...

Thanks a lot!

**Comment by twinssbc** [comment]
@chewCCS It seems you want to bind the onViewTitleChanged function in your HTML. Do you have this onViewTitleChanged method implemented in your component?

**Comment by twinssbc** [comment]
@chewCCS It seems you want to bind the onViewTitleChanged function in your HTML. Do you have this onViewTitleChanged method implemented in your component?

**Comment by chewCCS** [comment]
@twinssbc Hi, sorry for the late response. I've just gotten back to the code. Apparently quite a few functions not up yet, including the back and forth buttons, etc. Will work on those next.
