### ISSUE TITLE
Issue on load multi event on the same day

### ISSUE THREAD

**Issue by mariosanz97** [twinssbc/Ionic2-Calendar#529]
-My event has one attribute, 'approved' can be true or false, in case the event is false the bg color is red, and in case true, green.

In case the day has two events, (one aproved and one not), the color would be the last one event.

-But my problem is when i want to load the events with my own template, the event duplicate my div.

Any idea about how to solve it? Thx a lot.

My template:

                <ng-template #template let-view="view" let-row="row" let-col="col">
                        <div *ngIf="view.dates[row*7+col].events == ''">{{view.dates[row*7+col].label}}</div>
                        <div *ngFor="let obj of view.dates[row*7+col].events" style="padding: 0%;">
                           <div *ngIf="obj.aproved == true" [ngStyle]="{'background-color': 'green'}">{{view.dates[row*7+col].label}}</div>
                           <div *ngIf="obj.aproved == false" [ngStyle]="{'background-color': 'red'}">{{view.dates[row*7+col].label}}</div>
                        </div>
                </ng-template>

And it works, but when the day has multi-event, its look like this:

![Captura2](https://user-images.githubusercontent.com/15921818/79779133-24628680-833a-11ea-9ab1-4c9dc2e31eef.PNG)

**Comment by twinssbc** [comment]
@Mariosanz97 You may want to try ngClass to apply the custom css class based on your event property. Then add the styles for different css class.

**Comment by mariosanz97** [comment]
Solved, Thanks so much.

I did this.


                <ng-template #template let-view="view" let-row="row" let-col="col">
                        <div  *ngIf="view.dates[row*7+col].events == ''">{{view.dates[row*7+col].label}}</div>
                        <div [ngClass]="view.dates[row*7+col].events[0].aproved ? 'withEvent' : 'withNoEvent'" 
                                *ngIf="view.dates[row*7+col].events != ''" style="padding:8px;">{{view.dates[row*7+col].label}}</div>
               </ng-template>


![Captura2](https://user-images.githubusercontent.com/15921818/80006038-a1ba0280-84c4-11ea-81ee-e8a21cc1911f.PNG)
