### ISSUE TITLE
Request for some assistance in changing or adding few things

### ISSUE THREAD

**Issue by satyagupta** [twinssbc/Ionic2-Calendar#53]
Thanks for creating such a fantastic component. 

Its almost perfect but just few things i would like to know.

here is how the calendar that we want to look like https://gyazo.com/8b2d678ec14e97a9919326b126cef99b

to make it look like this we just need to know following things.

1. How do we make the calendar border less? 
2. Right now to change month and we have to swipe which is good but what if we want to change months why clicks? I read that you have used ion-slide for this but is this slide api accessible from outside? 
3. Want the remove the event listing that you have at bottom of the calendar how do we do that?

**Comment by twinssbc** [comment]
@satyagupta 
1. You can override css to set the border to none
2. You can change the currentCalendarDate to the date in previous and next month in your button click callback
3. You can set showEventDetail option to false

**Comment by satyagupta** [comment]
Excellent, i will try these and update you on Monday :)

**Comment by satyagupta** [comment]
Thanks, all your suggestion worked beautifully :) thank you so much for this
