### ISSUE TITLE
Is it possible to hide the calendar after choosing a day?

### ISSUE THREAD

**Issue by TitoSniberb** [twinssbc/Ionic2-Calendar#534]
This is my current calendar:

![image](https://user-images.githubusercontent.com/44405296/80593289-3a023b00-8a21-11ea-8c18-70f47bbab3e2.png)

I wanted to know if it was possible to hide it like this after selecting a day:
![image](https://user-images.githubusercontent.com/44405296/80593470-96655a80-8a21-11ea-99f5-46c866e660a9.png)

Is this possible? Thanks in advance!

**Comment by twinssbc** [comment]
@aldimirprincipal This calendar doesn't support such feature.
