### ISSUE TITLE
Current day row and column style

### ISSUE THREAD

**Issue by benmesza** [twinssbc/Ionic2-Calendar#536]
Hello!

I would like to ask, how can I set a different background color for the row and column of the current day in the month view?
Thank you in advance for your reply.

All the best!

**Comment by twinssbc** [comment]
@benmesza Do you want to just change current day cell? Or entire row and column?

**Comment by benmesza** [comment]
@twinssbc Entire row and column.

**Comment by twinssbc** [comment]
@benmesza This is not supported. The closest solution (but not perfect) I can think out is you could insert "fake" event on each day of entire row the column. Then do some customization thing to set different background for these fake events.

**Comment by benmesza** [comment]
@twinssbc Thanks your help!
