### ISSUE TITLE
Remove All Day row

### ISSUE THREAD

**Issue by TanguyMrtn** [twinssbc/Ionic2-Calendar#537]
Hello,

I'd like to know if it's possible to remove the whole All Day feature ? (at least the All Day line from the Week and Day Views, and also in Month View).

Regards !

TanguyMrtn

**Comment by TanguyMrtn** [comment]
I find an Issue with the answer, thanks

**Comment by shalini-github** [comment]
how to remove the all day row

**Comment by twinssbc** [comment]
@shalini-github you could try the approaches in https://github.com/twinssbc/Ionic2-Calendar/issues/54
