### ISSUE TITLE
All Day Feature

### ISSUE THREAD

**Issue by TanguyMrtn** [twinssbc/Ionic2-Calendar#538]
Hello,

I'd like to know if it was possible to display all the All Day events without the need of scrolling ? 

Regards,

TanguyMrtn

**Comment by twinssbc** [comment]
@TanguyMrtn Yes, you can increase the height by overriding css.
You could increase the height of weekview-allday-table (currently is 50px) and increase the margin-top of weekview-normal-event-container (currently is 87px). But one thing to note that, no matter what value do you increase, you can't predict how many all day events need to be displayed. So scrolling probably is still needed, if they exceeds the all day event container height.

**Comment by TanguyMrtn** [comment]
Ok so I'll keep the scrolable feature, thanks for your answer anyway 🥇
