### ISSUE TITLE
Change event color based on a value in weekview

### ISSUE THREAD

**Issue by TanguyMrtn** [twinssbc/Ionic2-Calendar#539]
Hello, 

I'd like to change the color of an event, based on a value (if the value is 1 then color is red, if 2 then green etc...) on weekview, I shall use a template or override css there ? Without changing the other parameters (width etc)

Thanks

**Comment by twinssbc** [comment]
@TanguyMrtn You need to use the custom template as you have some logic based on a field value. You could use weekviewNormalEventTemplate option, use ngClass to bind some event field to different css classes. Then set different color on these css classes. More information can be found in README.

**Comment by TanguyMrtn** [comment]
Thanks a lot for your answer ! 👍
