### ISSUE TITLE
Hide all day event row

### ISSUE THREAD

**Issue by viklele** [twinssbc/Ionic2-Calendar#54]
Thanks for this nice component.

I have started trying it out to check its suitability for our requirements.

In my application, we don't have a need and support for all day event. I was wondering if there is a way to hide the all day event row in day view? 

Regards,
Vikram

**Comment by twinssbc** [comment]
@viklele You can achieve this requirement by overriding the css styles.
Set the display of weekview-allday-table to none and set the margin-top of weekview-normal-event-container accordingly.

**Comment by viklele** [comment]
Thanks. I will try this approach.

Regards,
Vikram

**Comment by viklele** [comment]
Thanks it worked - with a small obvious change in your suggestion.

I had to change styles of dayview-allday-table and dayview-normal-event-container.

Regards,
Vikram

**Comment by viklele** [comment]
How do I get the correct margin-top setting for **weekview-normal-event-container** after setting display: none for **weekview-allday-table**?

**Comment by twinssbc** [comment]
margin-top: 37px;

**Comment by en-sevilla** [comment]
Thanks, it worked for me:

`    .weekview-allday-table{
        display: none;
    }
        
    .weekview-normal-event-container{
        margin-top: 37px;
    }`

**Comment by newzhongdan** [comment]
for a dayview

`      .dayview-allday-label{
        display: none;
      }
      .dayview-normal-event-container{
       margin-top: 0px;
     }
     .dayview-allday-content-wrapper{
       height: 0px;
     }`

**Comment by karouAhmed** [comment]
@twinssbc I overriding the scss styles like this  but it not working for me !!!
![Annotation 2019-05-22 013516](https://user-images.githubusercontent.com/39932045/58139456-f9a81380-7c3a-11e9-8f80-c572e5268a6d.png)

**Comment by twinssbc** [comment]
@karouAhmed Do you add your styles to component scss file or global.scss file? Could you try global.scss file? Also could you use Developer Tools to inspect the DOM element to see if the styles are applied to the element or not?

**Comment by karouAhmed** [comment]
@twinssbc it work now when i put it in global.scss ,thanks :)

**Comment by SackeyDavid** [comment]
Hello @twinssbc. Thanks for your work. 

How do I show only tr with monthview-selected class? That is, only week with the current day for month view.

**Comment by twinssbc** [comment]
@SackeyDavid You could certainly use css to achieve that. But the month view itself doesn't support navigating between weeks. When you swipe left or right, the whole month changes.

**Comment by SackeyDavid** [comment]
@twinssbc i tried this 

`.monthview-datetable tr:not(td:not([class])) {
    display: none;
}
`
to access the rows other than the current day row which do not have any css class. But it didn't work.
Basically I was trying to **hide html `table tr` if it does not contain a `td` with specified classname using css.**

The current day row has a `td` with `monthview-selected` and `monthview-current` class names where as the other rows and their `td`(s) do not have any class name.

The css `:has()` pseudo selector is still experimental according to browser compatibility section on
https://developer.mozilla.org/en-US/docs/Web/CSS/:has and doesn't work so far for me.

I guess you have I better approach to the problem for me. Kindly suggest how to achieve this using css.

Thank you very much.

**Comment by twinssbc** [comment]
@SackeyDavid As I explained, even if you could make the month view only show one week, you won't be able to navigate from week to week in the month view, it is navigated per month. So before you spend a lot of effort on sorting out the CSS trick, maybe you could first think about if that could fit your requirement?

**Comment by SackeyDavid** [comment]
Okay, thanks @twinssbc.

**Comment by SagarJHedau** [comment]
@twinssbc is there a way I can hide no events

**Comment by twinssbc** [comment]
@SagarJHedau If you want to hide the event detail section, you can set **showEventDetail** option to false.

**Comment by shanthan25** [comment]
It is work for me

```
.event-detail-container {
  display: none;
}
```

**Comment by aminaalsindi** [comment]
![image](https://user-images.githubusercontent.com/88036620/137628887-f6c012f9-d7cc-4137-b3f9-69e823f5369b.png)
The all day event did disappear but there is still an empty space, what can I do to remove it?
this is my css:

 .weekview-allday-table{
        display: none;
    }
        
.weekview-normal-event-container{
   margin-top: 37px;
}

**Comment by Saifsliti** [comment]
.weekview-normal-event-container{
margin-top: 37px !important;
}
