### ISSUE TITLE
If 'calendar' is an Angular component, then verify that it is part of this module

### ISSUE THREAD

**Issue by mikeaka** [twinssbc/Ionic2-Calendar#542]
Hello guys,
I create a new project and try to implement ionic2-calendar and i have this issue?.

[Angular]
'calendar' is not a known element:

If 'calendar' is an Angular component, then verify that it is part of this module.
To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

i am using page module so i add the calendar module into page module instead of app module
but no luck.

**Home.module.ts**
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { FormsModule } from '@angular/forms';
import { HomePage } from './home.page';

import { HomePageRoutingModule } from './home-routing.module';
import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  imports: [
    NgCalendarModule,
    CommonModule,
    FormsModule,
    IonicModule,
    HomePageRoutingModule
  ],
  declarations: [HomePage]
})
export class HomePageModule {}

**package.json**
{
  "name": "calendar",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "cordova": "^9.0.0",
    "ionic2-calendar": "^0.6.4",
    "rxjs": "^6.5.5",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler": "~9.1.6",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  },
  "description": "An Ionic project"
}

**IONIC INFO**
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\makanzore\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
Thank you very much for your help

**Comment by twinssbc** [comment]
@mikeaka Where do you use the calendar element in your html file? This error indicates that the Angular doesn't recognize the calendar element. You need to make sure the NgCalendarModule is properly set up. I see you Home.module.ts has related code, but probably not linked with your HTML file?

**Comment by mikeaka** [comment]
@twinssbc thank you very much for your reply below the HTML, NgCalendarModule is imported in home.module.ts

**Home.page.html**
<ion-content>
  <calendar
    [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate"
    step="30">
  </calendar>
</ion-content>

Did i do something wrong ?

Thank you.

**Comment by mikeaka** [comment]
<ion-content>
  <calendar
    [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate"
    step="30">
  </calendar>

</ion-content>

**Comment by twinssbc** [comment]
@mikeaka I didn't spot anything wrong. Although what's the version of @ionic/angular are you using? I saw the dependency is ^5.0.0, could you upgrade it to ^5.1.0?

**Comment by chewCCS** [comment]
Hi,

I also have a similar problem, though probably in a different situation. Do I need to create a new post or can I seek your assistance from here?

1. I created a new project with tabs template
2. renamed Tab1, Tab2, Tab3 into Calendar, Inbox and Notepad
3. ported the package.json file from my previous successful ionic-calendar project
4. copied the home.page.ts, home.page.html and home.module.ts into calendar.page.ts, calendar.page.html and calendar.module.ts, respectively

I got the same "if calendar is an angular component" warning in my VSCode editor, in my calendar.page.html.

In the original calendar.page.ts, angular/core was imported via this call:
"import { Component } from '@angular/core';"
However, for ionic-calendar, I have been using
"import { Component, ViewChild, OnInit, Inject, LOCALE_ID } from '@angular/core';"

When I run ionic serve, I get tonnes of errors related to "Cannot find module '@angular/core'"

Are these situations related? Do I need to import NgCalendarModule in tabs.module.ts and app.module.ts as well?

**Comment by mikeaka** [comment]
@twinssbc i have upgrade but still the same issue. 
in Chrome i have this ERROR TypeError: Cannot read property 'dayHeaders' of undefined
in HTML still not recognized.
it is a fresh project.
i used Ionic start calendar blank --type=angular to start the project

**Comment by chewCCS** [comment]
@twinssbc hi, please ignore my feedback. Apparently I was forgetful enough to miss out running npm ionic-calendar in the first place :P the whole thing works now. Thanks!

**Comment by SatyaShodhaka** [comment]
Hey i've the same issue If 'calendar' is an Angular component, then verify that it is part of this module

**Comment by twinssbc** [comment]
@SatyaShodhaka Could you try the latest version 0.6.5?
