### ISSUE TITLE
Calendar is not a known element and Can't Bind to XXX since it is not a known property

### ISSUE THREAD

**Issue by ustadji** [twinssbc/Ionic2-Calendar#545]
Hey twinssbc,
Love the work you're doing!   Getting these errors after upgrading Ionic and Angular to latest:
'calendar' is not a known element:
1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
Can't bind to 'eventSource' since it isn't a known property of 'calendar'.
{several other binding errors as well}

Everything was fine up until the upgrade.  Here are my versions:
"@angular/core": "^9.1.4",
"@ionic/angular": "^5.1.0"
"ionic2-calendar": "^0.6.4",
"typescript": "^3.8.3"

I am importing NgCalendarModule within my page module.  Funny thing is everything seems to work but just getting errors within vscode.  Could it be Typescript?  
Thank you!
Ustad

**Comment by SansDK** [comment]
This seems to be fixed in version 0.6.5.
