### ISSUE TITLE
event is not loaded in remote query mode

### ISSUE THREAD

**Issue by playgamemy** [twinssbc/Ionic2-Calendar#548]
Expected: In remote query mode, events are loaded once and displayed when the calendar DOM instantiate, and persist to be displayed between range/mode change. Events are reload and re-render automatically when the binded eventSource variable is reassigned to new value (not push).

Issue: event is not loaded unless loadEvent() is called manually, both at the start and everytime the mode/range is changed (no persistence/auto load at start).  Reassigning binded eventSource or the instance eventSource do not trigger the events being loaded (confirm the instance eventSource is populated with events). All tested using mock data instead of truly using a remote API. local query mode work as expected.

ionic2-calendar version: 0.5.8/0.5.10 (both tested, cannot update calendar to 0.6.x because angular is 8.x)

Code attached below, following almost like in demo.

home.page.html
```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-menu-button></ion-menu-button>
    </ion-buttons>
    <ion-title>{{viewTitle}}</ion-title>
    <ion-buttons slot="end">
      <ion-button [disabled]="isToday" (click)="today()">Today</ion-button>
      <ion-button (click)="changeMode('month')">M</ion-button>
      <ion-button (click)="changeMode('week')">W</ion-button>
      <ion-button (click)="changeMode('day')">D</ion-button>
      <ion-button (click)="loadEvents()">Load Events</ion-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content>
  <calendar [eventSource]="eventSource"
    [calendarMode]="calendar.mode"
    [queryMode]="calendar.queryMode"
    [currentDate]="calendar.currentDate"
    (onCurrentDateChanged)="onCurrentDateChanged($event)"
    (onRangeChanged)="updateDateRange($event)"
    (onEventSelected)="onEventSelected($event)"
    (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)"
    step="30">
  </calendar>
  <ion-fab vertical="bottom" horizontal="end" slot="fixed">
    <ion-fab-button (click)="openAddClassModal()">
      <ion-icon name="add"></ion-icon>
    </ion-fab-button>
  </ion-fab>
</ion-content>
```
home.page.ts
```
import { Component, OnInit, ViewChild } from '@angular/core';
import { ClassService, Class } from "../../services/class.service";
import { LoggingService, Logger } from "ionic-logging-service";
import { ModalController } from '@ionic/angular';
import { AddClassPage } from "../../modals/add-class/add-class.page";
import { CalendarComponent, IEvent } from "ionic2-calendar/calendar";

@Component({
  selector: 'app-home',
  templateUrl: './home.page.html',
  styleUrls: ['./home.page.scss'],
})
export class HomePage implements OnInit {
  @ViewChild(CalendarComponent, null) myCalendar:CalendarComponent;
  startDate:Date;
  endDate:Date;
  isToday: Boolean;
  eventSource: Class[] = [];
  logger: Logger;
  viewTitle:string;
  calendar = {
    currentDate: new Date,
    mode: "month",
    queryMode: "remote"    
  }
  sampleEvent:Class[];

  constructor(private classService: ClassService, private loggingService:LoggingService, private modalCtrl:ModalController) {
    this.logger = this.loggingService.getLogger("App.HomePage");
    var endTime = new Date(Date.now());
    endTime.setHours(endTime.getHours() + 1);
    
    this.sampleEvent = [{
      title: "test class",
      classId:"test class ID",
      startTime: new Date(Date.now()),
      endTime: endTime,
      allDay:false,
      room:[{
        roomId: "test room ID",
        roomName:"test room name"
      },],
      staffs:[{
        staffId: "test staff ID",
        staffName: "Nick Li"
      }],
    }]
  }

  ngOnInit() {
    this.eventSource = this.sampleEvent;
  }
  
  onViewTitleChanged(title){
    this.viewTitle = title;
  }

  changeMode(mode) {
    this.calendar.mode = mode;
  }
  
  today() {
    this.calendar.currentDate = new Date();
  }
  
  loadEvents(){
    this.myCalendar.eventSource = [];
    this.myCalendar.eventSource = this.sampleEvent as IEvent[];
    this.myCalendar.loadEvents(); //no event is loaded into view if this is commented out
  }

  async openAddClassModal(){
    const now = new Date(Date.now());
    var startTime = new Date(this.myCalendar.currentDate);
    startTime.setHours(now.getHours(),now.getMinutes(),now.getSeconds(),0);
    var endTime = new Date(startTime);
    endTime.setHours(startTime.getHours()+1);
    this.logger.entry("openAddClassModal");
    var cls = {
      startTime: startTime,
      endTime: endTime
    } as Class;
    const modal = await this.modalCtrl.create({
      component: AddClassPage,
      componentProps:{
        cls:cls
      }
    })
    return await modal.present();
  }

  updateEvents(){
    this.logger.entry("updateEvents");
    this.classService.getClasses(this.startDate, this.endDate).valueChanges({idField:'classId'}).subscribe((res) =>{
      this.eventSource = res as Class[];
    })
    this.logger.exit("updateEvents");
  }

  updateDateRange(ev: { startTime: Date, endTime: Date }){
    this.logger.entry("updateDateRange");
    this.eventSource = this.sampleEvent; 
    this.myCalendar.loadEvents(); //no events loaded into view without this line, and event is only rendered after range change, but not immediately after calendar initiated or right after mode change, even if event is in date range
    this.logger.exit("updateDateRange");
  }
}

```

**Comment by twinssbc** [comment]
@playgamemy I don't quite understand your test code. In updateDateRange method, this.eventSource is always assigned same sampleEvent variable which is initialized in the constructor. How do you expect any update when range is changed?

**Comment by playgamemy** [comment]
> @playgamemy I don't quite understand your test code. In updateDateRange method, this.eventSource is always assigned same sampleEvent variable which is initialized in the constructor. How do you expect any update when range is changed?

This is test code, I have not put in the logic to grab the data from the firestore backend yet. I am just using that sampleEvent mocking that the eventSource is indeed updated.
The problem I have is unless instance method loadEvents() is called, no events will be loaded into view for ALL triggers in remote querymode.
I thought the eventSource is watched such once new value is assigned it will automatically called loadEvents(), and the event should also be loaded/rendered/persist between mode change

**Comment by twinssbc** [comment]
@playgamemy yes, that's how it should work. But your test code seems not assign new value to eventSource.

**Comment by playgamemy** [comment]
> @playgamemy yes, that's how it should work. But your test code seems not assign new value to eventSource.

Sorry was in another project and did not get to reply promptly.
Maybe it is my misunderstanding on "assign new value to eventSource".
In readme you explicitly said not to use Array.push() as it does not assign new value and need to assign new value in order to trigger the loadEvent()

if  `this.eventSource = this.sampleEvent; ` 
&
```
this.myCalendar.eventSource = [];
this.myCalendar.eventSource = this.sampleEvent as IEvent[];
```
are both not counted as assign new value, what is counted as assign new value? can you give me an example code?

**Comment by playgamemy** [comment]
Thank you for your response previously. I have done a bit more digging and realise
`this.eventSource = this.sampleEvent;`
is assigning the eventSource to sampleEvent by reference instead of by value. Which is probably why you said "not assign new value to eventSource"
This problem would have been solved if it is truly calling a function/API where an array is returned as value.

Just to proof the conept I have also change the testing code to
`this.eventSource = this.sampleEvent.slice();`
which the slice function return the array as value, leading to eventSource is assign by value instead of by reference, and now the library is behaving as expected in the remote query mode.

Note: in remote query mode the updateDateRange() is called initially, so no need to initialise the eventSource in ngOnInit()
