### ISSUE TITLE
[HELP] Show month only

### ISSUE THREAD

**Issue by danbn-100295** [twinssbc/Ionic2-Calendar#552]
Hi guys
I want display month and year only like this.
<img width="339" alt="85198548-9ee85c00-b313-11ea-9af1-d4bf893b40d0" src="https://user-images.githubusercontent.com/61224981/85201508-20e37f80-b32a-11ea-871d-88398ffa8b07.png">
How can i implement it ? 
Thanks all !

**Comment by twinssbc** [comment]
@danbn-100295 this calendar is mainly for displaying events in a calendar look and feel. It doesn't support such year/month selection.

**Comment by danbn-100295** [comment]
@twinssbc  Ok.thanks so much
