### ISSUE TITLE
Disable sliding action

### ISSUE THREAD

**Issue by viklele** [twinssbc/Ionic2-Calendar#56]
Sorry for posting so many question - I am just trying out the component - and while it seems to meet my needs, I am not able to figure out how to do certain things in the component.

Is there a way to disable the sliding action?

In my scenario, I want to keep the user on a particular day and don't want him to slide out to a different date under some conditions.

Regards,
Vikram

**Comment by twinssbc** [comment]
@viklele Currently this calendar control doesn't expose the option to disable sliding on demand. The underlying slides control has such option, so it's possible to expose it.
But I wonder if disabling sliding is the best interact way, as slides is the base of this control. If you want user to stay on certain to do some operation, maybe you could let user navigate to another page when user selects a day?

**Comment by viklele** [comment]
Thanks for your prompt response.

I am looking to display appointments of "Today" in one of the views, but
want to reuse the same page in another context where user can freely
navigate to appointments of other days.

Now while on Today view, navigation to other dates is not desirable.

Regards,
Vikram
