### ISSUE TITLE
Wrong layout after navigating to other page first

### ISSUE THREAD

**Issue by tubauwe** [twinssbc/Ionic2-Calendar#567]
I've added a page with ionic2-calendar in my pwa. It's working well, but after navigating to another page and back to calendar again, the layout becomes wrong:

Here the wanted layout:
<img width="428" alt="ok" src="https://user-images.githubusercontent.com/5855116/92466784-ec68bc80-f1d0-11ea-9b27-ead9c9247e6b.png">

Here the wrong layout:
<img width="426" alt="not-ok" src="https://user-images.githubusercontent.com/5855116/92466868-086c5e00-f1d1-11ea-9a54-df83623b2778.png">

I think the problem are some of my css-styles of the other page, but I don't know what of them. Do you know how to set the correct css-styles for ionic2-calendar again? Thanks in advance for your help!

**Comment by twinssbc** [comment]
@tubauwe I'm afraid your question is too general. As I don't know what css styles causing the layout conflict. Could you use the browser developer toolbar to inspect the DOM element, see if any calendar element has some of your css class applied? And then try not to set your css class too generic?

**Comment by tubauwe** [comment]
Thanks for your help! It's solved now.
