### ISSUE TITLE
when i am installing it is shows the error below

### ISSUE THREAD

**Issue by gsaikrishna32** [twinssbc/Ionic2-Calendar#57]
![capture](https://cloud.githubusercontent.com/assets/25900718/23124415/eb7cf552-f792-11e6-9da4-c1950b16b8e2.PNG)

**Comment by twinssbc** [comment]
You need to run below command 
```
npm install -g typings
```

**Comment by gsaikrishna32** [comment]
i had tried the above command and run, by using the link  https://m.youtube.com/watch?v=UVOV2hTkkvE i had tried.And i am getting the below error
![capture2](https://cloud.githubusercontent.com/assets/25900718/23152661/6d334f10-f829-11e6-8dc1-5cda23b57a3e.PNG)
