### ISSUE TITLE
headers in month view with incorrect language

### ISSUE THREAD

**Issue by ErnestoLopez** [twinssbc/Ionic2-Calendar#578]
Good Morning,

I use ionic2-calendar in different sections of my app, but in one of them the day headers in the "month" view appear in English, while in the rest they appear as I am interested in "Spanish".

I've been looking and trying different things but can't find the reason.

Does anyone think of what I can try?

Thank you,

Ernesto

**Comment by twinssbc** [comment]
@ErnestoLopez how do you set Spanish? could you compare if there's any difference between the place you got English?

**Comment by ErnestoLopez** [comment]
buff !!

sorry to bother you with something so obvious.

I've added

calendar = {...
, locale: 'es-ES'
...
}

AND

[locale] = "calendar.locale"

in the definition of each ionic2-calendar and now it is seen in Spanish.

thank you !!
