### ISSUE TITLE
'calendar' is not a known element: 1. If 'calendar' is an Angular component, then verify that it is part of this module.

### ISSUE THREAD

**Issue by rs-prakash** [twinssbc/Ionic2-Calendar#579]
Hi,

I have used "ionic2-calendar": "^0.4.6", in my ionic app. But when i try to deploy i got an Error like,
typescript error
            Can't bind to 'eventSource' since it isn't a known property of 'calendar'. (" </ion-grid> <calendar [ERROR
            ->][eventSource]="eventSource" [calendarMode]="calendar.mode" [currentDate]="calendar.currentDat")
  typescript error
            Can't bind to 'calendarMode' since it isn't a known property of 'calendar'. (" <calendar
            [eventSource]="eventSource" [ERROR ->][calendarMode]="calendar.mode" [currentDate]="calendar.currentDate"
            (onEventSelected)="onEven")
typescript error
            Can't bind to 'currentDate' since it isn't a known property of 'calendar'. (" [eventSource]="eventSource"
            [calendarMode]="calendar.mode" [ERROR ->][currentDate]="calendar.currentDate"
            (onEventSelected)="onEventSelected($event)" (onTitleCha")
typescript error
            'calendar' is not a known element: 1. If 'calendar' is an Angular component, then verify that it is part of
            this module. 2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            </ion-row> </ion-grid> [ERROR ->]<calendar [eventSource]="eventSource" [calendarMode]="calendar.mode" ")
As per few discussions done in this Github i have tried all the possbilities but still it hrows same error. Any one help me to fix this.

Thank you

**Comment by twinssbc** [comment]
@rs-prakash This error is most likely caused by that the related module hasn't been imported.
Did you import the calendar module in your app module file or page module file?

```
import { NgCalendarModule  } from 'ionic2-calendar';
```

**Comment by rs-prakash** [comment]
@twinssbc Thanks for your response, I have added import in both section: app.module.ts & Calendar Page module.ts files too. 
In html file I have mentioned like this,

<calendar 
    [(eventSource)]="eventSource"
    [calendarMode]="calendar.mode"
    [currentDate]="calendar.currentDate"
    (onEventSelected)="onEventSelected($event)" 
    (onTitleChanged)="onViewTitleChanged($event)"
    (onTimeSelected)="onTimeSelected($event)"
     step="30"
     class="calendar">
</calendar> 

If I have used anything wrong, please share with me. Sorry I have noticed your response today only.

**Comment by twinssbc** [comment]
@rs-prakash In this case, could you double check if the calendar is really downloaded into your npm folder? Also could you provide your package.json, especially the ionic version and angular version you are using?

**Comment by rs-prakash** [comment]
@twinssbc In node_modules folder contains ionic2-calendar folder.
In Package.Json,

"@angular/core": "5.2.11",
"@ionic-native/core": "4.20.0",
"ionic-angular": "^3.9.10",
"ionic2-calendar": "^0.4.6",

I hope I have given proper information as you have asked

**Comment by rs-prakash** [comment]
@twinssbc when I run this app using ionic serve its working fine, When I have run this command " ionic cordova build android" its creating apk file there is no erros. Now I am trying to upload the apk file in Playstore for that purpose I have tried to use this command "ionic cordova build android --prod --release" in that time I have faced an issue.

**Comment by LCDBLUE** [comment]
I am getting the same error on prod build otherwise its working without error.
@rs-prakash did u find a solution for this??

**Comment by pixunen** [comment]
I had the same issue and couldn't find any resolution. Fixed mine by adding `import { NgCalendarModule  } from 'ionic2-calendar';` to **app.module.ts** and then to `providers: [NgCalendarModule]`

**Comment by TayYeeTeng** [comment]
Hello! I had the same issue and fixed it using the solution provided in this [link](https://github.com/twinssbc/Ionic2-Calendar/issues/267). Hope it helps!
