### ISSUE TITLE
passing title with different key to eventSource

### ISSUE THREAD

**Issue by severus1990** [twinssbc/Ionic2-Calendar#58]
Hi,

Now we are passing the title of an event to the calendar as "title". Is it possible to change this to some other key ?
**title**: 'Event - ' + i,
startTime: startTime,
endTime: endTime,
allDay: false

I am consuming a web service data and want to directly pass the data to eventSource. But the title part is having a different key. eg "eventName"

Please advice on how to proceed.

**Comment by twinssbc** [comment]
Yes, you can use different key, then use customized template to consume your own field.

**Comment by severus1990** [comment]
@twinssbc Can you please elaborate on customized template? Where should i do the changes to make title as eventName so that i can feed the eventSource with below parameters:

**eventName
startTime
endTime
allDay**

**Comment by twinssbc** [comment]
@severus1990 Take a look at the **View Customization Option** section in README.
Let's say you want to display eventName as title in the weekview normal event, the code snippet is like below:
```
<template #template let-displayEvent="displayEvent">
    <div class="calendar-event-inner">{{displayEvent.event.eventName}}</div>
</template>

<calendar ... [weekviewNormalEventTemplate]=“template”></calendar>

```
