### ISSUE TITLE
Week and Day tabs not loading events

### ISSUE THREAD

**Issue by joeldacuma** [twinssbc/Ionic2-Calendar#581]
Angular: 9.1.6
Ionic-angular: 5.0.0

Hi,

I am having some issues on loading my events when using moment.js  for the week and day tab as they are not showing in the page.

dateformat Object:
{date: 2020-12-29,
  startTime: 19:40:19,
endTime: 21:40:19,
title: 'Event 1'
}

retrieve event:
      events.map(arr => {
        const startTime = new Date(moment(`${arr.date} ${arr.startTime}`).toDate());
        const endTime = new Date(moment(`${arr.date} ${arr.startTime}`).toDate());
        _eventSource.push({ title: arr.title, startTime: startTime, endTime: endTime, allDay: false });
      });

      this.eventSource = _eventSource;

**Comment by twinssbc** [comment]
@joeldacuma It seems you set the event start time and end time exactly the same?

**Comment by joeldacuma** [comment]
> @joeldacuma It seems you set the event start time and end time exactly the same?

@twinssbc they are different values in my sample object.

startTime: 19:40:19,
endTime: 21:40:19

**Comment by twinssbc** [comment]
what's the type of 19:40:19? The start time and end time only accepts a JavaScript Date object.  Also your retrieve event code sets start time and end time the same value.

**Comment by joeldacuma** [comment]
Fix my code there something with the format returned by moment.js.
