### ISSUE TITLE
Unable to change bottom part (list view) of the calendar

### ISSUE THREAD

**Issue by Tusharbalar** [twinssbc/Ionic2-Calendar#59]
I am able to customize the calendar but I am unable to access the list of the events in month view event template.
Is there any way to **customized** or add buttons in the event list item. Also is there any inbuilt method to **edit or delete** events dynamically.

**Comment by twinssbc** [comment]
@Tusharbalar You can use monthviewEventDetailTemplate to customize the event list.
There's no build-in method to edit/delete events, you just need to modify the eventSource array.
