### ISSUE TITLE
How to slide on the item where the events are listed so as to add an edit/delete button

### ISSUE THREAD

**Issue by febymathews** [twinssbc/Ionic2-Calendar#596]
Hi I want to know where to place the edit delete button so that i can modify individual events.Like i would like to slide the individual event to add the edit/delete button.Like how do that both in the view way and coddewise.Like the codewise would trigger the onEventSelected().How do i implement the logic for the edit/delete if edit/delete buttons are clicked.

**Comment by twinssbc** [comment]
@febymathews I think that's your own design decision. My recommendation would be when onEventSelected is triggered, the user will enter into an event detail page. In that page, you can have edit and delete button.

**Comment by febymathews** [comment]
Is there a way i can access the ion-list where the events are listed from the code

**Comment by twinssbc** [comment]
@febymathews What do you mean access the ion-list? The Angular view update is driven by the model update. Normally you don't need to access the element in view, instead you should change the model behind the scene.

**Comment by febymathews** [comment]
Thanks a lot for your help.Your repo is really great and has been of very great help to me
