### ISSUE TITLE
'nl-NL' as locale is not recognized

### ISSUE THREAD

**Issue by JanDa-ma** [twinssbc/Ionic2-Calendar#601]
I want to have the days in the monthview in dutch. When I set 'nl-NL' as locale, my calendar disappears. How can I change the dayheaders in monthview?
 ```
 calendar = {
    mode: 'month',
    startingDayMonth: 1,
    currentDate: this.currentDate,
    locale: 'nl-NL',
  };
```

**Comment by twinssbc** [comment]
@JanDa-ma 
You need to manually import the locale file. Below is the supported list.
https://github.com/angular/angular/tree/master/packages/common/locales

It seems nl-NL is not in the list, below is the sample code to import nl-AW.
import '@angular/common/locales/global/nl-AW';

**Comment by JanDa-ma** [comment]
I had two problems. As you said, nl-NL is not supported and I also forgot to import the method.
