### ISSUE TITLE
[Feature request] Go to a day view by clicking a day header in a week view

### ISSUE THREAD

**Issue by MaximS** [twinssbc/Ionic2-Calendar#608]
It would be convenient for a user to jump to a day view by clicking a day in header of a week view.
Or `onWeekHeaderClick(ev: {day: Date})` event would be enough.

The same could be done for weeks in a month view if the month view would ever be extended with a left column showing week numbers. This way a user could click a week number and jump to a corresponing week in a week view. (Or event for this)

**Comment by twinssbc** [comment]
@MaximS DayHeaderSelected event is exposed in version 0.6.8. Feel free to give a try.
