### ISSUE TITLE
[Docs issue] onTimeSelected doc states that it works for month view only while it works in all modes

### ISSUE THREAD

**Issue by MaximS** [twinssbc/Ionic2-Calendar#610]
- onTimeSelected

The callback function triggered when a date is selected `in the monthview`.
The ev parameter contains two fields, selectedTime and events, if there's no event at the selected time, the events field will be either undefined or empty array.

_"in the monthview"_ is wrong

**Comment by twinssbc** [comment]
@MaximS Fixed README
