### ISSUE TITLE
I can't add ionic2-calendar to my project: ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by ErnestoLopez** [twinssbc/Ionic2-Calendar#616]
Hello,

For a couple of days I could not "serve" the application and I have recreated it from scratch by importing the code little by little.

When I went to include ionic2-calendar in the app I had this problem

  ERESOLVE unable to resolve dependency tree

I have tried to create a blank ionic project and add the calendar but the same thing happens.

How can i install ionic2-calendar?

Attached a screenshot and the logs.

I add a screenshot with my current ionic version.

Greetings,

Ernesto

![error adding ionic2-calendar](https://user-images.githubusercontent.com/4478968/123083608-7f04e000-d420-11eb-9b21-46148a63305b.jpg)

[2021-06-23T10_38_46_741Z-debug.log](https://github.com/twinssbc/Ionic2-Calendar/files/6701169/2021-06-23T10_38_46_741Z-debug.log)

[eresolve-report.txt](https://github.com/twinssbc/Ionic2-Calendar/files/6701186/eresolve-report.txt)

![image](https://user-images.githubusercontent.com/4478968/123086275-824d9b00-d423-11eb-84b4-ce7fb46bf4af.png)

**Comment by twinssbc** [comment]
@ErnestoLopez try this
```
npm install ionic2-calendar --save --legacy-peer-deps
```

**Comment by twinssbc** [comment]
@ErnestoLopez I also updated the tslib dependency to 2.0 in 0.6.9 version. Feel free to give a try.

**Comment by ErnestoLopez** [comment]
Hi,

It works in a blank project, I think it will works in production app too.

My first attempt was 
"npm install ionic2-calendar --save"

without
"--legacy-peer-deps"

and I've no error.

Thanks a lot,

Ernesto
