### ISSUE TITLE
Selecting other dates

### ISSUE THREAD

**Issue by ece4afe** [twinssbc/Ionic2-Calendar#62]
It is better if we select other dates on say current or next month or so, there should be no "mark with green" yet as if the user already selected a date already, but actually he has not yet selected. In other words, no "green mark" yet should be found for a particular day

**Comment by twinssbc** [comment]
@ece4afe Do you mean you want a feature that the date is not automatically selected, only selected when user click that date?

**Comment by ece4afe** [comment]
Exactly..

--------------------------------------------
On Sat, 2/25/17, twinssbc <notifications@github.com> wrote:

 Subject: Re: [twinssbc/Ionic2-Calendar] Selecting other dates (#62)
 To: "twinssbc/Ionic2-Calendar" <Ionic2-Calendar@noreply.github.com>
 Cc: "ece4afe" <ece4afe@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Saturday, February 25, 2017, 12:48 AM
 
 @ece4afe Do you mean
 you want a feature that the date is not automatically
 selected, only selected when user click that date?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by twinssbc** [comment]
@ece4afe I added this feature in version 0.2.4. Feel free to have a try.
