### ISSUE TITLE
Insert tag tappable for remove delay when click on specific day in month calendar

### ISSUE THREAD

**Issue by filippodicostanzo** [twinssbc/Ionic2-Calendar#63]
Advice to add a tappable tag in a monthview.js in all <td> generated by *ngFor

 <td *ngFor="let col of [0,1,2,3,4,5,6]" tappable>

for remove the delay when someone click on the specific td for select a day

**Comment by twinssbc** [comment]
@filippodicostanzo Thanks for the suggestion. I have added this attribute in version 0.2.4. Feel free to have a try.

**Comment by filippodicostanzo** [comment]
thank you for your work,
this plugin is incredible, many thanks :)
