### ISSUE TITLE
[Question] Compatible versions

### ISSUE THREAD

**Issue by marticrespi** [twinssbc/Ionic2-Calendar#64]
Hi @twinssbc ,

I have version 0.2.1 installed with angular 2.2.1 and ionic rc5. With 0.2.3 version is possible upgrade to ionic 2.1.0 or is not tested?

Many thanks!

**Comment by twinssbc** [comment]
@marticrespi Yes, version 0.2.1 is compatible to 2.1.0.
I have just released version 0.2.4 and increased the dependency to Ionic 2.1.0 in the package.json.
Feel free to have a try.

**Comment by marticrespi** [comment]
Perfect @twinssbc , works like a charm! Many thanks for your hard job!

**Comment by marticrespi** [comment]
Hi @twinssbc , I have a little problem. My calendar shows in english again, I lost my spanish configuration. I have tried to use LOCALE_ID in app.module.ts with 'es-ES' and doesn't work. Can you check it?

Thanks!

**Comment by twinssbc** [comment]
Yes, thats expected. Before that, the localization is not fully supported, for example, the hour column in the weekview. Now the new version is localized by the LOCALE_ID. The side effect is the user has to specify the locale explicitly. You can also use 'undefined', it will automatically use the language setting of the device, but different browser may have different extent of the support.
