### ISSUE TITLE
How do I display Forward and Backward arrows

### ISSUE THREAD

**Issue by seatechdev** [twinssbc/Ionic2-Calendar#644]
I have been trying to figure out how do I show the forward and backward arrows on the calendar to navigate to the next or previous, month, week or day.   Slider works fine but not very intuitive without any guide.

**Comment by seatechdev** [comment]
Never mind.  Decided to create next and prev functions and stick them on a toolbar.  Thanks!

**Comment by twinssbc** [comment]
The calendar component doesn't have built-in forward and backward arrow. It exposes the Instance method to slide to next and previous time range. How to navigate the calendar depends on your own use case.

**Comment by seatechdev** [comment]
Thanks!  I would recommend adding your comments to the documentation.  It is great to have flexibility as you have described.
