### ISSUE TITLE
Differentiating days with a certain event with different color CSS.

### ISSUE THREAD

**Issue by seatechdev** [twinssbc/Ionic2-Calendar#645]
Use Case:  
John uses an app built with the ionic2-calendar to track his weekday schedule.  Of course, as designed john can see the days with appointments in a specific color and non-appointment days with white color.  However, on some of the days John goes for a soccer practice.  These days can vary every week and can fall either on a weekend and or a weekday.  

Question:
Is there a way to add a third color to highlight those days?  As matter of fact, even have a 4th color for something different.  For example in angular-calendar you can show different color dots.

**Comment by twinssbc** [comment]
@seatechdev  Yes, it's achievable using monthviewDisplayEventTemplate. There's some sample code in below discussion.
https://github.com/twinssbc/Ionic2-Calendar/issues/497#issuecomment-585484628

**Comment by seatechdev** [comment]
This is very helpful.  Thanks!
