### ISSUE TITLE
On MonthView lockSwipeToPrev create a strange behaviour on click to day

### ISSUE THREAD

**Issue by frizzo** [twinssbc/Ionic2-Calendar#648]
Hi,
I've implemented lockSwipeToPrev as explained in the read.me file but I have found a strange behaviour when I try to click on single date to see loaded events (i.e. sometimes do not show events, others it swipe to another month when I click on a month date, etc)

Here my code forked from demo 
https://stackblitz.com/edit/ionic-calendar-demo-1-0-ax3anq

Thanks in advance

**Comment by twinssbc** [comment]
@frizzo I think this is because you were set the hour on ev object. ev is actually the current date inside the calendar, if you manipulate hours, you are basically changing the current date again.
If you just create a new Date object based on ev, then do the manipulation as below, it works.

```
  onCurrentDateChanged(ev: Date) {
    var today = new Date();
    today.setHours(0, 0, 0, 0);

    var eventDate = new Date(ev);
    eventDate.setHours(0, 0, 0, 0);
    this.isToday = today.getTime() === eventDate.getTime();
    console.log('Currently viewed date: ' + eventDate);

    //ADDED CODE FOR lockSwipeToPrev
    if (this.calendar.mode === 'month') {
      if (
        eventDate.getFullYear() < today.getFullYear() ||
        (eventDate.getFullYear() === today.getFullYear() &&
        eventDate.getMonth() <= today.getMonth())
      ) {
        this.lockSwipeToPrev = true;
      } else {
        this.lockSwipeToPrev = false;
      }
    }
  }
```

**Comment by frizzo** [comment]
It works, thanks a lot!
