### ISSUE TITLE
Change week view

### ISSUE THREAD

**Issue by asamyx02** [twinssbc/Ionic2-Calendar#651]
Hi, is it possible to have a weekly view like this?

![Raggruppa 28](https://user-images.githubusercontent.com/97625296/233579067-d84972f1-b03b-420c-8328-3ef251c7e1dd.png)

**Comment by asamyx02** [comment]
![Raggruppa 28](https://user-images.githubusercontent.com/97625296/233579208-7c5a20e6-dd36-4225-bd36-c27bc0596333.png)

**Comment by twinssbc** [comment]
I believe if you use the weekview template, should be able to achieve something like that. You could check "View Customization" for more details.
