### ISSUE TITLE
could you include the version 9.x of swipper in ionic2-calendar ?

### ISSUE THREAD

**Issue by aragon5956** [twinssbc/Ionic2-Calendar#654]
hello i have problem with dependencies , could you include the last version of swipper , the 9.x instead the 8.x version, please?
Cordially

**Comment by twinssbc** [comment]
yes, it's on the todo list.

**Comment by aragon5956** [comment]
thanks you !

**Comment by twinssbc** [comment]
I have published the version 2.1.0, it supports 10.1.0 swiper now.

**Comment by aragon5956** [comment]
thanks you !!:)
