### ISSUE TITLE
Update to ionic 7

### ISSUE THREAD

**Issue by darthnox123** [twinssbc/Ionic2-Calendar#656]
Just updated my project to ionic7 and i know i can't use no more ion-slide now i have to use swiper.js and ionic2-calendar it's  only compatible with swiper 8, but after installing swiper@8.4.6 and following the migration guide on ionic documentation (https://ionicframework.com/docs/angular/slides) it's giving me the following error on app.component.ts:

Error: src/app/app.component.ts:14:26 - error TS2307: Cannot find module 'swiper/element/bundle' or its corresponding type declarations.

[ng] 14 import { register } from 'swiper/element/bundle';

how I can turn around this so i can use swiper and ionic2-calendar?

Note: 

I'm using swiper in this form and not working:

 <swiper-container #swiper class="dashboard-slides">
        <swiper-slide>
....

**Comment by twinssbc** [comment]
I have published version 2.1.0, which supports swiper 10.1.0. Feel free to give a try to see if the problem still exists
