### ISSUE TITLE
Module '"swiper/types"' has no exported member 'SwiperOptions'.

### ISSUE THREAD

**Issue by bebofit** [twinssbc/Ionic2-Calendar#659]
hello I have been trying to upgrade my proejct to latest ionic2-calendar but for some reason it cant detect swiper SwiperOptions.

I am using 
    "@angular/core": "^16.2.4",
    "@ionic/angular": "^7.3.3",
    "swiper": "^10.2.0",
    "ionic2-calendar": "^2.1.0",

**Comment by porterwilcox** [comment]
Ditto

**Comment by porterwilcox** [comment]
Downgrading to v2.0.0 allowed the application to build but the calendar UI doesnt work at all. nothing displays

**Comment by porterwilcox** [comment]
Temporarily removed the type import in the day, week, month files to get this working and used `any`

**Comment by chabaudC** [comment]
Up @twinssbc still the same issue with the 2.2.0
"@angular/core": "^16.2.10",
"@ionic/angular": "^7.5.5",
    "swiper": "^11.0.4",
    "ionic2-calendar": "^2.2.0",

**Comment by twinssbc** [comment]
> Up @twinssbc still the same issue with the 2.2.0 "@angular/core": "^16.2.10", "@ionic/angular": "^7.5.5", "swiper": "^11.0.4", "ionic2-calendar": "^2.2.0",

Although not related, ionic2-calendar 2.2.0 requires angular 17.
I do see SwiperOptions is exported in the swiper/types/index.d.ts.
```
export * from './swiper-options.d.ts';
```
Could you share your entire package.json so that I can test at my side?

**Comment by porterwilcox** [comment]
As of at least v2.4.0 this is no longer an issue
