### ISSUE TITLE
Error while loading from a JSON response

### ISSUE THREAD

**Issue by seatechdev** [twinssbc/Ionic2-Calendar#662]
I get the following error while loading my events in the calendar.  Please look at my json below.  startTime and endTime  are in the format similar to what you have in the sample JSON that comes with this module.   I also tried start and end times with the ISO format but still no success.  Also tried  the following formats for the dates.
```
"startTime":"2023-10-17T20:05:00",
"endTime":"2023-10-18T20:06:00"

```

What am I doing wrong?

ERROR TypeError: eventStartTime.getFullYear is not a function
    at MonthViewComponent.onDataLoaded (vendor.js:111071:53)
    at MonthViewComponent.ngOnChanges (vendor.js:110895:12)
    at MonthViewComponent.rememberChangeHistoryAndInvokeOnChangesHook (vendor.js:55696:10)
    at callHook (vendor.js:56604:12)
    at callHooks (vendor.js:56569:9)
    at executeCheckHooks (vendor.js:56508:3)
 ----
My JSON from the API - 
```
[
    {
        "id": 2,
         "title": "Test Appointment 2",
        "startTime": "new Date(2023,9,15,17,49,0)",
        "endTime": "new Date(2023,9,16,17,49,0)",
        "description": null
    },
    {
        "id": 1,
        "title": "Test Appointment 1",
        "startTime": "new Date(2023,9,14,17,48,0)",
        "endTime": "new Date(2023,9,15,17,48,0)",
        "description": null
    }
]
```

Sample JSON from the the example that actually works - 

```
myData = [
    {
     id: '1',
     title: 'Is it Today?',
     description: 'What is Lorem Ipsum today?',
     startTime: new Date(2023,10,12,20,1,0),
     endTime: new Date(2023,10,12,20,1,0),
     location: 'Nancy Residence'
    },
    {
     id: '2',
     title: 'What is Lorem Ipsum?',
     description: 'What is Lorem Ipsum on 22nd?',
     startTime: new Date(2023,3,22,12,11,11),
     endTime: new Date(2023,3,22,14,11,11),
     location: 'Pete Bar'
   }
];

**Comment by seatechdev** [comment]
This is how I resolved it but I don't think its the most optimum way to do it since a user can have thousands of events over time time.  I had to do this after storing the date and time using the default ion-datetime format.  I am leaving it open so that if the developer of ionic2-Calendar or anyone else has a better suggestion.  Ideally I would like to resolve it at the time of submitting my event instead of getting the payload full of events via my API.   This loop is going to degrade the performance but ti works.  I tried storing the dates by running them through ``` new Date() ``` but that didn't work.
```
                         var i;
                        var countData = res.length;  // res is my api response in the json format
                        for (i = 0; i < countData; i++) {
                         this.eventSource[i].startTime = new Date(this.eventSource[i].startTime);
                         this.eventSource[i].endTime = new Date(this.eventSource[i].endTime);
                        }
```

**Comment by twinssbc** [comment]
The data type and format you store and display are not necessarily the same.
Since there could be different date time format of a string, so the calendar as a generic component can't support every type. So it accepts Date type which is common, and let the backend service to return the response properly.

**Comment by seatechdev** [comment]
Fair enough.   Thank you for your reply.  However, since in this case I am using my own API to generate the JSON (which I am sure lot of developers will be doing), can you please recommend a format e.g. YYYY-MM-DDTHH:MM:SS.000Z that I can store my date string in so that I don't have go through extra processing and the JSON response can work out of the box.

**Comment by twinssbc** [comment]
> Fair enough. Thank you for your reply. However, since in this case I am using my own API to generate the JSON (which I am sure lot of developers will be doing), can you please recommend a format e.g. YYYY-MM-DDTHH:MM:SS.000Z that I can store my date string in so that I don't have go through extra processing and the JSON response can work out of the box.

The calendar doesn't support String format of the startTime and endTime. You have to construct a Date object based on what you stored.

**Comment by seatechdev** [comment]
Thanks!  I handled it from the backend by using a package to manipulate dates.
