### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by eLyrin** [twinssbc/Ionic2-Calendar#668]
Can you add support for Angular 17 please? `^16.0.0` currently blocks ng update

Thanks for your efforts ❤

**Comment by twinssbc** [comment]
I have published a new version 2.2.0 which has dependency on Angular 17. Feel free to give a try.

**Comment by Marius-Romanus** [comment]
Could you also update the ionic7-calendar package to 2.2.0? https://www.npmjs.com/package/ionic7-calendar

Thank you very much!

**Comment by twinssbc** [comment]
published.
