### ISSUE TITLE
Working flow of calendar?

### ISSUE THREAD

**Issue by venubollu** [twinssbc/Ionic2-Calendar#67]
In the calendar.html page you had written many methods like
             `[calendarMode]="calendar.mode"
              [currentDate]="calendar.currentDate"
              [onCurrentDateChanged]="onCurrentDateChanged($event)"
              (onTitleChanged)="onViewTitleChanged($event)"
              (onTimeSelected)="onTimeSelected($event)"` 
   The above code i mentioned is the part of these plugin,but i am not able to understand who it is working on and what function it is triggered when i call?Can you please explain me @twinssbc

**Comment by venubollu** [comment]
`[calendarMode]="calendar.mode"
              [currentDate]="calendar.currentDate"
              [onCurrentDateChanged]="onCurrentDateChanged($event)"
              (onTitleChanged)="onViewTitleChanged($event)"
              (onTimeSelected)="onTimeSelected($event)"`

**Comment by twinssbc** [comment]
@venubollu These methods are all explained in the README.
