### ISSUE TITLE
swiper 11 support

### ISSUE THREAD

**Issue by Marius-Romanus** [twinssbc/Ionic2-Calendar#672]
Hello, it would be great if the library accepted swiper 11, so you don't have to force the installation. I have been testing it in my project and it seems to work without problems.

```
"peerDependencies": {
        "swiper": "^11.0.0"
},
```
https://swiperjs.com/migration-guide-v11

Greetings!

**Comment by twinssbc** [comment]
I have published a new version 2.3.0 which has swiper dependency upgraded to 11.
