### ISSUE TITLE
Unable to install the Ionic7-calendar in ionic 8

### ISSUE THREAD

**Issue by niveditarao27** [twinssbc/Ionic2-Calendar#677]
The Ionic7-calendar doesn't get installed in the latest ionic 8 version , throws a dependency error  
![image](https://github.com/twinssbc/Ionic2-Calendar/assets/100689415/53a90525-34ae-428e-8f26-31ed82917d95)

A sample project to the above mentioned issue 
https://github.com/niveditarao27/ionic8-sample-calendar

**Comment by B-UMA** [comment]
Yes, I got the same error too.

**Comment by Eraldo** [comment]
Same. ;)

**Comment by twinssbc** [comment]
released 2.5.0 version to support Ionic8 and Angular 18

**Comment by twinssbc** [comment]
released 2.5.0 version to support Ionic8 and Angular 18
