### ISSUE TITLE
IntlPolyfill is not defined

### ISSUE THREAD

**Issue by mitob** [twinssbc/Ionic2-Calendar#68]
Hi, 

I'm using ionic 2.0.1. After installing the adding the calendar, I get 'intl' not defined (in your component) while building. After installing intl 1.2.5, I get IntlPolyfill is not defined and the app crushes on start up. Any help?

**Comment by twinssbc** [comment]
@mitob 
According to below documentation, this Intl is a polyfill lib to support Safari 10-.
So if you use this control in a device has old ios (I guess below ios 10), you may need this Intl polyfill.

https://angular.io/docs/ts/latest/guide/browser-support.html
