### ISSUE TITLE
HourParts not working

### ISSUE THREAD

**Issue by rickli1989** [twinssbc/Ionic2-Calendar#69]
Hi, 

In the day view mode, trying to split the the calendar into halfHour unit, but it doesn't work. Checked your source code, it does provide this input. Can you guide me how to use this ?

**Comment by twinssbc** [comment]
@rickli1989 hourParts is an input of day view, but it's not the input of the whole calendar control.
Instead, you could use "step" option.

```
      <calendar [eventSource]="eventSource"
          ...
        step="30">
      </calendar>

```
