### ISSUE TITLE
EXCEPTION: Error in ./CalendarComponent class CalendarComponent - inline template:39:16 caused by: Cannot read property 'getFullYear' of undefined

### ISSUE THREAD

**Issue by christiams** [twinssbc/Ionic2-Calendar#70]
Hello! I'm trying to run `ionic serve` and have this problem:

> EXCEPTION: Error in ./CalendarComponent class CalendarComponent - inline template:39:16 caused by: Cannot read property 'getFullYear' of undefined

I try to import import explicitly below lines in main.prod.ts

```
import { CalendarComponent } from 'ionic2-calendar/calendar';
import { MonthViewComponent } from 'ionic2-calendar/monthview';
import { WeekViewComponent } from 'ionic2-calendar/weekview';
import { DayViewComponent } from 'ionic2-calendar/dayview';
```

> Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: 1.8.6 
ios-sim version: 4.1.1 
OS: OS X El Capitan
Node Version: v7.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002

But same error. Can you help? Thanks

**Comment by christiams** [comment]
I solved

**Comment by ChrisProlls** [comment]
Please post your solution @christiams I have the same problem.

**Comment by christiams** [comment]
My solution was copy paste all the functions from controller. In first instance i copied only some

**Comment by ChrisProlls** [comment]
Thanks. My solution was to affect the current date property.
```
<calendar [currentDate]="currentDate">
</calendar>
```
