### ISSUE TITLE
Customization of monthviewEventDetailTemplate using Ionic 2 Framework

### ISSUE THREAD

**Issue by kkhwee** [twinssbc/Ionic2-Calendar#73]
Hi,

I am using Ionic v2.2.1 and I am trying to customize the month view event details. However since i am using a Http Call to load my eventSource. I am getting a cannot read property "events" of undefined.

This is my Html Page

    <template #template let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel" let-eventSource="eventSource">
      <ion-list>
        <button ion-item *ngFor="let event of selectedDate.ITimeSelected?.events">
          {{ event }}
        </button>
     </ion-list>
    </template>

    <h2>{{viewTitle}}</h2>
    <calendar position [eventSource]="eventSource"
      [calendarMode]="calendar.mode"
      [currentDate]="calendar.currentDate"
      [noEventsLabel]="calendar.noEventsLabel"
      (onCurrectDateChanged)="onCurrentDateChanged($event)"
      (onRangeChanged)="onRangeChanged($event)"
      (onEventSelected)="onEventSelected($event)"
      (onTitleChanged)="onViewTitleChanged($event)"
      (onTimeSelected)="onTimeSelected($event)"
      [monthviewEventDetailTemplate]="template"
    step="30">
    </calendar>

**Comment by twinssbc** [comment]
@kkhwee 
I think the real problem is the ITimeSelected property is undefined.
Below code snippet is how selectedDate is used in the default template. 
You can check from here.
https://github.com/twinssbc/Ionic2-Calendar/blob/master/src/calendar.ts
It doesn't have a ITimeSelected field, but events field as a direct property.

```
<ion-item *ngFor="let event of selectedDate?.events" (click)="eventSelected(event)">
```

**Comment by kkhwee** [comment]
@twinssbc Hi thanks, i realised i made a foolish mistake. But is it possible for the IEvent to have more things? Cause i added more fields in the eventSource and i wanted to display them. Is that possible?

**Comment by kkhwee** [comment]
Hi, sorry actually it was working once i made the the amendment you state above. Thank you for your help 👍
