### ISSUE TITLE
Suggestions for handling date range selection?

### ISSUE THREAD

**Issue by larpo1** [twinssbc/Ionic2-Calendar#78]
Hi - looking to allow a behaviour for an accommodation booking calendar where a user can select a range of empty dates by tapping one empty date followed by a second empty date. How would you recommend handling that?

Thanks

**Comment by twinssbc** [comment]
@larpo1 I think you need to record some state like startDate in the onTimeSelected callback.
Another common way is when user selects a date, navigate to a form to allow user further adjust the startTime and endTime.
