### ISSUE TITLE
Idea: use fullcalendar

### ISSUE THREAD

**Issue by ganySA** [twinssbc/Ionic2-Calendar#8]
Hi

I have been torn between using your calendar vs fullcalendar. I would like to recommend that instead of building the control from scratch it might be better to simply use something like fullcalendar which has a large set of features and that way you can either customise the views to your liking. Its feature rich and tried and tested by thousands of users and recently they included touch support.

Right now i am probably going to hack out how you implemented swiper and try use your approach with fullcalendar.

Just my 2 cents.

**Comment by mihairadulescu** [comment]
@ganySA  do you have any updates regarding swiping on full calendar?

**Comment by twinssbc** [comment]
@ganySA, the reason I built this calendar is because fullcalendar is not mobile friendly.
Especially dragging and dropping a particular event in a small phone screen is error prone.
I just added view customization to the Ionic1 version, will port it to Ionic2 version.

**Comment by ganySA** [comment]
Full calendar now supports drag and drop and a whole bunch of other features. Just saying.

**Comment by ganySA** [comment]
I think the best feature it has are:
1) how events are rendered and the flexibility to modify cell events
2) sizing of calendar - e.g size of cells etc 
3) 3 day view
4) listviews

Check out the latest version porting it or building around would be great.

**Comment by ganySA** [comment]
Only big disadvantage is it uses jquery.

**Comment by twinssbc** [comment]
@ganySA
As I said drag and drop is not suitable for the mobile phone, IMO.
It wont' be easy to move the event to a particular cell or extend the end time to a specific hour with a fat finger.

Regarding the size of calendar, when I want to use fullcalendar years ago, I found it's not responsive, that's also another reason I built the first version of control, called "Angular Responsive Calendar".
I'm not a fan of setting fixed size. Also I plan to allow user passing in the customised template. They can do more customisation, not just adjusting size.

Could you provide more detail on the 3 day view? what does it look like?

listview is a useful feature, I can add that.

**Comment by mihairadulescu** [comment]
@ganySA  from what i say on their blog they stoped using jquery as a dependency.

**Comment by ganySA** [comment]
Check out the latest. Currently I use fullcalendar in ionic they have fixed a lot of the mobile stuff like responsive and auto sizing , drag drop and reside.

So instead of a full week view there is a 3 day view similar to the outlook app for iOS. Shows 3 days next to each other which is better on mobile

**Comment by ganySA** [comment]
I thought jquery was a dependency... hmmm

**Comment by Jlabarca** [comment]
@ganySA Can you share an example using fullcalendar on ionic2?
