### ISSUE TITLE
Event list items wrapped into an ion-label

### ISSUE THREAD

**Issue by ChrisProlls** [twinssbc/Ionic2-Calendar#80]
I was playing with the `monthviewEventDetailTemplate` to change how events are displayed into the calendar. As I can see, all item are wrapped into an `ion-label`, which add lots of useless margin that I don't want for my view. I that normal ? It's possible to remove these margins for these specific items ?

**Comment by twinssbc** [comment]
@ChrisProlls 
Below is the default event detail template code
```
        <template #monthviewDefaultEventDetailTemplate let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabel">
            <ion-list class="event-detail-container" has-bouncing="false" *ngIf="showEventDetail" overflow-scroll="false">
                <ion-item *ngFor="let event of selectedDate?.events" (click)="eventSelected(event)">
                        <span *ngIf="!event.allDay" class="monthview-eventdetail-timecolumn">{{event.startTime|date: 'HH:mm'}}
                            -
                            {{event.endTime|date: 'HH:mm'}}
                        </span>
                    <span *ngIf="event.allDay" class="monthview-eventdetail-timecolumn">All day</span>
                    <span class="event-detail">  |  {{event.title}}</span>
                </ion-item>
                <ion-item *ngIf="selectedDate?.events.length==0">
                    <div class="no-events-label">{{noEventsLabel}}</div>
                </ion-item>
            </ion-list>
        </template>
```

I think the ion-label is generated by the ion-item element.
You can simply replace it with simple div element and apply your own styles.

**Comment by AravindrajanSampathkumar** [comment]
@twinssbc while using the above code I got the below error what I do for that?

Template parse errors:
"let-" is only supported on ng-template elements. ("
        </calendar>

     <template #monthviewDefaultEventDetailTemplate [ERROR ->]let-showEventDetail="showEventDetail" let-selectedDate="selectedDate" let-noEventsLabel="noEventsLabe"): ng:///AppModule/HomePage.html@66:52
"let-" is only supported on ng-template elements. ("alendar>

**Comment by twinssbc** [comment]
@AravindrajanSampathkumar As the error message indicates, you should use **ng-template**, instead of "template". "template" is some syntax in the old version of AngularJS.

**Comment by AravindrajanSampathkumar** [comment]
@twinssbc I used ng-template but the values from the back end it won't take and also it wont show the ng-template code while debuging

**Comment by twinssbc** [comment]
@AravindrajanSampathkumar What error message do you get after using ng-template?
