### ISSUE TITLE
I get a error

### ISSUE THREAD

**Issue by weitaoyang** [twinssbc/Ionic2-Calendar#82]
I use "ionic build browser --prod"

result:
Failed to load resource: net::ERR_FILE_NOT_FOUND
main.js:27 Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\yjbs\node_modules\._ionic2-calendar@0.2.4@ionic2-calendar\calendar.ngfactory.js.map'

![Uploading QQ截图20170401112708.png…]()

**Comment by weitaoyang** [comment]
![qq 20170401114759](https://cloud.githubusercontent.com/assets/3806482/24575200/b7287610-16d1-11e7-9035-93ffd21064f9.png)

**Comment by twinssbc** [comment]
Resolved in https://github.com/twinssbc/Ionic2-Calendar/issues/51
