### ISSUE TITLE
Default stylesheet will be loaded after refreshing the Calendar view

### ISSUE THREAD

**Issue by LanceGin** [twinssbc/Ionic2-Calendar#83]
I got a problem just like the title says.

I used ionic2-calendar on one of my side-menus and I have a custom stylesheet for calendar, but when I goto another side-menu and then go back to this calendar view, your default stylesheet will be loaded to my calendar instead of my custom one. 

If I kill my app, and open it again, my custom stylesheet will be loaded, but when I repeat the operation above, the problem will happen again.

It confused me ...

**Comment by twinssbc** [comment]
@LanceGin What if you specify your style selector to be more specific or use !important?

**Comment by LanceGin** [comment]
@twinssbc I have specify my style selector block by block, but that dose not effect.  `!important` can't solve this problem either...

**Comment by LanceGin** [comment]
![calendar](http://wx4.sinaimg.cn/mw1024/89243dfbgy1feamg8s3dcg20q80jwdzy.gif)

I have added `!important` to the style, but it's also like above

**Comment by twinssbc** [comment]
If you move the cursor to the element in browser developer tools, can you see if your styles are actually applied but overrided?

**Comment by LanceGin** [comment]
@twinssbc when the calendar view reload at the first time, my styles were applied, but when I get in the calendar view the next time, my styles seemed to disappear

**Comment by LanceGin** [comment]
@twinssbc 
loading at the first time:

![calendar](http://wx4.sinaimg.cn/mw690/89243dfbly1feaz0pf0yxj21kw0d1gxb.jpg)

loading at the next time

![calendar](http://wx1.sinaimg.cn/mw690/89243dfbly1feaz0uxk13j21kw0cm4c3.jpg)

**Comment by twinssbc** [comment]
Your selector seems very specific, can you make a bit generic?
You could even try just using .monthview-current?

**Comment by LanceGin** [comment]
@twinssbc I have found the error, `ion-slides` element has a progressive increase class `slides-N`, I delete `.slides-0` when I select `ion-slides` and it works.
