### ISSUE TITLE
How to set formatDayHeader input

### ISSUE THREAD

**Issue by marcRDZ** [twinssbc/Ionic2-Calendar#84]
First of all, congratulations for your work.

I was playing with your awesome customizable calendar trying to display only the first letter of the day of the week in the monthview header. I don't know if it's an issue or a missing explanation but modifying the formatDayHeader in the HTML directly doesn't work:
`...
    [formatDayHeader]="E"
...`

Instead of this, I added to the calendar variable in the ts file:
```
...
  calendar = {
      mode: 'month',
      currentDate: new Date(),
      formatDayHeader: 'E'
  };
...
```
And then in the HTML:

`[formatDayHeader]="calendar.formatDayHeader"`

That's all. I expect to be helpful ;)

**Comment by twinssbc** [comment]
@marcRDZ You should use **formatDayHeader = "E"**

**Comment by marcRDZ** [comment]
Sorry, I don't understand. Should I use that in the HTML or in the .ts file? Do you refer to the double quotes or the parameter without brackets [...]? As I said firstly, I tried that in the calendar directive in HTML in this form: [formatDayHeader]="E", and it didn't work.

**Comment by twinssbc** [comment]
@marcRDZ No need to add brackets for formatDayHeader.

**Comment by marcRDZ** [comment]
OK, I got it.
Thanks for all :)

**Comment by hzhu212** [comment]
@marcRDZ I think you should use `formatDayHeader = " 'E' "` in HTML, because `'E'` is a Javascript string. If you use `formatDayHeader = "E"`, it means `E` is a Javascript variable, which obviously can not work.

**Comment by SoulSolider** [comment]
what is the answer ?

**Comment by jayzyaj** [comment]
what's the official solution?

**Comment by twinssbc** [comment]
@SoulSolider @jayzyaj Just simply use formatDayHeader option. I tried below, it's working
```
  <calendar formatDayHeader = "EEEE d" ...></calendar>
```

**Comment by Sunil0710** [comment]
@twinssbc  just now i tired the bellow 
<calendar formatDayHeader = "E" ...></calendar> not working as expected.

but
<calendar formatDayHeader = "EEEE d" ></calendar> is working fine.


Can you tell me what is the exact answer ?

**Comment by Sunil0710** [comment]
@marcRDZ can i have your code to display the first letter of the DayHeader.?

**Comment by jloria13** [comment]
Hey @twinssbc, I found this https://medium.com/a-curious-life/customizing-angular-ui-bootstrap-directives-c4461c12afa9 he solve this problem in angular but where can I this in my app ?

**Comment by ghost** [comment]
You can use formatDayHeader="EEEEE" as described in https://angular.io/api/common/DatePipe

It's not only one 'E' as we imagined but 5 :)

**Comment by oriol592** [comment]
I played around with the attribute formatDayHeader on the HTML, and I have seen:

- formatDayHeader="EEE": (3 times E) prints the 3 first letters of the day of the week
- formatDayHeader="EEEE": (4 times E) prints the whole day of the week name
- formatDayHeader="EEEEE": (5 times E) prints the first letter (capitalized) of the day of the week name
- formatDayHeader="EEEEEE": (6 times E) prints first two letters (capitalized) of the day of the week name

**Comment by PriyaJagan11** [comment]
How to get all the letters capitalized by using formatDayHeader. like SUNDAY, MONDAY

**Comment by twinssbc** [comment]
> How to get all the letters capitalized by using formatDayHeader. like SUNDAY, MONDAY

you could use dateFormatter option to achieve this.
