### ISSUE TITLE
Unhandled Promise rejection: Template parse errors: Can't bind to 'loop' since it isn't a known property of 'ion-slides'

### ISSUE THREAD

**Issue by Samzerge** [twinssbc/Ionic2-Calendar#85]
I get this error when running the app in the device:

Unhandled Promise rejection: Template parse errors:
Can't bind to 'loop' since it isn't a known property of 'ion-slides'.
1. If 'ion-slides' is an Angular component and it has 'loop' input, then verify that it is part of this module.
2. If 'ion-slides' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        <div>
            <ion-slides #monthSlider [ERROR ->][loop]="true" (ionSlideDidChange)="onSlideChanged()">
                <ion-slide>
                   "): MonthViewComponent@2:37 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'loop' since it isn't a known property of 'ion-slides'.
1. If 'ion-slides' is an Angular component and it has 'loop' input, then verify that it is part of this module.
2. If 'ion-slides' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        <div>
            <ion-slides #monthSlider [ERROR ->][loop]="true" (ionSlideDidChange)="onSlideChanged()">
                <ion-slide>
                   "): MonthViewComponent@2:37 Error: Template parse errors:
Can't bind to 'loop' since it isn't a known property of 'ion-slides'.
1. If 'ion-slides' is an Angular component and it has 'loop' input, then verify that it is part of this module.
2. If 'ion-slides' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("
        <div>
            <ion-slides #monthSlider [ERROR ->][loop]="true" (ionSlideDidChange)="onSlideChanged()">
                <ion-slide>
                   "): MonthViewComponent@2:37
    at TemplateParser.parse (file:///android_asset/www/build/main.js:21738:19)
    at RuntimeCompiler._compileTemplate (file:///android_asset/www/build/main.js:49026:51)
    at file:///android_asset/www/build/main.js:48946:62
    at forEach (native)
    at RuntimeCompiler._compileComponents (file:///android_asset/www/build/main.js:48946:19)
    at createResult (file:///android_asset/www/build/main.js:48842:19)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9094)
    at e.run (file:///android_asset/www/build/polyfills.js:3:6481)
    at file:///android_asset/www/build/polyfills.js:3:4583
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9723)

The only code in my app is the one from app.module.ts

```
import { NgModule, ErrorHandler } from '@angular/core';
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { EventDetailsPage } from '../pages/event-details/event-details';
import { ReminderDetailsPage } from '../pages/reminder-details/reminder-details'
import { EventService } from '../services/events.service';
import { NotificationsProvider } from '../providers/notifications-provider'
import { LocalNotifications } from '@ionic-native/local-notifications';

import { NgCalendarModule  } from 'ionic2-calendar';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    EventDetailsPage,
    ReminderDetailsPage
  ],
  imports: [
    NgCalendarModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    EventDetailsPage,
    ReminderDetailsPage
  ],
  providers: [
  {provide: ErrorHandler, useClass: IonicErrorHandler},
   EventService,
   LocalNotifications,
   NotificationsProvider]
})
export class AppModule {}

```

**Comment by twinssbc** [comment]
@Samzerge Which version of the Ionic and Calendar are you using?

**Comment by Samzerge** [comment]
This is what I'm using:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.4
Xcode version: Not installed

ionic2-calendar 0.2.4

**Comment by twinssbc** [comment]
@Samzerge Is it working when running in browser?
Could you provide your package.json?

**Comment by Samzerge** [comment]
When running in browser with ionic serve it returns the same error.

```
{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic-native/core": "^3.4.4",
    "@ionic-native/local-notifications": "^3.4.4",
    "@ionic/storage": "1.1.6",
    "intl": "^1.2.5",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "^2.2.11",
    "ionic2-calendar": "^0.2.4",
    "ionicons": "3.0.0",
    "pouchdb": "^6.1.2",
    "pouchdb-adapter-cordova-sqlite": "^2.0.2",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.0.0",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "ionic2-tutorial-pouchdb: An Ionic project"
}
```

**Comment by twinssbc** [comment]
OK. So you are actually using Ionic 2.0.0-rc.4. As the REAMEME says, Ionic2-Calendar 0.2.x is compatible to Ionic 2.0.0-rc.5 and final version onwards. You need to update your Ionic dependency to the newer version.

**Comment by carlos-olivera** [comment]
Hi! I got the same error with ionic v2.2.2

**Comment by twinssbc** [comment]
@carlos-olivera What's the calendar version are you using?

**Comment by carlos-olivera** [comment]
0.2.4.

I did a project refresh (re import and update node modules), and the problem was gone.

Thanks!

Carlos.
