### ISSUE TITLE
EventSource Data binding not working?

### ISSUE THREAD

**Issue by gdesplin** [twinssbc/Ionic2-Calendar#86]
When I set eventSource to new set of data, it doesn't update the view, like I think it should. 
```
updateEventSource(data) {
        for (let i of data) {
                this.events.push(i);
            }
        this.eventSource = data;
        console.log(this.eventSource);
    }
```
It wont show the new event until after move away the view and change back. It actually removes any event from view until its reloaded. This is all happening in the browser view.

I may just be misunderstanding how eventSource works, or how to keep the view updated.

**Comment by twinssbc** [comment]
@gdesplin 
What's the relationship between this.events and this.eventSource?
There were similar issues opened by other users, and they are mainly because they thought the logic in the synchronous way, didn't update the eventSource in the async callback.

**Comment by gdesplin** [comment]
What do mean by the async callback.
This is what I mean to post for code last 
```
    updateEventSource(data) {
        for (let i of data) {
                this.events.push(i);
            }
        this.eventSource = this.events;
        console.log(this.eventSource);
    }
```

this.events is possibly unnecessary, it is a list of event objects, which eventSource is as well. I will look for those other issues opened up that had this same problem. Any you might refer to me?

**Comment by twinssbc** [comment]
@gdesplin 
How is this updateEventSource method get called?
Are you using the 'local' or 'remote' query mode?

**Comment by GenerationLabs** [comment]
Its being called like this 
```
 newEvent(ev) {

        let addModal = this.modalCtrl.create( NewEventPage, {
            ev: ev
        });
        addModal.onDidDismiss( (event) => {
            if (event) {
                console.log(event);
                // this.saveEvent(event);
                var data = this.eventService.createEvent(event);
                console.log(data);
                this.updateEventSource(data);

            }
        });
        
        addModal.present();
    };
```

where var data = this.eventService.createEvent(event); is setting data to a list of events returned from as a response to creating the event, the console.log(data) looks like this
```
[]0:
 ObjectallDay: falsecreatedAt: "2017-04-13T15:23:48.518Z"endTime: Thu Apr 13 2017 18:00:00 GMT-0600 (MDT)goalLink: "Purple"ownerId: "58ec4d2194d7b4658677d42b"startTime: Thu Apr 13 2017 17:00:00 GMT-0600 (MDT)title: "test"updatedAt: "2017-04-13T15:23:48.518Z"__v: 0_id: "58ef9804a4379b0012ac524e"__proto__: Objectlength: 1__proto__: Array(0)
```
which there is supposed to be one event total in this case. Is this not the proper format? 
This then gets put into that updateEventSource function which doesn't succeed.
I call updateEventSource on ionpage view and it works when I call a different getEvents function.

**Comment by gdesplin** [comment]
@twinssbc 
Its being called like this
```
 newEvent(ev) {

        let addModal = this.modalCtrl.create( NewEventPage, {
            ev: ev
        });
        addModal.onDidDismiss( (event) => {
            if (event) {
                console.log(event);
                // this.saveEvent(event);
                var data = this.eventService.createEvent(event);
                console.log(data);
                this.updateEventSource(data);

            }
        });
        
        addModal.present();
    };
```
where var data = this.eventService.createEvent(event); is setting data to a list of events returned from as a response to creating the event, the console.log(data) looks like this
```
[]0:
 ObjectallDay: falsecreatedAt: "2017-04-13T15:23:48.518Z"endTime: Thu Apr 13 2017 18:00:00 GMT-0600 (MDT)goalLink: "Purple"ownerId: "58ec4d2194d7b4658677d42b"startTime: Thu Apr 13 2017 17:00:00 GMT-0600 (MDT)title: "test"updatedAt: "2017-04-13T15:23:48.518Z"__v: 0_id: "58ef9804a4379b0012ac524e"__proto__: Objectlength: 1__proto__: Array(0)
```
which there is supposed to be one event total in this case. Is this not the proper format?
This then gets put into that updateEventSource function which doesn't succeed.
I call updateEventSource on ionpage view and it works when I call a different getEvents function.

**Comment by twinssbc** [comment]
@gdesplin Is createEvent method fetching events from your server or directly generate event objects?

If it's the first case, this is async call, you need to use remote mode. And the response is returned in async way, you won't get anything in data variable. So you need to call updateEventSource method in the callback method of createEvent.

**Comment by gdesplin** [comment]
Now I have 
```
    newEvent(ev) {
        let addModal = this.modalCtrl.create( NewEventPage, {
            ev: ev
        });
        addModal.onDidDismiss( (event) => {
            if (event) {
                console.log(event);
                // this.saveEvent(event);
                this.eventService.createEvent(event, **this.updateEventSource**);
            }
        });
        addModal.present();
    };
```
and 
```

  createEvent(event, callback){
    let headers = new Headers();
    headers.append('Content-Type', 'application/json');
    headers.append('Authorization', this.authService.token);
    var data = [];
    this.http.post(this.baseURL+'api/myEvents', JSON.stringify(event), {headers: headers})
      .subscribe(res => { 
        for (let i of res.json()) {
            // console.log(i);
            i.startTime = new Date(i.startTime);
            i.endTime = new Date(i.endTime);
            // console.log(i);
            data.push(i)
          }
          console.log(data);          
          **callback(data);** 
      }); 
  }
```
Using that same this.updateEventSource function I had before
i've set it to remote mode like this 
```
    <calendar [eventSource]="eventSource"
              [calendarMode]="calendar.mode"
              [currentDate]="calendar.currentDate"
              [dayviewNormalEventTemplate]=colors
              [dayviewAllDayEventTemplate]=colors
              [weekviewNormalEventTemplate]=colors
              [weekviewAllDayEventTemplate]=colors
              (onCurrentDateChanged)="onCurrentDateChanged($event)"
              (onEventSelected)="onEventSelected($event)"
              (onTitleChanged)="onViewTitleChanged($event)"
              (onTimeSelected)="onTimeSelected($event)"
              **queryMode="remote"**
              step="30">
    </calendar>
```
Which i'm sure if that is correct
I am getting this error 
```
core.es5.js:1085 ERROR TypeError: Cannot set property 'eventSource' of undefined
    at CalendarPage.updateEventSource (calendar.ts:49)
    at SafeSubscriber._next (events.ts:80)
```
meaning I can't use the eventSource in the callback... What am I missing here? How can I set the eventSource in a callback function in a different file?

**Comment by gdesplin** [comment]
I just made it work by passing around 'this' like so:
                this.eventService.createEvent(event, this.updateEventSource, this);
and I made sure any function that would be called as a callback received 'this'... I don't know if this is the smartest way to do it, but I guess it works.

**Comment by twinssbc** [comment]
@gdesplin This way looks correct. The key point is to manipulate the eventSource in the callback.
