### ISSUE TITLE
Use ionic2-calendar in plunker

### ISSUE THREAD

**Issue by SimoneMSR** [twinssbc/Ionic2-Calendar#87]
Hello,
I am trying to use the component in plunker.
Would you know what I should put in systemjs.config.js, something like
         `ionic2-calendar" : "npm:ionic2-calendar@0.2.4/`

but if so I get this error when I try do to 
      `import { NgCalendarModule  } from 'ionic2-calendar';`

> Error: (SystemJS) Unexpected token <

I thik I am not importing well the module, but just some html file.

Thank you very much for your help!

**Comment by twinssbc** [comment]
@SimoneMSR I'm not too familiar with setting up the component in plunker.
Below mapping is coming from the config.js of my demo page, I either point the module to a URL or a relative path.
Not sure, "npm:ionic2-calendar@0.2.4" will load the module from npm repository automatically?

```
    var map = {
        'app': 'app', // 'dist',
        'rxjs': 'https://unpkg.com/rxjs@5.0.1',
        'angular2-in-memory-web-api': 'https://unpkg.com/angular2-in-memory-web-api', // get latest
        'ionic2-calendar': '../src',
        'ionic-angular': 'https://unpkg.com/ionic-angular@2.1.0',
        'pages': 'pages',
        'intl': 'https://unpkg.com/intl@1.2.5'
    };
```

**Comment by SimoneMSR** [comment]
Hello,

thank you for your replay. I have successfully managed to install your component in my plunker. Here you can see the code:
[(https://plnkr.co/edit/psl7o2)]

look at the ` the systemjs.config.js` file

**Comment by twinssbc** [comment]
Cool. It's a great sample.
