### ISSUE TITLE
Ionic 3 - Angular 4

### ISSUE THREAD

**Issue by claudiozam** [twinssbc/Ionic2-Calendar#88]
Hi, thanks for your excellent plugin and your effort.  Do you have plans to migrate to Ionic 3 + Angular 4? 

Thanks!!

**Comment by twinssbc** [comment]
@claudiozam Yeah, definitely.

**Comment by giorgiopiatti** [comment]
I've tried it with Ionic 3 and Angular 4 and all seems to properly work.
There is only one warning:
```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("          [ngClass]="getHighlightClass(views[0].dates[row*7+col])">
                                [WARNING ->]<template [ngTemplateOutlet]="monthviewDisplayEventTemplate"
                                [ngOutle"): ng:///NgCalendarModule/MonthViewComponent.html@16:32
```

**Comment by ChrisProlls** [comment]
Yes for me too, just this warning but no big errors.

**Comment by twinssbc** [comment]
Cool, this is great.
That means I just need to to make little change to get rid off the warnings.

**Comment by Adomako-Bismark** [comment]
this doesn't seem to work for me here.
the error i get is:

Can't bind to 'eventSource' since it isn't a known property of 'calendar'

**Comment by giorgiopiatti** [comment]
@Adomako-Bismark Have you added the module into  page.module.ts?

**Comment by Adomako-Bismark** [comment]
@giorgiopiatti that was silly of me. forgot to add that previously. just did and it works just fine. thank you very much

**Comment by ataraxus** [comment]
Hey Guys, I'm on Ionic 3.1.0 and i get these errors

```
167 silly rollbackFailedOptional Starting
168 silly rollbackFailedOptional Finishing
169 silly runTopLevelLifecycles Finishing
170 silly install printInstalled
171 warn @angular/platform-server@2.4.8 requires a peer of @angular/core@2.4.8 but none was installed.
172 verbose If you need help, you may report this error at:
172 verbose     <https://github.com/npm/npm/issues>
173 warn @angular/platform-server@2.4.8 requires a peer of @angular/common@2.4.8 but none was installed.
174 verbose If you need help, you may report this error at:
174 verbose     <https://github.com/npm/npm/issues>
175 warn @angular/platform-server@2.4.8 requires a peer of @angular/compiler@2.4.8 but none was installed.
176 verbose If you need help, you may report this error at:
176 verbose     <https://github.com/npm/npm/issues>
177 warn @angular/platform-server@2.4.8 requires a peer of @angular/platform-browser@2.4.8 but none was installed.
178 verbose If you need help, you may report this error at:
178 verbose     <https://github.com/npm/npm/issues>
179 verbose stack Error: ionic2-calendar@0.2.5 postinstall: `typings install`
179 verbose stack spawn ENOENT
179 verbose stack     at ChildProcess.<anonymous> (/Users/xx/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/spawn.js:33:16)
179 verbose stack     at emitTwo (events.js:106:13)
179 verbose stack     at ChildProcess.emit (events.js:191:7)
179 verbose stack     at maybeClose (internal/child_process.js:877:16)
179 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
180 verbose pkgid ionic2-calendar@0.2.5
181 verbose cwd /Users/xx/git/mobile/projects/mze/client/mze
182 error Darwin 16.5.0
183 error argv "/Users/xx/.nvm/versions/node/v6.9.5/bin/node" "/Users/xx/.nvm/versions/node/v6.9.5/bin/npm" "install" "ionic2-calendar" "-se"
184 error node v6.9.5
185 error npm  v3.10.10
186 error file sh
187 error code ELIFECYCLE
188 error errno ENOENT
189 error syscall spawn
190 error ionic2-calendar@0.2.5 postinstall: `typings install`
190 error spawn ENOENT
191 error Failed at the ionic2-calendar@0.2.5 postinstall script 'typings install'.
191 error Make sure you have the latest version of node.js and npm installed.
191 error If you do, this is most likely a problem with the ionic2-calendar package,
191 error not with npm itself.
191 error Tell the author that this fails on your system:
191 error     typings install
191 error You can get information on how to open an issue for this project with:
191 error     npm bugs ionic2-calendar
191 error Or if that isn't available, you can get their info via:
191 error     npm owner ls ionic2-calendar
191 error There is likely additional logging output above.
```
How did you get this running with angular4 ?

**Comment by ataraxus** [comment]
I would actually suggest to create a branch/fork Ionic3-Calendar so it doesnt confuse people search for something compatible to ionic3

**Comment by twinssbc** [comment]
@ataraxus Looks like your error is not related to Ionic3 or Angular4.
It seems related to the postinstall step.
```
190 error ionic2-calendar@0.2.5 postinstall: `typings install`
```
Could you run npm install -g typings to install typings?
Yes, I will create a branch for Ionic3 compatible version.

**Comment by twinssbc** [comment]
I have released 0.3.0 which is compatible with Ionic3 and Angular4. Feel free to have a try.

**Comment by ataraxus** [comment]
Great thank you so much!

**Comment by Adomako-Bismark** [comment]
@twinssbc it appears some of your modules are importing BrowserModule. i have the error below:


ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by twinssbc** [comment]
@Adomako-Bismark I have removed dependency on BrowserModule in version 0.3.1. Feel free to have a try.

**Comment by Adomako-Bismark** [comment]
@twinssbc thank you for the quick update. It works great now.

**Comment by claudiozam** [comment]
@twinssbc thanks for your excellent job!

**Comment by dluque92** [comment]
@twinssbc Hello, thanks for your amazing plugin. Do you have plans to put descriptions inside the events? Thanks!

**Comment by twinssbc** [comment]
@dluque92 By using the View Customization options, you could display any custom fields. You don't have to use predefined fields.
