### ISSUE TITLE
Disable events in calendar.

### ISSUE THREAD

**Issue by mihairadulescu** [twinssbc/Ionic2-Calendar#9]
HI guys nice work here.
it would be great to support disabling calendar dates, like for 1 day disable a range of hours.
disableEventSource = {
 monday: [startDate:8 am: endDate:3pm]
 tuesday: same stuff 
}
another nice feature would be to show events with different colors. on event source to set event cell class and then in css you can customize appereance of that cel.

**Comment by twinssbc** [comment]
@mihairadulescu 
Yes, these two features have been raised for the Ionic1 version.
https://github.com/twinssbc/Ionic-Calendar/issues/92
https://github.com/twinssbc/Ionic-Calendar/issues/88
I have implemented the view customisation and going to implement the disabling date in Ionic1 version first, then I will port it to Ionic2 version.

**Comment by mihairadulescu** [comment]
@twinssbc cool work man!
👍

**Comment by twinssbc** [comment]
@mihairadulescu I have added markDisabled option to the calendar. Feel free to have a try.

**Comment by twinssbc** [comment]
@mihairadulescu I have added view customization in version 0.1.0. You can get more information from README. Feel free to have a try. Thanks.

**Comment by urfli911** [comment]
hi guys, i'm new hear, any idea on how to disable the entire month of the calendar dynamically? Thanks.

**Comment by twinssbc** [comment]
@urfli911 What do you mean disable entire month? And what do you mean disable dynamically?

**Comment by daviddickson** [comment]
@twinssbc I think @urfli911 has the same question as I do.  Is there a way disable a date after the initial render?

**Comment by twinssbc** [comment]
@daviddickson Unfortunately, markDisabled method is only triggered during the initial render. But you could still achieve the disable effect by using custom template. You could create a dummy event on that date, and return a "disabled" css class if that dummy event exists.
