### ISSUE TITLE
error while install npm calendar

### ISSUE THREAD

**Issue by faisalsaghir7** [twinssbc/Ionic2-Calendar#92]
$ npm install ionic2-calendar --save

> ionic2-calendar@0.2.5 postinstall E:\Repository\Form Fresh\node_modules\ionic2-calendar
> typings install

'typings' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @ionic-native/calendar@3.5.0 requires a peer of @ionic-native/core@^3.1.0 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionic2-calendar" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ionic2-calendar@0.2.5 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic2-calendar@0.2.5 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic2-calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic2-calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic2-calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Repository\Form Fresh\npm-debug.log

**Comment by twinssbc** [comment]
@faisalsaghir7 You need to install typings
npm install -g typings

**Comment by faisalsaghir7** [comment]
npm install -g typings is already installled

**Comment by twinssbc** [comment]
@faisalsaghir7 If you successfully install typings, you should be able to execute
typings install

Otherwise, could you check if typings binaries appear in your NPM repository and added to your PATH?
