### ISSUE TITLE
Insert new Event

### ISSUE THREAD

**Issue by cesargrano** [twinssbc/Ionic2-Calendar#93]
Please I need help.
When I need to include a new event, how do I do this.
I tried to do so

		let event =
		{
			id: 20,
			title: 'Eventa - New',
			startTime: new Date('2017-04-27 14:00:00'),
			endTime: new Date('2017-04-27 14:30:00'),
			allDay: false
		};
		this.eventSource.push(event);

The event does not appear on the day immediately, it only appears when I go to another week or another month

Could you give me a light? 
Thank you.

**Comment by twinssbc** [comment]
@cesargrano The calendar doesn't watch the element change in side eventSource. You need to reassign the eventSource variable.

**Comment by cesargrano** [comment]
I managed to solve it like this:

		let event =
		{
			id: 20,
			title: 'Eventa - New',
			startTime: new Date('2017-04-27 14:00:00'),
			endTime: new Date('2017-04-27 14:30:00'),
			allDay: false
		};
		let events = this.eventSource;
		events.push(event);

		this.eventSource = [];
		setTimeout(() => {
			this.eventSource = events;
		});

It was improvised, but it worked perfectly.

Tip: You could implement this type of automatic update on the eventSource variable itself.

Thanks for the support, I'm liking your Component.
