### ISSUE TITLE
month view highlighting

### ISSUE THREAD

**Issue by gabrielalack** [twinssbc/Ionic2-Calendar#94]
Hello

I'm wondering how to change the styles on the month view. I want to:

- override the whole day highlight feature and instead show colored blocks for each of the events (without the highlight). I know I can add the event blocks by using the template but I still want to get rid of the highlight.

- override the selection highlighting as well

Is there an easy way to do that?

**Comment by twinssbc** [comment]
@gabrielalack Are you referring to the GREEN highlight color when you select a day?
When you select a day having event, the css applied on it is like below:
So you can set your own color.
```
td.monthview-primary-with-event.monthview-selected {
    background-color: xxx;
}
```
Another way is you could add css class in your template, and apply background class for your css class. Since the highlight class is applied on the outer DOM element, you should be able to override the style in the inner DOM element.

**Comment by fureszk** [comment]
Probably not the best (getColorClass gets called too many times) but a working solution:

ts:
```
getColorClass(date: Date) {
    let colors: string[] = ['primary', 'warning', 'danger', 'light', 'success'];
    return colors[Math.floor(date.getDay()/6*colors.length)];
  }
```


html:
```
<template #template let-view="view" let-row="row" let-col="col">
    <div class="calendar-day {{ getColorClass(view.dates[row*7+col].date) }}">
      {{view.dates[row*7+col].label}}
    </div>
  </template>

  <calendar [eventSource]="eventSource"
            [currentDate]="calendar.currentDate"
            [showEventDetail]="false"
            [monthviewDisplayEventTemplate]="template"
            startingDayMonth="1"
            formatMonthTitle="yyyy MMMM"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)">
  </calendar>
```

css:
```
 .monthview-selected {
    background-color: transparent !important;
    color: black !important;
  }

  td.monthview-current {
    color: white;

    .calendar-day {
      background-color: color($colors, 'light') !important;
    }
  }
  
  .monthview-datetable {
    border: 0 !important;

    td, th {
      border: 0 !important;
      padding: 3px!important;
    }
  }

  .calendar-day {
    border-radius: 6px;
    padding: 3px 5px;

    &.primary {
      background-color: color($colors, 'primary');
      color: white;
    }

    &.success {
      background-color: color($colors, 'success');
      color: white;
    }

    &.warning {
      background-color: color($colors, 'warning');
      color: white;
    }

    &.danger {
      background-color: color($colors, 'danger');
      color: white;
    }

    &.light {
      background-color: color($colors, 'light');
      color: white;
    }
  }
```

**Comment by fureszk** [comment]
@gabrielalack 
I believe I wanted the same thing and achieved it. I only have single allDay events, so events[0] works all the time:

ts:
```
        events.push({
          title: 'Event - ' + i,
          startTime: startTime,
          endTime: endTime,
          allDay: true,
          color: colors[Math.floor(Math.random()*colors.length)]
        });
```


html:
```
  <template #template let-view="view" let-row="row" let-col="col">
    <div class="calendar-day {{ view.dates[row*7+col].events[0]?.color }}">
      {{view.dates[row*7+col].label}}
    </div>
  </template>

  <calendar [eventSource]="eventSource"
            [currentDate]="calendar.currentDate"
            [showEventDetail]="false"
            [monthviewDisplayEventTemplate]="template"
            startingDayMonth="1"
            formatMonthTitle="yyyy MMMM"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)">
  </calendar>
```

css:
```
  .monthview-selected {
    background-color: transparent !important;
    color: black !important;
  }

  td.monthview-current {
    color: white;

    .calendar-day {
      background-color: color($colors, 'light') !important;
    }
  }

  .monthview-datetable {
    border: 0 !important;

    td, th {
      border: 0 !important;
      padding: 3px!important;
      background-color: transparent!important;
    }
  }

  .calendar-day {
    border-radius: 6px;
    padding: 3px 5px;

    &.primary {
      background-color: color($colors, 'primary');
      color: white;
    }

    &.success {
      background-color: color($colors, 'success');
      color: white;
    }

    &.warning {
      background-color: color($colors, 'warning');
      color: white;
    }

    &.danger {
      background-color: color($colors, 'danger');
      color: white;
    }
  }
```

**Comment by Bhavana1622** [comment]
this is what i did and it worked. please check the code. Hope this helps

https://github.com/Bhavana1622/ionic2-calendar-event

**Comment by Hanzofm** [comment]
@fureszk How do you show the month title and back/next arrows?

**Comment by fureszk** [comment]
@Hanzofm this is what I have right above the html I have previously posted:
```
  <ion-grid class="calendar-header">
    <ion-row>
      <ion-col col-2>
        <button ion-button item-left clear (click)="prevMonth()">
          <ion-icon name="arrow-back"></ion-icon>
        </button>
      </ion-col>
      <ion-col col-8>
        <button ion-button block clear>{{ viewTitle }}</button>
      </ion-col>
      <ion-col col-2>
        <button ion-button item-right clear (click)="nextMonth()">
          <ion-icon name="arrow-forward"></ion-icon>
        </button>
      </ion-col>
    </ion-row>
  </ion-grid>
```

javascript:
```
  onViewTitleChanged(title) {
    this.viewTitle = title;
  }

  prevMonth() {
    this.calendar.currentDate = new Date(this.calendar.currentDate.setMonth(this.calendar.currentDate.getMonth() - 1));
  }

  nextMonth() {
    this.calendar.currentDate = new Date(this.calendar.currentDate.setMonth(this.calendar.currentDate.getMonth() + 1));
  }
```

onViewTitleChanged is called by the calendar's callback "onTitleChanged" its also in the comment above.

**Comment by waleedshkt** [comment]
Hi guys, I'm trying to show events' marks - like red (past) and green (upcoming) dots on each block - on month view. 

Is there anyway to achieve this in ionic-calendar? If so, please help me on this. 

Would greatly appreciate the positive response! :)

**Comment by twinssbc** [comment]
@waleedshkt This is for Ionic2-Calendar. If you are using ionic-calendar, you could create an issue under below URL.
https://github.com/twinssbc/Ionic-Calendar/issues

**Comment by waleedshkt** [comment]
@twinssbc , I'm using ionic2-calender.

Any possibility to add the above mentioned style?
Btw, styling the calendar is a little confusing for me. I don;t understand the template syntax, and don't fully sure what classes to target for different elements in MonthView mode.

**Comment by twinssbc** [comment]
@waleedshkt You could refer to Angular doc about the template syntax.
Below is just an example.
You could have a template in your html like this, notice the getCustomClass, it accepts the current date on the cell.
```
   <ng-template #template let-view="view" let-row="row" let-col="col">
    <div [ngClass]="getCustomClass(view.dates[row*7+col].date)">
      {{view.dates[row*7+col].label}}
    </div>
  </ng-template>

  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [currentDate]="calendar.currentDate"
            [monthviewDisplayEventTemplate]="template"
            (onCurrentDateChanged)="onCurrentDateChanged($event)"
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)"
            (onTimeSelected)="onTimeSelected($event)"
            step="30">
  </calendar>
```

In your component code, you need to implement getCustomClass logic.
It accepts a date object, then you could check if it's past date or future date, and return different class name.
Then you could apply different styles on the css classes.
```
  getCustomClass(date) {
    return 'test';
  }
```

**Comment by jcmendes9898** [comment]
Hi, i can only change de color of the days if i had `:host ::ng-deep .monthview-primary-with-event {
    background-color: #387ef5 !important;
    color: white !important;
}
`,
Need the :host ::ng-deep. That way i can't change the color of each day. Any suggestions or tips? I'm using this [template](https://github.com/twinssbc/Ionic2-Calendar/issues/94#issuecomment-298194910)

**Comment by twinssbc** [comment]
@jcmendes9898 You could put it in global.scss, then you don't need :host ::ng-deep.
