### ISSUE TITLE
Week view - Select day

### ISSUE THREAD

**Issue by lucifer-cross99** [twinssbc/Ionic2-Calendar#95]
I think we should be allowed to select a day in the week view

**Comment by twinssbc** [comment]
@jacob-cross99 Could you elaborate more about this functionality?
How is it selected and once it's selected, what to do next?
If you want to add an event, I guess selecting an hour slot is a more common use case? 
The calendar already exposes onTimeSelected callback once an hour slot is selected.

**Comment by RS-Shekhawat** [comment]
@twinssbc ,
I need to get click event on week day, so could you suggest me the way of getting this event.

**Comment by twinssbc** [comment]
@RS-Shekhawat Are you saying you want to get click event when you click a day in weekview?

**Comment by RS-Shekhawat** [comment]
@twinssbc yes, when i click on day from week view then i want to get this event. I am attaching my app week design header its my requirement. 
![screen shot 2017-10-11 at 5 36 43 pm](https://user-images.githubusercontent.com/25079413/31439562-3dff9982-aeaa-11e7-9cfd-cc3cb3e70ba2.png)

**Comment by twinssbc** [comment]
@RS-Shekhawat You could use onTimeSelected function.
It has an argument called selectedTime, which could be used to determine the selected day.
Note that this selected time might not be the exact hour you clicks, depending you are clicking on a cell having events or not. Let's say you have an event starting from 7-9, when you click the cell on 8, you might think the selectedTime is 8, but actually the click event happens on a hovering DOM element starting from 7, so the selectedTime is 7. Anyway, it should still serve your need, as you only care about the selected day.

**Comment by RS-Shekhawat** [comment]
@twinssbc thanks for reply me, actually i have some changed the functions in the "week.js"  file in node_modules

**Comment by RS-Shekhawat** [comment]
@twinssbc could you suggest me how to re-generate "weekview.js.map" & "weekview.meta.json" from "weekview.js" file so all the updated code move in these files "weekview.js.map" & "weekview.meta.json" . Because these are encrypted files so, i am little bit confused if i will change these file code and any kind of issue will come after that change.

Thanks

**Comment by twinssbc** [comment]
@RS-Shekhawat If you decided to modify the source code, I suggest you fork the repository and modify the ts file. Then run "npm run build-prod", all necessary files will be generated under aot folder.

**Comment by RS-Shekhawat** [comment]
@twinssbc ok... thanks for provide me solution, let me try it & if i got any trouble then will update you.

**Comment by kapilkarda** [comment]
Hello @twinssbc I just  want that In weekView when I click to time "onTimeSelected" I want that field
background to be changed and when I again clicked is goes to unselect..  
![image](https://user-images.githubusercontent.com/4336836/31704525-66097d62-b3ff-11e7-9f37-450e1b3526c0.png)

**Comment by twinssbc** [comment]
@kapilkarda Actually onTimeSelected probably doesn't work as you expected. It's because let's say you have an event starting from 7AM to 9AM. The event DOM element basically hover on the 7AM and 8AM cell. Now if you click the 8AM cell, the element response to the click event is not the 8AM cell element, it's the hovering event DOM starting from 7AM. It results to that onTimeSelected will think the selected time is 7AM.
I still don't have any way to fix this behavior. One potential workaround is to calculate the mouse/finger coordinate to find out it actually happens on which cell.
Suppose you could find out which cell is clicked, to add some customized background color, I think you could attach a fake event to that time, then you could generate some css class based on this event.

**Comment by lcaprini** [comment]
Hi @twinssbc and @RS-Shekhawat , I've created the pull request https://github.com/twinssbc/Ionic2-Calendar/pull/306  in order to select a day in week view by click on releated day in header.
I've tested in my ionic 3 and angular 5 app.
Thank you.

**Comment by bhawanatyagi2010** [comment]
Hi Everyone,

Can you please help me to create a calendar to show Week View of a Month using ionic2 calendar.I have tried various options present on github but unable to achieve this.For Month View i was successfully able to create the calendar.

Thank You

**Comment by twinssbc** [comment]
@bhawanatyagi2010 If you use the calendar in your HTML like below, you just need to set calendar.mode to week in your component code.
You could refer to the Demo page to see how to toggle between month/week/day views.

```
      <calendar [eventSource]="eventSource"
        [calendarMode]="calendar.mode"
        ...
      </calendar>
```

**Comment by shashical** [comment]
onselect date i want to move to week display how do i call week ?

**Comment by shashical** [comment]
thank for your reply

Problem 1.:
I want to display month first -> calendar.mode to 'month'.
Onselect date --> i want to hide month and display week

Problem 2:
I want to display entire year full calender -> then month and year
selection should be there

How do i do this can you please help me

**Comment by twinssbc** [comment]
@shashical 
1. Suppose you use the calendar in your HTML as below
```
        <calendar ... [calendarMode]="calendar.mode"  (onTimeSelected)="onTimeSelected($event)"></calendar>
```
Then you could set calendar.mode to 'month' in your component code.
And change the value to 'week' in onTimeSelected function
```
        onTimeSelected(ev) {
            this.calendar.mode='week';
        };
```

2. This calendar control only supports month, week and day view, looks like you want to have a year view? Then you need to create a separate page to implement your view. Then you could provide a group of toggle button, if month/week/day button is clicked, then display the calendar and set the calendar mode accordingly. You could refer to the Demo page, it allows you to toggle among the views.

**Comment by shashical** [comment]
Hi,

I did same way but when its loading at that time only week is displaying

 <calendar ... [calendarMode]="calendar.mode"
(onTimeSelected)="onTimeSelected($event)"></calendar>

   onTimeSelected(ev) {
            this.calendar.mode='week';
        };

actually i wanted like when i click on date then it should take me to week
display

**Comment by shashical** [comment]
Am trying to change calendar header color how do i change?

**Comment by twinssbc** [comment]
@shashical Which view? You just need to add proper css style to locate the header element to change the background color.

**Comment by shashical** [comment]
Hi,

How do i connect angular with google calendar

Can you please help me

**Comment by twinssbc** [comment]
@shashical This calendar doesn't care where do you get the event data? It could be from the database or other source like google calendar. You could call the google calendar API to retrieve the data and do the proper transformation and fill it into the eventSource.

**Comment by jayzyaj** [comment]
how did u change the header to that?

**Comment by shashical** [comment]
I just gave important to which classes i wanted to use and added bootstrap
4

**Comment by akshaykatale99** [comment]
hi @twinssbc i am facing the same issue like https://github.com/twinssbc/Ionic2-Calendar/issues/95#issuecomment-399317331 calender not shows week and day view even when i set mode..

**Comment by twinssbc** [comment]
@akshaykatale99 Could you provide your code? Not showing week and day view means the calendar stays on the month view?

**Comment by akshaykatale99** [comment]
@twinssbc check this...

yes calendar shows on month view but not on week and day..

.ts

calendar = {
        mode: 'month',
        currentDate: new Date(),
        dateFormatter: {
            formatMonthViewDay: function(date:Date) {
                return date.getDate().toString();
            },
            formatMonthViewDayHeader: function(date:Date) {
                return 'MonMH';
            },
            formatMonthViewTitle: function(date:Date) {
                return 'testMT';
            },
            formatWeekViewDayHeader: function(date:Date) {
                return 'MonWH';
            },
            formatWeekViewTitle: function(date:Date) {
                return 'testWT';
            },
            formatWeekViewHourColumn: function(date:Date) {
                return 'testWH';
            },
            formatDayViewHourColumn: function(date:Date) {
                return 'testDH';
            },
            formatDayViewTitle: function(date:Date) {
                return 'testDT';
            },
            formatDate: function(date:Date) {
              return date.getDate() + '-' + (+date.getMonth() + +1) + '-' + date.getFullYear();
            }
        }
    };

public getEvents(reload = false) {
    
    // console.log('start get event');
    this.calenderLoader = true;
    // this.events = []; for desk Style
    this.calenderEvents2 = []; /*for mobile*/
    this.refresh.next();
    const apiurlgetCalender = 'getevent?id=' + this.mtserv.getLoggedUser().uid;
    this.mtserv.MtGetPromise(apiurlgetCalender).then(data => {
      //this.calenderLoader = false;
      // console.log(data.json());
      this.eventData = data.json();
      const temp = [];
      if (this.eventData['getevent']) {

        this.eventData['data'].forEach(event => {
          const eventDate = new Date(event.date);
          const availability = (event.type == 'available' || event.type == 'hours') ? 'A' : 'U';
          const eventHours = (event.isAllDay == 0) ? event.hours_start + ' - ' + event.hours_end : 'All Day';
          const eventTitle = availability + ' ' + eventHours;
          const eventStatus = (event.status == 0) ? this.colors.green : this.colors.red;
          temp.push({
            startTime: setHours(setMinutes(event.date, 0), this.getHourE(event.date + ' ' + event.hours_start)),
            endTime: setHours(setMinutes(event.date, 0), this.getHourE(event.date + ' ' + event.hours_end)),
            // start: setHours(setMinutes(event.date, 0), this.getHourE(event.date + ' ' + event.hours_start)), for desk
            // end: setHours(setMinutes(event.date, 0), this.getHourE(event.date + ' ' + event.hours_end)), for desk
            title: eventTitle,
            // color: eventStatus,
            allDay: false
          });
       });
       
       const classUrls = 'getwizurls';
          this.mtserv.MtGetPromise(classUrls).then(classes => {
            this.calenderLoader = false;
            if(reload){
              reload.target.complete();
            }
            let classData = classes.json();
            //console.log(classData);
            /*
            let recData = classData.view_schedule.recurring_list.class_details;
            recData.forEach(ev => {
              temp.push({
                start: subDays(startOfDay(ev.start_time), 0),
                title: ev.class_title + ' (' + ev.class_status + ') ',
                color: this.colors.yellow,
                allDay: true,
                meta: {
                  ev
                }
              });
            });*/

            classData['data'].forEach(urlData => {
              var className = urlData.name;
              var teacher = urlData.teacher;
              var times = urlData.tms;
              var urls = urlData.url;
              var timeUrl = this.maparray.transform(times, urls);

                timeUrl.forEach(cal => {
                  temp.push({
                    startTime: setHours(setMinutes(cal.date, 0), this.getHourE(cal.date + ' ' + cal.hours_start)),
                    endTime: setHours(setMinutes(cal.date, 0), this.getHourE(cal.date + ' ' + cal.hours_end)),
                    // start: setHours(setMinutes(cal.date, 0), this.getHourE(cal.date + ' ' + cal.hours_start)), for desk
                    // end: setHours(setMinutes(cal.date, 0), this.getHourE(cal.date + ' ' + cal.hours_end)), for desk
                    title: className + ' by ' + teacher,
                    // title: cal.hours_start + ' to ' + cal.hours_end + ' - [' + className + ']',
                    // color: this.colors.yellow,
                    allDay: false,
                     meta: {
                      cal
                    }
                  });
                });
            });

            this.calenderEvents2 = temp;
            this.refresh.next();
            
          });

       
        console.log('don',this.calenderEvents2);
      }
      // console.log('out',this.events);
    });
  }


.html

<calendar [eventSource]="calenderEvents2"
                [calendarMode]="calendar.mode"
                [currentDate]="calendar.currentDate"
                (onCurrentDateChanged)="onCurrentDateChanged($event)"
                (onEventSelected)="onEventSelected($event)"
                (onTitleChanged)="onViewTitleChanged($event)"
                (onTimeSelected)="onTimeSelected($event)"
                [monthviewEventDetailTemplate]="template"
                step="30">
          </calendar>

**Comment by twinssbc** [comment]
@akshaykatale99 How do you set the calendar.mode to week or day?

**Comment by akshaykatale99** [comment]
@twinssbc here i set the mode

calendar = {
mode: 'month',
currentDate: new Date(),
dateFormatter: {
formatMonthViewDay: function(date:Date) {
return date.getDate().toString();
},
formatMonthViewDayHeader: function(date:Date) {
return 'MonMH';
},
formatMonthViewTitle: function(date:Date) {
return 'testMT';
},
formatWeekViewDayHeader: function(date:Date) {
return 'MonWH';
},
formatWeekViewTitle: function(date:Date) {
return 'testWT';
},
formatWeekViewHourColumn: function(date:Date) {
return 'testWH';
},
formatDayViewHourColumn: function(date:Date) {
return 'testDH';
},
formatDayViewTitle: function(date:Date) {
return 'testDT';
},
formatDate: function(date:Date) {
return date.getDate() + '-' + (+date.getMonth() + +1) + '-' + date.getFullYear();
}
}
};

**Comment by twinssbc** [comment]
@akshaykatale99 How do you switch to week or day?

**Comment by akshaykatale99** [comment]
@twinssbc i switch it using on click event

**Comment by twinssbc** [comment]
@akshaykatale99 Is there any error printed out in the console? Also could you use Developer Tools to hover on the element to see if it is actually there but not rendered correctly for some reason (maybe your other element or css has some conflict with it)

**Comment by akshaykatale99** [comment]
@twinssbc No error in console...wait let me share my screenshot

**Comment by akshaykatale99** [comment]
@twinssbc here is my screens 
![FireShot Capture 028 - Ionic App - localhost](https://user-images.githubusercontent.com/12472207/54641303-e3090300-4ab7-11e9-8e99-7048d3d0968a.png)
![FireShot Capture 026 - Ionic App - localhost](https://user-images.githubusercontent.com/12472207/54641304-e3090300-4ab7-11e9-91a8-d3b2cbae2a4a.png)
![FireShot Capture 027 - Ionic App - localhost](https://user-images.githubusercontent.com/12472207/54641306-e3a19980-4ab7-11e9-911e-88de72fcd695.png)

**Comment by twinssbc** [comment]
@jacob-cross99 So the week view is displayed, but not rendered completely. Usually this is because some other DOM element or customized css cause the rendering issue. Could you use the Developer Tool to check the page content to see why the rest of the calendar is not rendered properly?

**Comment by antoniomtnez** [comment]
> @jacob-cross99 So the week view is displayed, but not rendered completely. Usually this is because some other DOM element or customized css cause the rendering issue. Could you use the Developer Tool to check the page content to see why the rest of the calendar is not rendered properly?

The same thing happens to me, the week view is shown, but without data.
.....
I fixed it. In my code, the element above <calendar ... <ion-list, I added style = "height: 100%! important"

**Comment by stojankukrika** [comment]
@antoniomtnez thank you 💯 it saves me 100 years of life 👍
