### ISSUE TITLE
Select event in month or day

### ISSUE THREAD

**Issue by cesargrano** [twinssbc/Ionic2-Calendar#96]
It's like when selecting an event in the week or day, change the background color so you do in the month.

**Comment by twinssbc** [comment]
@cesargrano I get the idea, but I think different people may expect different effect. It could be changing the background color when selecting the event or selecting the whole time slot. It could also be changing the background color of the event itself or the whole time slot. So I generally try to avoid a functionality requires tuning for different user.
If you have more specific requirement, feel free to let me know, may be the available options can already achieve your expected effect.

**Comment by cesargrano** [comment]
Got it, but please tell me where I make this color change on week or day when it is selected.

**Comment by twinssbc** [comment]
@cesargrano 
Could you let me know you want to change the background color of the selected event, or selected hour, or the whole day? It may lead to different solution.
