### ISSUE TITLE
A couple of issues I've noticed

### ISSUE THREAD

**Issue by gabrielalack** [twinssbc/Ionic2-Calendar#97]
1. I am using a custom month-view template with custom styling and event display. I notice that when swiping left or right to change month, it shows the unstyled/untemplated default view until the slide action is complete then it applies the template. I really don't like that because the unstyled view does not match what I've worked on at all and there's a weird delay. How hard is it to show the styled view in the previous/next month slides?

2. I also thought maybe it would be more efficient to load in a year's worth of events at a time so it doesn't have to do a database call every time I swipe to change months. However, when I switch months, it does not display any of the events that are loaded. As an experiment, I reloaded all the same data using onRangeChange when switching months, and then it will show up on the calendar. Is this a bug or by design? Does it expect that the source data will have to be reloaded when the range changes? Is there a way around it?

**Comment by twinssbc** [comment]
@gabrielalack There's monthviewInactiveDisplayEventTemplate can be used for your first requirement.
Regarding your second question, it's expected to change the source data each time the rangeChanged callback is triggered. You could load one year data and store it somewhere and provide a slice of data only required for current range. It also make the calendar avoid processing unnecessary events.

**Comment by gabrielalack** [comment]
Gotcha! Thanks!
