### ISSUE TITLE
Calendar not working in RTL

### ISSUE THREAD

**Issue by theunreal** [twinssbc/Ionic2-Calendar#98]
I'm using right to left language, the calendar do not appear in this case.

It seem like Ionic2-Calendar using old Ionic version. The newest version, 3.1.0 has alot of fixes and one of them are the slides.

![image](https://cloud.githubusercontent.com/assets/6171883/25542582/d4322450-2c5b-11e7-8907-7b9d94813196.png)

**Comment by twinssbc** [comment]
@theunreal Yes, the latest calendar version is built on Ionic2.
Although according to this issue, https://github.com/twinssbc/Ionic2-Calendar/issues/88, it's almost compatible with Ionic3, just some warnings.
So I guess your error may related to something else.
Could you check if any error is printed out in the console?
And which version of Ionic, Angular, Ionic2-Calendar are you using?

**Comment by theunreal** [comment]
@twinssbc This is not releated tos omething else,
try add `style="dircetion:rtl"` to your calendar and see if it works. 
I'm using Ionic 3.1.1, Angular 4 and latest ionic2-calendar (to this date)

**Comment by KarimOmar** [comment]
@theunreal I am also have the same problem with RTL version but it all about missing styling support for RTL 
this element <div class="swiper-wrapper" style="transform: translate3d(-278px, 0px, 0px); transition-duration: 0ms;"> has transform rule (-)278px if you make it (+)278px it will be fixed. let say that what I said is not a solution but it's workaround till the component update by @twinssbc  
![myapp ionic lab](https://cloud.githubusercontent.com/assets/5624984/26283447/19c12082-3e29-11e7-81bf-8dd947e62790.png)

**Comment by twinssbc** [comment]
@theunreal @KarimOmar I have published the version supporting RTL.
You could add [dir]="rtl" to the calendar element to use this feature.
Note that it's only supported in Ionic 2.3.0 version onwards.
Feel free to have a try.

**Comment by KarimOmar** [comment]
@twinssbc i checked your update [dir]="rtl" but it didn't add any update to the UI check below screenshot
![myapp ionic lab](https://cloud.githubusercontent.com/assets/5624984/26303427/e94c8206-3ee7-11e7-85f7-2b2293edcdeb.png)

I know that my workaround is not valid or genius but is represent the RTL in UI check screenshot below :
![myapp ionic lab-workaround](https://cloud.githubusercontent.com/assets/5624984/26303519/2d641652-3ee8-11e7-8c1e-b811a2c1d1ad.png)

**Comment by twinssbc** [comment]
It should work, which calendar version are you using?

**Comment by terminaltor** [comment]
Hey, I'm using the latest version of your calendar, latest version of Ionic, a new project just started yesterday.
When I try to add the attribute [dir]="rtl" to the calendar element I got the next error:
Cannot read property 'toLowerCase' of undefined at Slides.set

Any suggestions?
Thanks.

**Comment by twinssbc** [comment]
@terminaltor No need to add square bracket. Just dir="rtl"
